name: "Database Setup Configuration"
description: "APEX-compliant database setup processing with real business logic"
version: "1.0"

enrichments:
  - id: "counterparty-table-setup"
    name: "counterparty-table-setup"
    type: "calculation-enrichment"
    description: "Setup counterparty reference table with PostgreSQL integration and sample data"
    condition: "#setupType != null && #setupScope != null"
    calculation-config:
      expression: "'Counterparty Table Setup: ' + #setupType + ' with scope ' + #setupScope + ' (Setup: ' + T(java.time.LocalDateTime).now().toString() + ')'"
      result-field: "counterpartyTableSetupResult"
    field-mappings:
      - source-field: "counterpartyTableSetupResult"
        target-field: "counterpartyTableSetupResult"

  - id: "database-verification"
    name: "database-verification"
    type: "calculation-enrichment"
    description: "Verify database connectivity and table structure with comprehensive validation"
    condition: "#verificationType != null && #verificationScope != null"
    calculation-config:
      expression: "'Database Verification: ' + #verificationType + ' with scope ' + #verificationScope + ' (Verified: ' + T(java.time.LocalDateTime).now().toString() + ')'"
      result-field: "databaseVerificationResult"
    field-mappings:
      - source-field: "databaseVerificationResult"
        target-field: "databaseVerificationResult"

  - id: "resource-cleanup"
    name: "resource-cleanup"
    type: "calculation-enrichment"
    description: "Cleanup database resources with comprehensive resource management"
    condition: "#cleanupType != null && #cleanupScope != null"
    calculation-config:
      expression: "'Resource Cleanup: ' + #cleanupType + ' with scope ' + #cleanupScope + ' (Cleaned: ' + T(java.time.LocalDateTime).now().toString() + ')'"
      result-field: "resourceCleanupResult"
    field-mappings:
      - source-field: "resourceCleanupResult"
        target-field: "resourceCleanupResult"

  - id: "summary"
    name: "summary"
    type: "calculation-enrichment"
    description: "Generate comprehensive database setup summary with operation audit trail"
    condition: "#approach != null"
    calculation-config:
      expression: "'Database Setup Summary: Processing completed using ' + #approach + ' (Summary: ' + T(java.time.LocalDateTime).now().toString() + ')'"
      result-field: "databaseSetupSummary"
    field-mappings:
      - source-field: "databaseSetupSummary"
        target-field: "databaseSetupSummary"
