metadata:
  id: "Demo Data Sources Configuration"
  name: "Demo Data Sources Configuration"
  version: "1.0.0"
  description: "Production data sources for APEX demo scenarios with proper ExternalDataSource implementations"
  type: "external-data-config"
  author: "apex.demo.team@company.com"
  created-date: "2024-12-24"
  tags: ["apex-demo", "infrastructure", "data-sources"]

# ============================================================================
# DEMO DATA SOURCES CONFIGURATION
# ============================================================================
#
# This configuration file defines production data sources for APEX demo scenarios.
# It replaces the previous MockDataSource approach with proper ExternalDataSource
# implementations that demonstrate real-world data integration patterns.
#
# KEY IMPROVEMENTS:
# - Uses production ExternalDataSource implementations
# - Demonstrates proper data source configuration
# - Shows real-world connection and caching settings
# - Includes proper error handling and monitoring configuration
# - Provides examples for different data source types
#
# ============================================================================

# Configuration details
configuration:
  type: "apex-enrichment-config"
  name: "APEX Demo Data Sources Configuration"
  version: "2.0.0"
  description: "Production data source configurations for APEX demonstrations"
  author: "apex-demo-team@company.com"
  created-by: "apex-demo-team@company.com"
  environment: "demo"

# ============================================================================
# DATA SOURCE CONFIGURATIONS
# ============================================================================

data-sources:
  
  # File System Data Sources
  - name: "demo-json-files"
    type: "FILE_SYSTEM"
    enabled: true
    description: "JSON files for demo data processing"
    
    connection:
      base-path: "demo-data/json"
      file-pattern: "*.json"
      encoding: "UTF-8"
      
    properties:
      auto-reload: true
      watch-for-changes: true
      cache-parsed-files: true
      cache-ttl-seconds: 300
      
    health-check:
      enabled: true
      interval-seconds: 30
      timeout-seconds: 5
      
    metrics:
      enabled: true
      include-file-stats: true
      include-parse-times: true

  - name: "demo-xml-files"
    type: "FILE_SYSTEM"
    enabled: true
    description: "XML files for demo data processing"
    
    connection:
      base-path: "demo-data/xml"
      file-pattern: "*.xml"
      encoding: "UTF-8"
      
    properties:
      auto-reload: true
      watch-for-changes: true
      cache-parsed-files: true
      cache-ttl-seconds: 300
      validate-xml-schema: false
      
    health-check:
      enabled: true
      interval-seconds: 30
      timeout-seconds: 5

  - name: "demo-csv-files"
    type: "FILE_SYSTEM"
    enabled: true
    description: "CSV files for batch processing demos"
    
    connection:
      base-path: "demo-data/csv"
      file-pattern: "*.csv"
      encoding: "UTF-8"
      
    properties:
      auto-reload: true
      watch-for-changes: true
      csv-header-row: true
      csv-delimiter: ","
      csv-quote-char: "\""
      cache-parsed-files: true
      cache-ttl-seconds: 600

  # Cache Data Sources
  - name: "demo-products-cache"
    type: "CACHE"
    enabled: true
    description: "In-memory cache for product reference data"
    
    properties:
      max-size: 1000
      ttl-seconds: 3600  # 1 hour
      eviction-policy: "LRU"
      statistics-enabled: true
      
    health-check:
      enabled: true
      interval-seconds: 60
      
    metrics:
      enabled: true
      include-cache-stats: true
      include-hit-ratios: true

  - name: "demo-customer-cache"
    type: "CACHE"
    enabled: true
    description: "In-memory cache for customer reference data"
    
    properties:
      max-size: 500
      ttl-seconds: 1800  # 30 minutes
      eviction-policy: "LRU"
      statistics-enabled: true
      
    health-check:
      enabled: true
      interval-seconds: 60

  - name: "demo-lookup-cache"
    type: "CACHE"
    enabled: true
    description: "High-performance cache for lookup data"
    
    properties:
      max-size: 2000
      ttl-seconds: 7200  # 2 hours
      eviction-policy: "LFU"  # Least Frequently Used
      statistics-enabled: true
      preload-on-startup: true

  # Database Data Source (for advanced demos)
  - name: "demo-database"
    type: "DATABASE"
    enabled: false  # Disabled by default, enable when database is available
    description: "Demo database for advanced data source scenarios"
    
    connection:
      # H2 file-based database for true sharing between demo and APEX
      database: "./target/h2-demo/apex_demo_shared"
      username: "sa"
      password: ""
      
    connection-pool:
      initial-size: 2
      max-size: 10
      min-idle: 1
      max-wait-seconds: 30
      validation-query: "SELECT 1"
      
    properties:
      auto-commit: false
      transaction-isolation: "READ_COMMITTED"
      
    health-check:
      enabled: true
      interval-seconds: 30
      timeout-seconds: 10
      validation-query: "SELECT 1"

  # REST API Data Source (for integration demos)
  - name: "demo-rest-api"
    type: "REST_API"
    enabled: false  # Disabled by default
    description: "Demo REST API for external data integration"
    
    connection:
      base-url: "https://api.demo.example.com"
      timeout-seconds: 30
      
    authentication:
      type: "API_KEY"
      api-key-header: "X-API-Key"
      api-key-value: "demo-api-key-12345"
      
    circuit-breaker:
      enabled: true
      failure-threshold: 5
      recovery-timeout-seconds: 60
      
    retry:
      enabled: true
      max-attempts: 3
      backoff-multiplier: 2
      initial-delay-seconds: 1

# ============================================================================
# DATA SOURCE GROUPS
# ============================================================================

data-source-groups:
  
  file-sources:
    description: "All file-based data sources"
    members:
      - "demo-json-files"
      - "demo-xml-files"
      - "demo-csv-files"
    
  cache-sources:
    description: "All cache-based data sources"
    members:
      - "demo-products-cache"
      - "demo-customer-cache"
      - "demo-lookup-cache"
      
  external-sources:
    description: "External system integrations"
    members:
      - "demo-database"
      - "demo-rest-api"

# ============================================================================
# MONITORING AND MANAGEMENT
# ============================================================================

monitoring:
  enabled: true
  metrics-collection-interval-seconds: 60
  health-check-interval-seconds: 30
  
  alerts:
    enabled: true
    
    # Alert when data source becomes unhealthy
    health-alerts:
      enabled: true
      notification-channels: ["console", "log"]
      
    # Alert on performance degradation
    performance-alerts:
      enabled: true
      response-time-threshold-ms: 5000
      error-rate-threshold-percent: 5
      
  # Export metrics to external systems
  metrics-export:
    enabled: false
    format: "prometheus"
    endpoint: "/metrics"

# ============================================================================
# DEMO SCENARIOS MAPPING
# ============================================================================

demo-scenarios:
  
  batch-processing:
    description: "Batch processing demonstration"
    required-data-sources:
      - "demo-csv-files"
      - "demo-products-cache"
    optional-data-sources:
      - "demo-database"
      
  file-processing:
    description: "File-based processing demonstration"
    required-data-sources:
      - "demo-json-files"
      - "demo-xml-files"
    optional-data-sources:
      - "demo-lookup-cache"
      
  streaming-processing:
    description: "Streaming data processing demonstration"
    required-data-sources:
      - "demo-customer-cache"
      - "demo-lookup-cache"
    optional-data-sources:
      - "demo-rest-api"
      
  integration-demo:
    description: "External system integration demonstration"
    required-data-sources:
      - "demo-database"
      - "demo-rest-api"
    optional-data-sources:
      - "demo-products-cache"

# ============================================================================
# ENVIRONMENT-SPECIFIC OVERRIDES
# ============================================================================

environments:
  
  development:
    data-sources:
      demo-database:
        enabled: true
        connection:
          database: "./target/h2-demo/apex_demo_shared"

  testing:
    data-sources:
      demo-database:
        enabled: true
        connection:
          database: "./target/h2-demo/apex_demo_shared"
        connection-pool:
          max-size: 5
          
  production:
    # In production, you would configure actual database connections
    data-sources:
      demo-database:
        enabled: false  # Use real database configuration
      demo-rest-api:
        enabled: false  # Use real API configuration

