# ============================================================================
# APEX Rules Engine - Derivatives Validation Rules Configuration
# ============================================================================
#
# This configuration file contains comprehensive validation rules for
# derivatives trading, specifically focused on OTC (Over-the-Counter)
# derivatives including options, swaps, forwards, and other structured products.
#
# SCOPE:
# - Structural validation for derivatives data
# - Business logic validation for trading rules
# - Risk management and compliance checks
# - Regulatory validation requirements
#
# INTEGRATION:
# This file is referenced by scenario configurations that process derivatives
# data and provides additional validation rules beyond those defined in
# bootstrap configurations.
#
# ============================================================================

metadata:
  id: "derivatives-validation-rules"
  name: "Derivatives Validation Rules"
  version: "1.0.0"
  description: "Comprehensive validation rules for derivatives trading and risk management"
  type: "rule-config"
  author: "risk.management@company.com"
  created-by: "risk.management@company.com"
  business-domain: "Derivatives Trading"
  business-owner: "Risk Management Team"
  created-date: "2025-08-11"
  tags: ["derivatives", "validation", "risk-management", "compliance"]

# ============================================================================
# STRUCTURAL VALIDATION RULES
# ============================================================================
#
# These rules ensure that derivatives data has proper structure and
# required fields for processing and risk management.
#
rules:
  # TradeB Identification Rules
  - id: "derivatives-validation-rules"
    name: "TradeB ID Format Validation"
    condition: "#tradeId != null && #tradeId.matches('^[A-Z]{2}[0-9]{8}$')"
    message: "TradeB ID must follow format: 2 letters followed by 8 digits"
    severity: "ERROR"
    priority: 1
    categories: ["structural", "identification"]

  - id: "derivatives-validation-rules"
    name: "Unique TradeB Reference"
    condition: "#uniqueTradeReference != null && #uniqueTradeReference.length() >= 10"
    message: "Unique trade reference must be at least 10 characters"
    severity: "ERROR"
    priority: 1
    categories: ["structural", "identification"]

  # Counterparty Validation Rules
  - id: "derivatives-validation-rules"
    name: "Counterparty LEI Required"
    condition: "#counterpartyLei != null && #counterpartyLei.matches('^[A-Z0-9]{20}$')"
    message: "Counterparty LEI must be 20 alphanumeric characters"
    severity: "ERROR"
    priority: 2
    categories: ["structural", "counterparty", "regulatory"]

  - id: "derivatives-validation-rules"
    name: "Counterparty Jurisdiction Validation"
    condition: "#counterpartyJurisdiction != null && #counterpartyJurisdiction in {'US', 'EU', 'UK', 'JP', 'CA', 'AU'}"
    message: "Counterparty jurisdiction must be a supported jurisdiction"
    severity: "WARNING"
    priority: 3
    categories: ["business-logic", "counterparty"]

# ============================================================================
# BUSINESS LOGIC VALIDATION RULES
# ============================================================================
#
# These rules implement business logic specific to derivatives trading
# and ensure compliance with trading policies and procedures.
#
  # Notional Amount Rules
  - id: "derivatives-validation-rules"
    name: "Minimum Notional Amount"
    condition: "#notionalAmount != null && #notionalAmount >= 1000"
    message: "Notional amount must be at least 1,000"
    severity: "WARNING"
    priority: 4
    categories: ["business-logic", "sizing"]

  - id: "derivatives-validation-rules"
    name: "Maximum Notional Limit Check"
    condition: "#notionalAmount != null && #notionalAmount <= 100000000"
    message: "Notional amount exceeds maximum limit of 100 million"
    severity: "ERROR"
    priority: 2
    categories: ["risk-management", "limits"]

  # Maturity and Tenor Rules
  - id: "derivatives-validation-rules"
    name: "Maximum Maturity Period"
    condition: "#maturityDate != null && #tradeDate != null && T(java.time.temporal.ChronoUnit).YEARS.between(#tradeDate, #maturityDate) <= 30"
    message: "Maturity period cannot exceed 30 years"
    severity: "ERROR"
    priority: 2
    categories: ["business-logic", "temporal", "risk-management"]

  - id: "derivatives-validation-rules"
    name: "Minimum Maturity Period"
    condition: "#maturityDate != null && #tradeDate != null && T(java.time.temporal.ChronoUnit).DAYS.between(#tradeDate, #maturityDate) >= 1"
    message: "Maturity date must be at least 1 day after trade date"
    severity: "ERROR"
    priority: 1
    categories: ["business-logic", "temporal"]

# ============================================================================
# RISK MANAGEMENT RULES
# ============================================================================
#
# These rules implement risk management policies and ensure trades
# comply with risk limits and exposure guidelines.
#
  # Credit Risk Rules
  - id: "derivatives-validation-rules"
    name: "Counterparty Credit Rating Check"
    condition: "#counterpartyCreditRating != null && #counterpartyCreditRating in {'AAA', 'AA+', 'AA', 'AA-', 'A+', 'A', 'A-', 'BBB+', 'BBB', 'BBB-'}"
    message: "Counterparty must have investment grade credit rating"
    severity: "WARNING"
    priority: 3
    categories: ["risk-management", "credit-risk"]

  - id: "derivatives-validation-rules"
    name: "High Risk Counterparty Check"
    condition: "#counterpartyCreditRating == null || !#counterpartyCreditRating in {'CCC', 'CC', 'C', 'D'}"
    message: "TradeB with high-risk counterparty requires additional approval"
    severity: "INFO"
    priority: 5
    categories: ["risk-management", "credit-risk", "approval"]

  # Market Risk Rules
  - id: "derivatives-validation-rules"
    name: "Currency Risk Assessment"
    condition: "#baseCurrency != null && #quoteCurrency != null && (#baseCurrency == #quoteCurrency || (#baseCurrency in {'USD', 'EUR', 'GBP'} && #quoteCurrency in {'USD', 'EUR', 'GBP'}))"
    message: "Cross-currency trades require additional risk assessment"
    severity: "INFO"
    priority: 4
    categories: ["risk-management", "market-risk", "currency"]

# ============================================================================
# REGULATORY COMPLIANCE RULES
# ============================================================================
#
# These rules ensure compliance with regulatory requirements for
# derivatives trading and reporting.
#
  # Reporting Requirements
  - id: "derivatives-validation-rules"
    name: "Regulatory Reporting Required"
    condition: "#notionalAmount != null && #notionalAmount >= 50000"
    message: "TradeB requires regulatory reporting due to notional amount threshold"
    severity: "INFO"
    priority: 5
    categories: ["regulatory", "reporting"]

  - id: "derivatives-validation-rules"
    name: "Central Clearing Requirement"
    condition: "#productType != null && #productType in {'IRS', 'CDS'} && #notionalAmount >= 1000000"
    message: "TradeB may be subject to central clearing requirements"
    severity: "INFO"
    priority: 4
    categories: ["regulatory", "clearing"]

  # Documentation Requirements
  - id: "derivatives-validation-rules"
    name: "ISDA Agreement Required"
    condition: "#isdaAgreement != null && #isdaAgreement == true"
    message: "Valid ISDA agreement required for OTC derivatives"
    severity: "ERROR"
    priority: 1
    categories: ["regulatory", "documentation"]

# ============================================================================
# PROCESSING CONFIGURATION
# ============================================================================
#
# Configuration settings for derivatives validation processing.
#
processing:
  # Error Handling
  stopOnFirstError: false
  enableValidation: true
  
  # Performance Settings
  batchSize: 50
  
  # Logging
  logLevel: "INFO"
  enableAuditTrail: true
