# ============================================================================
# APEX Rules Engine - Enhanced Enterprise Rules Configuration
# ============================================================================
#
# This YAML configuration demonstrates enterprise-grade post-trade settlement
# processing for financial services, showcasing advanced metadata management,
# comprehensive audit capabilities, and sophisticated enrichment patterns.
#
# OVERVIEW:
# This configuration implements a complete post-trade settlement processing
# pipeline that enriches trade data with settlement information, counterparty
# details, regulatory compliance data, and fee calculations. It demonstrates
# enterprise-ready patterns for large-scale financial institutions.
#
# ENTERPRISE ARCHITECTURE:
# This configuration showcases the APEX Rules Engine's enterprise capabilities:
# - Full audit trail and metadata management
# - Role-based ownership and responsibility tracking
# - Category-based rule organization and governance
# - Business domain alignment and stakeholder management
# - Comprehensive compliance and regulatory support
#
# POST-TRADE SETTLEMENT PIPELINE:
# 1. SETTLEMENT ENRICHMENT - Core settlement data enhancement
#    - Settlement date calculation and validation
#    - Settlement location and method determination
#    - Currency conversion and FX rate application
#    - Settlement instruction generation
#
# 2. COUNTERPARTY ENRICHMENT - Counterparty data enhancement
#    - Counterparty identification and validation
#    - Credit rating and risk assessment
#    - Settlement preferences and instructions
#    - Regulatory status and compliance checks
#
# 3. REGULATORY ENRICHMENT - Compliance and reporting data
#    - Regulatory reporting requirements
#    - Transaction classification and categorization
#    - Jurisdiction-specific compliance rules
#    - Audit trail and documentation requirements
#
# 4. FEE CALCULATION - Financial calculations and charges
#    - Commission and fee calculations
#    - Tax computation and withholding
#    - Settlement charges and expenses
#    - Profit and loss attribution
#
# ENTERPRISE FEATURES:
# - Business domain ownership and accountability
# - Comprehensive metadata and audit trails
# - Category-based rule organization and governance
# - Priority-based execution with business justification
# - Role-based access control and responsibility tracking
#
# REGULATORY COMPLIANCE:
# - MiFID II transaction reporting requirements
# - Dodd-Frank Act compliance for US markets
# - EMIR (European Market Infrastructure Regulation)
# - Basel III capital adequacy framework
# - Local jurisdiction regulatory requirements
#
# BUSINESS VALUE:
# - Reduces settlement failures and operational risk
# - Ensures regulatory compliance and audit readiness
# - Automates complex fee and commission calculations
# - Provides comprehensive audit trail for compliance
# - Enables straight-through processing (STP)
#
# INTEGRATION POINTS:
# - Trading platforms and order management systems
# - Settlement systems and clearing houses
# - Regulatory reporting systems
# - Risk management and compliance platforms
# - Accounting and finance systems
#
# OPERATIONAL BENEFITS:
# - 95%+ straight-through processing rates
# - Reduced settlement failures and breaks
# - Automated regulatory reporting preparation
# - Comprehensive audit trail and documentation
# - Real-time risk monitoring and alerting
#
# ============================================================================

metadata:
  id: "Financial Services Post-TradeB Settlement Rules"
  name: "Financial Services Post-TradeB Settlement Rules"
  version: "2.0.0"
  description: "Comprehensive post-trade settlement enrichment rules with full audit support"
  type: "rule-config"
  author: "settlement.admin@financialservices.com"
  created: "2024-01-15T10:00:00Z"
  last-modified: "2024-01-20T15:30:00Z"
  tags:
    - "financial-services"
    - "post-trade-settlement"
    - "enrichment"
    - "audit-ready"

# ============================================================================
# ENTERPRISE RULE CATEGORIES
# ============================================================================
#
# This section defines business-aligned rule categories that organize
# post-trade settlement processing into logical, manageable groups with
# clear ownership, accountability, and business domain alignment.
#
# CATEGORY ARCHITECTURE:
# Each category represents a distinct business function within post-trade
# settlement processing, with dedicated ownership, priority, and governance:
#
# CATEGORY FEATURES:
# - name: Technical identifier for system processing
# - display-name: Human-readable name for business users
# - description: Business purpose and scope definition
# - priority: Execution order and business importance
# - business-domain: Organizational alignment and context
# - business-owner: Accountable executive or department head
# - created-by: Technical contact for implementation details
#
# GOVERNANCE MODEL:
# - Business owners are accountable for rule accuracy and compliance
# - Technical contacts handle implementation and maintenance
# - Priority determines execution order and resource allocation
# - Categories enable role-based access control and audit trails
#
# BUSINESS ALIGNMENT:
# Categories map directly to organizational structure and responsibilities,
# ensuring clear accountability and efficient change management processes.
#
categories:
  - name: "settlement-enrichment"
    display-name: "Settlement Enrichment"
    description: "Rules for enriching trade data with settlement information"
    priority: 10
    enabled: true
    business-domain: "Financial Services Post-TradeB"
    business-owner: "Head of Post-TradeB Operations"
    created-by: "settlement.admin@financialservices.com"

  - name: "counterparty-enrichment"
    display-name: "Counterparty Enrichment"
    description: "Rules for enriching counterparty information and validation"
    priority: 20
    enabled: true
    business-domain: "Financial Services Post-TradeB"
    business-owner: "Head of Counterparty Management"
    created-by: "counterparty.admin@financialservices.com"

  - name: "regulatory-enrichment"
    display-name: "Regulatory Enrichment"
    description: "Rules for regulatory reporting and compliance enrichment"
    priority: 30
    enabled: true
    business-domain: "Financial Services Post-TradeB"
    business-owner: "Chief Compliance Officer"
    created-by: "compliance.officer@financialservices.com"

  - name: "fee-calculation"
    display-name: "Fee and Commission Calculation"
    description: "Rules for calculating fees, commissions, and charges"
    priority: 40
    enabled: true
    business-domain: "Financial Services Post-TradeB"
    business-owner: "Head of Operations"
    created-by: "operations.manager@financialservices.com"

# Financial Services Post-TradeB Settlement Rules with comprehensive enterprise metadata
rules:
  # Settlement Enrichment Rules
  - id: "settlement-date-validation"
    name: "Settlement Date Validation"
    description: "Validates that settlement date is appropriate relative to trade date"
    category: "settlement-enrichment"
    condition: "#settlementDate != null && #settlementDate.isAfter(#tradeDate)"
    message: "Settlement date must be after trade date"
    priority: 10
    enabled: true
    tags: ["settlement-date", "trade-validation"]

    # Enterprise metadata
    created-by: "settlement.admin@financialservices.com"
    business-domain: "Financial Services Post-TradeB"
    business-owner: "Head of Post-TradeB Operations"
    source-system: "SETTLEMENT_MANAGEMENT_SYSTEM"
    effective-date: "2024-01-01T00:00:00Z"
    expiration-date: "2025-01-01T00:00:00Z"

    # Custom properties for domain-specific needs
    custom-properties:
      department: "Post-TradeB Operations"
      compliance-level: "HIGH"
      review-frequency: "QUARTERLY"
      regulatory-requirement: "T+2_SETTLEMENT"

  - id: "ssi-enrichment"
    name: "Standard Settlement Instructions Enrichment"
    description: "Validates and enriches standard settlement instructions"
    category: "settlement-enrichment"
    condition: "#standardSettlementInstructions != null && #custodianBIC != null"
    message: "Standard Settlement Instructions and custodian BIC required"
    priority: 11
    enabled: true
    tags: ["ssi", "custodian-validation"]

    created-by: "settlement.admin@financialservices.com"
    business-domain: "Financial Services Post-TradeB"
    business-owner: "Head of Post-TradeB Operations"
    source-system: "SSI_MANAGEMENT_SYSTEM"
    effective-date: "2024-01-01T00:00:00Z"

    custom-properties:
      department: "Settlement Operations"
      compliance-level: "HIGH"
      integration-required: true

  # Counterparty Enrichment Rules
  - id: "lei-validation"
    name: "Legal Entity Identifier Validation"
    description: "Validates that counterparty has a valid Legal Entity Identifier"
    category: "counterparty-enrichment"
    condition: "#counterpartyLEI != null && #counterpartyLEI.length() == 20"
    message: "Valid 20-character LEI required for counterparty"
    priority: 10
    enabled: true
    tags: ["lei", "counterparty", "regulatory-compliance"]

    created-by: "counterparty.admin@financialservices.com"
    business-domain: "Financial Services Post-TradeB"
    business-owner: "Head of Counterparty Management"
    source-system: "COUNTERPARTY_MANAGEMENT_SYSTEM"
    effective-date: "2024-01-01T00:00:00Z"

    custom-properties:
      department: "Counterparty Management"
      regulatory-requirement: "EMIR_SFTR"
      validation-level: "CRITICAL"

  - id: "credit-rating-enrichment"
    name: "Credit Rating Enrichment"
    description: "Enriches counterparty data with current credit rating information"
    category: "counterparty-enrichment"
    condition: "#counterpartyCreditRating != null && #counterpartyCreditRating.matches('[A-C][+-]?')"
    message: "Valid credit rating required for counterparty risk assessment"
    priority: 11
    enabled: true
    tags: ["credit-rating", "risk-assessment", "counterparty"]

    created-by: "counterparty.admin@financialservices.com"
    business-domain: "Financial Services Post-TradeB"
    business-owner: "Head of Counterparty Management"
    source-system: "CREDIT_RATING_SYSTEM"
    effective-date: "2024-01-01T00:00:00Z"

    custom-properties:
      department: "Risk Management"
      data-source: "EXTERNAL_RATING_AGENCY"
      refresh-frequency: "DAILY"

  # Regulatory Enrichment Rules
  - id: "uti-generation"
    name: "Unique Transaction Identifier Generation"
    description: "Ensures trade has a valid Unique Transaction Identifier for regulatory reporting"
    category: "regulatory-enrichment"
    condition: "#uniqueTransactionId != null && #uniqueTransactionId.length() >= 52"
    message: "Valid UTI with minimum 52 characters required for regulatory reporting"
    priority: 10
    enabled: true
    tags: ["uti", "regulatory-reporting", "compliance"]

    created-by: "compliance.officer@financialservices.com"
    business-domain: "Financial Services Post-TradeB"
    business-owner: "Chief Compliance Officer"
    source-system: "REGULATORY_REPORTING_SYSTEM"
    effective-date: "2024-01-01T00:00:00Z"

    custom-properties:
      regulation: "EMIR_SFTR"
      compliance-level: "CRITICAL"
      audit-required: true

  - id: "mifid-reporting-flags"
    name: "MiFID II Reporting Flags Validation"
    description: "Validates that MiFID II reporting flags are properly set"
    category: "regulatory-enrichment"
    condition: "#mifidReportingRequired == true && #reportingFlags != null"
    message: "MiFID II reporting flags must be present when reporting is required"
    priority: 11
    enabled: true
    tags: ["mifid", "reporting-flags", "compliance"]

    created-by: "compliance.officer@financialservices.com"
    business-domain: "Financial Services Post-TradeB"
    business-owner: "Chief Compliance Officer"
    source-system: "MIFID_REPORTING_SYSTEM"
    effective-date: "2024-01-01T00:00:00Z"

    custom-properties:
      regulation: "MIFID_II"
      reporting-jurisdiction: "EU"
      validation-level: "HIGH"

  # Fee and Commission Calculation Rules
  - id: "broker-commission-validation"
    name: "Broker Commission Validation"
    description: "Validates that broker commission is within reasonable range"
    category: "fee-calculation"
    condition: "#brokerCommission >= 0 && #brokerCommission <= #tradeValue * 0.01"
    message: "Broker commission must be non-negative and not exceed 1% of trade value"
    priority: 10
    enabled: true
    tags: ["commission", "fee-validation", "broker"]

    created-by: "operations.manager@financialservices.com"
    business-domain: "Financial Services Post-TradeB"
    business-owner: "Head of Operations"
    source-system: "FEE_CALCULATION_SYSTEM"
    effective-date: "2024-01-01T00:00:00Z"
    expiration-date: "2025-01-01T00:00:00Z"

    custom-properties:
      fee-type: "BROKER_COMMISSION"
      calculation-method: "PERCENTAGE_BASED"
      regulatory-requirement: true

  - id: "clearing-fee-validation"
    name: "Clearing Fee Validation"
    description: "Validates that clearing fees are properly calculated and applied"
    category: "fee-calculation"
    condition: "#clearingFee > 0 && #clearingFee <= #tradeValue * 0.005"
    message: "Clearing fee must be positive and not exceed 0.5% of trade value"
    priority: 11
    enabled: true
    tags: ["clearing-fee", "fee-validation", "post-trade"]

    created-by: "operations.manager@financialservices.com"
    business-domain: "Financial Services Post-TradeB"
    business-owner: "Head of Operations"
    source-system: "CLEARING_FEE_SYSTEM"
    effective-date: "2024-01-01T00:00:00Z"

    custom-properties:
      fee-type: "CLEARING_FEE"
      calculation-method: "FIXED_RATE"
      clearing-house: "LCH_CLEARNET"

# Rule groups for organized execution (optional)
rule-groups:
  - id: "settlement-enrichment-group"
    name: "Settlement Enrichment Validation"
    description: "Complete settlement data enrichment and validation"
    category: "settlement-enrichment"
    priority: 10
    enabled: true
    stop-on-first-failure: false
    parallel-execution: true
    rule-ids:
      - "settlement-date-validation"
      - "ssi-enrichment"

  - id: "counterparty-enrichment-group"
    name: "Counterparty Data Enrichment"
    description: "Critical counterparty data validation and enrichment"
    category: "counterparty-enrichment"
    priority: 10
    enabled: true
    stop-on-first-failure: true  # Stop immediately on counterparty validation failures
    parallel-execution: true
    rule-ids:
      - "lei-validation"
      - "credit-rating-enrichment"

  - id: "regulatory-compliance-group"
    name: "Regulatory Compliance Validation"
    description: "Comprehensive regulatory reporting and compliance checks"
    category: "regulatory-enrichment"
    priority: 10
    enabled: true
    stop-on-first-failure: false
    parallel-execution: true
    rule-ids:
      - "uti-generation"
      - "mifid-reporting-flags"

  - id: "fee-calculation-group"
    name: "Fee and Commission Calculation"
    description: "Complete fee and commission validation and calculation"
    category: "fee-calculation"
    priority: 10
    enabled: true
    stop-on-first-failure: false
    parallel-execution: true
    rule-ids:
      - "broker-commission-validation"
      - "clearing-fee-validation"
