# Enterprise Database Configuration Demo
# Demonstrates enterprise-grade database features including SSL, HA, and advanced connection pooling
# Use Case: Production-ready database configuration with high availability and security

metadata:
  id: "enterprise-database-configuration-demo"
  name: "Enterprise Database Configuration Demo"
  version: "1.0.0"
  description: "Demonstrates enterprise-grade database configuration with SSL, high availability, and advanced connection pooling"
  type: "external-data-config"
  author: "apex.demo.team@company.com"
  created-date: "2025-01-13"
  tags: ["apex-demo", "enterprise", "database", "ssl", "high-availability"]

# Enterprise database data sources
data-sources:
  # Production Database Configuration with Enterprise Features
  - name: "production-trading-db"
    type: "database"
    source-type: "postgresql"  # Supports: postgresql, mysql, oracle, sqlserver, h2
    enabled: true
    description: "Production trading database with enterprise-grade configuration"
    tags: ["production", "trading", "enterprise"]

    connection:
      host: "prod-db-cluster.company.com"
      port: 5432
      database: "trading_system"
      username: "${DB_USERNAME}"  # Environment variable support
      password: "${DB_PASSWORD}"

      # SSL Configuration for secure connections
      ssl:
        enabled: true
        mode: "require"
        cert-path: "/etc/ssl/certs/db-client.crt"
        key-path: "/etc/ssl/private/db-client.key"
        ca-path: "/etc/ssl/certs/ca-cert.pem"
        verify-hostname: true
        cipher-suites: ["TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384", "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256"]

    # Enterprise Connection Pool Configuration
    connection-pool:
      max-size: 100
      min-size: 20
      initial-size: 30
      connection-timeout: 45000
      idle-timeout: 900000
      max-lifetime: 3600000
      leak-detection-threshold: 120000
      
      # Advanced pool features
      validation-timeout: 5000
      initialization-fail-timeout: 1
      isolate-internal-queries: true
      allow-pool-suspension: true
      
      # Performance tuning
      prepared-statement-cache-size: 250
      prepared-statement-cache-sql-limit: 2048
      use-server-prepared-statements: true
      cache-server-configuration: true

    # High Availability Configuration
    high-availability:
      enabled: true
      read-replicas:
        - host: "prod-db-read1.company.com"
          port: 5432
          weight: 1.0
        - host: "prod-db-read2.company.com"
          port: 5432
          weight: 1.0
      failover:
        enabled: true
        max-retry-attempts: 3
        retry-delay-seconds: 5
        health-check-interval: 30
        failback-enabled: true

    # Query Optimization
    query-optimization:
      prepared-statement-cache-size: 500
      query-timeout-seconds: 30
      batch-size: 1000
      fetch-size: 100
      enable-query-plan-cache: true
      statement-pooling: true

    # Enterprise caching with advanced features
    cache:
      enabled: true
      ttlSeconds: 300
      maxSize: 50000
      eviction-policy: "LRU"
      statistics-enabled: true
      distributed-cache-enabled: true
      cache-cluster-nodes:
        - "cache-node1.company.com:6379"
        - "cache-node2.company.com:6379"

    # Comprehensive health monitoring
    healthCheck:
      enabled: true
      intervalSeconds: 30
      timeoutSeconds: 10
      query: "SELECT 1"
      
      # Advanced health validation
      health-validation:
        queries:
          - name: "primary-connectivity"
            query: "SELECT 1"
            timeout: 5
            critical: true
          - name: "replica-connectivity"
            query: "SELECT COUNT(*) FROM pg_stat_replication"
            timeout: 10
            critical: false
          - name: "performance-check"
            query: "SELECT pg_database_size(current_database())"
            timeout: 15
            critical: false

    # Named queries for enterprise operations
    queries:
      getTradesByCounterparty: |
        SELECT t.trade_id, t.counterparty_id, t.instrument_id, t.quantity, t.price, t.trade_date
        FROM trades t
        WHERE t.counterparty_id = :counterpartyId
          AND t.trade_date >= :startDate
          AND t.trade_date <= :endDate
        ORDER BY t.trade_date DESC
        LIMIT :limit

      getSettlementInstructions: |
        SELECT si.instruction_id, si.counterparty_id, cp.counterparty_name,
               si.settlement_date, si.currency, si.amount
        FROM settlement_instructions si
        JOIN counterparties cp ON si.counterparty_id = cp.counterparty_id
        WHERE si.counterparty_id = :counterpartyId
          AND si.status = :status
        ORDER BY si.settlement_date

    parameter-names:
      - "counterpartyId"
      - "startDate"
      - "endDate"
      - "limit"
      - "status"

  # H2 Database with Enterprise Features (for demo/testing)
  - name: "enterprise-h2-database"
    type: "database"
    source-type: "h2"
    enabled: true
    description: "H2 database configured with enterprise-like features for demonstration"
    tags: ["demo", "h2", "enterprise-features"]

    connection:
      # H2 with enterprise-like parameters
      database: "./target/h2-demo/enterprise_demo;MODE=PostgreSQL;DATABASE_TO_UPPER=FALSE;TRACE_LEVEL_FILE=2;CACHE_SIZE=65536;MULTI_THREADED=TRUE"
      username: "sa"
      password: ""

    # Enterprise-style connection pool for H2
    connection-pool:
      max-size: 50
      min-size: 10
      initial-size: 15
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      leak-detection-threshold: 60000
      connection-test-query: "SELECT 1"
      test-on-borrow: true
      test-while-idle: true

    # Advanced caching for H2
    cache:
      enabled: true
      ttlSeconds: 1800
      maxSize: 25000
      eviction-policy: "LRU"
      statistics-enabled: true
      preload-on-startup: false

    # Health monitoring for H2
    healthCheck:
      enabled: true
      intervalSeconds: 60
      timeoutSeconds: 5
      query: "SELECT COUNT(*) FROM INFORMATION_SCHEMA.TABLES"

    # Demo queries
    queries:
      customerLookup: |
        SELECT customer_id, customer_name, customer_type, tier, region, status
        FROM customers
        WHERE customer_id = :customerId

      customersByRegion: |
        SELECT customer_id, customer_name, tier, status
        FROM customers
        WHERE region = :region
          AND status = :status
        ORDER BY customer_name
        LIMIT :limit

    parameter-names:
      - "customerId"
      - "region"
      - "status"
      - "limit"

# Connection Pool Monitoring Configuration
monitoring:
  enabled: true
  metrics-collection-interval: 30  # seconds

  # Connection Pool Monitoring
  connection-pool:
    enabled: true
    track-metrics:
      - "active-connections"
      - "idle-connections"
      - "pending-requests"
      - "connection-creation-rate"
      - "connection-usage-time"
      - "pool-exhaustion-events"
      - "connection-leak-events"
      - "ssl-handshake-time"

    # Alerting Thresholds
    alerts:
      high-usage-threshold: 0.8      # 80% pool utilization
      connection-leak-threshold: 5   # 5 leaked connections
      slow-query-threshold: 5000     # 5 second query threshold
      ssl-handshake-slow-threshold: 1000  # 1 second SSL handshake

  # High Availability Monitoring
  high-availability:
    enabled: true
    track-metrics:
      - "primary-database-health"
      - "replica-lag-time"
      - "failover-events"
      - "replica-availability"

    alerts:
      replica-lag-threshold: 5000    # 5 seconds
      replica-unavailable-threshold: 2  # 2 replicas unavailable

# Security Configuration
security:
  encryption:
    enabled: true
    algorithm: "AES-256-GCM"
    key-rotation-interval: 86400  # 24 hours
    
  access-control:
    enabled: true
    role-based-access: true
    audit-logging: true
    
  compliance:
    pci-dss-compliant: true
    gdpr-compliant: true
    sox-compliant: true

# Processing configuration
processing:
  continue-on-error: true
  max-errors: 10
  error-handling: "log-and-continue"
  enterprise-features-enabled: true

# Output configuration
output:
  include-connection-metrics: true
  include-ssl-information: true
  include-ha-status: true
  format: "enterprise"
