# Comprehensive Monitoring and Metrics Demo
# Demonstrates enterprise-grade monitoring, metrics collection, and alerting
# Use Case: Production monitoring with comprehensive metrics and alerting

metadata:
  id: "comprehensive-monitoring-metrics-demo"
  name: "Comprehensive Monitoring and Metrics Demo"
  version: "1.0.0"
  description: "Demonstrates enterprise-grade monitoring with comprehensive metrics collection, alerting, and performance tracking"
  type: "external-data-config"
  author: "apex.demo.team@company.com"
  created-date: "2025-01-13"
  tags: ["apex-demo", "monitoring", "metrics", "alerting", "performance"]

# Data source with comprehensive monitoring
data-sources:
  - name: "monitored-trading-system"
    type: "database"
    source-type: "h2"
    enabled: true
    description: "Trading system database with comprehensive monitoring and metrics collection"
    tags: ["production", "monitored", "trading"]

    connection:
      database: "./target/h2-demo/apex_demo_shared"
      username: "sa"
      password: ""

    # Connection pool with monitoring
    connection-pool:
      max-size: 50
      min-size: 10
      initial-size: 15
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      leak-detection-threshold: 60000

    # Comprehensive monitoring configuration
    monitoring:
      enabled: true
      metrics-collection-interval: 30  # seconds
      
      # Database operation metrics
      database-metrics:
        enabled: true
        collect-query-metrics: true
        collect-connection-metrics: true
        collect-transaction-metrics: true
        
        # Query performance metrics
        query-metrics:
          - "query-execution-time"
          - "query-success-rate"
          - "query-failure-rate"
          - "slow-query-count"
          - "query-throughput"
          - "parameter-binding-time"
          - "result-processing-time"
        
        # Connection pool metrics
        connection-metrics:
          - "active-connections"
          - "idle-connections"
          - "pending-requests"
          - "connection-creation-rate"
          - "connection-usage-time"
          - "pool-exhaustion-events"
          - "connection-leak-events"
        
        # Transaction metrics
        transaction-metrics:
          - "transaction-count"
          - "transaction-duration"
          - "rollback-rate"
          - "deadlock-count"

    # Cache monitoring
    cache:
      enabled: true
      ttlSeconds: 300
      maxSize: 10000
      eviction-policy: "LRU"
      statistics-enabled: true
      
      # Cache-specific monitoring
      cache-monitoring:
        enabled: true
        track-metrics:
          - "cache-hit-ratio"
          - "cache-miss-ratio"
          - "cache-eviction-rate"
          - "cache-size-utilization"
          - "cache-memory-usage"
          - "cache-load-time"

    # Health monitoring with detailed checks
    healthCheck:
      enabled: true
      intervalSeconds: 30
      timeoutSeconds: 10
      
      health-validation:
        queries:
          - name: "basic-connectivity"
            query: "SELECT 1"
            timeout: 5
            critical: true
            
          - name: "data-availability"
            query: "SELECT COUNT(*) FROM trades WHERE trade_date >= CURRENT_DATE - 1"
            timeout: 10
            critical: true
            expected-result-validation:
              min-count: 1
              
          - name: "performance-benchmark"
            query: "SELECT AVG(quantity * price) FROM trades WHERE trade_date >= CURRENT_DATE - 7"
            timeout: 15
            critical: false

    queries:
      tradeMetrics: |
        SELECT 
          COUNT(*) as trade_count,
          AVG(quantity * price) as avg_trade_value,
          MAX(quantity * price) as max_trade_value,
          MIN(quantity * price) as min_trade_value
        FROM trades
        WHERE trade_date >= :startDate
          AND trade_date <= :endDate

    parameter-names:
      - "startDate"
      - "endDate"

# Comprehensive System Monitoring Configuration
system-monitoring:
  enabled: true
  collection-interval: 60  # seconds
  
  # Application Performance Monitoring (APM)
  apm:
    enabled: true
    trace-sampling-rate: 0.1  # 10% sampling
    
    # Performance metrics
    performance-metrics:
      - "request-throughput"
      - "response-time-percentiles"
      - "error-rate"
      - "cpu-utilization"
      - "memory-utilization"
      - "gc-metrics"
      - "thread-pool-metrics"
    
    # Business metrics
    business-metrics:
      - "trades-processed-per-minute"
      - "settlement-success-rate"
      - "enrichment-processing-time"
      - "validation-failure-rate"

  # Infrastructure Monitoring
  infrastructure:
    enabled: true
    
    # System resource metrics
    system-metrics:
      - "cpu-usage"
      - "memory-usage"
      - "disk-usage"
      - "network-io"
      - "file-descriptors"
      - "process-count"
    
    # JVM metrics
    jvm-metrics:
      - "heap-memory-usage"
      - "non-heap-memory-usage"
      - "garbage-collection-time"
      - "garbage-collection-count"
      - "thread-count"
      - "class-loading-count"

  # Custom Business Metrics
  custom-metrics:
    enabled: true
    
    # Trading system specific metrics
    trading-metrics:
      - name: "daily-trade-volume"
        type: "GAUGE"
        description: "Total daily trading volume"
        unit: "USD"
        
      - name: "settlement-processing-rate"
        type: "COUNTER"
        description: "Number of settlements processed"
        unit: "count"
        
      - name: "enrichment-latency"
        type: "HISTOGRAM"
        description: "Data enrichment processing latency"
        unit: "milliseconds"
        
      - name: "validation-errors"
        type: "COUNTER"
        description: "Number of validation errors"
        unit: "count"

# Alerting Configuration
alerting:
  enabled: true
  
  # Alert channels
  notification-channels:
    - name: "console"
      type: "CONSOLE"
      enabled: true
      
    - name: "log-file"
      type: "LOG_FILE"
      enabled: true
      log-path: "./target/alerts.log"
      
    - name: "email"
      type: "EMAIL"
      enabled: false  # Disabled for demo
      smtp-host: "smtp.company.com"
      recipients: ["ops-team@company.com"]

  # Performance alerts
  performance-alerts:
    - name: "high-response-time"
      condition: "avg_response_time > 5000"  # 5 seconds
      severity: "WARNING"
      threshold-duration: 300  # 5 minutes
      notification-channels: ["console", "log-file"]
      description: "Average response time is higher than expected"
      
    - name: "low-throughput"
      condition: "request_throughput < 10"  # 10 requests per second
      severity: "CRITICAL"
      threshold-duration: 180  # 3 minutes
      notification-channels: ["console", "log-file"]
      description: "Request throughput is critically low"
      
    - name: "high-error-rate"
      condition: "error_rate > 0.05"  # 5% error rate
      severity: "CRITICAL"
      threshold-duration: 120  # 2 minutes
      notification-channels: ["console", "log-file"]
      description: "Error rate is above acceptable threshold"

  # Resource alerts
  resource-alerts:
    - name: "high-cpu-usage"
      condition: "cpu_utilization > 0.8"  # 80% CPU
      severity: "WARNING"
      threshold-duration: 300  # 5 minutes
      notification-channels: ["console", "log-file"]
      description: "CPU utilization is high"
      
    - name: "high-memory-usage"
      condition: "memory_utilization > 0.85"  # 85% memory
      severity: "CRITICAL"
      threshold-duration: 180  # 3 minutes
      notification-channels: ["console", "log-file"]
      description: "Memory utilization is critically high"
      
    - name: "low-disk-space"
      condition: "disk_usage > 0.9"  # 90% disk usage
      severity: "CRITICAL"
      threshold-duration: 60  # 1 minute
      notification-channels: ["console", "log-file"]
      description: "Disk space is critically low"

  # Business alerts
  business-alerts:
    - name: "low-trade-volume"
      condition: "daily_trade_volume < 1000000"  # $1M daily volume
      severity: "WARNING"
      threshold-duration: 3600  # 1 hour
      notification-channels: ["console", "log-file"]
      description: "Daily trade volume is below expected threshold"
      
    - name: "high-settlement-failures"
      condition: "settlement_failure_rate > 0.02"  # 2% failure rate
      severity: "CRITICAL"
      threshold-duration: 300  # 5 minutes
      notification-channels: ["console", "log-file"]
      description: "Settlement failure rate is above acceptable threshold"

# Metrics Export Configuration
metrics-export:
  enabled: true
  
  # Export formats
  exporters:
    - name: "prometheus"
      type: "PROMETHEUS"
      enabled: true
      endpoint: "/metrics"
      port: 9090
      
    - name: "json-file"
      type: "JSON_FILE"
      enabled: true
      file-path: "./target/metrics.json"
      export-interval: 300  # 5 minutes
      
    - name: "csv-file"
      type: "CSV_FILE"
      enabled: true
      file-path: "./target/metrics.csv"
      export-interval: 3600  # 1 hour

# Dashboard Configuration
dashboards:
  enabled: true
  
  # Performance dashboard
  performance-dashboard:
    enabled: true
    refresh-interval: 30  # seconds
    
    panels:
      - name: "Response Time"
        type: "LINE_CHART"
        metrics: ["avg_response_time", "p95_response_time", "p99_response_time"]
        
      - name: "Throughput"
        type: "GAUGE"
        metrics: ["request_throughput"]
        
      - name: "Error Rate"
        type: "SINGLE_STAT"
        metrics: ["error_rate"]

  # System dashboard
  system-dashboard:
    enabled: true
    refresh-interval: 60  # seconds
    
    panels:
      - name: "CPU Usage"
        type: "GAUGE"
        metrics: ["cpu_utilization"]
        
      - name: "Memory Usage"
        type: "GAUGE"
        metrics: ["memory_utilization"]
        
      - name: "Database Connections"
        type: "LINE_CHART"
        metrics: ["active_connections", "idle_connections"]

# Processing configuration
processing:
  continue-on-error: true
  max-errors: 10
  error-handling: "log-and-continue"
  monitoring-enabled: true

# Output configuration
output:
  include-metrics: true
  include-performance-data: true
  include-alert-status: true
  format: "enhanced"
