# Multi-Level Caching Strategy Demo
# Demonstrates comprehensive multi-level caching architecture
# Use Case: Enterprise-grade caching with multiple cache levels and strategies

metadata:
  id: "multi-level-caching-strategy-demo"
  name: "Multi-Level Caching Strategy Demo"
  version: "1.0.0"
  description: "Demonstrates multi-level caching architecture with query result caching, lookup service caching, and application-level caching"
  type: "external-data-config"
  author: "apex.demo.team@company.com"
  created-date: "2025-01-13"
  tags: ["apex-demo", "multi-level-caching", "performance", "architecture"]

# Level 1: Query Result Caching - Database level
data-sources:
  - name: "trading-database-l1-cache"
    type: "database"
    source-type: "h2"
    enabled: true
    description: "Trading database with Level 1 query result caching"
    tags: ["level-1", "query-cache", "database"]

    connection:
      database: "./target/h2-demo/apex_demo_shared"
      username: "sa"
      password: ""

    # Level 1: Query Result Caching
    cache:
      enabled: true
      ttlSeconds: 300  # 5 minutes for frequently changing data
      maxSize: 10000
      eviction-policy: "LFU"  # Least Frequently Used for hot data
      keyPrefix: "l1-query"
      statistics-enabled: true
      
      # Level 1 specific configuration
      cache-level: "QUERY_RESULT"
      cache-scope: "DATABASE"
      invalidation-strategy: "TTL_BASED"
      compression-enabled: true

    queries:
      frequentTradeQuery: |
        SELECT trade_id, counterparty_id, instrument_id, quantity, price
        FROM trades
        WHERE counterparty_id = :counterpartyId
          AND trade_date >= :startDate
        ORDER BY trade_date DESC
        LIMIT :limit

    parameter-names:
      - "counterpartyId"
      - "startDate"
      - "limit"

    healthCheck:
      enabled: true
      query: "SELECT COUNT(*) FROM trades"
      timeout: 5000

  - name: "reference-data-database-l1-cache"
    type: "database"
    source-type: "h2"
    enabled: true
    description: "Reference data database with Level 1 caching for static data"
    tags: ["level-1", "reference-data", "static"]

    connection:
      database: "./target/h2-demo/apex_demo_shared"
      username: "sa"
      password: ""

    # Level 1: Different cache strategy for reference data
    cache:
      enabled: true
      ttlSeconds: 3600  # 1 hour for reference data
      maxSize: 5000
      eviction-policy: "LRU"  # Least Recently Used for reference data
      keyPrefix: "l1-ref"
      statistics-enabled: true
      preload-on-startup: true  # Preload reference data
      
      # Reference data specific configuration
      cache-level: "QUERY_RESULT"
      cache-scope: "REFERENCE_DATA"
      invalidation-strategy: "MANUAL"
      compression-enabled: false  # Small reference data

    queries:
      counterpartyLookup: |
        SELECT counterparty_id, counterparty_name, counterparty_type, jurisdiction
        FROM counterparties
        WHERE counterparty_id = :counterpartyId

    parameter-names:
      - "counterpartyId"

# Level 2: Lookup Service Caching - Enrichment level
enrichments:
  - id: "settlement-lookup-l2-cache"
    name: "Settlement Lookup with Level 2 Caching"
    description: "Level 2 caching at enrichment service level for processed results"
    type: "lookup-enrichment"
    enabled: true
    condition: "#counterpartyId != null"
    
    lookup-config:
      lookup-key: "#counterpartyId"
      lookup-dataset:
        type: "database"
        connection-name: "trading-database-l1-cache"
        query: |
          SELECT trade_id, counterparty_id, instrument_id, quantity, price
          FROM trades
          WHERE counterparty_id = :counterpartyId
        parameters:
          - field: "counterpartyId"
            type: "string"
      
      # Level 2: Lookup Service Caching
      cache:
        enabled: true
        ttlSeconds: 1800  # 30 minutes for reference data
        maxSize: 5000
        eviction-policy: "LFU"  # Least Frequently Used
        keyPrefix: "l2-lookup"
        statistics-enabled: true
        
        # Cache at enrichment level for processed results
        cache-processed-results: true
        cache-level: "LOOKUP_SERVICE"
        cache-scope: "ENRICHMENT"
        invalidation-strategy: "TTL_BASED"

    field-mappings:
      - source-field: "TRADE_ID"
        target-field: "tradeId"
        required: true
      - source-field: "COUNTERPARTY_ID"
        target-field: "counterpartyId"
        required: true
      - source-field: "INSTRUMENT_ID"
        target-field: "instrumentId"
        required: true

  - id: "reference-data-lookup-l2-cache"
    name: "Reference Data Lookup with Level 2 Caching"
    description: "Level 2 caching for reference data enrichment"
    type: "lookup-enrichment"
    enabled: true
    condition: "#counterpartyId != null"
    
    lookup-config:
      lookup-key: "#counterpartyId"
      lookup-dataset:
        type: "database"
        connection-name: "reference-data-database-l1-cache"
        query: |
          SELECT counterparty_id, counterparty_name, counterparty_type, jurisdiction
          FROM counterparties
          WHERE counterparty_id = :counterpartyId
        parameters:
          - field: "counterpartyId"
            type: "string"
      
      # Level 2: Different cache strategy for reference data
      cache:
        enabled: true
        ttlSeconds: 7200  # 2 hours for reference data
        maxSize: 2000
        eviction-policy: "LRU"
        keyPrefix: "l2-ref"
        statistics-enabled: true
        preload-on-startup: true
        
        cache-processed-results: true
        cache-level: "LOOKUP_SERVICE"
        cache-scope: "REFERENCE_DATA"
        invalidation-strategy: "MANUAL"

    field-mappings:
      - source-field: "COUNTERPARTY_NAME"
        target-field: "counterpartyName"
        required: true
      - source-field: "COUNTERPARTY_TYPE"
        target-field: "counterpartyType"
        required: true
      - source-field: "JURISDICTION"
        target-field: "jurisdiction"
        required: true

# Level 3: Application-Level Caching
cache-sources:
  - name: "demo-lookup-cache"
    type: "CACHE"
    enabled: true
    description: "Level 3 application-level cache for static reference data"
    tags: ["level-3", "application-cache", "static-data"]
    
    properties:
      max-size: 2000
      ttl-seconds: 7200  # 2 hours for static reference data
      eviction-policy: "LFU"  # Least Frequently Used
      statistics-enabled: true
      preload-on-startup: true
      
      # Level 3 specific configuration
      cache-level: "APPLICATION"
      cache-scope: "GLOBAL"
      cache-type: "DISTRIBUTED"
      invalidation-strategy: "EVENT_BASED"
      
      # Distributed cache configuration
      distributed-cache:
        enabled: true
        cluster-nodes:
          - "localhost:6379"
        replication-factor: 1
        consistency-level: "EVENTUAL"

  - name: "session-cache"
    type: "CACHE"
    enabled: true
    description: "Level 3 session-specific cache for user data"
    tags: ["level-3", "session-cache", "user-data"]
    
    properties:
      max-size: 1000
      ttl-seconds: 1800  # 30 minutes for session data
      eviction-policy: "LRU"  # Least Recently Used for session data
      statistics-enabled: true
      preload-on-startup: false
      
      # Session cache specific configuration
      cache-level: "APPLICATION"
      cache-scope: "SESSION"
      cache-type: "LOCAL"
      invalidation-strategy: "TTL_BASED"

  - name: "computation-cache"
    type: "CACHE"
    enabled: true
    description: "Level 3 cache for expensive computations"
    tags: ["level-3", "computation-cache", "expensive-operations"]
    
    properties:
      max-size: 500
      ttl-seconds: 3600  # 1 hour for computation results
      eviction-policy: "LFU"  # Keep frequently used computations
      statistics-enabled: true
      preload-on-startup: false
      
      # Computation cache specific configuration
      cache-level: "APPLICATION"
      cache-scope: "COMPUTATION"
      cache-type: "HYBRID"  # Local + distributed
      invalidation-strategy: "DEPENDENCY_BASED"

# Multi-Level Cache Coordination
cache-coordination:
  enabled: true
  
  # Cache hierarchy configuration
  cache-hierarchy:
    - level: 1
      name: "Query Result Cache"
      scope: "DATABASE"
      priority: "HIGH"
      
    - level: 2
      name: "Lookup Service Cache"
      scope: "ENRICHMENT"
      priority: "MEDIUM"
      
    - level: 3
      name: "Application Cache"
      scope: "GLOBAL"
      priority: "LOW"

  # Cache invalidation coordination
  invalidation-coordination:
    enabled: true
    cascade-invalidation: true
    invalidation-events:
      - "DATA_UPDATE"
      - "SCHEMA_CHANGE"
      - "MANUAL_REFRESH"

  # Cache warming strategies
  cache-warming:
    enabled: true
    warming-strategies:
      - strategy: "PRELOAD_REFERENCE_DATA"
        target-caches: ["l1-ref", "l2-ref", "demo-lookup-cache"]
        schedule: "0 0 6 * * ?"  # Daily at 6 AM
        
      - strategy: "PREDICTIVE_WARMING"
        target-caches: ["l1-query", "l2-lookup"]
        based-on: "USAGE_PATTERNS"

# Cache Performance Monitoring
cache-monitoring:
  enabled: true
  metrics-collection-interval: 60  # seconds
  
  # Multi-level cache metrics
  track-metrics:
    - "cache-hit-ratio-by-level"
    - "cache-miss-ratio-by-level"
    - "cache-eviction-rate-by-level"
    - "cache-size-utilization-by-level"
    - "cross-level-cache-efficiency"
    - "cache-warming-effectiveness"

  # Performance alerts
  alerts:
    - name: "low-l1-hit-ratio"
      condition: "l1_cache_hit_ratio < 0.7"
      severity: "WARNING"
      
    - name: "low-l2-hit-ratio"
      condition: "l2_cache_hit_ratio < 0.8"
      severity: "WARNING"
      
    - name: "low-l3-hit-ratio"
      condition: "l3_cache_hit_ratio < 0.9"
      severity: "WARNING"

# Processing configuration
processing:
  continue-on-error: true
  max-errors: 5
  error-handling: "log-and-continue"
  multi-level-caching-enabled: true

# Output configuration
output:
  include-cache-statistics: true
  include-multi-level-metrics: true
  include-cache-coordination-info: true
  format: "enhanced"
