name: "Rule Config Data Source Verifier Configuration"
description: "APEX-compliant rule config data source verifier processing with real business logic"
version: "1.0"

enrichments:
  - id: "rule-config-verification"
    name: "rule-config-verification"
    type: "calculation-enrichment"
    description: "Verify rule configuration with comprehensive rule config validation and structure analysis"
    condition: "#ruleConfigVerificationType != null && #ruleConfigVerificationScope != null"
    calculation-config:
      expression: "'Rule Config Verification: ' + #ruleConfigVerificationType + ' with scope ' + #ruleConfigVerificationScope + ' (Verified: ' + T(java.time.LocalDateTime).now().toString() + ')'"
      result-field: "ruleConfigVerificationResult"
    field-mappings:
      - source-field: "ruleConfigVerificationResult"
        target-field: "ruleConfigVerificationResult"

  - id: "database-verification"
    name: "database-verification"
    type: "calculation-enrichment"
    description: "Verify PostgreSQL database connectivity and rule config table validation"
    condition: "#databaseVerificationType != null && #databaseVerificationScope != null"
    calculation-config:
      expression: "'Database Verification: ' + #databaseVerificationType + ' with scope ' + #databaseVerificationScope + ' (Verified: ' + T(java.time.LocalDateTime).now().toString() + ')'"
      result-field: "databaseVerificationResult"
    field-mappings:
      - source-field: "databaseVerificationResult"
        target-field: "databaseVerificationResult"

  - id: "external-dataset-verification"
    name: "external-dataset-verification"
    type: "calculation-enrichment"
    description: "Verify external YAML dataset structure and rule configuration validation"
    condition: "#externalDatasetVerificationType != null && #externalDatasetVerificationScope != null"
    calculation-config:
      expression: "'External Dataset Verification: ' + #externalDatasetVerificationType + ' with scope ' + #externalDatasetVerificationScope + ' (Verified: ' + T(java.time.LocalDateTime).now().toString() + ')'"
      result-field: "externalDatasetVerificationResult"
    field-mappings:
      - source-field: "externalDatasetVerificationResult"
        target-field: "externalDatasetVerificationResult"

  - id: "summary"
    name: "summary"
    type: "calculation-enrichment"
    description: "Generate comprehensive rule config data source verifier summary with verification audit trail"
    condition: "#approach != null"
    calculation-config:
      expression: "'Rule Config Data Source Verifier Summary: Processing completed using ' + #approach + ' (Summary: ' + T(java.time.LocalDateTime).now().toString() + ')'"
      result-field: "ruleConfigDataSourceVerifierSummary"
    field-mappings:
      - source-field: "ruleConfigDataSourceVerifierSummary"
        target-field: "ruleConfigDataSourceVerifierSummary"
