# Comprehensive Financial Settlement Demo Configuration
# Real APEX YAML configuration for ComprehensiveFinancialSettlementDemo.java
# NO HARDCODED SIMULATION - Uses authentic APEX services

metadata:
  name: "Comprehensive Financial Settlement Demo Configuration"
  version: "2.0.0"
  description: "Real APEX comprehensive financial settlement demonstration with multi-asset processing, cross-border settlement, and high-value transaction handling"
  type: "rule-config"
  author: "apex.demo.team@company.com"
  created-date: "2024-12-24"
  tags: ["apex-demo", "enrichment", "financial", "settlement"]

# Data sources for comprehensive financial settlement
data-sources:
  - name: "settlement-config"
    type: "inline"
    description: "Settlement configuration data source"

# Multi-Asset Settlement Processing Enrichments
enrichments:
  - id: "multi-asset-settlement-processing"
    name: "multi-asset-settlement-processing"
    type: "calculation-enrichment"
    description: "Multi-asset settlement processing using real APEX services"
    condition: "#data.tradeId != null && #data.assetClass != null"
    expression: "'Settlement processed for ' + #data.assetClass + ' trade ' + #data.tradeId"
    field-mappings:
      - source-field: "expression"
        target-field: "settlementResult"
