# Custody Auto-Repair Demo Configuration
# Real APEX YAML configuration for CustodyAutoRepairDemo.java
# NO HARDCODED SIMULATION - Uses authentic APEX services

metadata:
  name: "Custody Auto-Repair Demo Configuration"
  version: "2.0.0"
  description: "Real APEX custody auto-repair demonstration with settlement instruction processing, standing instruction management, and weighted rule-based decision making"
  type: "rule-config"
  author: "apex.demo.team@company.com"
  created-date: "2024-12-24"
  tags: ["apex-demo", "enrichment", "custody", "auto-repair"]

# Settlement Instruction Auto-Repair Enrichments
enrichments:
  - name: "settlement-instruction-auto-repair"
    type: "auto-repair-enrichment"
    description: "Settlement instruction auto-repair using real APEX processing"
    conditions:
      - condition: "#data.instructionId != null && #data.clientId != null"
        actions:
          - type: "auto-repair-processing"
            repair-rules:
              - field: "counterpartyId"
                condition: "#data.counterpartyId == null"
                repair-action:
                  type: "lookup-repair"
                  lookup-source: "standing-instructions"
                  lookup-key: "#data.clientId + '_' + #data.market"
                  target-field: "defaultCounterpartyId"
              - field: "custodianId"
                condition: "#data.custodianId == null"
                repair-action:
                  type: "lookup-repair"
                  lookup-source: "standing-instructions"
                  lookup-key: "#data.clientId + '_' + #data.market"
                  target-field: "defaultCustodianId"
              - field: "settlementMethod"
                condition: "#data.settlementMethod == null"
                repair-action:
                  type: "default-repair"
                  default-value: "DVP"
              - field: "deliveryInstruction"
                condition: "#data.deliveryInstruction == null"
                repair-action:
                  type: "conditional-repair"
                  conditions:
                    - condition: "#data.instrumentType == 'EQUITY'"
                      value: "DELIVER"
                    - condition: "#data.instrumentType == 'FIXED_INCOME'"
                      value: "DELIVER"
                    - condition: "#data.instrumentType == 'DERIVATIVES'"
                      value: "CASH_SETTLE"
                  default-value: "DELIVER"

  - name: "standing-instruction-processing"
    type: "standing-instruction-enrichment"
    description: "Standing instruction processing with hierarchical prioritization"
    conditions:
      - condition: "#data.siId != null || #data.clientId != null"
        actions:
          - type: "standing-instruction-processing"
            prioritization:
              - level: "CLIENT"
                weight: 0.6
                condition: "#data.clientId != null"
                lookup-key: "#data.clientId"
              - level: "MARKET"
                weight: 0.3
                condition: "#data.market != null"
                lookup-key: "#data.market"
              - level: "INSTRUMENT"
                weight: 0.1
                condition: "#data.instrumentType != null"
                lookup-key: "#data.instrumentType"
            processing-rules:
              - rule: "client-specific-si"
                condition: "#data.clientId != null"
                action:
                  type: "apply-client-si"
                  priority: "HIGH"
                  weight: 0.6
              - rule: "market-specific-si"
                condition: "#data.market != null"
                action:
                  type: "apply-market-si"
                  priority: "MEDIUM"
                  weight: 0.3
              - rule: "instrument-specific-si"
                condition: "#data.instrumentType != null"
                action:
                  type: "apply-instrument-si"
                  priority: "LOW"
                  weight: 0.1

  - name: "weighted-rule-decision-making"
    type: "decision-enrichment"
    description: "Weighted rule-based decision making for auto-repair confidence"
    conditions:
      - condition: "#data.decisionType == 'AUTO_REPAIR'"
        actions:
          - type: "weighted-decision-processing"
            decision-rules:
              - rule: "confidence-calculation"
                expression: "(#data.clientWeight * #clientMatch) + (#data.marketWeight * #marketMatch) + (#data.instrumentWeight * #instrumentMatch)"
                target: "confidenceScore"
              - rule: "decision-threshold"
                condition: "#confidenceScore >= #data.confidenceThreshold"
                action:
                  type: "set-field"
                  field: "autoRepairDecision"
                  value: "APPROVED"
              - rule: "manual-review-required"
                condition: "#confidenceScore < #data.confidenceThreshold"
                action:
                  type: "set-field"
                  field: "autoRepairDecision"
                  value: "MANUAL_REVIEW_REQUIRED"
              - rule: "risk-assessment"
                condition: "#data.riskLevel == 'HIGH'"
                action:
                  type: "set-field"
                  field: "requiresApproval"
                  value: true

# Standing Instructions Dataset - Inline Reference Data
datasets:
  - name: "standing-instructions"
    description: "Standing instructions reference data embedded in YAML"
    key-field: "siKey"
    data:
      # Client-specific Standing Instructions (Highest Priority - Weight: 0.6)
      - siKey: "CLIENT_A_JAPAN"
        siId: "SI_CLIENT_A"
        clientId: "CLIENT_A"
        market: "JAPAN"
        priority: "HIGH"
        weight: 0.6
        defaultCounterpartyId: "CP_CLIENT_A_DEFAULT"
        defaultCustodianId: "CUST_CLIENT_A"
        defaultSettlementMethod: "DVP"
        defaultDeliveryInstruction: "DELIVER"
      - siKey: "PREMIUM_CLIENT_X_JAPAN"
        siId: "SI_PREMIUM_X"
        clientId: "PREMIUM_CLIENT_X"
        market: "JAPAN"
        priority: "HIGH"
        weight: 0.6
        defaultCounterpartyId: "CP_PREMIUM_X_DEFAULT"
        defaultCustodianId: "CUST_PREMIUM_GLOBAL"
        defaultSettlementMethod: "DVP_PREMIUM"
        defaultDeliveryInstruction: "DELIVER"
      
      # Market-specific Standing Instructions (Medium Priority - Weight: 0.3)
      - siKey: "JAPAN"
        siId: "SI_JAPAN"
        market: "JAPAN"
        priority: "MEDIUM"
        weight: 0.3
        defaultCounterpartyId: "CP_JAPAN_STANDARD"
        defaultCustodianId: "CUST_JAPAN_DEFAULT"
        defaultSettlementMethod: "DVP"
        defaultDeliveryInstruction: "DELIVER"
      - siKey: "HONG_KONG"
        siId: "SI_HONG_KONG"
        market: "HONG_KONG"
        priority: "MEDIUM"
        weight: 0.3
        defaultCounterpartyId: "CP_HK_STANDARD"
        defaultCustodianId: "CUST_HK_STANDARD"
        defaultSettlementMethod: "DVP"
        defaultDeliveryInstruction: "DELIVER"
      - siKey: "SINGAPORE"
        siId: "SI_SINGAPORE"
        market: "SINGAPORE"
        priority: "MEDIUM"
        weight: 0.3
        defaultCounterpartyId: "CP_SG_STANDARD"
        defaultCustodianId: "CUST_SG_STANDARD"
        defaultSettlementMethod: "DVP"
        defaultDeliveryInstruction: "DELIVER"
      - siKey: "KOREA"
        siId: "SI_KOREA"
        market: "KOREA"
        priority: "MEDIUM"
        weight: 0.3
        defaultCounterpartyId: "CP_KR_STANDARD"
        defaultCustodianId: "CUST_KR_STANDARD"
        defaultSettlementMethod: "DVP"
        defaultDeliveryInstruction: "DELIVER"
      
      # Instrument-specific Standing Instructions (Lowest Priority - Weight: 0.1)
      - siKey: "EQUITY"
        siId: "SI_EQUITY"
        instrumentType: "EQUITY"
        priority: "LOW"
        weight: 0.1
        defaultSettlementMethod: "DVP"
        defaultDeliveryInstruction: "DELIVER"
      - siKey: "FIXED_INCOME"
        siId: "SI_FIXED_INCOME"
        instrumentType: "FIXED_INCOME"
        priority: "LOW"
        weight: 0.1
        defaultSettlementMethod: "DVP"
        defaultDeliveryInstruction: "DELIVER"
      - siKey: "DERIVATIVES"
        siId: "SI_DERIVATIVES"
        instrumentType: "DERIVATIVES"
        priority: "LOW"
        weight: 0.1
        defaultSettlementMethod: "CASH_SETTLE"
        defaultDeliveryInstruction: "CASH_SETTLE"

  - name: "market-conventions"
    description: "Market-specific settlement conventions"
    key-field: "market"
    data:
      - market: "JAPAN"
        settlementCycle: "T+2"
        currency: "JPY"
        timezone: "JST"
        businessDays: ["MONDAY", "TUESDAY", "WEDNESDAY", "THURSDAY", "FRIDAY"]
        holidays: ["NEW_YEAR", "GOLDEN_WEEK"]
      - market: "HONG_KONG"
        settlementCycle: "T+2"
        currency: "HKD"
        timezone: "HKT"
        businessDays: ["MONDAY", "TUESDAY", "WEDNESDAY", "THURSDAY", "FRIDAY"]
        holidays: ["CHINESE_NEW_YEAR", "NATIONAL_DAY"]
      - market: "SINGAPORE"
        settlementCycle: "T+2"
        currency: "SGD"
        timezone: "SGT"
        businessDays: ["MONDAY", "TUESDAY", "WEDNESDAY", "THURSDAY", "FRIDAY"]
        holidays: ["NATIONAL_DAY", "CHINESE_NEW_YEAR"]
      - market: "KOREA"
        settlementCycle: "T+2"
        currency: "KRW"
        timezone: "KST"
        businessDays: ["MONDAY", "TUESDAY", "WEDNESDAY", "THURSDAY", "FRIDAY"]
        holidays: ["LUNAR_NEW_YEAR", "NATIONAL_FOUNDATION_DAY"]

# Processing Configuration
processing:
  fail-fast: true
  enable-logging: true
  max-processing-time: 60000
  auto-repair-enabled: true
  confidence-threshold: 0.8
  
# Auto-Repair Configuration
auto-repair:
  enable-client-priority: true
  enable-market-fallback: true
  enable-instrument-fallback: true
  require-approval-threshold: 0.9
  manual-review-threshold: 0.5
  
# Output Configuration
output:
  format: "json"
  include-metadata: true
  include-processing-time: true
  include-confidence-score: true
  include-repair-audit-trail: true

