# Data Management Demo Configuration
# Real APEX YAML configuration for DataManagementDemo.java
# NO HARDCODED SIMULATION - Uses authentic APEX services

metadata:
  name: "Data Management Demo Configuration"
  version: "2.0"
  description: "Real APEX data management demonstration with dataset structure, enrichment, validation, and error handling"
  author: "APEX Demo Team"
  created: "2025-08-29"

# Basic Dataset Structure Enrichments
enrichments:
  - id: "basic-dataset-structure-processing"
    name: "basic-dataset-structure-processing"
    type: "field-enrichment"
    description: "Basic dataset structure processing using real APEX services"
    conditions:
      - condition: "#processingType == 'BASIC_DATASET'"
        actions:
          - type: "dataset-processing"
            dataset-operations:
              - operation: "currency-lookup"
                condition: "#currency != null"
                action:
                  type: "set-field"
                  field: "currencyName"
                  value: "#currency == 'USD' ? 'US Dollar' : (#currency == 'EUR' ? 'Euro' : (#currency == 'GBP' ? 'British Pound' : 'Unknown Currency'))"
                message: "Currency lookup for dataset structure"
              - operation: "amount-validation"
                condition: "#amount != null && #amount > 0"
                action:
                  type: "set-field"
                  field: "amountValid"
                  value: true
                message: "Amount validation for dataset structure"
              - operation: "customer-classification"
                condition: "#customerId != null"
                action:
                  type: "set-field"
                  field: "customerType"
                  value: "#customerId.startsWith('CUST') ? 'STANDARD_CUSTOMER' : 'UNKNOWN_CUSTOMER'"
                message: "Customer classification for dataset structure"
            processing-metadata:
              processing-type: "BASIC_DATASET"
              complexity: "LOW"
              dataset-operations: 3

  - id: "simple-data-enrichment-processing"
    name: "simple-data-enrichment-processing"
    type: "lookup-enrichment"
    description: "Simple data enrichment with lookup operations"
    conditions:
      - condition: "#processingType == 'SIMPLE_ENRICHMENT'"
        actions:
          - type: "simple-enrichment-processing"
            enrichment-operations:
              - operation: "product-lookup"
                condition: "#productId != null"
                action:
                  type: "set-field"
                  field: "productName"
                  value: "#productId == 'LAPTOP001' ? 'Business Laptop' : (#productId == 'DESKTOP001' ? 'Business Desktop' : 'Unknown Product')"
                message: "Product lookup for simple enrichment"
              - operation: "quantity-validation"
                condition: "#quantity != null && #quantity > 0"
                action:
                  type: "set-field"
                  field: "quantityValid"
                  value: true
                message: "Quantity validation for simple enrichment"
              - operation: "customer-enrichment"
                condition: "#customerId != null"
                action:
                  type: "set-field"
                  field: "customerStatus"
                  value: "#customerId == 'CUST001' ? 'ACTIVE' : 'INACTIVE'"
                message: "Customer enrichment for simple processing"
            processing-metadata:
              processing-type: "SIMPLE_ENRICHMENT"
              complexity: "MEDIUM"
              enrichment-operations: 3

  - id: "complex-data-enrichment-processing"
    name: "complex-data-enrichment-processing"
    type: "calculation-enrichment"
    description: "Complex data enrichment with nested structures and mappings"
    conditions:
      - condition: "#processingType == 'COMPLEX_ENRICHMENT'"
        actions:
          - type: "complex-enrichment-processing"
            complex-operations:
              - operation: "order-enrichment"
                condition: "#orderId != null && #customerId != null && #productId != null"
                actions:
                  - type: "set-field"
                    field: "orderStatus"
                    value: "PROCESSING"
                  - type: "set-field"
                    field: "orderType"
                    value: "STANDARD_ORDER"
                  - type: "set-field"
                    field: "priorityLevel"
                    value: "#amount > 2000 ? 'HIGH' : 'NORMAL'"
                message: "Complex order enrichment with multiple fields"
              - operation: "pricing-calculation"
                condition: "#quantity != null && #amount != null"
                actions:
                  - type: "set-field"
                    field: "unitPrice"
                    value: "#amount / #quantity"
                  - type: "set-field"
                    field: "totalValue"
                    value: "#amount"
                  - type: "set-field"
                    field: "discountEligible"
                    value: "#amount > 2000"
                message: "Complex pricing calculation with derived fields"
              - operation: "fulfillment-planning"
                condition: "#productId != null && #quantity != null"
                actions:
                  - type: "set-field"
                    field: "estimatedDelivery"
                    value: "3-5_BUSINESS_DAYS"
                  - type: "set-field"
                    field: "warehouseLocation"
                    value: "CENTRAL_WAREHOUSE"
                  - type: "set-field"
                    field: "shippingMethod"
                    value: "#amount > 2000 ? 'EXPRESS' : 'STANDARD'"
                message: "Complex fulfillment planning with logistics"
            processing-metadata:
              processing-type: "COMPLEX_ENRICHMENT"
              complexity: "HIGH"
              complex-operations: 3

  - id: "multi-dataset-scenarios-processing"
    name: "multi-dataset-scenarios-processing"
    type: "lookup-enrichment"
    description: "Multi-dataset scenarios with relationships and cross-references"
    conditions:
      - condition: "#processingType == 'MULTI_DATASET'"
        actions:
          - type: "multi-dataset-processing"
            dataset-relationships:
              - relationship: "transaction-currency-product"
                datasets: ["transaction", "currency", "product"]
                operations:
                  - operation: "cross-reference-validation"
                    condition: "#transactionId != null && #currency != null && #productId != null"
                    action:
                      type: "set-field"
                      field: "crossReferenceValid"
                      value: true
                    message: "Cross-reference validation across multiple datasets"
                  - operation: "currency-product-compatibility"
                    condition: "#currency == 'USD' && #productId.startsWith('LAPTOP')"
                    action:
                      type: "set-field"
                      field: "currencyProductCompatible"
                      value: true
                    message: "Currency and product compatibility check"
                  - operation: "customer-transaction-history"
                    condition: "#customerId != null && #amount != null"
                    action:
                      type: "set-field"
                      field: "customerTransactionProfile"
                      value: "#amount > 1000 ? 'HIGH_VALUE_CUSTOMER' : 'STANDARD_CUSTOMER'"
                    message: "Customer transaction history analysis"
            processing-metadata:
              processing-type: "MULTI_DATASET"
              complexity: "HIGH"
              dataset-relationships: 1
              cross-references: 3

  - id: "validation-with-enriched-data-processing"
    name: "validation-with-enriched-data-processing"
    type: "field-enrichment"
    description: "Validation with enriched data and quality assurance"
    conditions:
      - condition: "#processingType == 'VALIDATION_ENRICHED'"
        actions:
          - type: "validation-enriched-processing"
            validation-rules:
              - rule: "currency-validation"
                condition: "#currency != null"
                validations:
                  - validation: "currency-format"
                    condition: "#currency.length() == 3"
                    action:
                      type: "set-field"
                      field: "currencyFormatValid"
                      value: true
                    message: "Currency format validation (3-letter code)"
                  - validation: "currency-supported"
                    condition: "#currency == 'USD' || #currency == 'EUR' || #currency == 'GBP'"
                    action:
                      type: "set-field"
                      field: "currencySupported"
                      value: true
                    message: "Currency support validation"
              - rule: "amount-validation"
                condition: "#amount != null"
                validations:
                  - validation: "amount-positive"
                    condition: "#amount > 0"
                    action:
                      type: "set-field"
                      field: "amountPositive"
                      value: true
                    message: "Amount must be positive"
                  - validation: "amount-reasonable"
                    condition: "#amount <= 1000000"
                    action:
                      type: "set-field"
                      field: "amountReasonable"
                      value: true
                    message: "Amount must be within reasonable limits"
            processing-metadata:
              processing-type: "VALIDATION_ENRICHED"
              complexity: "MEDIUM"
              validation-rules: 2
              total-validations: 4

  - id: "error-handling-and-defaults-processing"
    name: "error-handling-and-defaults-processing"
    type: "field-enrichment"
    description: "Error handling and default value strategies"
    conditions:
      - condition: "#processingType == 'ERROR_HANDLING'"
        actions:
          - type: "error-handling-processing"
            error-handling-strategies:
              - strategy: "unknown-currency-handling"
                condition: "#currency == 'UNKNOWN' || #currency == null"
                actions:
                  - type: "set-field"
                    field: "currencyName"
                    value: "Unknown Currency"
                  - type: "set-field"
                    field: "currencyActive"
                    value: false
                  - type: "set-field"
                    field: "currencyRegion"
                    value: "UNKNOWN"
                  - type: "set-field"
                    field: "errorHandled"
                    value: true
                message: "Handle unknown currency with default values"
              - strategy: "missing-amount-handling"
                condition: "#amount == null"
                actions:
                  - type: "set-field"
                    field: "amount"
                    value: 0.0
                  - type: "set-field"
                    field: "amountDefaulted"
                    value: true
                  - type: "set-field"
                    field: "errorHandled"
                    value: true
                message: "Handle missing amount with default value"
              - strategy: "default-values-application"
                condition: "#requireDefaults == true"
                actions:
                  - type: "set-field"
                    field: "defaultsApplied"
                    value: true
                  - type: "set-field"
                    field: "processingStatus"
                    value: "COMPLETED_WITH_DEFAULTS"
                  - type: "set-field"
                    field: "qualityScore"
                    value: 0.7
                message: "Apply default values and quality scoring"
            processing-metadata:
              processing-type: "ERROR_HANDLING"
              complexity: "HIGH"
              error-strategies: 3
              resilience-level: "HIGH"

# Data Management Configuration
data-management-config:
  basic-dataset:
    description: "Basic dataset structure and operations"
    features:
      - "dataset-creation"
      - "metadata-management"
      - "data-validation"
      - "structure-verification"
    performance:
      target-latency: "< 10ms"
      throughput: "HIGH"
      memory-usage: "LOW"
    
  simple-enrichment:
    description: "Simple data enrichment with single-field lookups"
    features:
      - "field-lookup"
      - "data-transformation"
      - "value-mapping"
      - "basic-validation"
    performance:
      target-latency: "< 25ms"
      throughput: "HIGH"
      memory-usage: "MEDIUM"
    
  complex-enrichment:
    description: "Complex data enrichment with multi-field transformations"
    features:
      - "multi-field-processing"
      - "nested-structure-handling"
      - "complex-calculations"
      - "derived-field-creation"
    performance:
      target-latency: "< 100ms"
      throughput: "MEDIUM"
      memory-usage: "HIGH"
    
  multi-dataset:
    description: "Multi-dataset scenarios with relationships"
    features:
      - "cross-dataset-references"
      - "relationship-management"
      - "data-consistency-checks"
      - "referential-integrity"
    performance:
      target-latency: "< 200ms"
      throughput: "MEDIUM"
      memory-usage: "HIGH"
    
  validation-enriched:
    description: "Validation with enriched data and quality assurance"
    features:
      - "enriched-data-validation"
      - "quality-scoring"
      - "completeness-checks"
      - "consistency-validation"
    performance:
      target-latency: "< 50ms"
      throughput: "HIGH"
      memory-usage: "MEDIUM"
    
  error-handling:
    description: "Error handling and default value strategies"
    features:
      - "graceful-degradation"
      - "default-value-application"
      - "error-recovery"
      - "quality-scoring"
    performance:
      target-latency: "< 75ms"
      throughput: "MEDIUM"
      memory-usage: "MEDIUM"

# Processing Configuration
processing:
  fail-fast: false
  enable-logging: true
  max-processing-time: 30000
  data-management-processing: true
  enrichment-processing: true
  validation-processing: true
  error-handling: true
  
# Output Configuration
output:
  format: "json"
  include-metadata: true
  include-processing-time: true
  include-processing-type: true
  include-data-quality-metrics: true
  include-enrichment-details: true

# Error Handling Configuration
error-handling:
  dataset-errors: "collect-and-continue"
  enrichment-errors: "collect-and-continue"
  validation-errors: "collect"
  multi-dataset-errors: "collect-with-fallback"
  default-value-errors: "apply-defaults"
