# YAML Dataset Demo Configuration
# Real APEX YAML configuration for YamlDatasetDemo.java
# NO HARDCODED SIMULATION - Uses authentic APEX services

metadata:
  id: "YAML Dataset Demo Configuration"
  name: "YAML Dataset Demo Configuration"
  version: "2.0.0"
  description: "Real APEX YAML dataset demonstration with inline datasets, field mappings, and conditional processing"
  type: "rule-config"
  author: "apex.demo.team@company.com"
  created-date: "2024-12-24"
  tags: ["apex-demo", "enrichment", "yaml-dataset"]

# Dataset-Based Enrichments with Inline Data
enrichments:
  - id: "currency-dataset-enrichment"
    name: "currency-dataset-enrichment"
    type: "lookup-enrichment"
    description: "Currency enrichment using inline dataset - NO external service required"
    conditions:
      - condition: "#data.currencyCode != null"
        actions:
          - type: "dataset-lookup"
            dataset-name: "currency-reference"
            lookup-key: "#data.currencyCode"
            target-fields:
              - source: "name"
                target: "currencyName"
              - source: "region"
                target: "currencyRegion"
              - source: "symbol"
                target: "currencySymbol"
              - source: "decimalPlaces"
                target: "currencyDecimalPlaces"

  - id: "country-dataset-enrichment"
    name: "country-dataset-enrichment"
    type: "lookup-enrichment"
    description: "Country enrichment using inline dataset"
    conditions:
      - condition: "#data.countryCode != null"
        actions:
          - type: "dataset-lookup"
            dataset-name: "country-reference"
            lookup-key: "#data.countryCode"
            target-fields:
              - source: "name"
                target: "countryName"
              - source: "continent"
                target: "continent"
              - source: "timezone"
                target: "timezone"
              - source: "language"
                target: "primaryLanguage"

  - id: "product-dataset-enrichment"
    name: "product-dataset-enrichment"
    type: "lookup-enrichment"
    description: "Product type enrichment using inline dataset"
    conditions:
      - condition: "#data.productType != null"
        actions:
          - type: "dataset-lookup"
            dataset-name: "product-reference"
            lookup-key: "#data.productType"
            target-fields:
              - source: "category"
                target: "productCategory"
              - source: "riskLevel"
                target: "productRiskLevel"
              - source: "minInvestment"
                target: "minimumInvestment"

  - id: "field-mapping-enrichment"
    name: "field-mapping-enrichment"
    type: "field-mapping-enrichment"
    description: "Field mapping and transformation processing"
    conditions:
      - condition: "#data.sourceField1 != null || #data.sourceField2 != null"
        actions:
          - type: "field-mapping"
            mappings:
              - source: "sourceField1"
                target: "mappedField1"
                transform: "#value.toUpperCase()"
              - source: "sourceField2"
                target: "mappedField2"
                transform: "#value + '_PROCESSED'"
              - source: "transformField"
                target: "transformedField"
                transform: "#value == 'TRANSFORM_ME' ? 'TRANSFORMED' : #value"

  - id: "conditional-dataset-enrichment"
    name: "conditional-dataset-enrichment"
    type: "conditional-enrichment"
    description: "Conditional processing based on data content"
    conditions:
      - condition: "#data.processingType == 'CONDITIONAL'"
        actions:
          - type: "conditional-processing"
            rules:
              - condition: "#data.riskLevel == 'HIGH'"
                action:
                  type: "set-field"
                  field: "processingPath"
                  value: "HIGH_RISK_PROCESSING"
              - condition: "#data.customerTier == 'PREMIUM'"
                action:
                  type: "set-field"
                  field: "customerBenefits"
                  value: "PREMIUM_BENEFITS_APPLIED"
              - condition: "#data.riskLevel == 'HIGH' && #data.customerTier == 'PREMIUM'"
                action:
                  type: "set-field"
                  field: "specialHandling"
                  value: "VIP_HIGH_RISK_PROCESSING"

# Inline Datasets - Revolutionary approach to reference data
datasets:
  - name: "currency-reference"
    description: "Currency reference data embedded in YAML"
    key-field: "code"
    data:
      - code: "USD"
        name: "US Dollar"
        region: "North America"
        symbol: "$"
        decimalPlaces: 2
      - code: "EUR"
        name: "Euro"
        region: "Europe"
        symbol: "€"
        decimalPlaces: 2
      - code: "GBP"
        name: "British Pound"
        region: "Europe"
        symbol: "£"
        decimalPlaces: 2
      - code: "JPY"
        name: "Japanese Yen"
        region: "Asia"
        symbol: "¥"
        decimalPlaces: 0
      - code: "CHF"
        name: "Swiss Franc"
        region: "Europe"
        symbol: "CHF"
        decimalPlaces: 2

  - name: "country-reference"
    description: "Country reference data embedded in YAML"
    key-field: "code"
    data:
      - code: "US"
        name: "United States"
        continent: "North America"
        timezone: "EST/PST"
        language: "English"
      - code: "GB"
        name: "United Kingdom"
        continent: "Europe"
        timezone: "GMT"
        language: "English"
      - code: "DE"
        name: "Germany"
        continent: "Europe"
        timezone: "CET"
        language: "German"
      - code: "JP"
        name: "Japan"
        continent: "Asia"
        timezone: "JST"
        language: "Japanese"
      - code: "CH"
        name: "Switzerland"
        continent: "Europe"
        timezone: "CET"
        language: "German/French/Italian"

  - name: "product-reference"
    description: "Product type reference data embedded in YAML"
    key-field: "type"
    data:
      - type: "EQUITY"
        category: "STOCKS"
        riskLevel: "HIGH"
        minInvestment: 1000
      - type: "BOND"
        category: "FIXED_INCOME"
        riskLevel: "LOW"
        minInvestment: 5000
      - type: "MUTUAL_FUND"
        category: "DIVERSIFIED"
        riskLevel: "MEDIUM"
        minInvestment: 500
      - type: "ETF"
        category: "EXCHANGE_TRADED"
        riskLevel: "MEDIUM"
        minInvestment: 100
      - type: "COMMODITY"
        category: "ALTERNATIVE"
        riskLevel: "HIGH"
        minInvestment: 10000

# Processing Configuration
processing:
  fail-fast: true
  enable-logging: true
  max-processing-time: 30000
  dataset-cache-enabled: true
  
# Output Configuration
output:
  format: "json"
  include-metadata: true
  include-processing-time: true
  include-dataset-info: true

