apiVersion: "apex.dev/v1"
kind: "DataSource"
metadata:
  name: "postgresql-customer-database"
  version: "1.0.0"
  type: "external-data-config"
  description: "PostgreSQL customer database configuration for external reference testing"
  author: "APEX Demo Team"

spec:
  type: "database"
  source-type: "h2"
  enabled: true

  # Database connection configuration
  connection:
    # H2 in-memory database configuration with shared access (PostgreSQL mode)
    database: "apex_demo_shared;DB_CLOSE_DELAY=-1;MODE=PostgreSQL"
    username: "sa"
    password: ""

    # Connection pool configuration
    maxPoolSize: 10
    minPoolSize: 2
    connectionTimeout: 30000
    idleTimeout: 600000
    maxLifetime: 1800000

  # Named SQL queries for customer operations
  queries:
    # Primary customer lookup query
    getCustomerById: |
      SELECT
        customer_id,
        customer_name,
        customer_type,
        tier,
        region,
        status,
        created_date,
        last_updated
      FROM customers
      WHERE customer_id = :customerId

    # Active customer lookup query
    getActiveCustomerById: |
      SELECT
        customer_id,
        customer_name,
        customer_type,
        tier,
        region,
        status,
        created_date
      FROM customers
      WHERE customer_id = :customerId
        AND status = 'ACTIVE'

    # Customer lookup by region
    getCustomersByRegion: |
      SELECT
        customer_id,
        customer_name,
        customer_type,
        tier,
        region,
        status,
        created_date
      FROM customers
      WHERE region = :region
        AND status = 'ACTIVE'
      ORDER BY customer_name

    # Health check query
    healthCheck: "SELECT 1 as health_check"

  # Parameter definitions for named parameter binding
  parameters:
    customerId:
      type: "string"
      description: "Customer identifier"
      required: true
    region:
      type: "string"
      description: "Customer region code"
      required: false

  # Infrastructure settings
  cache:
    enabled: true
    ttlSeconds: 300
    maxSize: 1000
