# APEX Processing Execution Configuration
# External data source configuration for processing execution
# Replaces hardcoded processing execution logic from ScenarioBasedProcessingDemo

metadata:
  id: "Processing Execution Configuration"
  name: "Processing Execution Configuration"
  version: "1.0.0"
  description: "Data-driven processing execution configuration for scenarios"
  type: "external-data-config"
  author: "apex.demo.team@company.com"
  created-date: "2024-12-24"
  tags: ["apex-demo", "evaluation", "scenario-processing", "processing-execution"]

# Processing execution configuration by execution type
data:
  scenario-processing-execution:
    execution-id: "EXEC001"
    execution-type: "scenario-processing-execution"
    description: "Scenario-specific processing pipeline execution"
    execution-patterns:
      otc-options-execution:
        scenario-id: "otc-options-standard"
        execution-name: "OTC Options Processing Execution"
        execution-stages:
          - stage-id: "validation"
            stage-name: "OTC Option Validation"
            stage-description: "Validate OTC option data and business rules"
            execution-steps:
              - step: "data-structure-validation"
                description: "Validate data structure and required fields"
                timeout: 500
              - step: "business-rule-validation"
                description: "Apply OTC option business rules"
                timeout: 1000
              - step: "counterparty-validation"
                description: "Validate counterparty information"
                timeout: 500
            stage-timeout: 2000
            retry-attempts: 2
            
          - stage-id: "enrichment"
            stage-name: "Data Enrichment"
            stage-description: "Enrich OTC option with market and reference data"
            execution-steps:
              - step: "market-data-lookup"
                description: "Lookup current market data"
                timeout: 1000
              - step: "counterparty-enrichment"
                description: "Enrich counterparty information"
                timeout: 1000
              - step: "underlying-asset-enrichment"
                description: "Enrich underlying asset information"
                timeout: 1000
            stage-timeout: 3000
            retry-attempts: 2
            
          - stage-id: "risk-assessment"
            stage-name: "Risk Assessment"
            stage-description: "Assess risk for OTC option"
            execution-steps:
              - step: "credit-risk-assessment"
                description: "Assess counterparty credit risk"
                timeout: 800
              - step: "market-risk-assessment"
                description: "Assess market risk exposure"
                timeout: 800
              - step: "operational-risk-assessment"
                description: "Assess operational risk factors"
                timeout: 400
            stage-timeout: 2000
            retry-attempts: 1
            
          - stage-id: "settlement"
            stage-name: "Settlement Processing"
            stage-description: "Process OTC option settlement"
            execution-steps:
              - step: "settlement-instruction-generation"
                description: "Generate settlement instructions"
                timeout: 500
              - step: "settlement-validation"
                description: "Validate settlement instructions"
                timeout: 500
            stage-timeout: 1000
            retry-attempts: 2
        execution-settings:
          total-timeout: 8000
          parallel-stages: false
          error-handling: "fail-fast"
          performance-monitoring: true
          
      commodity-swaps-execution:
        scenario-id: "commodity-swaps-standard"
        execution-name: "Commodity Swaps Processing Execution"
        execution-stages:
          - stage-id: "swap-validation"
            stage-name: "Commodity Swap Validation"
            stage-description: "Validate commodity swap data and business rules"
            execution-steps:
              - step: "swap-structure-validation"
                description: "Validate swap structure and required fields"
                timeout: 800
              - step: "commodity-validation"
                description: "Validate commodity type and reference index"
                timeout: 1000
              - step: "notional-validation"
                description: "Validate notional amount and currency"
                timeout: 700
            stage-timeout: 2500
            retry-attempts: 2
            
          - stage-id: "commodity-enrichment"
            stage-name: "Commodity Data Enrichment"
            stage-description: "Enrich commodity swap with reference data"
            execution-steps:
              - step: "commodity-reference-lookup"
                description: "Lookup commodity reference data"
                timeout: 1500
              - step: "index-data-enrichment"
                description: "Enrich with index data"
                timeout: 1000
              - step: "market-data-enrichment"
                description: "Enrich with current market data"
                timeout: 1000
            stage-timeout: 3500
            retry-attempts: 2
            
          - stage-id: "pricing-calculation"
            stage-name: "Pricing Calculation"
            stage-description: "Calculate commodity swap pricing"
            execution-steps:
              - step: "forward-curve-calculation"
                description: "Calculate forward curve"
                timeout: 1000
              - step: "present-value-calculation"
                description: "Calculate present value"
                timeout: 800
              - step: "risk-metrics-calculation"
                description: "Calculate risk metrics"
                timeout: 200
            stage-timeout: 2000
            retry-attempts: 1
            
          - stage-id: "risk-monitoring"
            stage-name: "Risk Monitoring"
            stage-description: "Monitor commodity swap risk"
            execution-steps:
              - step: "position-risk-monitoring"
                description: "Monitor position risk"
                timeout: 750
              - step: "concentration-risk-monitoring"
                description: "Monitor concentration risk"
                timeout: 750
            stage-timeout: 1500
            retry-attempts: 1
        execution-settings:
          total-timeout: 9500
          parallel-stages: false
          error-handling: "continue-on-error"
          performance-monitoring: true
          
      settlement-auto-repair-execution:
        scenario-id: "settlement-auto-repair"
        execution-name: "Settlement Auto-Repair Execution"
        execution-stages:
          - stage-id: "instruction-validation"
            stage-name: "Settlement Instruction Validation"
            stage-description: "Validate settlement instruction data"
            execution-steps:
              - step: "instruction-structure-validation"
                description: "Validate instruction structure"
                timeout: 500
              - step: "market-validation"
                description: "Validate market and instrument type"
                timeout: 500
              - step: "amount-validation"
                description: "Validate settlement amount and currency"
                timeout: 500
            stage-timeout: 1500
            retry-attempts: 2
            
          - stage-id: "auto-repair-assessment"
            stage-name: "Auto-Repair Assessment"
            stage-description: "Assess feasibility of auto-repair"
            execution-steps:
              - step: "repair-eligibility-check"
                description: "Check if instruction is eligible for auto-repair"
                timeout: 800
              - step: "repair-complexity-assessment"
                description: "Assess complexity of required repairs"
                timeout: 1000
              - step: "repair-confidence-scoring"
                description: "Score confidence in auto-repair success"
                timeout: 700
            stage-timeout: 2500
            retry-attempts: 1
            
          - stage-id: "standing-instruction-lookup"
            stage-name: "Standing Instruction Lookup"
            stage-description: "Lookup and match standing instructions"
            execution-steps:
              - step: "client-si-lookup"
                description: "Lookup client standing instructions"
                timeout: 1000
              - step: "market-si-lookup"
                description: "Lookup market standing instructions"
                timeout: 800
              - step: "si-matching"
                description: "Match and prioritize standing instructions"
                timeout: 200
            stage-timeout: 2000
            retry-attempts: 2
            
          - stage-id: "repair-execution"
            stage-name: "Repair Execution"
            stage-description: "Execute automated repair"
            execution-steps:
              - step: "repair-plan-generation"
                description: "Generate repair plan"
                timeout: 1000
              - step: "repair-execution"
                description: "Execute repair actions"
                timeout: 1500
              - step: "repair-validation"
                description: "Validate repair results"
                timeout: 500
            stage-timeout: 3000
            retry-attempts: 1
        execution-settings:
          total-timeout: 9000
          parallel-stages: false
          error-handling: "rollback-on-error"
          performance-monitoring: true
    execution-settings:
      monitoring-enabled: true
      performance-tracking: true
      error-logging: true
      result-caching: false
    
  performance-monitoring-execution:
    execution-id: "EXEC002"
    execution-type: "performance-monitoring-execution"
    description: "Performance monitoring and metrics collection during execution"
    monitoring-aspects:
      execution-timing:
        measure-stage-timing: true
        measure-step-timing: true
        measure-total-timing: true
        timing-precision: "milliseconds"
        
      resource-monitoring:
        monitor-memory-usage: true
        monitor-cpu-usage: true
        monitor-thread-usage: true
        monitoring-interval: 1000
        
      throughput-monitoring:
        measure-records-per-second: true
        measure-stages-per-second: true
        measure-operations-per-second: true
        throughput-window: 60000
        
      error-monitoring:
        track-error-rates: true
        track-retry-rates: true
        track-timeout-rates: true
        error-categorization: true
    monitoring-settings:
      real-time-monitoring: true
      historical-tracking: true
      alert-thresholds: true
      reporting-enabled: true
    
  result-aggregation-execution:
    execution-id: "EXEC003"
    execution-type: "result-aggregation-execution"
    description: "Aggregation and reporting of processing results"
    aggregation-aspects:
      stage-results:
        aggregate-stage-outcomes: true
        aggregate-stage-timing: true
        aggregate-stage-errors: true
        
      scenario-results:
        aggregate-scenario-outcomes: true
        aggregate-scenario-performance: true
        aggregate-scenario-errors: true
        
      overall-results:
        aggregate-total-outcomes: true
        aggregate-total-performance: true
        aggregate-total-errors: true
        generate-summary-report: true
    aggregation-settings:
      real-time-aggregation: true
      batch-aggregation: false
      result-persistence: true
      reporting-format: "JSON"
    
  default:
    execution-id: "EXEC000"
    execution-type: "default"
    description: "Default processing execution"
    basic-execution:
      - "Basic processing step"
    execution-settings:
      basic-processing: true

# Execution algorithms
execution-algorithms:
  sequential-execution:
    algorithm-name: "Sequential Stage Execution"
    description: "Execute stages sequentially with dependency management"
    characteristics:
      - "Stages execute in defined order"
      - "Dependencies are respected"
      - "Error handling per stage"
    parameters:
      dependency-checking: true
      error-propagation: "fail-fast"
      
  parallel-execution:
    algorithm-name: "Parallel Stage Execution"
    description: "Execute independent stages in parallel"
    characteristics:
      - "Independent stages run in parallel"
      - "Dependency constraints respected"
      - "Resource pooling"
    parameters:
      thread-pool-size: 4
      dependency-analysis: true
      resource-management: true
      
  adaptive-execution:
    algorithm-name: "Adaptive Execution"
    description: "Adaptive execution based on performance and load"
    characteristics:
      - "Adapts to system load"
      - "Optimizes resource usage"
      - "Performance-based decisions"
    parameters:
      load-monitoring: true
      adaptation-threshold: 0.8
      optimization-interval: 5000

# Quality assurance
quality-assurance:
  execution-reliability:
    - "All stages must complete successfully or fail gracefully"
    - "Timeouts must be respected"
    - "Retry logic must be robust"
    - "Error handling must be comprehensive"
    
  performance-requirements:
    - "Execution time must be within specified limits"
    - "Resource usage must be controlled"
    - "Throughput must meet requirements"
    - "Scalability must be demonstrated"
    
  result-integrity:
    - "Results must be accurate and complete"
    - "Aggregations must be correct"
    - "Reports must be consistent"
    - "Data must not be corrupted"
