# APEX Sample Data Records Configuration
# External data source configuration for sample data records creation
# Replaces hardcoded sample data creation from ScenarioBasedProcessingDemo

metadata:
  id: "Sample Data Records Configuration"
  name: "Sample Data Records Configuration"
  version: "1.0.0"
  description: "Data-driven sample data records configuration for scenario processing"
  type: "external-data-config"
  author: "apex.demo.team@company.com"
  created-date: "2024-12-24"
  tags: ["apex-demo", "evaluation", "scenario-processing", "sample-data-records"]

# Sample data records configuration by data type
data:
  otc-option-records:
    data-id: "SAMPLE001"
    data-type: "otc-option-records"
    description: "OTC Option sample data records for scenario routing"
    sample-records:
      - record-id: "OTC001"
        record-type: "OtcOption"
        trade-date: "2025-08-02"
        counterparty: "GOLDMAN_SACHS"
        client: "JP_MORGAN"
        option-type: "Call"
        underlying-asset:
          name: "Natural Gas"
          unit: "MMBtu"
        strike-price: 3.50
        currency: "USD"
        notional-amount: 10000.00
        expiry-date: "2025-12-28"
        settlement-type: "Cash"
        scenario-routing: "otc-options-standard"
        
      - record-id: "OTC002"
        record-type: "OtcOption"
        trade-date: "2025-08-02"
        counterparty: "JPMORGAN"
        client: "GOLDMAN_SACHS"
        option-type: "Put"
        underlying-asset:
          name: "Crude Oil"
          unit: "Barrel"
        strike-price: 75.00
        currency: "USD"
        notional-amount: 2500000.00
        expiry-date: "2025-11-15"
        settlement-type: "Physical"
        scenario-routing: "otc-options-complex"
        
      - record-id: "OTC003"
        record-type: "OtcOption"
        trade-date: "2025-08-02"
        counterparty: "MORGAN_STANLEY"
        client: "CITIGROUP"
        option-type: "Call"
        underlying-asset:
          name: "Gold"
          unit: "Troy Ounce"
        strike-price: 2100.00
        currency: "USD"
        notional-amount: 500000.00
        expiry-date: "2026-02-28"
        settlement-type: "Cash"
        scenario-routing: "otc-options-standard"
    creation-rules:
      - "OTC Options must have valid counterparties"
      - "Strike prices must be positive"
      - "Expiry dates must be in the future"
      - "Notional amounts must be positive"
    
  commodity-swap-records:
    data-id: "SAMPLE002"
    data-type: "commodity-swap-records"
    description: "Commodity Swap sample data records for scenario routing"
    sample-records:
      - record-id: "CS001"
        record-type: "CommoditySwap"
        data-type: "CommoditySwap"
        trade-id: "CS_20250802_001"
        counterparty-id: "CP001"
        client-id: "CLI001"
        commodity-type: "ENERGY"
        reference-index: "WTI"
        notional-amount: 5000000.00
        notional-currency: "USD"
        trade-date: "2025-08-02"
        maturity-date: "2027-08-02"
        scenario-routing: "commodity-swaps-standard"
        
      - record-id: "CS002"
        record-type: "CommoditySwap"
        data-type: "CommoditySwap"
        trade-id: "CS_20250802_002"
        counterparty-id: "CP002"
        client-id: "CLI002"
        commodity-type: "METALS"
        reference-index: "GOLD_SPOT"
        notional-amount: 15000000.00
        notional-currency: "USD"
        trade-date: "2025-08-02"
        maturity-date: "2028-08-02"
        scenario-routing: "commodity-swaps-complex"
        
      - record-id: "CS003"
        record-type: "CommoditySwap"
        data-type: "CommoditySwap"
        trade-id: "CS_20250802_003"
        counterparty-id: "CP003"
        client-id: "CLI003"
        commodity-type: "AGRICULTURE"
        reference-index: "CORN_FUTURES"
        notional-amount: 2500000.00
        notional-currency: "USD"
        trade-date: "2025-08-02"
        maturity-date: "2026-08-02"
        scenario-routing: "commodity-swaps-standard"
    creation-rules:
      - "Commodity swaps must have valid reference indices"
      - "Notional amounts must be positive"
      - "Maturity dates must be after trade dates"
      - "Commodity types must be recognized"
    
  settlement-instruction-records:
    data-id: "SAMPLE003"
    data-type: "settlement-instruction-records"
    description: "Settlement Instruction sample data records for scenario routing"
    sample-records:
      - record-id: "SI001"
        record-type: "SettlementInstruction"
        data-type: "SettlementInstruction"
        instruction-id: "SI_20250802_001"
        client-id: "CLIENT_PREMIUM_ASIA_001"
        market: "JAPAN"
        instrument-type: "EQUITY"
        settlement-amount: 2000000.00
        settlement-currency: "JPY"
        settlement-date: "2025-08-04"
        requires-repair: true
        scenario-routing: "settlement-auto-repair"
        
      - record-id: "SI002"
        record-type: "SettlementInstruction"
        data-type: "SettlementInstruction"
        instruction-id: "SI_20250802_002"
        client-id: "CLIENT_STANDARD_EUROPE_001"
        market: "LONDON"
        instrument-type: "BOND"
        settlement-amount: 5000000.00
        settlement-currency: "GBP"
        settlement-date: "2025-08-05"
        requires-repair: false
        scenario-routing: "settlement-manual-review"
        
      - record-id: "SI003"
        record-type: "SettlementInstruction"
        data-type: "SettlementInstruction"
        instruction-id: "SI_20250802_003"
        client-id: "CLIENT_PREMIUM_ASIA_002"
        market: "SINGAPORE"
        instrument-type: "EQUITY"
        settlement-amount: 3500000.00
        settlement-currency: "SGD"
        settlement-date: "2025-08-04"
        requires-repair: true
        scenario-routing: "settlement-auto-repair"
    creation-rules:
      - "Settlement instructions must have valid markets"
      - "Settlement amounts must be positive"
      - "Settlement dates must be valid business days"
      - "Currencies must match market conventions"
    
  default:
    data-id: "SAMPLE000"
    data-type: "default"
    description: "Default sample data records"
    sample-records:
      - record-id: "DEFAULT001"
        record-type: "DefaultRecord"
        name: "Default Record"
        value: "Default Value"
        scenario-routing: "default-scenario"
    creation-rules:
      - "Basic data validation"

# Data record patterns
record-patterns:
  otc-option-pattern:
    pattern-name: "OTC Option Record Pattern"
    description: "Pattern for creating OTC Option sample records"
    required-fields:
      - "trade-date"
      - "counterparty"
      - "client"
      - "option-type"
      - "underlying-asset"
      - "strike-price"
      - "notional-amount"
      - "expiry-date"
    optional-fields:
      - "settlement-type"
      - "premium"
      - "volatility"
    validation-rules:
      - "Strike price must be positive"
      - "Notional amount must be positive"
      - "Expiry date must be in the future"
    
  commodity-swap-pattern:
    pattern-name: "Commodity Swap Record Pattern"
    description: "Pattern for creating commodity swap sample records"
    required-fields:
      - "trade-id"
      - "counterparty-id"
      - "client-id"
      - "commodity-type"
      - "reference-index"
      - "notional-amount"
      - "trade-date"
      - "maturity-date"
    optional-fields:
      - "payment-frequency"
      - "reset-frequency"
      - "spread"
    validation-rules:
      - "Notional amount must be positive"
      - "Maturity date must be after trade date"
      - "Commodity type must be valid"
    
  settlement-instruction-pattern:
    pattern-name: "Settlement Instruction Record Pattern"
    description: "Pattern for creating settlement instruction sample records"
    required-fields:
      - "instruction-id"
      - "client-id"
      - "market"
      - "instrument-type"
      - "settlement-amount"
      - "settlement-currency"
      - "settlement-date"
    optional-fields:
      - "requires-repair"
      - "priority"
      - "special-instructions"
    validation-rules:
      - "Settlement amount must be positive"
      - "Settlement date must be valid"
      - "Market must be supported"

# Record generation settings
generation-settings:
  otc-options:
    default-count: 3
    variation-enabled: true
    realistic-data: true
    
  commodity-swaps:
    default-count: 3
    variation-enabled: true
    realistic-data: true
    
  settlement-instructions:
    default-count: 3
    variation-enabled: true
    realistic-data: true

# Quality assurance
quality-assurance:
  data-validation:
    - "All required fields must be present"
    - "Data types must be correct"
    - "Business rules must be satisfied"
    - "Relationships must be valid"
    
  scenario-routing:
    - "Routing decisions must be deterministic"
    - "Scenarios must be properly mapped"
    - "Fallback scenarios must be defined"
    - "Routing performance must be acceptable"
    
  record-integrity:
    - "Records must be internally consistent"
    - "Cross-record relationships must be valid"
    - "Data must be suitable for processing"
    - "Performance must be acceptable"
