# APEX Scenario Routing Configuration
# External data source configuration for scenario routing
# Replaces hardcoded scenario routing logic from ScenarioBasedProcessingDemo

metadata:
  id: "Scenario Routing Configuration"
  name: "Scenario Routing Configuration"
  version: "1.0.0"
  description: "Data-driven scenario routing configuration for processing"
  type: "external-data-config"
  author: "apex.demo.team@company.com"
  created-date: "2024-12-24"
  tags: ["apex-demo", "evaluation", "scenario-processing", "scenario-routing"]

# Scenario routing configuration by routing type
data:
  automatic-data-type-routing:
    routing-id: "ROUTE001"
    routing-type: "automatic-data-type-routing"
    description: "Automatic data type detection and scenario routing"
    routing-rules:
      otc-option-routing:
        data-type: "OtcOption"
        class-patterns:
          - "dev.mars.apex.demo.model.OtcOption"
          - "OtcOption"
        routing-conditions:
          - condition: "#data.optionType == 'Call' && #data.notionalAmount.compareTo(new java.math.BigDecimal('1000000')) < 0"
            target-scenario: "otc-options-standard"
            priority: 1
            description: "Standard Call options under $1M"
            
          - condition: "#data.optionType == 'Put' || #data.notionalAmount.compareTo(new java.math.BigDecimal('1000000')) >= 0"
            target-scenario: "otc-options-complex"
            priority: 2
            description: "Put options or large notional amounts"
            
          - condition: "true"
            target-scenario: "otc-options-standard"
            priority: 999
            description: "Default OTC options routing"
        default-scenario: "otc-options-standard"
        
      commodity-swap-routing:
        data-type: "CommoditySwap"
        class-patterns:
          - "java.util.Map"
          - "java.util.HashMap"
        field-detection:
          - field: "dataType"
            value: "CommoditySwap"
        routing-conditions:
          - condition: "#data.commodityType == 'ENERGY' && #data.notionalAmount.compareTo(new java.math.BigDecimal('5000000')) < 0"
            target-scenario: "commodity-swaps-standard"
            priority: 1
            description: "Standard energy swaps under $5M"
            
          - condition: "#data.commodityType != 'ENERGY' || #data.notionalAmount.compareTo(new java.math.BigDecimal('5000000')) >= 0"
            target-scenario: "commodity-swaps-complex"
            priority: 2
            description: "Non-energy swaps or large notional amounts"
            
          - condition: "true"
            target-scenario: "commodity-swaps-standard"
            priority: 999
            description: "Default commodity swaps routing"
        default-scenario: "commodity-swaps-standard"
        
      settlement-instruction-routing:
        data-type: "SettlementInstruction"
        class-patterns:
          - "java.util.Map"
          - "java.util.HashMap"
        field-detection:
          - field: "dataType"
            value: "SettlementInstruction"
        routing-conditions:
          - condition: "#data.requiresRepair == true && #data.market in {'JAPAN', 'SINGAPORE', 'HONG_KONG'}"
            target-scenario: "settlement-auto-repair"
            priority: 1
            description: "Asian markets requiring auto-repair"
            
          - condition: "#data.requiresRepair == false || #data.market not in {'JAPAN', 'SINGAPORE', 'HONG_KONG'}"
            target-scenario: "settlement-manual-review"
            priority: 2
            description: "Non-Asian markets or no repair required"
            
          - condition: "true"
            target-scenario: "settlement-manual-review"
            priority: 999
            description: "Default settlement instruction routing"
        default-scenario: "settlement-manual-review"
    routing-settings:
      evaluation-order: "priority-ascending"
      fallback-enabled: true
      caching-enabled: true
      performance-monitoring: true
    
  scenario-specific-routing:
    routing-id: "ROUTE002"
    routing-type: "scenario-specific-routing"
    description: "Scenario-specific processing pipeline routing"
    scenario-configurations:
      otc-options-standard:
        scenario-id: "otc-options-standard"
        scenario-name: "OTC Options Standard Processing"
        processing-pipeline:
          - stage: "validation"
            description: "Basic OTC option validation"
            timeout: 2000
          - stage: "enrichment"
            description: "Counterparty and market data enrichment"
            timeout: 3000
          - stage: "risk-assessment"
            description: "Standard risk assessment"
            timeout: 2000
          - stage: "settlement"
            description: "Settlement processing"
            timeout: 1000
        rule-configurations:
          - "demos/bootstrap/otc-options-bootstrap.yaml"
          - "config/derivatives-validation-rules.yaml"
        processing-settings:
          enabled: true
          priority: "normal"
          timeout-ms: 8000
          retry-attempts: 2
          
      otc-options-complex:
        scenario-id: "otc-options-complex"
        scenario-name: "OTC Options Complex Processing"
        processing-pipeline:
          - stage: "advanced-validation"
            description: "Advanced OTC option validation"
            timeout: 3000
          - stage: "complex-enrichment"
            description: "Complex counterparty and market data enrichment"
            timeout: 5000
          - stage: "advanced-risk-assessment"
            description: "Advanced risk assessment with stress testing"
            timeout: 4000
          - stage: "complex-settlement"
            description: "Complex settlement processing"
            timeout: 2000
        rule-configurations:
          - "demos/bootstrap/otc-options-complex-bootstrap.yaml"
          - "config/derivatives-complex-validation-rules.yaml"
        processing-settings:
          enabled: true
          priority: "high"
          timeout-ms: 14000
          retry-attempts: 3
          
      commodity-swaps-standard:
        scenario-id: "commodity-swaps-standard"
        scenario-name: "Commodity Swaps Standard Processing"
        processing-pipeline:
          - stage: "swap-validation"
            description: "Basic commodity swap validation"
            timeout: 2500
          - stage: "commodity-enrichment"
            description: "Commodity reference data enrichment"
            timeout: 3500
          - stage: "pricing-calculation"
            description: "Standard pricing calculation"
            timeout: 2000
          - stage: "risk-monitoring"
            description: "Risk monitoring and reporting"
            timeout: 1500
        rule-configurations:
          - "demos/bootstrap/commodity-swap/bootstrap-config.yaml"
        processing-settings:
          enabled: true
          priority: "normal"
          timeout-ms: 9500
          retry-attempts: 2
          
      commodity-swaps-complex:
        scenario-id: "commodity-swaps-complex"
        scenario-name: "Commodity Swaps Complex Processing"
        processing-pipeline:
          - stage: "advanced-swap-validation"
            description: "Advanced commodity swap validation"
            timeout: 4000
          - stage: "complex-commodity-enrichment"
            description: "Complex commodity reference data enrichment"
            timeout: 6000
          - stage: "advanced-pricing-calculation"
            description: "Advanced pricing calculation with scenarios"
            timeout: 5000
          - stage: "comprehensive-risk-monitoring"
            description: "Comprehensive risk monitoring and stress testing"
            timeout: 3000
        rule-configurations:
          - "demos/bootstrap/commodity-swap/complex-bootstrap-config.yaml"
          - "config/commodity-complex-validation-rules.yaml"
        processing-settings:
          enabled: true
          priority: "high"
          timeout-ms: 18000
          retry-attempts: 3
          
      settlement-auto-repair:
        scenario-id: "settlement-auto-repair"
        scenario-name: "Settlement Auto-Repair Processing"
        processing-pipeline:
          - stage: "instruction-validation"
            description: "Settlement instruction validation"
            timeout: 1500
          - stage: "auto-repair-assessment"
            description: "Auto-repair feasibility assessment"
            timeout: 2500
          - stage: "standing-instruction-lookup"
            description: "Standing instruction lookup and matching"
            timeout: 2000
          - stage: "repair-execution"
            description: "Automated repair execution"
            timeout: 3000
        rule-configurations:
          - "validation/custody-auto-repair-rules.yaml"
        processing-settings:
          enabled: true
          priority: "high"
          timeout-ms: 9000
          retry-attempts: 2
          
      settlement-manual-review:
        scenario-id: "settlement-manual-review"
        scenario-name: "Settlement Manual Review Processing"
        processing-pipeline:
          - stage: "instruction-validation"
            description: "Settlement instruction validation"
            timeout: 1500
          - stage: "manual-review-preparation"
            description: "Preparation for manual review"
            timeout: 2000
          - stage: "documentation-generation"
            description: "Generate review documentation"
            timeout: 1500
          - stage: "queue-assignment"
            description: "Assign to appropriate review queue"
            timeout: 1000
        rule-configurations:
          - "validation/settlement-manual-review-rules.yaml"
        processing-settings:
          enabled: true
          priority: "normal"
          timeout-ms: 6000
          retry-attempts: 1
    routing-settings:
      scenario-caching: true
      pipeline-optimization: true
      performance-monitoring: true
      error-handling: "graceful-degradation"
    
  fallback-routing:
    routing-id: "ROUTE003"
    routing-type: "fallback-routing"
    description: "Fallback routing for unknown data types"
    fallback-scenarios:
      unknown-data-type:
        scenario-id: "unknown-data-type"
        scenario-name: "Unknown Data Type Processing"
        processing-pipeline:
          - stage: "data-analysis"
            description: "Analyze unknown data structure"
            timeout: 3000
          - stage: "basic-validation"
            description: "Basic data validation"
            timeout: 2000
          - stage: "logging"
            description: "Log unknown data type for analysis"
            timeout: 1000
        processing-settings:
          enabled: true
          priority: "low"
          timeout-ms: 6000
          retry-attempts: 1
    routing-settings:
      always-available: true
      logging-enabled: true
      analysis-enabled: true
    
  default:
    routing-id: "ROUTE000"
    routing-type: "default"
    description: "Default routing configuration"
    default-scenario: "basic-processing"
    routing-settings:
      basic-routing: true

# Routing algorithms
routing-algorithms:
  priority-based-routing:
    algorithm-name: "Priority-Based Routing"
    description: "Route based on condition priority and evaluation order"
    characteristics:
      - "Evaluates conditions in priority order"
      - "First matching condition wins"
      - "Supports fallback scenarios"
    parameters:
      evaluation-strategy: "short-circuit"
      priority-order: "ascending"
      
  performance-optimized-routing:
    algorithm-name: "Performance-Optimized Routing"
    description: "Route with performance optimization and caching"
    characteristics:
      - "Caches routing decisions"
      - "Optimizes condition evaluation"
      - "Monitors performance metrics"
    parameters:
      caching-enabled: true
      cache-size: 1000
      cache-ttl: 300
      
  adaptive-routing:
    algorithm-name: "Adaptive Routing"
    description: "Adaptive routing based on historical performance"
    characteristics:
      - "Learns from routing history"
      - "Adapts to changing patterns"
      - "Optimizes for throughput"
    parameters:
      learning-enabled: true
      adaptation-interval: 3600
      performance-threshold: 0.95

# Performance optimization
performance-optimization:
  routing-performance:
    condition-evaluation-optimization: true
    expression-caching: true
    result-caching: true
    parallel-evaluation: false
    
  scenario-performance:
    scenario-caching: true
    pipeline-optimization: true
    resource-pooling: true
    batch-processing: false
    
  monitoring-performance:
    performance-tracking: true
    latency-monitoring: true
    throughput-monitoring: true
    error-rate-monitoring: true
