# APEX Transformer Rules Configuration
# External data source configuration for transformer rules processing
# Replaces hardcoded transformer rule creation from CustomerTransformerDemo

metadata:
  name: "Transformer Rules Configuration"
  version: "1.0.0"
  description: "Data-driven transformer rules configuration for customer transformation processing"
  type: "external-data-config"
  author: "apex.demo.team@company.com"
  created-date: "2024-12-24"
  tags: ["apex-demo", "enrichment", "transformer-rules", "external-data"]

# Transformer rules configuration by rule type
data:
  membership-based-rules:
    rule-type: "membership-based-rules"
    rule-name: "Membership-Based Transformer Rules"
    description: "Transformer rules based on customer membership levels"
    rule-parameters:
      priority-level: "high"
      execution-order: 100
      cache-results: true
    transformer-rules:
      gold-member-rule:
        rule-id: "GoldMemberRule"
        rule-name: "Gold Member Transformation Rule"
        rule-description: "Add recommended categories for Gold members"
        rule-condition: "#value.membershipLevel == 'Gold'"
        rule-priority: 100
        positive-actions:
          - action-type: "add-category"
            category: "Equity"
            description: "Add Equity category for Gold members"
          - action-type: "add-category"
            category: "FixedIncome"
            description: "Add FixedIncome category for Gold members"
          - action-type: "add-category"
            category: "ETF"
            description: "Add ETF category for Gold members"
          - action-type: "add-category"
            category: "Options"
            description: "Add Options category for Gold members"
        negative-actions: []
        validation-rules:
          - "membershipLevel != null"
          - "membershipLevel == 'Gold'"
        audit-requirements:
          - "Log Gold member transformation"
          - "Track category additions"
          
      silver-member-rule:
        rule-id: "SilverMemberRule"
        rule-name: "Silver Member Transformation Rule"
        rule-description: "Add recommended categories for Silver members"
        rule-condition: "#value.membershipLevel == 'Silver'"
        rule-priority: 200
        positive-actions:
          - action-type: "add-category"
            category: "FixedIncome"
            description: "Add FixedIncome category for Silver members"
          - action-type: "add-category"
            category: "ETF"
            description: "Add ETF category for Silver members"
          - action-type: "add-category"
            category: "Mutual Funds"
            description: "Add Mutual Funds category for Silver members"
        negative-actions: []
        validation-rules:
          - "membershipLevel != null"
          - "membershipLevel == 'Silver'"
        audit-requirements:
          - "Log Silver member transformation"
          - "Track category additions"
          
      bronze-member-rule:
        rule-id: "BronzeMemberRule"
        rule-name: "Bronze Member Transformation Rule"
        rule-description: "Add recommended categories for Bronze members"
        rule-condition: "#value.membershipLevel == 'Bronze'"
        rule-priority: 300
        positive-actions:
          - action-type: "add-category"
            category: "ETF"
            description: "Add ETF category for Bronze members"
          - action-type: "add-category"
            category: "Mutual Funds"
            description: "Add Mutual Funds category for Bronze members"
        negative-actions: []
        validation-rules:
          - "membershipLevel != null"
          - "membershipLevel == 'Bronze'"
        audit-requirements:
          - "Log Bronze member transformation"
          - "Track category additions"
          
      basic-member-rule:
        rule-id: "BasicMemberRule"
        rule-name: "Basic Member Transformation Rule"
        rule-description: "Add recommended categories for Basic members"
        rule-condition: "#value.membershipLevel == 'Basic'"
        rule-priority: 400
        positive-actions:
          - action-type: "add-category"
            category: "ETF"
            description: "Add ETF category for Basic members"
        negative-actions: []
        validation-rules:
          - "membershipLevel != null"
          - "membershipLevel == 'Basic'"
        audit-requirements:
          - "Log Basic member transformation"
          - "Track category additions"
    rule-settings:
      execution-timeout: 3000
      parallel-execution: true
      error-handling: "continue-on-warning"
    
  age-based-rules:
    rule-type: "age-based-rules"
    rule-name: "Age-Based Transformer Rules"
    description: "Transformer rules based on customer age demographics"
    rule-parameters:
      priority-level: "medium"
      execution-order: 200
      cache-results: true
    transformer-rules:
      young-customer-rule:
        rule-id: "YoungCustomerRule"
        rule-name: "Young Customer Transformation Rule"
        rule-description: "Add recommended categories for young customers"
        rule-condition: "#value.age < 35"
        rule-priority: 500
        positive-actions:
          - action-type: "add-category"
            category: "Equity"
            description: "Add Equity category for young customers"
          - action-type: "add-category"
            category: "Options"
            description: "Add Options category for young customers"
          - action-type: "add-category"
            category: "ETF"
            description: "Add ETF category for young customers"
        negative-actions: []
        validation-rules:
          - "age != null"
          - "age >= 18"
          - "age < 35"
        audit-requirements:
          - "Log young customer transformation"
          - "Track growth-oriented category additions"
          
      middle-aged-customer-rule:
        rule-id: "MiddleAgedCustomerRule"
        rule-name: "Middle-Aged Customer Transformation Rule"
        rule-description: "Add recommended categories for middle-aged customers"
        rule-condition: "#value.age >= 35 && #value.age < 60"
        rule-priority: 600
        positive-actions:
          - action-type: "add-category"
            category: "Equity"
            description: "Add Equity category for middle-aged customers"
          - action-type: "add-category"
            category: "FixedIncome"
            description: "Add FixedIncome category for middle-aged customers"
          - action-type: "add-category"
            category: "ETF"
            description: "Add ETF category for middle-aged customers"
          - action-type: "add-category"
            category: "Mutual Funds"
            description: "Add Mutual Funds category for middle-aged customers"
        negative-actions: []
        validation-rules:
          - "age != null"
          - "age >= 35"
          - "age < 60"
        audit-requirements:
          - "Log middle-aged customer transformation"
          - "Track balanced category additions"
          
      senior-customer-rule:
        rule-id: "SeniorCustomerRule"
        rule-name: "Senior Customer Transformation Rule"
        rule-description: "Add recommended categories for senior customers"
        rule-condition: "#value.age >= 60"
        rule-priority: 700
        positive-actions:
          - action-type: "add-category"
            category: "FixedIncome"
            description: "Add FixedIncome category for senior customers"
          - action-type: "add-category"
            category: "Mutual Funds"
            description: "Add Mutual Funds category for senior customers"
        negative-actions: []
        validation-rules:
          - "age != null"
          - "age >= 60"
        audit-requirements:
          - "Log senior customer transformation"
          - "Track conservative category additions"
    rule-settings:
      execution-timeout: 2500
      parallel-execution: true
      error-handling: "continue-on-warning"
    
  behavior-based-rules:
    rule-type: "behavior-based-rules"
    rule-name: "Behavior-Based Transformer Rules"
    description: "Transformer rules based on customer behavior patterns"
    rule-parameters:
      priority-level: "medium"
      execution-order: 300
      cache-results: true
    transformer-rules:
      active-trader-rule:
        rule-id: "ActiveTraderRule"
        rule-name: "Active Trader Transformation Rule"
        rule-description: "Add recommended categories for active traders"
        rule-condition: "#value.tradingFrequency == 'HIGH' && #value.riskTolerance == 'HIGH'"
        rule-priority: 800
        positive-actions:
          - action-type: "add-category"
            category: "Options"
            description: "Add Options category for active traders"
          - action-type: "add-category"
            category: "Futures"
            description: "Add Futures category for active traders"
          - action-type: "add-category"
            category: "Equity"
            description: "Add Equity category for active traders"
        negative-actions: []
        validation-rules:
          - "tradingFrequency != null"
          - "riskTolerance != null"
        audit-requirements:
          - "Log active trader transformation"
          - "Track high-risk category additions"
          
      conservative-investor-rule:
        rule-id: "ConservativeInvestorRule"
        rule-name: "Conservative Investor Transformation Rule"
        rule-description: "Add recommended categories for conservative investors"
        rule-condition: "#value.riskTolerance == 'LOW'"
        rule-priority: 900
        positive-actions:
          - action-type: "add-category"
            category: "FixedIncome"
            description: "Add FixedIncome category for conservative investors"
          - action-type: "add-category"
            category: "Mutual Funds"
            description: "Add Mutual Funds category for conservative investors"
        negative-actions:
          - action-type: "remove-category"
            category: "Options"
            description: "Remove Options category for conservative investors"
          - action-type: "remove-category"
            category: "Futures"
            description: "Remove Futures category for conservative investors"
        validation-rules:
          - "riskTolerance != null"
          - "riskTolerance == 'LOW'"
        audit-requirements:
          - "Log conservative investor transformation"
          - "Track low-risk category management"
    rule-settings:
      execution-timeout: 3500
      parallel-execution: false
      error-handling: "fail-on-error"
    
  default:
    rule-type: "default"
    rule-name: "Default Transformer Rules"
    description: "Default transformation processing"
    transformer-rules:
      default-rule:
        rule-id: "DefaultRule"
        rule-name: "Default Transformation Rule"
        rule-condition: "true"
        positive-actions:
          - action-type: "add-category"
            category: "ETF"
            description: "Add default ETF category"
    rule-settings:
      execution-timeout: 1000

# Rule execution patterns
execution-patterns:
  membership-priority-pattern:
    pattern-name: "Membership Priority Pattern"
    description: "Execute membership rules in priority order"
    execution-order: ["Gold", "Silver", "Bronze", "Basic"]
    
  age-demographic-pattern:
    pattern-name: "Age Demographic Pattern"
    description: "Execute age-based rules by demographic"
    execution-order: ["Young", "MiddleAged", "Senior"]
    
  behavior-analysis-pattern:
    pattern-name: "Behavior Analysis Pattern"
    description: "Execute behavior-based rules by risk profile"
    execution-order: ["ActiveTrader", "ConservativeInvestor"]

# Quality assurance
quality-assurance:
  rule-accuracy:
    - "Transformer rules must be logically correct"
    - "Rule conditions must be syntactically valid"
    - "Actions must be appropriate for customer segments"
    - "Validation rules must be comprehensive"
    
  performance-requirements:
    - "Rule execution must be within timeout limits"
    - "Complex rules must be optimized"
    - "Parallel execution must be thread-safe"
    - "Error handling must be robust"
    
  business-alignment:
    - "Rules must reflect business requirements"
    - "Customer segmentation must be accurate"
    - "Product recommendations must be appropriate"
    - "Risk management must be considered"
