# APEX Trade Transformer Rules Configuration
# External data source configuration for trade transformer rules processing
# Replaces hardcoded trade transformer rule creation from TradeTransformerDemo

metadata:
  id: "Trade Transformer Rules Configuration"
  name: "Trade Transformer Rules Configuration"
  version: "1.0.0"
  description: "Data-driven trade transformer rules configuration for trade transformation processing"
  type: "external-data-config"
  author: "apex.demo.team@company.com"
  created-date: "2024-12-24"
  tags: ["apex-demo", "enrichment", "trade-transformer-rules", "external-data"]

# Trade transformer rules configuration by rule type
data:
  instrument-based-rules:
    rule-type: "instrument-based-rules"
    rule-name: "Instrument-Based Transformer Rules"
    description: "Transformer rules based on trade instrument types"
    rule-parameters:
      priority-level: "high"
      execution-order: 100
      cache-results: true
    transformer-rules:
      equity-trade-rule:
        rule-id: "EQUITY_TRADE_RULE"
        rule-name: "Equity Trade Transformation Rule"
        rule-description: "Transform Equity trades with appropriate categorization"
        rule-condition: "#value.value == 'Equity'"
        rule-priority: 100
        transformation-actions:
          - action-type: "set-category"
            target-field: "category"
            action-value: "InstrumentType"
            action-description: "Set category to InstrumentType for Equity trades"
        validation-rules:
          - "value != null"
          - "value == 'Equity'"
        audit-requirements:
          - "Log Equity trade transformation"
          - "Track instrument categorization"
          
      bond-trade-rule:
        rule-id: "BOND_TRADE_RULE"
        rule-name: "Bond Trade Transformation Rule"
        rule-description: "Transform Bond trades with appropriate categorization"
        rule-condition: "#value.value == 'Bond'"
        rule-priority: 200
        transformation-actions:
          - action-type: "set-category"
            target-field: "category"
            action-value: "InstrumentType"
            action-description: "Set category to InstrumentType for Bond trades"
        validation-rules:
          - "value != null"
          - "value == 'Bond'"
        audit-requirements:
          - "Log Bond trade transformation"
          - "Track instrument categorization"
          
      etf-trade-rule:
        rule-id: "ETF_TRADE_RULE"
        rule-name: "ETF Trade Transformation Rule"
        rule-description: "Transform ETF trades with appropriate categorization"
        rule-condition: "#value.value == 'ETF'"
        rule-priority: 300
        transformation-actions:
          - action-type: "set-category"
            target-field: "category"
            action-value: "InstrumentType"
            action-description: "Set category to InstrumentType for ETF trades"
        validation-rules:
          - "value != null"
          - "value == 'ETF'"
        audit-requirements:
          - "Log ETF trade transformation"
          - "Track instrument categorization"
          
      commodity-trade-rule:
        rule-id: "COMMODITY_TRADE_RULE"
        rule-name: "Commodity Trade Transformation Rule"
        rule-description: "Transform Commodity trades with appropriate categorization"
        rule-condition: "#value.value == 'Commodity'"
        rule-priority: 400
        transformation-actions:
          - action-type: "set-category"
            target-field: "category"
            action-value: "InstrumentType"
            action-description: "Set category to InstrumentType for Commodity trades"
        validation-rules:
          - "value != null"
          - "value == 'Commodity'"
        audit-requirements:
          - "Log Commodity trade transformation"
          - "Track instrument categorization"
    rule-settings:
      execution-timeout: 3000
      parallel-execution: true
      error-handling: "continue-on-warning"
    
  priority-based-rules:
    rule-type: "priority-based-rules"
    rule-name: "Priority-Based Transformer Rules"
    description: "Transformer rules based on trade priority levels"
    rule-parameters:
      priority-level: "high"
      execution-order: 200
      cache-results: true
    transformer-rules:
      high-priority-trade-rule:
        rule-id: "HIGH_PRIORITY_TRADE_RULE"
        rule-name: "High Priority Trade Transformation Rule"
        rule-description: "Transform high priority trades with special handling"
        rule-condition: "#value.id.startsWith('HP')"
        rule-priority: 500
        transformation-actions:
          - action-type: "set-value"
            target-field: "value"
            action-value: "HighPriority"
            action-description: "Set value to HighPriority for high priority trades"
          - action-type: "set-category"
            target-field: "category"
            action-value: "PriorityLevel"
            action-description: "Set category to PriorityLevel for high priority trades"
        validation-rules:
          - "id != null"
          - "id.startsWith('HP')"
        audit-requirements:
          - "Log high priority trade transformation"
          - "Track priority assignment"
          
      urgent-priority-trade-rule:
        rule-id: "URGENT_PRIORITY_TRADE_RULE"
        rule-name: "Urgent Priority Trade Transformation Rule"
        rule-description: "Transform urgent priority trades with immediate handling"
        rule-condition: "#value.id.startsWith('UR')"
        rule-priority: 600
        transformation-actions:
          - action-type: "set-value"
            target-field: "value"
            action-value: "UrgentPriority"
            action-description: "Set value to UrgentPriority for urgent trades"
          - action-type: "set-category"
            target-field: "category"
            action-value: "PriorityLevel"
            action-description: "Set category to PriorityLevel for urgent trades"
        validation-rules:
          - "id != null"
          - "id.startsWith('UR')"
        audit-requirements:
          - "Log urgent priority trade transformation"
          - "Track urgent priority assignment"
          
      medium-priority-trade-rule:
        rule-id: "MEDIUM_PRIORITY_TRADE_RULE"
        rule-name: "Medium Priority Trade Transformation Rule"
        rule-description: "Transform medium priority trades with standard handling"
        rule-condition: "#value.id.startsWith('MP')"
        rule-priority: 700
        transformation-actions:
          - action-type: "set-value"
            target-field: "value"
            action-value: "MediumPriority"
            action-description: "Set value to MediumPriority for medium priority trades"
          - action-type: "set-category"
            target-field: "category"
            action-value: "PriorityLevel"
            action-description: "Set category to PriorityLevel for medium priority trades"
        validation-rules:
          - "id != null"
          - "id.startsWith('MP')"
        audit-requirements:
          - "Log medium priority trade transformation"
          - "Track medium priority assignment"
          
      low-priority-trade-rule:
        rule-id: "LOW_PRIORITY_TRADE_RULE"
        rule-name: "Low Priority Trade Transformation Rule"
        rule-description: "Transform low priority trades with batch handling"
        rule-condition: "#value.id.startsWith('LP')"
        rule-priority: 800
        transformation-actions:
          - action-type: "set-value"
            target-field: "value"
            action-value: "LowPriority"
            action-description: "Set value to LowPriority for low priority trades"
          - action-type: "set-category"
            target-field: "category"
            action-value: "PriorityLevel"
            action-description: "Set category to PriorityLevel for low priority trades"
        validation-rules:
          - "id != null"
          - "id.startsWith('LP')"
        audit-requirements:
          - "Log low priority trade transformation"
          - "Track low priority assignment"
    rule-settings:
      execution-timeout: 2500
      parallel-execution: true
      error-handling: "continue-on-warning"
    
  value-based-rules:
    rule-type: "value-based-rules"
    rule-name: "Value-Based Transformer Rules"
    description: "Transformer rules based on trade value ranges"
    rule-parameters:
      priority-level: "medium"
      execution-order: 300
      cache-results: true
    transformer-rules:
      large-value-trade-rule:
        rule-id: "LARGE_VALUE_TRADE_RULE"
        rule-name: "Large Value Trade Transformation Rule"
        rule-description: "Transform large value trades with enhanced processing"
        rule-condition: "#value.tradeAmount >= 1000000"
        rule-priority: 900
        transformation-actions:
          - action-type: "set-category"
            target-field: "category"
            action-value: "ValueRange"
            action-description: "Set category to ValueRange for large value trades"
          - action-type: "set-value"
            target-field: "value"
            action-value: "LargeValue"
            action-description: "Set value to LargeValue for large trades"
        validation-rules:
          - "tradeAmount != null"
          - "tradeAmount >= 1000000"
        audit-requirements:
          - "Log large value trade transformation"
          - "Track value-based categorization"
          
      medium-value-trade-rule:
        rule-id: "MEDIUM_VALUE_TRADE_RULE"
        rule-name: "Medium Value Trade Transformation Rule"
        rule-description: "Transform medium value trades with standard processing"
        rule-condition: "#value.tradeAmount >= 100000 && #value.tradeAmount < 1000000"
        rule-priority: 1000
        transformation-actions:
          - action-type: "set-category"
            target-field: "category"
            action-value: "ValueRange"
            action-description: "Set category to ValueRange for medium value trades"
          - action-type: "set-value"
            target-field: "value"
            action-value: "MediumValue"
            action-description: "Set value to MediumValue for medium trades"
        validation-rules:
          - "tradeAmount != null"
          - "tradeAmount >= 100000"
          - "tradeAmount < 1000000"
        audit-requirements:
          - "Log medium value trade transformation"
          - "Track value-based categorization"
          
      small-value-trade-rule:
        rule-id: "SMALL_VALUE_TRADE_RULE"
        rule-name: "Small Value Trade Transformation Rule"
        rule-description: "Transform small value trades with simplified processing"
        rule-condition: "#value.tradeAmount < 100000"
        rule-priority: 1100
        transformation-actions:
          - action-type: "set-category"
            target-field: "category"
            action-value: "ValueRange"
            action-description: "Set category to ValueRange for small value trades"
          - action-type: "set-value"
            target-field: "value"
            action-value: "SmallValue"
            action-description: "Set value to SmallValue for small trades"
        validation-rules:
          - "tradeAmount != null"
          - "tradeAmount < 100000"
        audit-requirements:
          - "Log small value trade transformation"
          - "Track value-based categorization"
    rule-settings:
      execution-timeout: 2000
      parallel-execution: true
      error-handling: "continue-on-warning"
    
  category-based-rules:
    rule-type: "category-based-rules"
    rule-name: "Category-Based Transformer Rules"
    description: "Transformer rules based on existing trade categories"
    rule-parameters:
      priority-level: "medium"
      execution-order: 400
      cache-results: true
    transformer-rules:
      uncategorized-trade-rule:
        rule-id: "UNCATEGORIZED_TRADE_RULE"
        rule-name: "Uncategorized Trade Transformation Rule"
        rule-description: "Transform uncategorized trades with default categorization"
        rule-condition: "#value.category == null || #value.category.isEmpty() || #value.category == 'Uncategorized'"
        rule-priority: 1200
        transformation-actions:
          - action-type: "set-category"
            target-field: "category"
            action-value: "DefaultCategory"
            action-description: "Set default category for uncategorized trades"
        validation-rules:
          - "category == null || category.isEmpty() || category == 'Uncategorized'"
        audit-requirements:
          - "Log uncategorized trade transformation"
          - "Track default categorization"
          
      existing-category-preservation-rule:
        rule-id: "EXISTING_CATEGORY_PRESERVATION_RULE"
        rule-name: "Existing Category Preservation Rule"
        rule-description: "Preserve existing valid categories"
        rule-condition: "#value.category != null && !#value.category.isEmpty() && #value.category != 'Uncategorized'"
        rule-priority: 1300
        transformation-actions:
          - action-type: "preserve-category"
            target-field: "category"
            action-description: "Preserve existing valid category"
        validation-rules:
          - "category != null"
          - "!category.isEmpty()"
          - "category != 'Uncategorized'"
        audit-requirements:
          - "Log category preservation"
          - "Track existing category maintenance"
    rule-settings:
      execution-timeout: 1500
      parallel-execution: true
      error-handling: "continue-on-warning"
    
  default:
    rule-type: "default"
    rule-name: "Default Trade Transformer Rules"
    description: "Default trade transformation processing"
    transformer-rules:
      default-rule:
        rule-id: "DEFAULT_RULE"
        rule-name: "Default Transformation Rule"
        rule-condition: "true"
        transformation-actions:
          - action-type: "set-category"
            target-field: "category"
            action-value: "DefaultCategory"
    rule-settings:
      execution-timeout: 1000

# Rule execution patterns
execution-patterns:
  instrument-priority-pattern:
    pattern-name: "Instrument Priority Pattern"
    description: "Execute instrument-based rules in priority order"
    execution-order: ["Equity", "Bond", "ETF", "Commodity"]
    
  priority-level-pattern:
    pattern-name: "Priority Level Pattern"
    description: "Execute priority-based rules by urgency"
    execution-order: ["Urgent", "High", "Medium", "Low"]
    
  value-range-pattern:
    pattern-name: "Value Range Pattern"
    description: "Execute value-based rules by trade size"
    execution-order: ["Large", "Medium", "Small"]

# Quality assurance
quality-assurance:
  rule-accuracy:
    - "Transformer rules must be logically correct"
    - "Rule conditions must be syntactically valid"
    - "Transformation actions must be appropriate"
    - "Validation rules must be comprehensive"
    
  performance-requirements:
    - "Rule execution must be within timeout limits"
    - "Complex rules must be optimized"
    - "Parallel execution must be thread-safe"
    - "Error handling must be robust"
    
  business-alignment:
    - "Rules must reflect business requirements"
    - "Trade categorization must be accurate"
    - "Priority assignments must be appropriate"
    - "Value-based processing must be correct"
