# APEX Compliance Service Configuration
# External data source configuration for compliance service
# Replaces hardcoded compliance logic from DynamicMethodExecutionDemo

metadata:
  id: "Compliance Service Configuration"
  name: "Compliance Service Configuration"
  version: "1.0.0"
  description: "Data-driven compliance service configuration for dynamic method execution"
  type: "external-data-config"
  author: "apex.demo.team@company.com"
  created-date: "2024-12-24"
  tags: ["apex-demo", "evaluation", "dynamic-execution", "compliance-service"]

# Applicable regulations by trade type
data:
  Equity_regulations:
    regulations:
      - "SEC Rule 10b-5"
      - "Regulation SHO"
      - "Market Access Rule"
      - "Regulation NMS"
      - "FINRA Rule 5310"
    description: "Regulatory framework for equity trading"
    jurisdiction: "United States"
    regulatory-bodies: ["SEC", "FINRA"]
    compliance-level: "high"
    
  FixedIncome_regulations:
    regulations:
      - "MSRB Rule G-15"
      - "TRACE Reporting"
      - "Best Execution"
      - "FINRA Rule 4210"
      - "SEC Rule 15c3-3"
    description: "Regulatory framework for fixed income trading"
    jurisdiction: "United States"
    regulatory-bodies: ["MSRB", "FINRA", "SEC"]
    compliance-level: "high"
    
  Derivative_regulations:
    regulations:
      - "Dodd-Frank Act"
      - "EMIR"
      - "Basel III"
      - "CFTC Part 23"
      - "MiFID II"
    description: "Regulatory framework for derivative trading"
    jurisdiction: "Global"
    regulatory-bodies: ["CFTC", "ESMA", "Basel Committee"]
    compliance-level: "very-high"
    
  Forex_regulations:
    regulations:
      - "CFTC Part 23"
      - "MiFID II"
      - "Basel III"
      - "FXGC Code"
      - "BIS Guidelines"
    description: "Regulatory framework for foreign exchange trading"
    jurisdiction: "Global"
    regulatory-bodies: ["CFTC", "ESMA", "BIS"]
    compliance-level: "high"
    
  Commodity_regulations:
    regulations:
      - "CEA Section 4s"
      - "REMIT"
      - "Position Limits"
      - "CFTC Part 150"
      - "EMIR Clearing"
    description: "Regulatory framework for commodity trading"
    jurisdiction: "Global"
    regulatory-bodies: ["CFTC", "ACER", "ESMA"]
    compliance-level: "very-high"

# Detailed regulatory requirements
regulatory-details:
  SEC-Rule-10b-5:
    full-name: "Employment of Manipulative and Deceptive Practices"
    category: "Anti-Fraud"
    requirements:
      - "Prohibition of insider trading"
      - "Material information disclosure"
      - "Market manipulation prevention"
    penalties: "Civil and criminal sanctions"
    monitoring-required: true
    
  Regulation-SHO:
    full-name: "Regulation SHO - Short Sale Rules"
    category: "Short Selling"
    requirements:
      - "Locate requirement for short sales"
      - "Close-out requirement"
      - "Marking requirements"
    penalties: "Fines and trading restrictions"
    monitoring-required: true
    
  Dodd-Frank-Act:
    full-name: "Dodd-Frank Wall Street Reform Act"
    category: "Systemic Risk"
    requirements:
      - "Central clearing of derivatives"
      - "Margin requirements"
      - "Trade reporting"
      - "Position limits"
    penalties: "Significant fines and restrictions"
    monitoring-required: true
    
  MiFID-II:
    full-name: "Markets in Financial Instruments Directive II"
    category: "Market Structure"
    requirements:
      - "Best execution reporting"
      - "Transaction reporting"
      - "Investor protection"
      - "Market transparency"
    penalties: "Administrative sanctions"
    monitoring-required: true
    
  Basel-III:
    full-name: "Basel III Capital Requirements"
    category: "Capital Adequacy"
    requirements:
      - "Capital adequacy ratios"
      - "Liquidity requirements"
      - "Leverage ratio"
      - "Risk management"
    penalties: "Regulatory intervention"
    monitoring-required: true

# Compliance monitoring and controls
monitoring-controls:
  real-time-monitoring:
    trade-surveillance: true
    position-monitoring: true
    limit-monitoring: true
    exception-detection: true
    
  periodic-reviews:
    daily-reviews:
      - "Position limits compliance"
      - "Trading violations"
      - "Regulatory reporting status"
    weekly-reviews:
      - "Risk limit breaches"
      - "Client suitability"
      - "Best execution analysis"
    monthly-reviews:
      - "Regulatory change impact"
      - "Compliance training status"
      - "Audit findings resolution"
      
  automated-controls:
    pre-trade-checks:
      - "Position limit validation"
      - "Client authorization"
      - "Regulatory restrictions"
    post-trade-checks:
      - "Trade reporting validation"
      - "Settlement compliance"
      - "Documentation completeness"

# Reporting requirements
reporting-requirements:
  regulatory-reporting:
    trade-reporting:
      frequency: "T+1"
      recipients: ["Regulatory authorities", "Trade repositories"]
      data-elements: ["Trade details", "Counterparty information", "Risk metrics"]
      
    position-reporting:
      frequency: "Daily"
      recipients: ["Regulatory authorities"]
      data-elements: ["Position sizes", "Concentration limits", "Risk exposures"]
      
    incident-reporting:
      frequency: "Immediate"
      recipients: ["Regulatory authorities", "Senior management"]
      data-elements: ["Incident details", "Impact assessment", "Remediation plan"]
      
  internal-reporting:
    compliance-dashboard:
      frequency: "Real-time"
      recipients: ["Compliance team", "Risk management", "Senior management"]
      
    exception-reports:
      frequency: "Daily"
      recipients: ["Compliance officers", "Business heads"]
      
    trend-analysis:
      frequency: "Monthly"
      recipients: ["Senior management", "Board of directors"]

# Risk assessment and mitigation
risk-assessment:
  compliance-risks:
    regulatory-risk:
      description: "Risk of regulatory violations"
      impact: "High"
      likelihood: "Medium"
      mitigation: "Robust monitoring and controls"
      
    reputational-risk:
      description: "Risk of reputational damage"
      impact: "High"
      likelihood: "Low"
      mitigation: "Strong compliance culture"
      
    operational-risk:
      description: "Risk of operational failures"
      impact: "Medium"
      likelihood: "Medium"
      mitigation: "Process automation and controls"
      
  mitigation-strategies:
    preventive-controls:
      - "Pre-trade compliance checks"
      - "Automated limit monitoring"
      - "Regular training programs"
      
    detective-controls:
      - "Trade surveillance systems"
      - "Exception reporting"
      - "Periodic compliance reviews"
      
    corrective-controls:
      - "Incident response procedures"
      - "Remediation processes"
      - "Disciplinary actions"

# Performance metrics
performance-metrics:
  compliance-effectiveness:
    violation-rate: "< 0.1%"
    detection-time: "< 1 hour"
    resolution-time: "< 24 hours"
    
  regulatory-relationships:
    examination-ratings: "Satisfactory or better"
    regulatory-actions: "Zero"
    cooperation-level: "Excellent"
    
  operational-efficiency:
    automation-rate: "> 90%"
    false-positive-rate: "< 5%"
    processing-time: "< 30 seconds"
