# APEX Settlement Processing Configuration
# External data source configuration for settlement processing
# Replaces hardcoded settlement logic from DynamicMethodExecutionDemo

metadata:
  id: "settlement-processing-configuration"
  name: "Settlement Processing Configuration"
  version: "1.0.0"
  description: "Data-driven settlement processing configuration for dynamic method execution"
  type: "external-data-config"
  author: "apex.demo.team@company.com"
  created-date: "2024-12-24"
  tags: ["apex-demo", "evaluation", "dynamic-execution", "settlement-processing"]

# Settlement days configuration by trade type
data:
  Equity:
    settlement-days: 2
    description: "Equity trades settle in T+2 business days"
    business-rules:
      - "Standard equity settlement cycle"
      - "Follows SEC T+2 regulation"
    risk-level: "low"
    
  FixedIncome:
    settlement-days: 1
    description: "Fixed income trades settle in T+1 business days"
    business-rules:
      - "Bond settlement cycle"
      - "Government and corporate bonds"
    risk-level: "low"
    
  Derivative:
    settlement-days: 1
    description: "Derivative trades settle in T+1 business days"
    business-rules:
      - "Options and futures settlement"
      - "Margin requirements apply"
    risk-level: "medium"
    
  Forex:
    settlement-days: 2
    description: "Foreign exchange trades settle in T+2 business days"
    business-rules:
      - "Currency pair settlement"
      - "Cross-border considerations"
    risk-level: "medium"
    
  Commodity:
    settlement-days: 3
    description: "Commodity trades settle in T+3 business days"
    business-rules:
      - "Physical commodity delivery"
      - "Storage and transportation logistics"
    risk-level: "high"

# Settlement method configuration by trade type
  Equity_method:
    settlement-method: "DTC"
    description: "Depository Trust Company for equity settlements"
    processing-details:
      - "Electronic book-entry settlement"
      - "Automated clearing and settlement"
      - "Real-time gross settlement"
    fees:
      base-fee: 0.50
      volume-discount: true
    
  FixedIncome_method:
    settlement-method: "Fedwire"
    description: "Federal Reserve wire transfer system for fixed income"
    processing-details:
      - "Real-time gross settlement system"
      - "Federal Reserve operated"
      - "High-value payment system"
    fees:
      base-fee: 25.00
      volume-discount: false
    
  Derivative_method:
    settlement-method: "Clearstream"
    description: "Clearstream for derivative settlements"
    processing-details:
      - "International central securities depository"
      - "Cross-border settlement capabilities"
      - "Multi-currency support"
    fees:
      base-fee: 15.00
      volume-discount: true
    
  Forex_method:
    settlement-method: "Euroclear"
    description: "Euroclear for foreign exchange settlements"
    processing-details:
      - "International settlement system"
      - "Multi-currency capabilities"
      - "Global reach and connectivity"
    fees:
      base-fee: 20.00
      volume-discount: true
    
  Commodity_method:
    settlement-method: "Manual"
    description: "Manual settlement for commodity trades"
    processing-details:
      - "Physical delivery coordination"
      - "Warehouse receipt management"
      - "Quality inspection requirements"
    fees:
      base-fee: 100.00
      volume-discount: false

# Advanced settlement configurations
advanced-settlement:
  same-day-settlement:
    eligible-types: ["Forex", "Derivative"]
    additional-fee: 50.00
    cutoff-time: "15:00 EST"
    
  delayed-settlement:
    eligible-types: ["Commodity"]
    maximum-delay: 10
    penalty-fee: 25.00
    
  cross-border-settlement:
    additional-requirements:
      - "Regulatory approval"
      - "Currency conversion"
      - "Tax withholding"
    processing-time: "+1 business day"

# Settlement risk factors
risk-factors:
  counterparty-risk:
    Equity: 0.01
    FixedIncome: 0.005
    Derivative: 0.02
    Forex: 0.015
    Commodity: 0.03
    
  operational-risk:
    DTC: 0.001
    Fedwire: 0.0005
    Clearstream: 0.002
    Euroclear: 0.0015
    Manual: 0.01
    
  settlement-risk:
    T+1: 0.005
    T+2: 0.01
    T+3: 0.02

# Performance benchmarks
performance-benchmarks:
  processing-time:
    DTC: "< 1 second"
    Fedwire: "< 5 seconds"
    Clearstream: "< 3 seconds"
    Euroclear: "< 3 seconds"
    Manual: "1-4 hours"
    
  success-rate:
    DTC: 99.95
    Fedwire: 99.99
    Clearstream: 99.90
    Euroclear: 99.92
    Manual: 98.50
    
  daily-capacity:
    DTC: 1000000
    Fedwire: 500000
    Clearstream: 750000
    Euroclear: 800000
    Manual: 1000

# Compliance requirements
compliance:
  regulatory-frameworks:
    - "SEC Settlement Rules"
    - "CFTC Settlement Requirements"
    - "Basel III Settlement Risk"
    - "MiFID II Settlement Discipline"
    
  reporting-requirements:
    - "Trade reporting within T+1"
    - "Settlement failure reporting"
    - "Risk exposure reporting"
    - "Operational incident reporting"
    
  audit-trail:
    retention-period: "7 years"
    data-elements:
      - "Trade details"
      - "Settlement instructions"
      - "Confirmation timestamps"
      - "Exception handling"
