# APEX Risk Assessment Models Configuration
# External data source configuration for risk assessment models
# Replaces hardcoded risk assessment logic from RiskManagementService

metadata:
  name: "Risk Assessment Models Configuration"
  version: "1.0.0"
  description: "Data-driven risk assessment models configuration for risk management service"
  type: "external-data-config"
  author: "apex.demo.team@company.com"
  created-date: "2024-12-24"
  tags: ["apex-demo", "evaluation", "risk-management", "risk-assessment-models"]

# Risk assessment models configuration by model type
data:
  market-risk-assessment-models:
    model-type: "market-risk-assessment-models"
    model-name: "Market Risk Assessment Models"
    description: "Models for market risk assessment and evaluation"
    model-characteristics:
      risk-category: "MARKET"
      assessment-method: "FACTOR_BASED"
      volatility-sensitivity: "HIGH"
    assessment-models:
      equity-market-risk-model:
        model-id: "EQUITY_MARKET_RISK_MODEL"
        model-name: "Equity Market Risk Assessment Model"
        model-description: "Market risk assessment model for equity trades"
        risk-factors:
          volatility-factor: 0.15
          beta-factor: 1.2
          sector-concentration-factor: 0.08
          market-correlation-factor: 0.85
        assessment-rules:
          - rule-name: "equity-volatility-assessment"
            rule-condition: "#trade.type == 'Equity'"
            rule-calculation: "#trade.notionalAmount * 0.15 * #volatilityIndex"
            rule-description: "Assess equity volatility risk"
            rule-priority: 1
          - rule-name: "equity-beta-adjustment"
            rule-condition: "#trade.type == 'Equity' && #trade.beta != null"
            rule-calculation: "#baseRisk * #trade.beta"
            rule-description: "Adjust risk based on equity beta"
            rule-priority: 2
          - rule-name: "equity-sector-concentration"
            rule-condition: "#trade.type == 'Equity' && #sectorConcentration > 0.3"
            rule-calculation: "#baseRisk * 1.2"
            rule-description: "Increase risk for sector concentration"
            rule-priority: 3
        risk-thresholds:
          low-risk-threshold: 0.05
          medium-risk-threshold: 0.15
          high-risk-threshold: 0.25
          extreme-risk-threshold: 0.40
        audit-requirements:
          - "Log equity market risk assessments"
          - "Track volatility impact analysis"
          
      fixed-income-market-risk-model:
        model-id: "FIXED_INCOME_MARKET_RISK_MODEL"
        model-name: "Fixed Income Market Risk Assessment Model"
        model-description: "Market risk assessment model for fixed income trades"
        risk-factors:
          duration-factor: 0.12
          credit-spread-factor: 0.08
          yield-curve-factor: 0.10
          convexity-factor: 0.05
        assessment-rules:
          - rule-name: "duration-risk-assessment"
            rule-condition: "#trade.type == 'FixedIncome'"
            rule-calculation: "#trade.notionalAmount * 0.12 * #duration"
            rule-description: "Assess duration risk for fixed income"
            rule-priority: 1
          - rule-name: "credit-spread-risk"
            rule-condition: "#trade.type == 'FixedIncome' && #creditSpread != null"
            rule-calculation: "#baseRisk * (1 + #creditSpread)"
            rule-description: "Adjust risk based on credit spread"
            rule-priority: 2
          - rule-name: "yield-curve-risk"
            rule-condition: "#trade.type == 'FixedIncome'"
            rule-calculation: "#baseRisk * #yieldCurveShift"
            rule-description: "Assess yield curve risk"
            rule-priority: 3
        risk-thresholds:
          low-risk-threshold: 0.03
          medium-risk-threshold: 0.10
          high-risk-threshold: 0.20
          extreme-risk-threshold: 0.35
        audit-requirements:
          - "Log fixed income market risk assessments"
          - "Track duration and credit spread impact"
          
      derivative-market-risk-model:
        model-id: "DERIVATIVE_MARKET_RISK_MODEL"
        model-name: "Derivative Market Risk Assessment Model"
        model-description: "Market risk assessment model for derivative trades"
        risk-factors:
          delta-factor: 0.20
          gamma-factor: 0.15
          vega-factor: 0.18
          theta-factor: 0.10
        assessment-rules:
          - rule-name: "delta-risk-assessment"
            rule-condition: "#trade.type == 'Derivative'"
            rule-calculation: "#trade.notionalAmount * 0.20 * #delta"
            rule-description: "Assess delta risk for derivatives"
            rule-priority: 1
          - rule-name: "gamma-risk-assessment"
            rule-condition: "#trade.type == 'Derivative' && #gamma != null"
            rule-calculation: "#baseRisk + (#trade.notionalAmount * 0.15 * #gamma)"
            rule-description: "Add gamma risk component"
            rule-priority: 2
          - rule-name: "vega-risk-assessment"
            rule-condition: "#trade.type == 'Derivative' && #vega != null"
            rule-calculation: "#baseRisk + (#trade.notionalAmount * 0.18 * #vega)"
            rule-description: "Add vega (volatility) risk component"
            rule-priority: 3
        risk-thresholds:
          low-risk-threshold: 0.08
          medium-risk-threshold: 0.20
          high-risk-threshold: 0.35
          extreme-risk-threshold: 0.50
        audit-requirements:
          - "Log derivative market risk assessments"
          - "Track Greeks impact analysis"
    model-settings:
      volatility-tracking: true
      correlation-analysis: true
      stress-testing: true
    
  credit-risk-assessment-models:
    model-type: "credit-risk-assessment-models"
    model-name: "Credit Risk Assessment Models"
    description: "Models for credit risk assessment and evaluation"
    model-characteristics:
      risk-category: "CREDIT"
      assessment-method: "RATING_BASED"
      default-probability: "VARIABLE"
    assessment-models:
      counterparty-credit-risk-model:
        model-id: "COUNTERPARTY_CREDIT_RISK_MODEL"
        model-name: "Counterparty Credit Risk Assessment Model"
        model-description: "Credit risk assessment model based on counterparty ratings"
        risk-factors:
          rating-factor: 0.25
          exposure-factor: 0.20
          collateral-factor: 0.15
          maturity-factor: 0.10
        assessment-rules:
          - rule-name: "aaa-rating-assessment"
            rule-condition: "#counterparty.rating == 'AAA'"
            rule-calculation: "#trade.notionalAmount * 0.02"
            rule-description: "Minimal credit risk for AAA rating"
            rule-priority: 1
          - rule-name: "aa-rating-assessment"
            rule-condition: "#counterparty.rating == 'AA'"
            rule-calculation: "#trade.notionalAmount * 0.05"
            rule-description: "Low credit risk for AA rating"
            rule-priority: 1
          - rule-name: "a-rating-assessment"
            rule-condition: "#counterparty.rating == 'A'"
            rule-calculation: "#trade.notionalAmount * 0.08"
            rule-description: "Moderate credit risk for A rating"
            rule-priority: 1
          - rule-name: "bbb-rating-assessment"
            rule-condition: "#counterparty.rating == 'BBB'"
            rule-calculation: "#trade.notionalAmount * 0.12"
            rule-description: "Higher credit risk for BBB rating"
            rule-priority: 1
          - rule-name: "below-investment-grade"
            rule-condition: "#counterparty.rating != null && !T(java.util.Arrays).asList('AAA', 'AA', 'A', 'BBB').contains(#counterparty.rating)"
            rule-calculation: "#trade.notionalAmount * 0.25"
            rule-description: "High credit risk for below investment grade"
            rule-priority: 1
        risk-thresholds:
          low-risk-threshold: 0.05
          medium-risk-threshold: 0.12
          high-risk-threshold: 0.20
          extreme-risk-threshold: 0.30
        audit-requirements:
          - "Log counterparty credit risk assessments"
          - "Track rating impact analysis"
          
      collateral-credit-risk-model:
        model-id: "COLLATERAL_CREDIT_RISK_MODEL"
        model-name: "Collateral Credit Risk Assessment Model"
        model-description: "Credit risk assessment model considering collateral"
        risk-factors:
          collateral-coverage-factor: 0.30
          collateral-quality-factor: 0.25
          haircut-factor: 0.20
          liquidation-factor: 0.15
        assessment-rules:
          - rule-name: "full-collateral-coverage"
            rule-condition: "#collateral.coverage >= 1.0"
            rule-calculation: "#baseRisk * 0.3"
            rule-description: "Reduce risk for full collateral coverage"
            rule-priority: 1
          - rule-name: "partial-collateral-coverage"
            rule-condition: "#collateral.coverage >= 0.5 && #collateral.coverage < 1.0"
            rule-calculation: "#baseRisk * 0.7"
            rule-description: "Moderate risk reduction for partial collateral"
            rule-priority: 1
          - rule-name: "minimal-collateral-coverage"
            rule-condition: "#collateral.coverage < 0.5"
            rule-calculation: "#baseRisk * 0.9"
            rule-description: "Minimal risk reduction for low collateral"
            rule-priority: 1
          - rule-name: "high-quality-collateral"
            rule-condition: "#collateral.quality == 'HIGH'"
            rule-calculation: "#baseRisk * 0.8"
            rule-description: "Risk reduction for high-quality collateral"
            rule-priority: 2
        risk-thresholds:
          low-risk-threshold: 0.03
          medium-risk-threshold: 0.08
          high-risk-threshold: 0.15
          extreme-risk-threshold: 0.25
        audit-requirements:
          - "Log collateral credit risk assessments"
          - "Track collateral effectiveness"
    model-settings:
      rating-monitoring: true
      collateral-valuation: true
      exposure-tracking: true
    
  liquidity-risk-assessment-models:
    model-type: "liquidity-risk-assessment-models"
    model-name: "Liquidity Risk Assessment Models"
    description: "Models for liquidity risk assessment and evaluation"
    model-characteristics:
      risk-category: "LIQUIDITY"
      assessment-method: "MARKET_DEPTH"
      time-sensitivity: "HIGH"
    assessment-models:
      market-liquidity-risk-model:
        model-id: "MARKET_LIQUIDITY_RISK_MODEL"
        model-name: "Market Liquidity Risk Assessment Model"
        model-description: "Liquidity risk assessment based on market conditions"
        risk-factors:
          bid-ask-spread-factor: 0.30
          market-depth-factor: 0.25
          trading-volume-factor: 0.20
          volatility-factor: 0.15
        assessment-rules:
          - rule-name: "tight-spread-assessment"
            rule-condition: "#market.bidAskSpread <= 0.01"
            rule-calculation: "#trade.notionalAmount * 0.02"
            rule-description: "Low liquidity risk for tight spreads"
            rule-priority: 1
          - rule-name: "wide-spread-assessment"
            rule-condition: "#market.bidAskSpread > 0.05"
            rule-calculation: "#trade.notionalAmount * 0.15"
            rule-description: "High liquidity risk for wide spreads"
            rule-priority: 1
          - rule-name: "deep-market-assessment"
            rule-condition: "#market.depth == 'DEEP'"
            rule-calculation: "#baseRisk * 0.7"
            rule-description: "Risk reduction for deep markets"
            rule-priority: 2
          - rule-name: "shallow-market-assessment"
            rule-condition: "#market.depth == 'SHALLOW'"
            rule-calculation: "#baseRisk * 1.5"
            rule-description: "Risk increase for shallow markets"
            rule-priority: 2
        risk-thresholds:
          low-risk-threshold: 0.02
          medium-risk-threshold: 0.08
          high-risk-threshold: 0.15
          extreme-risk-threshold: 0.25
        audit-requirements:
          - "Log market liquidity risk assessments"
          - "Track market depth analysis"
          
      funding-liquidity-risk-model:
        model-id: "FUNDING_LIQUIDITY_RISK_MODEL"
        model-name: "Funding Liquidity Risk Assessment Model"
        model-description: "Liquidity risk assessment for funding requirements"
        risk-factors:
          cash-availability-factor: 0.35
          credit-facility-factor: 0.25
          maturity-mismatch-factor: 0.20
          concentration-factor: 0.15
        assessment-rules:
          - rule-name: "high-cash-availability"
            rule-condition: "#funding.cashRatio >= 0.2"
            rule-calculation: "#trade.notionalAmount * 0.01"
            rule-description: "Low funding risk with high cash"
            rule-priority: 1
          - rule-name: "low-cash-availability"
            rule-condition: "#funding.cashRatio < 0.05"
            rule-calculation: "#trade.notionalAmount * 0.12"
            rule-description: "High funding risk with low cash"
            rule-priority: 1
          - rule-name: "credit-facility-available"
            rule-condition: "#funding.creditFacilityAvailable == true"
            rule-calculation: "#baseRisk * 0.8"
            rule-description: "Risk reduction with credit facility"
            rule-priority: 2
        risk-thresholds:
          low-risk-threshold: 0.01
          medium-risk-threshold: 0.05
          high-risk-threshold: 0.12
          extreme-risk-threshold: 0.20
        audit-requirements:
          - "Log funding liquidity risk assessments"
          - "Track funding availability"
    model-settings:
      market-monitoring: true
      funding-tracking: true
      liquidity-optimization: true
    
  operational-risk-assessment-models:
    model-type: "operational-risk-assessment-models"
    model-name: "Operational Risk Assessment Models"
    description: "Models for operational risk assessment and evaluation"
    model-characteristics:
      risk-category: "OPERATIONAL"
      assessment-method: "PROCESS_BASED"
      human-factor: "SIGNIFICANT"
    assessment-models:
      process-operational-risk-model:
        model-id: "PROCESS_OPERATIONAL_RISK_MODEL"
        model-name: "Process Operational Risk Assessment Model"
        model-description: "Operational risk assessment based on process complexity"
        risk-factors:
          process-complexity-factor: 0.25
          automation-level-factor: 0.20
          human-intervention-factor: 0.30
          error-rate-factor: 0.15
        assessment-rules:
          - rule-name: "simple-process-assessment"
            rule-condition: "#process.complexity == 'SIMPLE'"
            rule-calculation: "#trade.notionalAmount * 0.02"
            rule-description: "Low operational risk for simple processes"
            rule-priority: 1
          - rule-name: "complex-process-assessment"
            rule-condition: "#process.complexity == 'COMPLEX'"
            rule-calculation: "#trade.notionalAmount * 0.08"
            rule-description: "Higher operational risk for complex processes"
            rule-priority: 1
          - rule-name: "high-automation-assessment"
            rule-condition: "#process.automationLevel >= 0.8"
            rule-calculation: "#baseRisk * 0.6"
            rule-description: "Risk reduction for high automation"
            rule-priority: 2
          - rule-name: "manual-process-assessment"
            rule-condition: "#process.automationLevel < 0.3"
            rule-calculation: "#baseRisk * 1.4"
            rule-description: "Risk increase for manual processes"
            rule-priority: 2
        risk-thresholds:
          low-risk-threshold: 0.02
          medium-risk-threshold: 0.06
          high-risk-threshold: 0.12
          extreme-risk-threshold: 0.20
        audit-requirements:
          - "Log process operational risk assessments"
          - "Track automation impact"
    model-settings:
      process-monitoring: true
      automation-tracking: true
      error-analysis: true
    
  default:
    model-type: "default"
    model-name: "Default Risk Assessment Models"
    description: "Default risk assessment model processing"
    assessment-models:
      default-model:
        model-id: "DEFAULT_MODEL"
        model-name: "Default Model"
        assessment-rules:
          - rule-name: "default-assessment"
            rule-calculation: "#trade.notionalAmount * 0.05"
            rule-description: "Default risk assessment"
    model-settings:
      default-processing: true

# Model execution patterns
execution-patterns:
  risk-category-pattern:
    pattern-name: "Risk Category Pattern"
    description: "Execute models based on risk categories"
    risk-categories: ["MARKET", "CREDIT", "LIQUIDITY", "OPERATIONAL"]
    
  assessment-method-pattern:
    pattern-name: "Assessment Method Pattern"
    description: "Execute models based on assessment methods"
    assessment-methods: ["FACTOR_BASED", "RATING_BASED", "MARKET_DEPTH", "PROCESS_BASED"]
    
  trade-type-pattern:
    pattern-name: "Trade Type Pattern"
    description: "Execute models based on trade types"
    trade-types: ["Equity", "FixedIncome", "Derivative", "Forex", "Commodity"]

# Quality assurance
quality-assurance:
  model-accuracy:
    - "Risk assessment models must be accurate"
    - "Risk calculations must be precise"
    - "Risk factors must be current"
    - "Risk thresholds must be appropriate"
    
  model-reliability:
    - "Models must be consistent"
    - "Assessments must be repeatable"
    - "Performance must be acceptable"
    - "Results must be auditable"
    
  regulatory-compliance:
    - "Models must comply with risk regulations"
    - "Assessments must meet standards"
    - "Documentation must be complete"
    - "Validation must be thorough"
