# APEX Risk Monitoring Frameworks Configuration
# External data source configuration for risk monitoring frameworks
# Replaces hardcoded risk monitoring logic from RiskManagementService

metadata:
  id: "risk-monitoring-frameworks-configuration"
  name: "Risk Monitoring Frameworks Configuration"
  version: "1.0.0"
  description: "Data-driven risk monitoring frameworks configuration for risk management service"
  type: "external-data-config"
  author: "apex.demo.team@company.com"
  created-date: "2024-12-24"
  tags: ["apex-demo", "evaluation", "risk-management", "risk-monitoring-frameworks"]

# Risk monitoring frameworks configuration by framework type
data:
  risk-level-determination-frameworks:
    framework-type: "risk-level-determination-frameworks"
    framework-name: "Risk Level Determination Frameworks"
    description: "Frameworks for determining risk levels and classifications"
    framework-characteristics:
      monitoring-category: "RISK_CLASSIFICATION"
      determination-method: "THRESHOLD_BASED"
      real-time-capability: true
    monitoring-frameworks:
      total-risk-level-framework:
        framework-id: "risk-monitoring-frameworks-configuration"
        framework-name: "Total Risk Level Determination Framework"
        framework-description: "Framework for determining overall risk level"
        risk-thresholds:
          low-risk-threshold: 0.0
          low-risk-upper-bound: 0.3
          medium-risk-threshold: 0.3
          medium-risk-upper-bound: 0.6
          high-risk-threshold: 0.6
          high-risk-upper-bound: 0.8
          extreme-risk-threshold: 0.8
          extreme-risk-upper-bound: 1.0
        determination-rules:
          - rule-name: "low-risk-determination"
            rule-condition: "#totalRisk >= 0.0 && #totalRisk < 0.3"
            rule-result: "Low"
            rule-description: "Classify as low risk (0-30%)"
            rule-priority: 1
            rule-action: "CLASSIFY"
          - rule-name: "medium-risk-determination"
            rule-condition: "#totalRisk >= 0.3 && #totalRisk < 0.6"
            rule-result: "Medium"
            rule-description: "Classify as medium risk (30-60%)"
            rule-priority: 1
            rule-action: "CLASSIFY"
          - rule-name: "high-risk-determination"
            rule-condition: "#totalRisk >= 0.6 && #totalRisk < 0.8"
            rule-result: "High"
            rule-description: "Classify as high risk (60-80%)"
            rule-priority: 1
            rule-action: "CLASSIFY"
          - rule-name: "extreme-risk-determination"
            rule-condition: "#totalRisk >= 0.8"
            rule-result: "Extreme"
            rule-description: "Classify as extreme risk (80%+)"
            rule-priority: 1
            rule-action: "CLASSIFY"
        monitoring-actions:
          low-risk-actions:
            - "Standard monitoring"
            - "Daily risk reports"
            - "Routine review"
          medium-risk-actions:
            - "Enhanced monitoring"
            - "Hourly risk reports"
            - "Supervisor notification"
          high-risk-actions:
            - "Intensive monitoring"
            - "Real-time risk reports"
            - "Manager escalation"
          extreme-risk-actions:
            - "Continuous monitoring"
            - "Immediate alerts"
            - "Executive escalation"
        framework-outcomes:
          success-outcome: "RISK_LEVEL_DETERMINED"
          failure-outcome: "RISK_LEVEL_DETERMINATION_FAILED"
        audit-requirements:
          - "Log risk level determinations"
          - "Track threshold breaches"
          
      component-risk-level-framework:
        framework-id: "risk-monitoring-frameworks-configuration"
        framework-name: "Component Risk Level Determination Framework"
        framework-description: "Framework for determining individual risk component levels"
        component-thresholds:
          market-risk-thresholds:
            low: 0.05
            medium: 0.15
            high: 0.25
            extreme: 0.40
          credit-risk-thresholds:
            low: 0.03
            medium: 0.10
            high: 0.20
            extreme: 0.35
          liquidity-risk-thresholds:
            low: 0.02
            medium: 0.08
            high: 0.15
            extreme: 0.25
          operational-risk-thresholds:
            low: 0.02
            medium: 0.06
            high: 0.12
            extreme: 0.20
          settlement-risk-thresholds:
            low: 0.01
            medium: 0.05
            high: 0.10
            extreme: 0.15
        determination-rules:
          - rule-name: "market-risk-level-determination"
            rule-condition: "true"
            rule-calculation: "#marketRisk < 0.05 ? 'Low' : (#marketRisk < 0.15 ? 'Medium' : (#marketRisk < 0.25 ? 'High' : 'Extreme'))"
            rule-description: "Determine market risk level"
            rule-priority: 1
            rule-action: "CLASSIFY"
          - rule-name: "credit-risk-level-determination"
            rule-condition: "true"
            rule-calculation: "#creditRisk < 0.03 ? 'Low' : (#creditRisk < 0.10 ? 'Medium' : (#creditRisk < 0.20 ? 'High' : 'Extreme'))"
            rule-description: "Determine credit risk level"
            rule-priority: 1
            rule-action: "CLASSIFY"
          - rule-name: "liquidity-risk-level-determination"
            rule-condition: "true"
            rule-calculation: "#liquidityRisk < 0.02 ? 'Low' : (#liquidityRisk < 0.08 ? 'Medium' : (#liquidityRisk < 0.15 ? 'High' : 'Extreme'))"
            rule-description: "Determine liquidity risk level"
            rule-priority: 1
            rule-action: "CLASSIFY"
        framework-outcomes:
          success-outcome: "COMPONENT_RISK_LEVELS_DETERMINED"
          failure-outcome: "COMPONENT_RISK_LEVEL_DETERMINATION_FAILED"
        audit-requirements:
          - "Log component risk level determinations"
          - "Track individual risk component trends"
    framework-settings:
      real-time-determination: true
      threshold-monitoring: true
      escalation-automation: true
    
  risk-threshold-monitoring-frameworks:
    framework-type: "risk-threshold-monitoring-frameworks"
    framework-name: "Risk Threshold Monitoring Frameworks"
    description: "Frameworks for monitoring risk thresholds and breach detection"
    framework-characteristics:
      monitoring-category: "THRESHOLD_MONITORING"
      detection-method: "CONTINUOUS"
      alert-capability: true
    monitoring-frameworks:
      breach-detection-framework:
        framework-id: "risk-monitoring-frameworks-configuration"
        framework-name: "Risk Threshold Breach Detection Framework"
        framework-description: "Framework for detecting risk threshold breaches"
        breach-thresholds:
          warning-threshold: 0.8
          critical-threshold: 0.9
          emergency-threshold: 0.95
        detection-rules:
          - rule-name: "warning-threshold-breach"
            rule-condition: "#totalRisk >= (#riskLimit * 0.8) && #totalRisk < (#riskLimit * 0.9)"
            rule-result: "WARNING"
            rule-description: "Warning threshold breach detected (80-90% of limit)"
            rule-priority: 1
            rule-action: "ALERT"
          - rule-name: "critical-threshold-breach"
            rule-condition: "#totalRisk >= (#riskLimit * 0.9) && #totalRisk < (#riskLimit * 0.95)"
            rule-result: "CRITICAL"
            rule-description: "Critical threshold breach detected (90-95% of limit)"
            rule-priority: 1
            rule-action: "ESCALATE"
          - rule-name: "emergency-threshold-breach"
            rule-condition: "#totalRisk >= (#riskLimit * 0.95)"
            rule-result: "EMERGENCY"
            rule-description: "Emergency threshold breach detected (95%+ of limit)"
            rule-priority: 1
            rule-action: "EMERGENCY"
          - rule-name: "limit-exceeded"
            rule-condition: "#totalRisk > #riskLimit"
            rule-result: "LIMIT_EXCEEDED"
            rule-description: "Risk limit exceeded"
            rule-priority: 1
            rule-action: "STOP"
        alert-actions:
          warning-actions:
            - "Send warning notification"
            - "Increase monitoring frequency"
            - "Prepare risk report"
          critical-actions:
            - "Send critical alert"
            - "Notify risk manager"
            - "Initiate risk review"
          emergency-actions:
            - "Send emergency alert"
            - "Notify senior management"
            - "Activate risk committee"
          limit-exceeded-actions:
            - "Stop new positions"
            - "Immediate escalation"
            - "Emergency risk meeting"
        framework-outcomes:
          success-outcome: "THRESHOLD_BREACH_DETECTED"
          failure-outcome: "THRESHOLD_MONITORING_FAILED"
        audit-requirements:
          - "Log all threshold breaches"
          - "Track breach response times"
          
      trend-monitoring-framework:
        framework-id: "risk-monitoring-frameworks-configuration"
        framework-name: "Risk Trend Monitoring Framework"
        framework-description: "Framework for monitoring risk trends and patterns"
        trend-parameters:
          trend-window: 24
          trend-threshold: 0.1
          acceleration-threshold: 0.05
        monitoring-rules:
          - rule-name: "increasing-risk-trend"
            rule-condition: "#riskTrend > 0.1"
            rule-result: "INCREASING"
            rule-description: "Risk is increasing significantly"
            rule-priority: 1
            rule-action: "MONITOR"
          - rule-name: "decreasing-risk-trend"
            rule-condition: "#riskTrend < -0.1"
            rule-result: "DECREASING"
            rule-description: "Risk is decreasing significantly"
            rule-priority: 1
            rule-action: "MONITOR"
          - rule-name: "accelerating-risk"
            rule-condition: "#riskAcceleration > 0.05"
            rule-result: "ACCELERATING"
            rule-description: "Risk is accelerating"
            rule-priority: 1
            rule-action: "ALERT"
          - rule-name: "stable-risk-trend"
            rule-condition: "T(java.lang.Math).abs(#riskTrend) <= 0.1"
            rule-result: "STABLE"
            rule-description: "Risk trend is stable"
            rule-priority: 2
            rule-action: "CONTINUE"
        framework-outcomes:
          success-outcome: "RISK_TREND_MONITORED"
          failure-outcome: "RISK_TREND_MONITORING_FAILED"
        audit-requirements:
          - "Log risk trend analysis"
          - "Track trend pattern changes"
    framework-settings:
      continuous-monitoring: true
      breach-detection: true
      trend-analysis: true
    
  risk-aggregation-frameworks:
    framework-type: "risk-aggregation-frameworks"
    framework-name: "Risk Aggregation Frameworks"
    description: "Frameworks for aggregating and consolidating risk measures"
    framework-characteristics:
      monitoring-category: "RISK_AGGREGATION"
      aggregation-method: "WEIGHTED_SUM"
      correlation-adjustment: true
    monitoring-frameworks:
      total-risk-aggregation-framework:
        framework-id: "risk-monitoring-frameworks-configuration"
        framework-name: "Total Risk Aggregation Framework"
        framework-description: "Framework for aggregating total risk from components"
        aggregation-weights:
          market-risk-weight: 0.3
          credit-risk-weight: 0.25
          liquidity-risk-weight: 0.2
          operational-risk-weight: 0.15
          settlement-risk-weight: 0.1
        aggregation-rules:
          - rule-name: "simple-risk-aggregation"
            rule-condition: "#correlationMatrix == null"
            rule-calculation: "#marketRisk + #creditRisk + #liquidityRisk + #operationalRisk + #settlementRisk"
            rule-description: "Simple sum aggregation without correlation"
            rule-priority: 1
            rule-action: "AGGREGATE"
          - rule-name: "weighted-risk-aggregation"
            rule-condition: "#useWeights == true"
            rule-calculation: "(#marketRisk * 0.3) + (#creditRisk * 0.25) + (#liquidityRisk * 0.2) + (#operationalRisk * 0.15) + (#settlementRisk * 0.1)"
            rule-description: "Weighted sum aggregation"
            rule-priority: 2
            rule-action: "AGGREGATE"
          - rule-name: "correlation-adjusted-aggregation"
            rule-condition: "#correlationMatrix != null"
            rule-calculation: "T(java.lang.Math).sqrt((#marketRisk * #marketRisk) + (#creditRisk * #creditRisk) + (#liquidityRisk * #liquidityRisk) + (#operationalRisk * #operationalRisk) + (#settlementRisk * #settlementRisk) + 2 * #correlationAdjustment)"
            rule-description: "Correlation-adjusted aggregation"
            rule-priority: 3
            rule-action: "AGGREGATE"
        diversification-benefits:
          - benefit-name: "market-credit-diversification"
            correlation-threshold: 0.3
            diversification-factor: 0.1
          - benefit-name: "liquidity-operational-diversification"
            correlation-threshold: 0.2
            diversification-factor: 0.05
        framework-outcomes:
          success-outcome: "TOTAL_RISK_AGGREGATED"
          failure-outcome: "RISK_AGGREGATION_FAILED"
        audit-requirements:
          - "Log risk aggregation calculations"
          - "Track diversification benefits"
          
      portfolio-risk-aggregation-framework:
        framework-id: "risk-monitoring-frameworks-configuration"
        framework-name: "Portfolio Risk Aggregation Framework"
        framework-description: "Framework for aggregating risk across portfolio positions"
        aggregation-methods:
          position-level: "INDIVIDUAL"
          sector-level: "GROUPED"
          portfolio-level: "CONSOLIDATED"
        aggregation-rules:
          - rule-name: "position-level-aggregation"
            rule-condition: "#aggregationLevel == 'POSITION'"
            rule-calculation: "#positionRisks.stream().mapToDouble(r -> r.doubleValue()).sum()"
            rule-description: "Aggregate risk at position level"
            rule-priority: 1
            rule-action: "AGGREGATE"
          - rule-name: "sector-level-aggregation"
            rule-condition: "#aggregationLevel == 'SECTOR'"
            rule-calculation: "#sectorRisks.values().stream().mapToDouble(r -> r.doubleValue()).sum()"
            rule-description: "Aggregate risk at sector level"
            rule-priority: 2
            rule-action: "AGGREGATE"
          - rule-name: "portfolio-level-aggregation"
            rule-condition: "#aggregationLevel == 'PORTFOLIO'"
            rule-calculation: "#portfolioRisk"
            rule-description: "Total portfolio risk"
            rule-priority: 3
            rule-action: "AGGREGATE"
        framework-outcomes:
          success-outcome: "PORTFOLIO_RISK_AGGREGATED"
          failure-outcome: "PORTFOLIO_RISK_AGGREGATION_FAILED"
        audit-requirements:
          - "Log portfolio risk aggregation"
          - "Track aggregation hierarchy"
    framework-settings:
      weighted-aggregation: true
      correlation-adjustment: true
      diversification-recognition: true
    
  risk-reporting-frameworks:
    framework-type: "risk-reporting-frameworks"
    framework-name: "Risk Reporting Frameworks"
    description: "Frameworks for risk reporting and communication"
    framework-characteristics:
      monitoring-category: "RISK_REPORTING"
      reporting-method: "AUTOMATED"
      stakeholder-focused: true
    monitoring-frameworks:
      executive-risk-reporting-framework:
        framework-id: "risk-monitoring-frameworks-configuration"
        framework-name: "Executive Risk Reporting Framework"
        framework-description: "Framework for executive-level risk reporting"
        reporting-frequency:
          daily-reports: "SUMMARY"
          weekly-reports: "DETAILED"
          monthly-reports: "COMPREHENSIVE"
          ad-hoc-reports: "EVENT_DRIVEN"
        reporting-rules:
          - rule-name: "daily-executive-summary"
            rule-condition: "#reportType == 'DAILY_EXECUTIVE'"
            rule-content: "Risk level: #riskLevel, Total risk: #totalRisk, Key concerns: #keyConcerns"
            rule-description: "Generate daily executive risk summary"
            rule-priority: 1
            rule-action: "REPORT"
          - rule-name: "threshold-breach-report"
            rule-condition: "#thresholdBreach == true"
            rule-content: "ALERT: Risk threshold breach detected. Current risk: #totalRisk, Limit: #riskLimit, Action required: #requiredAction"
            rule-description: "Generate threshold breach alert report"
            rule-priority: 1
            rule-action: "ALERT"
          - rule-name: "weekly-detailed-report"
            rule-condition: "#reportType == 'WEEKLY_DETAILED'"
            rule-content: "Detailed risk analysis including trends, component breakdown, and recommendations"
            rule-description: "Generate weekly detailed risk report"
            rule-priority: 2
            rule-action: "REPORT"
        stakeholder-distribution:
          executives: ["CEO", "CRO", "CFO"]
          risk-managers: ["HEAD_OF_RISK", "SENIOR_RISK_MANAGER"]
          regulators: ["REGULATORY_REPORTING"]
        framework-outcomes:
          success-outcome: "EXECUTIVE_RISK_REPORT_GENERATED"
          failure-outcome: "EXECUTIVE_RISK_REPORTING_FAILED"
        audit-requirements:
          - "Log all executive reports"
          - "Track report distribution"
    framework-settings:
      automated-reporting: true
      stakeholder-customization: true
      real-time-alerts: true
    
  default:
    framework-type: "default"
    framework-name: "Default Risk Monitoring Frameworks"
    description: "Default risk monitoring framework processing"
    monitoring-frameworks:
      default-framework:
        framework-id: "risk-monitoring-frameworks-configuration"
        framework-name: "Default Framework"
        determination-rules:
          - rule-name: "default-monitoring"
            rule-result: "Medium"
            rule-description: "Default risk monitoring"
    framework-settings:
      default-processing: true

# Framework execution patterns
execution-patterns:
  monitoring-category-pattern:
    pattern-name: "Monitoring Category Pattern"
    description: "Execute frameworks based on monitoring categories"
    monitoring-categories: ["RISK_CLASSIFICATION", "THRESHOLD_MONITORING", "RISK_AGGREGATION", "RISK_REPORTING"]
    
  determination-method-pattern:
    pattern-name: "Determination Method Pattern"
    description: "Execute frameworks based on determination methods"
    determination-methods: ["THRESHOLD_BASED", "CONTINUOUS", "WEIGHTED_SUM", "AUTOMATED"]
    
  risk-level-pattern:
    pattern-name: "Risk Level Pattern"
    description: "Execute frameworks based on risk levels"
    risk-levels: ["Low", "Medium", "High", "Extreme"]

# Quality assurance
quality-assurance:
  framework-accuracy:
    - "Risk monitoring frameworks must be accurate"
    - "Risk classifications must be correct"
    - "Threshold monitoring must be reliable"
    - "Aggregations must be mathematically sound"
    
  framework-reliability:
    - "Frameworks must be consistent"
    - "Monitoring must be continuous"
    - "Alerts must be timely"
    - "Reports must be accurate"
    
  regulatory-compliance:
    - "Monitoring must comply with regulations"
    - "Reporting must meet standards"
    - "Audit trails must be complete"
    - "Documentation must be thorough"
