# APEX Trade Processing Workflows Configuration
# External data source configuration for trade processing workflows
# Replaces hardcoded post-trade processing workflow logic from PostTradeProcessingServiceDemo

metadata:
  id: "Trade Processing Workflows Configuration"
  name: "Trade Processing Workflows Configuration"
  version: "1.0.0"
  description: "Data-driven trade processing workflows configuration for post-trade processing service"
  type: "external-data-config"
  author: "apex.demo.team@company.com"
  created-date: "2024-12-24"
  tags: ["apex-demo", "evaluation", "post-trade-processing", "trade-processing-workflows"]

# Trade processing workflows configuration by workflow type
data:
  trade-validation-workflows:
    workflow-type: "trade-validation-workflows"
    workflow-name: "Trade Validation Workflows"
    description: "Workflows for trade validation and compliance checking"
    workflow-characteristics:
      workflow-category: "VALIDATION"
      execution-model: "SEQUENTIAL"
      error-handling: "FAIL_FAST"
    processing-workflows:
      equity-trade-validation-workflow:
        workflow-id: "EQUITY_TRADE_VALIDATION_WORKFLOW"
        workflow-name: "Equity Trade Validation Workflow"
        workflow-description: "Comprehensive validation workflow for equity trades"
        trade-type: "Equity"
        validation-steps:
          - step-name: "basic-trade-validation"
            step-description: "Basic trade data validation"
            validation-rules:
              - rule-name: "trade-not-null"
                rule-condition: "#trade != null"
                rule-description: "Trade object must not be null"
              - rule-name: "trade-id-valid"
                rule-condition: "#trade.id != null && !#trade.id.isEmpty()"
                rule-description: "Trade ID must be valid"
              - rule-name: "trade-amount-positive"
                rule-condition: "#trade.amount > 0"
                rule-description: "Trade amount must be positive"
          - step-name: "equity-specific-validation"
            step-description: "Equity-specific validation rules"
            validation-rules:
              - rule-name: "equity-symbol-valid"
                rule-condition: "#trade.symbol != null && #trade.symbol.matches('[A-Z]{1,5}')"
                rule-description: "Equity symbol must be valid"
              - rule-name: "market-hours-check"
                rule-condition: "T(java.time.LocalTime).now().isAfter(T(java.time.LocalTime).of(9, 30)) && T(java.time.LocalTime).now().isBefore(T(java.time.LocalTime).of(16, 0))"
                rule-description: "Trade must be within market hours"
          - step-name: "compliance-validation"
            step-description: "Regulatory compliance validation"
            validation-rules:
              - rule-name: "position-limit-check"
                rule-condition: "#trade.quantity <= 10000"
                rule-description: "Position must not exceed limits"
              - rule-name: "insider-trading-check"
                rule-condition: "true"
                rule-description: "No insider trading violations"
        workflow-outcomes:
          success-outcome: "EQUITY_VALIDATION_PASSED"
          failure-outcome: "EQUITY_VALIDATION_FAILED"
        audit-requirements:
          - "Log equity trade validation steps"
          - "Track compliance check results"
          
      fixed-income-trade-validation-workflow:
        workflow-id: "FIXED_INCOME_TRADE_VALIDATION_WORKFLOW"
        workflow-name: "Fixed Income Trade Validation Workflow"
        workflow-description: "Comprehensive validation workflow for fixed income trades"
        trade-type: "FixedIncome"
        validation-steps:
          - step-name: "basic-trade-validation"
            step-description: "Basic trade data validation"
            validation-rules:
              - rule-name: "trade-not-null"
                rule-condition: "#trade != null"
                rule-description: "Trade object must not be null"
              - rule-name: "trade-id-valid"
                rule-condition: "#trade.id != null && !#trade.id.isEmpty()"
                rule-description: "Trade ID must be valid"
              - rule-name: "trade-amount-positive"
                rule-condition: "#trade.amount > 0"
                rule-description: "Trade amount must be positive"
          - step-name: "fixed-income-specific-validation"
            step-description: "Fixed income-specific validation rules"
            validation-rules:
              - rule-name: "bond-cusip-valid"
                rule-condition: "#trade.cusip != null && #trade.cusip.matches('[0-9A-Z]{9}')"
                rule-description: "Bond CUSIP must be valid"
              - rule-name: "maturity-date-valid"
                rule-condition: "#trade.maturityDate != null && #trade.maturityDate.isAfter(T(java.time.LocalDate).now())"
                rule-description: "Maturity date must be in the future"
          - step-name: "credit-risk-validation"
            step-description: "Credit risk assessment validation"
            validation-rules:
              - rule-name: "credit-rating-check"
                rule-condition: "#trade.creditRating != null && (#trade.creditRating == 'AAA' || #trade.creditRating == 'AA' || #trade.creditRating == 'A')"
                rule-description: "Credit rating must be investment grade"
              - rule-name: "issuer-limit-check"
                rule-condition: "#trade.amount <= 5000000"
                rule-description: "Issuer exposure must not exceed limits"
        workflow-outcomes:
          success-outcome: "FIXED_INCOME_VALIDATION_PASSED"
          failure-outcome: "FIXED_INCOME_VALIDATION_FAILED"
        audit-requirements:
          - "Log fixed income trade validation steps"
          - "Track credit risk assessment results"
          
      derivative-trade-validation-workflow:
        workflow-id: "DERIVATIVE_TRADE_VALIDATION_WORKFLOW"
        workflow-name: "Derivative Trade Validation Workflow"
        workflow-description: "Comprehensive validation workflow for derivative trades"
        trade-type: "Derivative"
        validation-steps:
          - step-name: "basic-trade-validation"
            step-description: "Basic trade data validation"
            validation-rules:
              - rule-name: "trade-not-null"
                rule-condition: "#trade != null"
                rule-description: "Trade object must not be null"
              - rule-name: "trade-id-valid"
                rule-condition: "#trade.id != null && !#trade.id.isEmpty()"
                rule-description: "Trade ID must be valid"
              - rule-name: "notional-amount-positive"
                rule-condition: "#trade.notionalAmount > 0"
                rule-description: "Notional amount must be positive"
          - step-name: "derivative-specific-validation"
            step-description: "Derivative-specific validation rules"
            validation-rules:
              - rule-name: "underlying-asset-valid"
                rule-condition: "#trade.underlyingAsset != null && !#trade.underlyingAsset.isEmpty()"
                rule-description: "Underlying asset must be specified"
              - rule-name: "expiration-date-valid"
                rule-condition: "#trade.expirationDate != null && #trade.expirationDate.isAfter(T(java.time.LocalDate).now())"
                rule-description: "Expiration date must be in the future"
          - step-name: "margin-requirement-validation"
            step-description: "Margin requirement validation"
            validation-rules:
              - rule-name: "initial-margin-sufficient"
                rule-condition: "#trade.initialMargin >= (#trade.notionalAmount * 0.05)"
                rule-description: "Initial margin must be at least 5% of notional"
              - rule-name: "variation-margin-available"
                rule-condition: "#trade.availableMargin >= 0"
                rule-description: "Variation margin must be available"
        workflow-outcomes:
          success-outcome: "DERIVATIVE_VALIDATION_PASSED"
          failure-outcome: "DERIVATIVE_VALIDATION_FAILED"
        audit-requirements:
          - "Log derivative trade validation steps"
          - "Track margin requirement results"
    workflow-settings:
      execution-timeout: 10000
      parallel-execution: false
      validation-optimization: true
    
  trade-matching-workflows:
    workflow-type: "trade-matching-workflows"
    workflow-name: "Trade Matching Workflows"
    description: "Workflows for trade matching with counterparties"
    workflow-characteristics:
      workflow-category: "MATCHING"
      execution-model: "PARALLEL"
      error-handling: "CONTINUE_ON_ERROR"
    processing-workflows:
      counterparty-matching-workflow:
        workflow-id: "COUNTERPARTY_MATCHING_WORKFLOW"
        workflow-name: "Counterparty Matching Workflow"
        workflow-description: "Workflow for matching trades with counterparties"
        matching-steps:
          - step-name: "counterparty-identification"
            step-description: "Identify potential counterparties"
            matching-rules:
              - rule-name: "counterparty-exists"
                rule-condition: "#trade.counterpartyId != null && !#trade.counterpartyId.isEmpty()"
                rule-description: "Counterparty must be identified"
              - rule-name: "counterparty-active"
                rule-condition: "#trade.counterpartyStatus == 'ACTIVE'"
                rule-description: "Counterparty must be active"
          - step-name: "trade-details-matching"
            step-description: "Match trade details with counterparty"
            matching-rules:
              - rule-name: "trade-amount-matches"
                rule-condition: "#trade.amount == #counterpartyTrade.amount"
                rule-description: "Trade amounts must match"
              - rule-name: "settlement-date-matches"
                rule-condition: "#trade.settlementDate.equals(#counterpartyTrade.settlementDate)"
                rule-description: "Settlement dates must match"
          - step-name: "risk-assessment-matching"
            step-description: "Assess counterparty risk compatibility"
            matching-rules:
              - rule-name: "credit-limit-sufficient"
                rule-condition: "#counterparty.availableCredit >= #trade.amount"
                rule-description: "Counterparty credit limit must be sufficient"
              - rule-name: "risk-tolerance-compatible"
                rule-condition: "#counterparty.riskTolerance >= #trade.riskLevel"
                rule-description: "Risk tolerance must be compatible"
        workflow-outcomes:
          success-outcome: "COUNTERPARTY_MATCHED"
          failure-outcome: "COUNTERPARTY_MATCHING_FAILED"
        audit-requirements:
          - "Log counterparty matching steps"
          - "Track risk assessment results"
          
      trade-confirmation-matching-workflow:
        workflow-id: "TRADE_CONFIRMATION_MATCHING_WORKFLOW"
        workflow-name: "Trade Confirmation Matching Workflow"
        workflow-description: "Workflow for confirming matched trades"
        confirmation-steps:
          - step-name: "trade-details-confirmation"
            step-description: "Confirm all trade details"
            confirmation-rules:
              - rule-name: "all-details-confirmed"
                rule-condition: "#trade.confirmed == true && #counterpartyTrade.confirmed == true"
                rule-description: "Both sides must confirm trade details"
              - rule-name: "no-discrepancies"
                rule-condition: "#trade.discrepancies == null || #trade.discrepancies.isEmpty()"
                rule-description: "No unresolved discrepancies"
          - step-name: "regulatory-confirmation"
            step-description: "Confirm regulatory compliance"
            confirmation-rules:
              - rule-name: "regulatory-approval"
                rule-condition: "#trade.regulatoryStatus == 'APPROVED'"
                rule-description: "Regulatory approval must be obtained"
              - rule-name: "compliance-verified"
                rule-condition: "#trade.complianceVerified == true"
                rule-description: "Compliance must be verified"
        workflow-outcomes:
          success-outcome: "TRADE_CONFIRMATION_COMPLETED"
          failure-outcome: "TRADE_CONFIRMATION_FAILED"
        audit-requirements:
          - "Log trade confirmation steps"
          - "Track regulatory approval status"
    workflow-settings:
      execution-timeout: 8000
      parallel-execution: true
      matching-optimization: true
    
  trade-affirmation-workflows:
    workflow-type: "trade-affirmation-workflows"
    workflow-name: "Trade Affirmation Workflows"
    description: "Workflows for trade affirmation and agreement"
    workflow-characteristics:
      workflow-category: "AFFIRMATION"
      execution-model: "SEQUENTIAL"
      error-handling: "RETRY_ON_ERROR"
    processing-workflows:
      trade-affirmation-workflow:
        workflow-id: "TRADE_AFFIRMATION_WORKFLOW"
        workflow-name: "Trade Affirmation Workflow"
        workflow-description: "Workflow for affirming trades with all parties"
        affirmation-steps:
          - step-name: "party-affirmation"
            step-description: "Obtain affirmation from all parties"
            affirmation-rules:
              - rule-name: "buyer-affirmation"
                rule-condition: "#trade.buyerAffirmed == true"
                rule-description: "Buyer must affirm the trade"
              - rule-name: "seller-affirmation"
                rule-condition: "#trade.sellerAffirmed == true"
                rule-description: "Seller must affirm the trade"
              - rule-name: "custodian-affirmation"
                rule-condition: "#trade.custodianAffirmed == true"
                rule-description: "Custodian must affirm the trade"
          - step-name: "documentation-affirmation"
            step-description: "Affirm all required documentation"
            affirmation-rules:
              - rule-name: "trade-documentation-complete"
                rule-condition: "#trade.documentationComplete == true"
                rule-description: "All trade documentation must be complete"
              - rule-name: "legal-documentation-valid"
                rule-condition: "#trade.legalDocumentationValid == true"
                rule-description: "Legal documentation must be valid"
          - step-name: "settlement-instruction-affirmation"
            step-description: "Affirm settlement instructions"
            affirmation-rules:
              - rule-name: "settlement-instructions-complete"
                rule-condition: "#trade.settlementInstructionsComplete == true"
                rule-description: "Settlement instructions must be complete"
              - rule-name: "settlement-accounts-verified"
                rule-condition: "#trade.settlementAccountsVerified == true"
                rule-description: "Settlement accounts must be verified"
        workflow-outcomes:
          success-outcome: "TRADE_AFFIRMATION_COMPLETED"
          failure-outcome: "TRADE_AFFIRMATION_FAILED"
        audit-requirements:
          - "Log trade affirmation steps"
          - "Track party affirmation status"
    workflow-settings:
      execution-timeout: 12000
      parallel-execution: false
      affirmation-optimization: true
    
  trade-settlement-workflows:
    workflow-type: "trade-settlement-workflows"
    workflow-name: "Trade Settlement Workflows"
    description: "Workflows for trade settlement and completion"
    workflow-characteristics:
      workflow-category: "SETTLEMENT"
      execution-model: "SEQUENTIAL"
      error-handling: "COMPENSATE_ON_ERROR"
    processing-workflows:
      trade-settlement-workflow:
        workflow-id: "TRADE_SETTLEMENT_WORKFLOW"
        workflow-name: "Trade Settlement Workflow"
        workflow-description: "Workflow for settling trades and completing transactions"
        settlement-steps:
          - step-name: "pre-settlement-validation"
            step-description: "Validate all pre-settlement requirements"
            settlement-rules:
              - rule-name: "funds-available"
                rule-condition: "#trade.buyerFundsAvailable >= #trade.amount"
                rule-description: "Buyer funds must be available"
              - rule-name: "securities-available"
                rule-condition: "#trade.sellerSecuritiesAvailable >= #trade.quantity"
                rule-description: "Seller securities must be available"
          - step-name: "settlement-execution"
            step-description: "Execute the settlement transaction"
            settlement-rules:
              - rule-name: "funds-transfer-successful"
                rule-condition: "#trade.fundsTransferStatus == 'COMPLETED'"
                rule-description: "Funds transfer must be successful"
              - rule-name: "securities-transfer-successful"
                rule-condition: "#trade.securitiesTransferStatus == 'COMPLETED'"
                rule-description: "Securities transfer must be successful"
          - step-name: "post-settlement-confirmation"
            step-description: "Confirm settlement completion"
            settlement-rules:
              - rule-name: "settlement-confirmed"
                rule-condition: "#trade.settlementConfirmed == true"
                rule-description: "Settlement must be confirmed"
              - rule-name: "all-parties-notified"
                rule-condition: "#trade.allPartiesNotified == true"
                rule-description: "All parties must be notified"
        workflow-outcomes:
          success-outcome: "TRADE_SETTLEMENT_COMPLETED"
          failure-outcome: "TRADE_SETTLEMENT_FAILED"
        audit-requirements:
          - "Log trade settlement steps"
          - "Track settlement completion status"
    workflow-settings:
      execution-timeout: 15000
      parallel-execution: false
      settlement-optimization: true
    
  default:
    workflow-type: "default"
    workflow-name: "Default Trade Processing Workflows"
    description: "Default trade processing workflow"
    processing-workflows:
      default-workflow:
        workflow-id: "DEFAULT_WORKFLOW"
        workflow-name: "Default Workflow"
        workflow-outcomes:
          success-outcome: "DEFAULT_SUCCESS"
    workflow-settings:
      execution-timeout: 5000

# Workflow execution patterns
execution-patterns:
  trade-type-pattern:
    pattern-name: "Trade Type Pattern"
    description: "Execute workflows based on trade types"
    trade-types: ["Equity", "FixedIncome", "Derivative", "Forex", "Commodity"]
    
  workflow-stage-pattern:
    pattern-name: "Workflow Stage Pattern"
    description: "Execute workflows based on processing stages"
    processing-stages: ["VALIDATION", "MATCHING", "AFFIRMATION", "SETTLEMENT"]
    
  execution-model-pattern:
    pattern-name: "Execution Model Pattern"
    description: "Execute workflows based on execution models"
    execution-models: ["SEQUENTIAL", "PARALLEL", "CONDITIONAL"]

# Quality assurance
quality-assurance:
  workflow-accuracy:
    - "Trade processing workflows must be accurate"
    - "Validation rules must be comprehensive"
    - "Matching logic must be precise"
    - "Settlement processes must be reliable"
    
  workflow-reliability:
    - "Workflows must be repeatable"
    - "Error handling must be robust"
    - "Performance must be consistent"
    - "Audit trails must be complete"
    
  business-alignment:
    - "Workflows must reflect business processes"
    - "Validation rules must meet regulatory requirements"
    - "Settlement processes must be compliant"
    - "Risk management must be integrated"
