# YAML Configuration Demo Configuration
# Real APEX YAML configuration for YamlConfigurationDemo.java
# NO HARDCODED SIMULATION - Uses authentic APEX services

metadata:
  name: "YAML Configuration Demo Configuration"
  version: "2.0"
  description: "Real APEX YAML configuration demonstration with external configuration, business user-editable rules, and dynamic configuration loading"
  author: "APEX Demo Team"
  created: "2025-01-29"

# External YAML Configuration Enrichments
enrichments:
  - name: "external-yaml-configuration-processing"
    type: "yaml-config-enrichment"
    description: "External YAML configuration processing using real APEX services"
    conditions:
      - condition: "#data.configType == 'EXTERNAL_YAML'"
        actions:
          - type: "yaml-configuration-processing"
            configuration-rules:
              - rule: "trade-validation"
                condition: "#data.tradeId != null && #data.tradeId.length() > 0"
                action:
                  type: "set-field"
                  field: "tradeValidation"
                  value: "VALID"
                message: "Trade ID must be present and non-empty"
              - rule: "notional-validation"
                condition: "#data.notionalAmount != null && #data.notionalAmount > 0"
                action:
                  type: "set-field"
                  field: "notionalValidation"
                  value: "VALID"
                message: "Notional amount must be positive"
              - rule: "currency-validation"
                condition: "#data.notionalCurrency != null && (#data.notionalCurrency == 'USD' || #data.notionalCurrency == 'EUR' || #data.notionalCurrency == 'GBP')"
                action:
                  type: "set-field"
                  field: "currencyValidation"
                  value: "VALID"
                message: "Currency must be supported (USD, EUR, GBP)"
              - rule: "commodity-classification"
                condition: "#data.commodityType == 'CRUDE_OIL'"
                action:
                  type: "set-field"
                  field: "commodityClassification"
                  value: "ENERGY_COMMODITY"
                message: "Classify commodity type for processing"
            processing-metadata:
              config-type: "EXTERNAL_YAML"
              editable-by: "TECHNICAL_USERS"
              reload-required: false

  - name: "business-user-editable-rules"
    type: "business-rule-enrichment"
    description: "Business user-editable rules without code changes"
    conditions:
      - condition: "#data.configType == 'BUSINESS_EDITABLE'"
        actions:
          - type: "business-editable-processing"
            business-rules:
              - rule: "client-approval"
                condition: "#data.clientId != null && #data.clientAccountId != null"
                action:
                  type: "set-field"
                  field: "clientApproval"
                  value: "APPROVED"
                message: "Client and account must be specified"
                editable-by: "BUSINESS_USERS"
              - rule: "counterparty-risk-assessment"
                condition: "#data.counterpartyRating == 'A+' || #data.counterpartyRating == 'A' || #data.counterpartyRating == 'A-'"
                action:
                  type: "set-field"
                  field: "counterpartyRisk"
                  value: "LOW_RISK"
                message: "High-rated counterparties are low risk"
                editable-by: "BUSINESS_USERS"
              - rule: "risk-level-processing"
                condition: "#data.riskLevel == 'LOW'"
                action:
                  type: "set-field"
                  field: "processingPath"
                  value: "AUTOMATED"
                message: "Low risk transactions can be processed automatically"
                editable-by: "BUSINESS_USERS"
              - rule: "approval-workflow"
                condition: "#data.businessApproval == 'PENDING'"
                action:
                  type: "set-field"
                  field: "approvalRequired"
                  value: true
                message: "Pending approvals require manual review"
                editable-by: "BUSINESS_USERS"
            processing-metadata:
              config-type: "BUSINESS_EDITABLE"
              editable-by: "BUSINESS_USERS"
              hot-reload: true

  - name: "dynamic-configuration-loading"
    type: "dynamic-config-enrichment"
    description: "Dynamic configuration loading and hot-reloading"
    conditions:
      - condition: "#data.configType == 'DYNAMIC_LOADING'"
        actions:
          - type: "dynamic-configuration-processing"
            dynamic-rules:
              - rule: "version-check"
                condition: "#data.configVersion == '2.0'"
                action:
                  type: "set-field"
                  field: "versionCompatible"
                  value: true
                message: "Configuration version is compatible"
              - rule: "environment-specific-config"
                condition: "#data.environment == 'PRODUCTION'"
                action:
                  type: "set-field"
                  field: "productionConfig"
                  value: "ENABLED"
                message: "Production-specific configuration applied"
              - rule: "hot-reload-capability"
                condition: "#data.hotReload == true"
                action:
                  type: "set-field"
                  field: "hotReloadEnabled"
                  value: true
                message: "Hot reload capability is enabled"
              - rule: "configuration-reload"
                condition: "#data.reloadRequired == true"
                action:
                  type: "set-field"
                  field: "configurationReloaded"
                  value: true
                message: "Configuration has been reloaded"
            processing-metadata:
              config-type: "DYNAMIC_LOADING"
              supports-hot-reload: true
              environment-aware: true

# Configuration Management Settings
configuration-management:
  external-yaml:
    description: "External YAML configuration management"
    features:
      - "file-based-configuration"
      - "version-control-integration"
      - "configuration-validation"
      - "schema-enforcement"
    reload-strategy: "MANUAL"
    
  business-editable:
    description: "Business user-editable rules management"
    features:
      - "web-based-editor"
      - "rule-validation"
      - "approval-workflow"
      - "audit-trail"
    reload-strategy: "HOT_RELOAD"
    
  dynamic-loading:
    description: "Dynamic configuration loading management"
    features:
      - "runtime-configuration-changes"
      - "environment-specific-configs"
      - "configuration-versioning"
      - "rollback-capability"
    reload-strategy: "AUTOMATIC"

# Rule Categories for Business Users
business-rule-categories:
  - category: "CLIENT_RULES"
    description: "Rules related to client validation and approval"
    editable-by: "CLIENT_MANAGERS"
    approval-required: false
    
  - category: "RISK_RULES"
    description: "Rules related to risk assessment and management"
    editable-by: "RISK_MANAGERS"
    approval-required: true
    
  - category: "COMPLIANCE_RULES"
    description: "Rules related to regulatory compliance"
    editable-by: "COMPLIANCE_OFFICERS"
    approval-required: true
    
  - category: "OPERATIONAL_RULES"
    description: "Rules related to operational processing"
    editable-by: "OPERATIONS_MANAGERS"
    approval-required: false

# Environment-Specific Configurations
environment-configurations:
  development:
    validation-level: "BASIC"
    logging-level: "DEBUG"
    performance-monitoring: false
    
  testing:
    validation-level: "COMPREHENSIVE"
    logging-level: "INFO"
    performance-monitoring: true
    
  production:
    validation-level: "STRICT"
    logging-level: "WARN"
    performance-monitoring: true
    audit-trail: true

# Configuration Validation Rules
validation-rules:
  yaml-syntax:
    - rule: "valid-yaml-structure"
      description: "YAML must have valid syntax and structure"
    - rule: "required-metadata"
      description: "Configuration must include required metadata"
    - rule: "version-compatibility"
      description: "Configuration version must be compatible"
      
  business-rules:
    - rule: "expression-syntax"
      description: "Business rule expressions must be valid SpEL"
    - rule: "field-references"
      description: "Field references must exist in data model"
    - rule: "circular-dependencies"
      description: "Rules must not have circular dependencies"
      
  security-rules:
    - rule: "authorized-editors"
      description: "Only authorized users can edit rules"
    - rule: "approval-workflow"
      description: "Critical rules require approval before activation"
    - rule: "audit-logging"
      description: "All rule changes must be logged for audit"

# Hot Reload Configuration
hot-reload:
  enabled: true
  watch-directories:
    - "config/rules"
    - "config/enrichments"
    - "config/business-rules"
  reload-interval: 30
  validation-on-reload: true
  rollback-on-error: true

# Processing Configuration
processing:
  fail-fast: false
  enable-logging: true
  max-processing-time: 30000
  yaml-configuration-processing: true
  business-rule-processing: true
  dynamic-configuration-processing: true
  
# Output Configuration
output:
  format: "json"
  include-metadata: true
  include-processing-time: true
  include-configuration-info: true
  include-rule-execution-details: true
  include-validation-results: true

# Error Handling Configuration
error-handling:
  yaml-configuration-errors: "collect-and-continue"
  business-rule-errors: "collect-and-continue"
  dynamic-configuration-errors: "fail-fast"
  validation-errors: "collect"
  reload-errors: "rollback"
