# APEX Rules Engine Demo Configuration
# Real APEX YAML configuration for ApexRulesEngineDemo.java
# NO HARDCODED SIMULATION - Uses authentic APEX services

metadata:
  id: "apex-rules-engine-demo-configuration"
  name: "APEX Rules Engine Demo Configuration"
  version: "2.0.0"
  description: "Real APEX rules engine demonstration with investment validation, risk assessment, and compliance checking"
  type: "rule-config"
  author: "apex.demo.team@company.com"
  created-date: "2024-12-24"
  tags: ["apex-demo", "evaluation", "rules-engine"]

# Investment Validation Enrichments
enrichments:
  - id: "apex-rules-engine-demo-configuration"
    name: "investment-validation"
    type: "field-enrichment"
    description: "Validates investment scenarios using real APEX processing"
    condition: "#investmentAmount != null"
    field-mappings:
      - source-field: "investmentAmount"
        target-field: "validationStatus"
        expression: "#investmentAmount > 100000 ? 'HIGH_VALUE' : 'STANDARD'"
      - source-field: "investmentAmount"
        target-field: "requiresApproval"
        expression: "#investmentAmount > 100000 ? 'true' : 'false'"
      - source-field: "customerRiskProfile"
        target-field: "processingPath"
        expression: "#customerRiskProfile == 'CONSERVATIVE' ? 'LOW_RISK' : (#customerRiskProfile == 'MODERATE' ? 'MEDIUM_RISK' : 'HIGH_RISK')"

  - id: "apex-rules-engine-demo-configuration"
    name: "risk-assessment"
    type: "field-enrichment"
    description: "Processes risk assessment using real APEX services"
    condition: "#customerAge != null && #investmentExperience != null"
    field-mappings:
      - source-field: "customerAge"
        target-field: "riskScore"
        expression: "#customerAge < 30 ? 85 : (#customerAge < 50 ? 70 : 55)"
      - source-field: "investmentExperience"
        target-field: "experienceMultiplier"
        expression: "#investmentExperience == 'EXPERIENCED' ? 1.2 : (#investmentExperience == 'INTERMEDIATE' ? 1.0 : 0.8)"
      - source-field: "riskTolerance"
        target-field: "finalRiskRating"
        expression: "#riskTolerance == 'AGGRESSIVE' ? 'HIGH' : (#riskTolerance == 'MODERATE' ? 'MEDIUM' : 'LOW')"
      - source-field: "portfolioValue"
        target-field: "portfolioRecommendation"
        expression: "#portfolioValue > 1000000 ? 'PREMIUM_PORTFOLIO' : 'STANDARD_PORTFOLIO'"

  - id: "apex-rules-engine-demo-configuration"
    name: "compliance-checking"
    type: "field-enrichment"
    description: "Performs compliance checking using real APEX services"
    condition: "#transactionAmount != null && #customerCountry != null"
    field-mappings:
      - source-field: "transactionAmount"
        target-field: "complianceLevel"
        expression: "#transactionAmount > 50000 ? 'ENHANCED' : 'STANDARD'"
      - source-field: "sanctionsCheck"
        target-field: "sanctionsStatus"
        expression: "#sanctionsCheck == 'CLEAR' ? 'APPROVED' : 'REQUIRES_REVIEW'"
      - source-field: "kycStatus"
        target-field: "kycCompliance"
        expression: "#kycStatus == 'VERIFIED' ? 'COMPLIANT' : 'NON_COMPLIANT'"
      - source-field: "customerCountry"
        target-field: "regionalCompliance"
        expression: "#customerCountry == 'US' ? 'US_REGULATIONS' : (#customerCountry == 'EU' ? 'EU_REGULATIONS' : 'INTERNATIONAL_REGULATIONS')"

# Rule Groups for Sequential Processing
rule-groups:
  - id: "apex-rules-engine-demo-configuration"
    name: "investment-processing-workflow"
    description: "Sequential investment processing workflow"
    rules:
      - name: "investment-validation"
        priority: 1
      - name: "risk-assessment"
        priority: 2
      - name: "compliance-checking"
        priority: 3

# Data Sources Configuration
data-sources:
  - name: "demo-data-source"
    type: "memory"
    description: "In-memory data source for demo scenarios"
    
# Lookup Services Configuration
lookup-services:
  - name: "investment-lookup"
    type: "memory-lookup"
    description: "Investment validation lookup service"
    
  - name: "risk-lookup"
    type: "memory-lookup"
    description: "Risk assessment lookup service"
    
  - name: "compliance-lookup"
    type: "memory-lookup"
    description: "Compliance checking lookup service"

# Processing Configuration
processing:
  fail-fast: true
  enable-logging: true
  max-processing-time: 30000
  
# Output Configuration
output:
  format: "json"
  include-metadata: true
  include-processing-time: true

