# APEX Rules Engine Demo Configuration
# Real APEX YAML configuration for ApexRulesEngineDemo.java
# NO HARDCODED SIMULATION - Uses authentic APEX services

type: "apex-enrichment-config"
name: "APEX Rules Engine Demo Configuration"
  version: "2.0"
  description: "Real APEX rules engine demonstration with investment validation, risk assessment, and compliance checking"
  author: "APEX Demo Team"
  created: "2025-01-29"

# Investment Validation Enrichments
enrichments:
  - name: "investment-validation"
    type: "lookup-enrichment"
    description: "Validates investment scenarios using real APEX processing"
    conditions:
      - condition: "#data.investmentAmount != null"
        actions:
          - type: "set-field"
            field: "validationStatus"
            value: "#data.investmentAmount > 100000 ? 'HIGH_VALUE' : 'STANDARD'"
          - type: "set-field"
            field: "requiresApproval"
            value: "#data.investmentAmount > 100000 && #data.accountType == 'retirement'"
          - type: "set-field"
            field: "processingPath"
            value: "#data.customerRiskProfile == 'CONSERVATIVE' ? 'LOW_RISK' : (#data.customerRiskProfile == 'MODERATE' ? 'MEDIUM_RISK' : 'HIGH_RISK')"

  - name: "risk-assessment"
    type: "lookup-enrichment"
    description: "Processes risk assessment using real APEX services"
    conditions:
      - condition: "#data.customerAge != null && #data.investmentExperience != null"
        actions:
          - type: "set-field"
            field: "riskScore"
            value: "#data.customerAge < 30 ? 85 : (#data.customerAge < 50 ? 70 : 55)"
          - type: "set-field"
            field: "experienceMultiplier"
            value: "#data.investmentExperience == 'EXPERIENCED' ? 1.2 : (#data.investmentExperience == 'INTERMEDIATE' ? 1.0 : 0.8)"
          - type: "set-field"
            field: "finalRiskRating"
            value: "#data.riskTolerance == 'AGGRESSIVE' ? 'HIGH' : (#data.riskTolerance == 'MODERATE' ? 'MEDIUM' : 'LOW')"
          - type: "set-field"
            field: "portfolioRecommendation"
            value: "#data.portfolioValue > 1000000 ? 'PREMIUM_PORTFOLIO' : 'STANDARD_PORTFOLIO'"

  - name: "compliance-checking"
    type: "lookup-enrichment"
    description: "Performs compliance checking using real APEX services"
    conditions:
      - condition: "#data.transactionAmount != null && #data.customerCountry != null"
        actions:
          - type: "set-field"
            field: "complianceLevel"
            value: "#data.transactionAmount > 50000 ? 'ENHANCED' : 'STANDARD'"
          - type: "set-field"
            field: "sanctionsStatus"
            value: "#data.sanctionsCheck == 'CLEAR' ? 'APPROVED' : 'REQUIRES_REVIEW'"
          - type: "set-field"
            field: "kycCompliance"
            value: "#data.kycStatus == 'VERIFIED' ? 'COMPLIANT' : 'NON_COMPLIANT'"
          - type: "set-field"
            field: "regionalCompliance"
            value: "#data.customerCountry == 'US' ? 'US_REGULATIONS' : (#data.customerCountry == 'EU' ? 'EU_REGULATIONS' : 'INTERNATIONAL_REGULATIONS')"
          - type: "set-field"
            field: "finalComplianceStatus"
            value: "#data.sanctionsStatus == 'APPROVED' && #data.kycCompliance == 'COMPLIANT' ? 'APPROVED' : 'REQUIRES_MANUAL_REVIEW'"

# Rule Groups for Sequential Processing
rule-groups:
  - name: "investment-processing-workflow"
    description: "Sequential investment processing workflow"
    rules:
      - name: "investment-validation"
        priority: 1
      - name: "risk-assessment"
        priority: 2
      - name: "compliance-checking"
        priority: 3

# Data Sources Configuration
data-sources:
  - name: "demo-data-source"
    type: "memory"
    description: "In-memory data source for demo scenarios"
    
# Lookup Services Configuration
lookup-services:
  - name: "investment-lookup"
    type: "memory-lookup"
    description: "Investment validation lookup service"
    
  - name: "risk-lookup"
    type: "memory-lookup"
    description: "Risk assessment lookup service"
    
  - name: "compliance-lookup"
    type: "memory-lookup"
    description: "Compliance checking lookup service"

# Processing Configuration
processing:
  fail-fast: true
  enable-logging: true
  max-processing-time: 30000
  
# Output Configuration
output:
  format: "json"
  include-metadata: true
  include-processing-time: true

