# Layered API Demo Configuration
# Real APEX YAML configuration for LayeredAPIDemo.java
# NO HARDCODED SIMULATION - Uses authentic APEX services

metadata:
  id: "Layered API Demo Configuration"
  name: "Layered API Demo Configuration"
  version: "2.0.0"
  description: "Real APEX layered API demonstration with Layer 1 simple validation, Layer 2 business rule management, and Layer 3 advanced features"
  type: "rule-config"
  author: "apex.demo.team@company.com"
  created-date: "2024-12-24"
  tags: ["apex-demo", "evaluation", "layered-api"]

# Layer 1: Simple Validation Enrichments
enrichments:
  - id: "layer1-simple-validation"
    name: "layer1-simple-validation"
    type: "validation-enrichment"
    description: "Layer 1 simple validation using real APEX processing"
    conditions:
      - condition: "#data.layerType == 'LAYER_1'"
        actions:
          - type: "simple-validation"
            validations:
              - field: "name"
                rules:
                  - condition: "#value != null && #value.length() > 0"
                    message: "Name must be present and non-empty"
                    severity: "ERROR"
                    result-field: "nameValid"
              - field: "age"
                rules:
                  - condition: "#value != null && #value >= 18"
                    message: "Customer must be 18 or older"
                    severity: "ERROR"
                    result-field: "ageValid"
              - field: "email"
                rules:
                  - condition: "#value != null && #value.contains('@')"
                    message: "Email address must be valid"
                    severity: "ERROR"
                    result-field: "emailValid"
            processing-metadata:
              layer: "LAYER_1"
              api-type: "SIMPLE_VALIDATION"
              performance-tier: "BASIC"

  - id: "layer2-business-rule-management"
    name: "layer2-business-rule-management"
    type: "business-rule-enrichment"
    description: "Layer 2 business rule management with real APEX services"
    conditions:
      - condition: "#data.layerType == 'LAYER_2'"
        actions:
          - type: "business-rule-processing"
            business-rules:
              - rule: "order-approval"
                condition: "#data.orderAmount <= #data.creditLimit && (#data.customerType == 'PREMIUM' || #data.orderAmount <= 10000)"
                action:
                  type: "set-field"
                  field: "orderApproved"
                  value: true
                message: "Order must be within credit limit and meet customer type requirements"
              - rule: "discount-eligibility"
                condition: "#data.customerType == 'PREMIUM' && #data.orderAmount > 10000"
                action:
                  type: "set-field"
                  field: "discountEligible"
                  value: true
                message: "Premium customers with orders over $10,000 qualify for discounts"
              - rule: "premium-customer-benefits"
                condition: "#data.customerType == 'PREMIUM'"
                action:
                  type: "set-field"
                  field: "premiumBenefits"
                  value: "ENHANCED_SUPPORT"
                message: "Premium customers receive enhanced support"
            processing-metadata:
              layer: "LAYER_2"
              api-type: "BUSINESS_RULE_MANAGEMENT"
              performance-tier: "INTERMEDIATE"

  - id: "layer3-advanced-features"
    name: "layer3-advanced-features"
    type: "advanced-enrichment"
    description: "Layer 3 advanced rule engine features with complex processing"
    conditions:
      - condition: "#data.layerType == 'LAYER_3'"
        actions:
          - type: "advanced-processing"
            complex-rules:
              - rule: "enterprise-transaction-approval"
                condition: "#data.transactionAmount > 50000 && #data.amlCheck == true && #data.sanctionsCheck == true && #data.customerRiskRating == 'LOW'"
                actions:
                  - type: "set-field"
                    field: "transactionApproved"
                    value: true
                  - type: "set-field"
                    field: "approvalLevel"
                    value: "AUTOMATED"
                  - type: "set-field"
                    field: "complianceStatus"
                    value: "COMPLIANT"
                message: "Complex transaction approval with multiple compliance checks"
              - rule: "high-risk-transaction-handling"
                condition: "#data.transactionAmount > 100000 || #data.customerRiskRating == 'HIGH'"
                actions:
                  - type: "set-field"
                    field: "requiresManualReview"
                    value: true
                  - type: "set-field"
                    field: "escalationLevel"
                    value: "SENIOR_COMPLIANCE"
                  - type: "set-field"
                    field: "additionalChecksRequired"
                    value: true
                message: "High-risk transactions require manual review"
              - rule: "cross-border-compliance"
                condition: "#data.country != 'US' && #data.transactionAmount > 25000"
                actions:
                  - type: "set-field"
                    field: "crossBorderReporting"
                    value: true
                  - type: "set-field"
                    field: "additionalDocumentation"
                    value: "REQUIRED"
                message: "Cross-border transactions require additional compliance"
            processing-metadata:
              layer: "LAYER_3"
              api-type: "ADVANCED_FEATURES"
              performance-tier: "ENTERPRISE"

# Performance Configuration by Layer
performance-configuration:
  layer1:
    cache-enabled: true
    cache-ttl: 300
    max-processing-time: 100
    concurrent-processing: false
    
  layer2:
    cache-enabled: true
    cache-ttl: 600
    max-processing-time: 500
    concurrent-processing: true
    rule-optimization: true
    
  layer3:
    cache-enabled: true
    cache-ttl: 900
    max-processing-time: 2000
    concurrent-processing: true
    rule-optimization: true
    advanced-analytics: true

# API Layer Definitions
api-layers:
  - layer: "LAYER_1"
    name: "Simple Validation Layer"
    description: "Basic field validation and simple rule testing"
    features:
      - "field-validation"
      - "simple-rule-testing"
      - "basic-error-handling"
    performance-characteristics:
      - "low-latency"
      - "high-throughput"
      - "minimal-memory-usage"
    
  - layer: "LAYER_2"
    name: "Business Rule Management Layer"
    description: "Complex business rule management with named rules and templates"
    features:
      - "named-rule-definitions"
      - "business-rule-templates"
      - "rule-composition"
      - "conditional-execution"
    performance-characteristics:
      - "medium-latency"
      - "medium-throughput"
      - "moderate-memory-usage"
    
  - layer: "LAYER_3"
    name: "Advanced Features Layer"
    description: "Enterprise-grade features with complex processing and analytics"
    features:
      - "complex-rule-chains"
      - "advanced-analytics"
      - "performance-monitoring"
      - "enterprise-integration"
      - "audit-trails"
    performance-characteristics:
      - "higher-latency"
      - "lower-throughput"
      - "higher-memory-usage"
      - "advanced-caching"

# Rule Templates by Layer
rule-templates:
  layer1-templates:
    - name: "basic-field-validation"
      pattern: "#field != null && #field.length() > 0"
      description: "Basic non-null and non-empty validation"
    - name: "numeric-range-validation"
      pattern: "#field >= #min && #field <= #max"
      description: "Numeric range validation"
    - name: "email-format-validation"
      pattern: "#field != null && #field.contains('@')"
      description: "Basic email format validation"
      
  layer2-templates:
    - name: "business-approval-rule"
      pattern: "#amount <= #limit && (#type == 'PREMIUM' || #amount <= #threshold)"
      description: "Business approval rule template"
    - name: "customer-eligibility-rule"
      pattern: "#customerType == #requiredType && #amount > #minimumAmount"
      description: "Customer eligibility rule template"
    - name: "discount-qualification-rule"
      pattern: "#customerTier == 'PREMIUM' && #orderValue > #discountThreshold"
      description: "Discount qualification rule template"
      
  layer3-templates:
    - name: "enterprise-compliance-rule"
      pattern: "#amount > #threshold && #amlCheck == true && #sanctionsCheck == true && #riskRating == 'LOW'"
      description: "Enterprise compliance rule template"
    - name: "risk-assessment-rule"
      pattern: "#transactionAmount > #riskThreshold || #customerRisk == 'HIGH' || #countryRisk == 'HIGH'"
      description: "Risk assessment rule template"
    - name: "regulatory-reporting-rule"
      pattern: "#jurisdiction != 'DOMESTIC' && #amount > #reportingThreshold"
      description: "Regulatory reporting rule template"

# Processing Configuration
processing:
  fail-fast: false
  enable-logging: true
  max-processing-time: 30000
  layer-specific-processing: true
  performance-monitoring: true
  
# Output Configuration
output:
  format: "json"
  include-metadata: true
  include-processing-time: true
  include-layer-information: true
  include-performance-metrics: true
  include-rule-execution-details: true

# Error Handling Configuration
error-handling:
  layer1-errors: "fail-fast"
  layer2-errors: "collect-and-continue"
  layer3-errors: "collect-with-fallback"
  validation-errors: "collect"
  business-rule-errors: "collect-and-continue"
  advanced-feature-errors: "collect-with-fallback"

