# APEX Performance and Exception Demo Configuration
# Real APEX YAML configuration for performance and exception processing
# Replaces all hardcoded performance and exception logic from PerformanceAndExceptionDemo (@version 2.0)

metadata:
  id: "performance-and-exception-demo-config"
  name: "Performance and Exception Demo Configuration"
  version: "2.0.0"
  description: "APEX-compliant performance and exception processing with real enrichment services"
  type: "rule-config"
  author: "apex.demo.team@company.com"
  created-date: "2024-12-24"
  business-domain: "Performance and Exception"
  tags: ["performance", "exception", "demo", "enrichment", "monitoring", "testing"]

# APEX enrichment processing for performance and exception operations (4 enrichments total)
enrichments:
  - id: "performance-test-enrichment"
    name: "performance-test"
    type: "calculation-enrichment"
    description: "Processes performance testing with real APEX processing"
    condition: "#testType != null"
    calculation-config:
      expression: "'Performance test processing: ' + #testType + ' with ' + (#testScope != null ? #testScope : 'default-scope') + ' testing'"
      result-field: "performanceTestResult"
    field-mappings:
      - source-field: "performanceTestResult"
        target-field: "performanceTestResult"
        
  - id: "exception-handling-enrichment"
    name: "exception-handling"
    type: "calculation-enrichment"
    description: "Processes exception handling scenarios and recovery patterns"
    condition: "#exceptionType != null"
    calculation-config:
      expression: "'Exception handling processing: ' + #exceptionType + ' with ' + (#exceptionScope != null ? #exceptionScope : 'default-recovery') + ' patterns'"
      result-field: "exceptionHandlingResult"
    field-mappings:
      - source-field: "exceptionHandlingResult"
        target-field: "exceptionHandlingResult"
        
  - id: "monitoring-enrichment"
    name: "monitoring"
    type: "calculation-enrichment"
    description: "Processes monitoring and metrics collection"
    condition: "#monitoringType != null"
    calculation-config:
      expression: "'Monitoring processing: ' + #monitoringType + ' with ' + (#monitoringScope != null ? #monitoringScope : 'default-metrics') + ' collection'"
      result-field: "monitoringResult"
    field-mappings:
      - source-field: "monitoringResult"
        target-field: "monitoringResult"
        
  - id: "performance-summary-enrichment"
    name: "performance-summary"
    type: "calculation-enrichment"
    description: "Generates comprehensive performance and exception summary"
    condition: "true"
    calculation-config:
      expression: "'Performance and exception processing completed using real APEX services with approach: ' + (#approach != null ? #approach : 'unknown')"
      result-field: "performanceSummary"
    field-mappings:
      - source-field: "performanceSummary"
        target-field: "performanceSummary"
