# APEX Risk Management Service Configuration
# Real APEX YAML configuration for risk management service
# Replaces all hardcoded risk management service logic from RiskManagementService (@version 2.0)

metadata:
  id: "risk-management-service-config"
  name: "Risk Management Service Configuration"
  version: "2.0.0"
  description: "APEX-compliant risk management service with real enrichment services"
  type: "rule-config"
  author: "apex.demo.team@company.com"
  created-date: "2024-12-24"
  business-domain: "Risk Management"
  tags: ["risk", "management", "service", "enrichment", "assessment", "calculation", "monitoring"]

# APEX enrichment processing for risk management service operations (4 enrichments total)
enrichments:
  - id: "risk-assessment-enrichment"
    name: "risk-assessment"
    type: "calculation-enrichment"
    description: "Processes risk assessment models with real APEX processing"
    condition: "#assessmentType != null"
    calculation-config:
      expression: "'Risk assessment processing: ' + #assessmentType + ' with ' + (#assessmentScope != null ? #assessmentScope : 'default-scope') + ' analysis'"
      result-field: "riskAssessmentResult"
    field-mappings:
      - source-field: "riskAssessmentResult"
        target-field: "riskAssessmentResult"
        
  - id: "calculation-engines-enrichment"
    name: "calculation-engines"
    type: "calculation-enrichment"
    description: "Processes calculation engines for risk computations"
    condition: "#calculationType != null"
    calculation-config:
      expression: "'Calculation engines processing: ' + #calculationType + ' with ' + (#calculationScope != null ? #calculationScope : 'default-computations') + ' processing'"
      result-field: "calculationEnginesResult"
    field-mappings:
      - source-field: "calculationEnginesResult"
        target-field: "calculationEnginesResult"
        
  - id: "monitoring-frameworks-enrichment"
    name: "monitoring-frameworks"
    type: "calculation-enrichment"
    description: "Processes monitoring frameworks for risk tracking"
    condition: "#monitoringType != null"
    calculation-config:
      expression: "'Monitoring frameworks processing: ' + #monitoringType + ' with ' + (#monitoringScope != null ? #monitoringScope : 'default-tracking') + ' capabilities'"
      result-field: "monitoringFrameworksResult"
    field-mappings:
      - source-field: "monitoringFrameworksResult"
        target-field: "monitoringFrameworksResult"
        
  - id: "risk-management-summary-enrichment"
    name: "risk-management-summary"
    type: "calculation-enrichment"
    description: "Generates comprehensive risk management service summary"
    condition: "true"
    calculation-config:
      expression: "'Risk management service processing completed using real APEX services with approach: ' + (#approach != null ? #approach : 'unknown')"
      result-field: "riskManagementSummary"
    field-mappings:
      - source-field: "riskManagementSummary"
        target-field: "riskManagementSummary"
