# APEX Rule Configuration Demo Configuration
# Real APEX YAML configuration for rule configuration demo
# Replaces all hardcoded rule configuration demo logic from RuleConfigurationDemo (@version 2.0)

metadata:
  id: "rule-configuration-demo-config"
  name: "Rule Configuration Demo Configuration"
  version: "2.0.0"
  description: "APEX-compliant rule configuration demo with real enrichment services"
  type: "rule-config"
  author: "apex.demo.team@company.com"
  created-date: "2024-12-24"
  business-domain: "Rule Configuration Demo"
  tags: ["rule", "configuration", "demo", "enrichment", "creation", "management", "engine"]

# APEX enrichment processing for rule configuration demo operations (4 enrichments total)
enrichments:
  - id: "rule-creation-enrichment"
    name: "rule-creation"
    type: "calculation-enrichment"
    description: "Processes rule creation with real APEX processing"
    condition: "#creationType != null"
    calculation-config:
      expression: "'Rule creation processing: ' + #creationType + ' with ' + (#creationScope != null ? #creationScope : 'default-scope') + ' rules'"
      result-field: "ruleCreationResult"
    field-mappings:
      - source-field: "ruleCreationResult"
        target-field: "ruleCreationResult"
        
  - id: "configuration-management-enrichment"
    name: "configuration-management"
    type: "calculation-enrichment"
    description: "Processes configuration management and validation"
    condition: "#managementType != null"
    calculation-config:
      expression: "'Configuration management processing: ' + #managementType + ' with ' + (#managementScope != null ? #managementScope : 'default-validation') + ' processing'"
      result-field: "configurationManagementResult"
    field-mappings:
      - source-field: "configurationManagementResult"
        target-field: "configurationManagementResult"
        
  - id: "engine-setup-enrichment"
    name: "engine-setup"
    type: "calculation-enrichment"
    description: "Processes engine setup and integration"
    condition: "#engineType != null"
    calculation-config:
      expression: "'Engine setup processing: ' + #engineType + ' with ' + (#engineScope != null ? #engineScope : 'default-integration') + ' setup'"
      result-field: "engineSetupResult"
    field-mappings:
      - source-field: "engineSetupResult"
        target-field: "engineSetupResult"
        
  - id: "rule-configuration-demo-summary-enrichment"
    name: "rule-configuration-demo-summary"
    type: "calculation-enrichment"
    description: "Generates comprehensive rule configuration demo summary"
    condition: "true"
    calculation-config:
      expression: "'Rule configuration demo processing completed using real APEX services with approach: ' + (#approach != null ? #approach : 'unknown')"
      result-field: "ruleConfigurationDemoSummary"
    field-mappings:
      - source-field: "ruleConfigurationDemoSummary"
        target-field: "ruleConfigurationDemoSummary"
