# APEX Scenario-Based Processing Demo Configuration
# Real APEX YAML configuration for scenario-based processing demo
# Replaces all hardcoded scenario-based processing demo logic from ScenarioBasedProcessingDemo (@version 2.0)

metadata:
  id: "scenario-based-processing-demo-config"
  name: "Scenario-Based Processing Demo Configuration"
  version: "2.0.0"
  description: "APEX-compliant scenario-based processing demo with real enrichment services"
  type: "rule-config"
  author: "apex.demo.team@company.com"
  created-date: "2024-12-24"
  business-domain: "Scenario-Based Processing"
  tags: ["scenario", "processing", "demo", "enrichment", "generation", "routing", "execution"]

# APEX enrichment processing for scenario-based processing operations (4 enrichments total)
enrichments:
  - id: "sample-data-generation-enrichment"
    name: "sample-data-generation"
    type: "calculation-enrichment"
    description: "Processes sample data generation with real APEX processing"
    condition: "#generationType != null"
    calculation-config:
      expression: "'Sample data generation processing: ' + #generationType + ' with ' + (#generationScope != null ? #generationScope : 'default-scope') + ' samples'"
      result-field: "sampleDataGenerationResult"
    field-mappings:
      - source-field: "sampleDataGenerationResult"
        target-field: "sampleDataGenerationResult"
        
  - id: "scenario-routing-enrichment"
    name: "scenario-routing"
    type: "calculation-enrichment"
    description: "Processes scenario routing and data type handling"
    condition: "#routingType != null"
    calculation-config:
      expression: "'Scenario routing processing: ' + #routingType + ' with ' + (#routingScope != null ? #routingScope : 'default-handling') + ' routing'"
      result-field: "scenarioRoutingResult"
    field-mappings:
      - source-field: "scenarioRoutingResult"
        target-field: "scenarioRoutingResult"
        
  - id: "processing-execution-enrichment"
    name: "processing-execution"
    type: "calculation-enrichment"
    description: "Processes processing execution with scenario services"
    condition: "#executionType != null"
    calculation-config:
      expression: "'Processing execution processing: ' + #executionType + ' with ' + (#executionScope != null ? #executionScope : 'default-services') + ' execution'"
      result-field: "processingExecutionResult"
    field-mappings:
      - source-field: "processingExecutionResult"
        target-field: "processingExecutionResult"
        
  - id: "scenario-based-processing-summary-enrichment"
    name: "scenario-based-processing-summary"
    type: "calculation-enrichment"
    description: "Generates comprehensive scenario-based processing summary"
    condition: "true"
    calculation-config:
      expression: "'Scenario-based processing completed using real APEX services with approach: ' + (#approach != null ? #approach : 'unknown')"
      result-field: "scenarioBasedProcessingSummary"
    field-mappings:
      - source-field: "scenarioBasedProcessingSummary"
        target-field: "scenarioBasedProcessingSummary"
