# Simplified API Demo Configuration
# Real APEX YAML configuration for SimplifiedAPIDemo.java
# NO HARDCODED SIMULATION - Uses authentic APEX services

metadata:
  id: "Simplified API Demo Configuration"
  name: "Simplified API Demo Configuration"
  version: "2.0.0"
  description: "Real APEX simplified API demonstration with ultra-simple processing, one-liner rule evaluations, and template-based validation"
  type: "rule-config"
  author: "apex.demo.team@company.com"
  created-date: "2024-12-24"
  tags: ["apex-demo", "evaluation", "simplified-api"]

# Ultra-Simple API Enrichments
enrichments:
  - id: "ultra-simple-api-processing"
    name: "ultra-simple-api-processing"
    type: "field-enrichment"
    description: "Ultra-simple API for 90% of use cases using real APEX processing"
    condition: "#apiType == 'ULTRA_SIMPLE'"
    field-mappings:
      - source-field: "name"
        target-field: "nameValid"
        expression: "#name != null && #name.length() > 0 ? 'true' : 'false'"
      - source-field: "email"
        target-field: "emailValid"
        expression: "#email != null && #email.contains('@') ? 'true' : 'false'"
      - source-field: "age"
        target-field: "ageValid"
        expression: "#age != null && #age >= 18 ? 'true' : 'false'"

  - id: "one-liner-rule-evaluations"
    name: "one-liner-rule-evaluations"
    type: "field-enrichment"
    description: "One-liner rule evaluations with simplified syntax"
    condition: "#apiType == 'ONE_LINER'"
    field-mappings:
      - source-field: "orderAmount"
        target-field: "orderApproved"
        expression: "#orderAmount <= #creditLimit && (#customerType == 'PREMIUM' || #orderAmount <= 10000) ? 'true' : 'false'"
      - source-field: "customerType"
        target-field: "discountEligible"
        expression: "#customerType == 'PREMIUM' && #orderAmount > 10000 ? 'true' : 'false'"
      - source-field: "orderAmount"
        target-field: "amountValid"
        expression: "#orderAmount > 0 && #orderAmount <= 1000000 ? 'true' : 'false'"

  - id: "template-based-validation"
    name: "template-based-validation"
    type: "field-enrichment"
    description: "Template-based validation patterns for common scenarios"
    condition: "#apiType == 'TEMPLATE_BASED'"
    field-mappings:
      - source-field: "customerName"
        target-field: "customerNameValid"
        expression: "#customerName != null && #customerName.length() >= 2 ? 'true' : 'false'"
      - source-field: "customerEmail"
        target-field: "customerEmailValid"
        expression: "#customerEmail != null && #customerEmail.contains('@') ? 'true' : 'false'"
      - source-field: "transactionAmount"
        target-field: "transactionAmountValid"
        expression: "#transactionAmount != null && #transactionAmount > 0 ? 'true' : 'false'"

# Simplified API Configuration
simplified-api-config:
  ultra-simple:
    description: "Ultra-simple API for 90% of common use cases"
    features:
      - "one-line-validations"
      - "simple-field-checks"
      - "basic-business-rules"
    performance:
      target-latency: "< 5ms"
      throughput: "HIGH"
      memory-usage: "MINIMAL"
    
  one-liner:
    description: "One-liner rule evaluations with simplified syntax"
    features:
      - "single-expression-rules"
      - "inline-conditions"
      - "immediate-results"
    performance:
      target-latency: "< 10ms"
      throughput: "HIGH"
      memory-usage: "LOW"
    
  template-based:
    description: "Template-based validation patterns for reusability"
    features:
      - "reusable-templates"
      - "pattern-matching"
      - "complex-validations"
    performance:
      target-latency: "< 25ms"
      throughput: "MEDIUM"
      memory-usage: "MEDIUM"

# Rule Templates for Simplified API
rule-templates:
  validation-templates:
    - name: "required-field"
      pattern: "#field != null && #field.length() > 0"
      description: "Required field validation template"
    - name: "numeric-range"
      pattern: "#field >= #min && #field <= #max"
      description: "Numeric range validation template"
    - name: "email-format"
      pattern: "#field != null && #field.contains('@')"
      description: "Basic email format validation template"
    - name: "positive-amount"
      pattern: "#field > 0"
      description: "Positive amount validation template"
      
  business-rule-templates:
    - name: "approval-rule"
      pattern: "#amount <= #limit && (#type == 'PREMIUM' || #amount <= #threshold)"
      description: "Business approval rule template"
    - name: "eligibility-rule"
      pattern: "#customerType == #requiredType && #amount > #minimumAmount"
      description: "Customer eligibility rule template"
    - name: "risk-rule"
      pattern: "#riskRating == 'LOW' && #amount <= #riskThreshold"
      description: "Risk assessment rule template"
      
  performance-templates:
    - name: "fast-validation"
      pattern: "#field != null"
      description: "Ultra-fast null check template"
      performance: "< 1ms"
    - name: "medium-validation"
      pattern: "#field != null && #field.matches(#pattern)"
      description: "Medium complexity validation template"
      performance: "< 5ms"
    - name: "complex-validation"
      pattern: "#field != null && #customFunction(#field, #parameters)"
      description: "Complex validation template"
      performance: "< 15ms"

# API Simplification Levels
simplification-levels:
  - level: 1
    name: "Ultra-Simple"
    description: "Single method calls with minimal parameters"
    target-users: "Beginners, quick prototyping"
    complexity: "MINIMAL"
    
  - level: 2
    name: "One-Liner"
    description: "Single expression evaluations with context"
    target-users: "Intermediate developers, common use cases"
    complexity: "LOW"
    
  - level: 3
    name: "Template-Based"
    description: "Reusable templates with parameterization"
    target-users: "Advanced developers, enterprise applications"
    complexity: "MEDIUM"

# Performance Optimization
performance-optimization:
  caching:
    enabled: true
    cache-size: 1000
    ttl: 300
    
  expression-compilation:
    enabled: true
    compilation-cache-size: 500
    
  result-caching:
    enabled: true
    result-cache-size: 200
    result-ttl: 60

# Processing Configuration
processing:
  fail-fast: true
  enable-logging: true
  max-processing-time: 5000
  simplified-processing: true
  template-caching: true
  
# Output Configuration
output:
  format: "json"
  include-metadata: true
  include-processing-time: true
  include-api-type: true
  include-simplification-level: true
  include-performance-metrics: true

# Error Handling Configuration
error-handling:
  ultra-simple-errors: "user-friendly"
  one-liner-errors: "detailed"
  template-errors: "comprehensive"
  validation-errors: "collect"
  business-rule-errors: "fail-fast"

