# YAML Configuration Demo Data Configuration
# Test data scenarios for YamlConfigurationDemo.java
# NO HARDCODED SIMULATION - Real APEX data processing

metadata:
  name: "YAML Configuration Demo Data"
  version: "2.0.0"
  description: "Test data scenarios for real APEX YAML configuration demonstration"
  type: "dataset"
  author: "apex.demo.team@company.com"
  source: "APEX Demo Data Generator"
  created-date: "2024-12-24"
  tags: ["apex-demo", "evaluation", "yaml-configuration", "test-data"]

# External YAML Configuration Test Scenarios
external-yaml-scenarios:
  - scenario: "valid-commodity-trade"
    description: "Valid commodity trade for external YAML configuration processing"
    data:
      tradeId: "COM123456"
      externalTradeId: "EXT-COM-001"
      counterpartyId: "COUNTERPARTY001"
      notionalAmount: 50000000
      notionalCurrency: "USD"
      referenceIndex: "WTI"
      commodityType: "CRUDE_OIL"
      configType: "EXTERNAL_YAML"
    expected-results:
      tradeValidation: "VALID"
      notionalValidation: "VALID"
      currencyValidation: "VALID"
      commodityClassification: "ENERGY_COMMODITY"
      config-type: "EXTERNAL_YAML"
      editable-by: "TECHNICAL_USERS"

  - scenario: "invalid-commodity-trade"
    description: "Invalid commodity trade for external YAML configuration validation"
    data:
      tradeId: ""
      externalTradeId: "EXT-COM-002"
      counterpartyId: "COUNTERPARTY002"
      notionalAmount: -1000000
      notionalCurrency: "INVALID_CURRENCY"
      referenceIndex: "BRENT"
      commodityType: "NATURAL_GAS"
      configType: "EXTERNAL_YAML"
    expected-results:
      tradeValidation: "INVALID"
      notionalValidation: "INVALID"
      currencyValidation: "INVALID"
      commodityClassification: null
      config-type: "EXTERNAL_YAML"
      validation-errors: 3

  - scenario: "eur-commodity-trade"
    description: "EUR-denominated commodity trade for external YAML configuration"
    data:
      tradeId: "COM789012"
      externalTradeId: "EXT-COM-003"
      counterpartyId: "COUNTERPARTY003"
      notionalAmount: 25000000
      notionalCurrency: "EUR"
      referenceIndex: "BRENT"
      commodityType: "CRUDE_OIL"
      configType: "EXTERNAL_YAML"
    expected-results:
      tradeValidation: "VALID"
      notionalValidation: "VALID"
      currencyValidation: "VALID"
      commodityClassification: "ENERGY_COMMODITY"
      config-type: "EXTERNAL_YAML"

# Business User-Editable Rules Test Scenarios
business-editable-scenarios:
  - scenario: "approved-client-low-risk"
    description: "Approved client with low risk for business user-editable rules"
    data:
      clientId: "CLIENT001"
      clientAccountId: "ACC001"
      counterpartyRating: "A+"
      riskLevel: "LOW"
      businessApproval: "APPROVED"
      configType: "BUSINESS_EDITABLE"
    expected-results:
      clientApproval: "APPROVED"
      counterpartyRisk: "LOW_RISK"
      processingPath: "AUTOMATED"
      approvalRequired: false
      config-type: "BUSINESS_EDITABLE"
      editable-by: "BUSINESS_USERS"
      hot-reload: true

  - scenario: "pending-approval-medium-risk"
    description: "Pending approval with medium risk for business rules"
    data:
      clientId: "CLIENT002"
      clientAccountId: "ACC002"
      counterpartyRating: "BBB"
      riskLevel: "MEDIUM"
      businessApproval: "PENDING"
      configType: "BUSINESS_EDITABLE"
    expected-results:
      clientApproval: "APPROVED"
      counterpartyRisk: null
      processingPath: null
      approvalRequired: true
      config-type: "BUSINESS_EDITABLE"

  - scenario: "high-rated-counterparty"
    description: "High-rated counterparty for business rules processing"
    data:
      clientId: "CLIENT003"
      clientAccountId: "ACC003"
      counterpartyRating: "A"
      riskLevel: "HIGH"
      businessApproval: "APPROVED"
      configType: "BUSINESS_EDITABLE"
    expected-results:
      clientApproval: "APPROVED"
      counterpartyRisk: "LOW_RISK"
      processingPath: null
      approvalRequired: false
      config-type: "BUSINESS_EDITABLE"

# Dynamic Configuration Loading Test Scenarios
dynamic-loading-scenarios:
  - scenario: "production-config-v2"
    description: "Production configuration version 2.0 for dynamic loading"
    data:
      configVersion: "2.0"
      environment: "PRODUCTION"
      reloadRequired: true
      hotReload: true
      configType: "DYNAMIC_LOADING"
    expected-results:
      versionCompatible: true
      productionConfig: "ENABLED"
      hotReloadEnabled: true
      configurationReloaded: true
      config-type: "DYNAMIC_LOADING"
      supports-hot-reload: true
      environment-aware: true

  - scenario: "development-config-v1"
    description: "Development configuration version 1.0 for dynamic loading"
    data:
      configVersion: "1.0"
      environment: "DEVELOPMENT"
      reloadRequired: false
      hotReload: false
      configType: "DYNAMIC_LOADING"
    expected-results:
      versionCompatible: false
      productionConfig: null
      hotReloadEnabled: false
      configurationReloaded: false
      config-type: "DYNAMIC_LOADING"

  - scenario: "testing-config-hot-reload"
    description: "Testing configuration with hot reload for dynamic loading"
    data:
      configVersion: "2.0"
      environment: "TESTING"
      reloadRequired: true
      hotReload: true
      configType: "DYNAMIC_LOADING"
    expected-results:
      versionCompatible: true
      productionConfig: null
      hotReloadEnabled: true
      configurationReloaded: true
      config-type: "DYNAMIC_LOADING"

# Integrated Workflow Test Scenarios
integrated-scenarios:
  - scenario: "complete-yaml-configuration-workflow"
    description: "Complete workflow demonstrating all YAML configuration types"
    data:
      # External YAML data
      tradeId: "COM456789"
      notionalAmount: 75000000
      notionalCurrency: "USD"
      commodityType: "CRUDE_OIL"
      # Business editable data
      clientId: "CLIENT004"
      clientAccountId: "ACC004"
      counterpartyRating: "A+"
      riskLevel: "LOW"
      businessApproval: "APPROVED"
      # Dynamic loading data
      configVersion: "2.0"
      environment: "PRODUCTION"
      reloadRequired: true
      hotReload: true
      configType: "ALL_TYPES"
    expected-workflow:
      external-yaml-processing: "VALID"
      business-editable-processing: "APPROVED"
      dynamic-loading-processing: "ENABLED"
      final-status: "PROCESSED"

# Configuration Management Test Scenarios
configuration-management-scenarios:
  - scenario: "business-rule-editing"
    description: "Business rule editing by authorized users"
    data:
      ruleCategory: "CLIENT_RULES"
      editedBy: "CLIENT_MANAGERS"
      approvalRequired: false
      ruleExpression: "#data.clientId != null"
      configType: "BUSINESS_EDITABLE"
    expected-results:
      editingAllowed: true
      approvalWorkflow: false
      validationStatus: "VALID"
      hot-reload: true

  - scenario: "compliance-rule-editing"
    description: "Compliance rule editing requiring approval"
    data:
      ruleCategory: "COMPLIANCE_RULES"
      editedBy: "COMPLIANCE_OFFICERS"
      approvalRequired: true
      ruleExpression: "#data.regulatoryCheck == true"
      configType: "BUSINESS_EDITABLE"
    expected-results:
      editingAllowed: true
      approvalWorkflow: true
      validationStatus: "PENDING_APPROVAL"
      hot-reload: false

# Performance Test Scenarios
performance-scenarios:
  - scenario: "external-yaml-performance"
    description: "Performance testing for external YAML configuration"
    data:
      tradeId: "PERF_COM_001"
      notionalAmount: 10000000
      notionalCurrency: "USD"
      commodityType: "CRUDE_OIL"
      configType: "EXTERNAL_YAML"
    expected-performance:
      processing-time: "< 50ms"
      memory-usage: "LOW"
      reload-required: false

  - scenario: "business-editable-performance"
    description: "Performance testing for business editable rules"
    data:
      clientId: "PERF_CLIENT_001"
      counterpartyRating: "A+"
      riskLevel: "LOW"
      configType: "BUSINESS_EDITABLE"
    expected-performance:
      processing-time: "< 25ms"
      memory-usage: "LOW"
      hot-reload: true

  - scenario: "dynamic-loading-performance"
    description: "Performance testing for dynamic configuration loading"
    data:
      configVersion: "2.0"
      environment: "PRODUCTION"
      hotReload: true
      configType: "DYNAMIC_LOADING"
    expected-performance:
      processing-time: "< 100ms"
      memory-usage: "MEDIUM"
      supports-hot-reload: true

# Reference Data for Validation
reference-data:
  currencies:
    - "USD"
    - "EUR"
    - "GBP"
    - "JPY"
  
  commodity-types:
    - "CRUDE_OIL"
    - "NATURAL_GAS"
    - "GOLD"
    - "SILVER"
    - "COPPER"
  
  counterparty-ratings:
    - "AAA"
    - "AA+"
    - "AA"
    - "AA-"
    - "A+"
    - "A"
    - "A-"
    - "BBB+"
    - "BBB"
    - "BBB-"
  
  risk-levels:
    - "LOW"
    - "MEDIUM"
    - "HIGH"
    - "CRITICAL"
  
  environments:
    - "DEVELOPMENT"
    - "TESTING"
    - "STAGING"
    - "PRODUCTION"
  
  config-types:
    - "EXTERNAL_YAML"
    - "BUSINESS_EDITABLE"
    - "DYNAMIC_LOADING"
    - "ALL_TYPES"

