# APEX Pricing Strategy Frameworks Configuration
# External data source configuration for pricing strategy frameworks
# Replaces hardcoded pricing strategy logic from PricingServiceDemo

metadata:
  id: "pricing-strategy-frameworks-configuration"
  name: "Pricing Strategy Frameworks Configuration"
  version: "1.0.0"
  description: "Data-driven pricing strategy frameworks configuration for pricing service"
  type: "external-data-config"
  author: "apex.demo.team@company.com"
  created-date: "2024-12-24"
  tags: ["apex-demo", "evaluation", "pricing-service", "pricing-strategy-frameworks"]

# Pricing strategy frameworks configuration by framework type
data:
  competitive-pricing-strategies:
    framework-type: "competitive-pricing-strategies"
    framework-name: "Competitive Pricing Strategies"
    description: "Frameworks for competitive pricing analysis and implementation"
    framework-characteristics:
      strategy-category: "COMPETITIVE"
      analysis-focus: "MARKET_POSITIONING"
      decision-model: "COMPETITOR_BASED"
    pricing-strategies:
      market-leader-strategy:
        strategy-id: "pricing-strategy-frameworks-configuration"
        strategy-name: "Market Leader Pricing Strategy"
        strategy-description: "Premium pricing strategy for market leaders"
        competitive-analysis:
          market-position: "LEADER"
          pricing-approach: "PREMIUM"
          competitive-advantage: "BRAND_VALUE"
        pricing-rules:
          - rule-name: "leader-premium-pricing"
            rule-condition: "#marketPosition == 'LEADER'"
            rule-calculation: "#basePrice * 1.15"
            rule-description: "15% premium for market leaders"
            rule-priority: 1
          - rule-name: "brand-value-adjustment"
            rule-condition: "#brandStrength == 'HIGH'"
            rule-calculation: "#basePrice * 1.1"
            rule-description: "10% premium for strong brand value"
            rule-priority: 2
          - rule-name: "quality-premium"
            rule-condition: "#qualityRating >= 4.5"
            rule-calculation: "#basePrice * 1.05"
            rule-description: "5% premium for high quality rating"
            rule-priority: 3
        strategy-outcomes:
          success-outcome: "MARKET_LEADER_PRICING_APPLIED"
          failure-outcome: "MARKET_LEADER_PRICING_FAILED"
        audit-requirements:
          - "Log market leader pricing decisions"
          - "Track premium pricing effectiveness"
          
      market-follower-strategy:
        strategy-id: "pricing-strategy-frameworks-configuration"
        strategy-name: "Market Follower Pricing Strategy"
        strategy-description: "Competitive pricing strategy for market followers"
        competitive-analysis:
          market-position: "FOLLOWER"
          pricing-approach: "COMPETITIVE"
          competitive-advantage: "PRICE_VALUE"
        pricing-rules:
          - rule-name: "follower-competitive-pricing"
            rule-condition: "#marketPosition == 'FOLLOWER'"
            rule-calculation: "#competitorPrice * 0.95"
            rule-description: "Price 5% below market leader"
            rule-priority: 1
          - rule-name: "value-positioning"
            rule-condition: "#valueProposition == 'HIGH'"
            rule-calculation: "#competitorPrice * 0.98"
            rule-description: "Price closer to competitor for high value"
            rule-priority: 2
          - rule-name: "market-share-growth"
            rule-condition: "#marketShareGoal == 'GROWTH'"
            rule-calculation: "#competitorPrice * 0.90"
            rule-description: "Aggressive pricing for market share growth"
            rule-priority: 3
        strategy-outcomes:
          success-outcome: "MARKET_FOLLOWER_PRICING_APPLIED"
          failure-outcome: "MARKET_FOLLOWER_PRICING_FAILED"
        audit-requirements:
          - "Log competitive pricing decisions"
          - "Track market share impact"
          
      price-challenger-strategy:
        strategy-id: "pricing-strategy-frameworks-configuration"
        strategy-name: "Price Challenger Strategy"
        strategy-description: "Aggressive pricing strategy to challenge market leaders"
        competitive-analysis:
          market-position: "CHALLENGER"
          pricing-approach: "AGGRESSIVE"
          competitive-advantage: "LOW_COST"
        pricing-rules:
          - rule-name: "challenger-aggressive-pricing"
            rule-condition: "#marketPosition == 'CHALLENGER'"
            rule-calculation: "#competitorPrice * 0.85"
            rule-description: "Price 15% below market leader"
            rule-priority: 1
          - rule-name: "cost-advantage-leverage"
            rule-condition: "#costAdvantage == true"
            rule-calculation: "#competitorPrice * 0.80"
            rule-description: "Leverage cost advantage for aggressive pricing"
            rule-priority: 2
          - rule-name: "market-disruption"
            rule-condition: "#disruptionStrategy == true"
            rule-calculation: "#competitorPrice * 0.75"
            rule-description: "Disruptive pricing to gain market share"
            rule-priority: 3
        strategy-outcomes:
          success-outcome: "PRICE_CHALLENGER_PRICING_APPLIED"
          failure-outcome: "PRICE_CHALLENGER_PRICING_FAILED"
        audit-requirements:
          - "Log aggressive pricing decisions"
          - "Track market disruption impact"
    framework-settings:
      competitive-analysis: true
      market-monitoring: true
      dynamic-adjustment: true
    
  value-based-pricing-strategies:
    framework-type: "value-based-pricing-strategies"
    framework-name: "Value-Based Pricing Strategies"
    description: "Frameworks for value-based pricing analysis and implementation"
    framework-characteristics:
      strategy-category: "VALUE_BASED"
      analysis-focus: "CUSTOMER_VALUE"
      decision-model: "VALUE_PROPOSITION"
    pricing-strategies:
      premium-value-strategy:
        strategy-id: "pricing-strategy-frameworks-configuration"
        strategy-name: "Premium Value Pricing Strategy"
        strategy-description: "Premium pricing based on superior value proposition"
        value-analysis:
          value-proposition: "PREMIUM"
          customer-benefit: "HIGH"
          differentiation: "SIGNIFICANT"
        pricing-rules:
          - rule-name: "premium-value-pricing"
            rule-condition: "#valueProposition == 'PREMIUM'"
            rule-calculation: "#basePrice * 1.3"
            rule-description: "30% premium for premium value proposition"
            rule-priority: 1
          - rule-name: "customer-benefit-adjustment"
            rule-condition: "#customerBenefit == 'HIGH'"
            rule-calculation: "#basePrice * 1.2"
            rule-description: "20% premium for high customer benefit"
            rule-priority: 2
          - rule-name: "differentiation-premium"
            rule-condition: "#differentiation == 'SIGNIFICANT'"
            rule-calculation: "#basePrice * 1.15"
            rule-description: "15% premium for significant differentiation"
            rule-priority: 3
        strategy-outcomes:
          success-outcome: "PREMIUM_VALUE_PRICING_APPLIED"
          failure-outcome: "PREMIUM_VALUE_PRICING_FAILED"
        audit-requirements:
          - "Log value-based pricing decisions"
          - "Track customer value perception"
          
      standard-value-strategy:
        strategy-id: "pricing-strategy-frameworks-configuration"
        strategy-name: "Standard Value Pricing Strategy"
        strategy-description: "Standard pricing based on balanced value proposition"
        value-analysis:
          value-proposition: "STANDARD"
          customer-benefit: "MODERATE"
          differentiation: "MODERATE"
        pricing-rules:
          - rule-name: "standard-value-pricing"
            rule-condition: "#valueProposition == 'STANDARD'"
            rule-calculation: "#basePrice * 1.1"
            rule-description: "10% premium for standard value proposition"
            rule-priority: 1
          - rule-name: "balanced-benefit-pricing"
            rule-condition: "#customerBenefit == 'MODERATE'"
            rule-calculation: "#basePrice * 1.05"
            rule-description: "5% premium for moderate customer benefit"
            rule-priority: 2
          - rule-name: "market-alignment"
            rule-condition: "#marketAlignment == true"
            rule-calculation: "#basePrice"
            rule-description: "Market-aligned pricing for standard value"
            rule-priority: 3
        strategy-outcomes:
          success-outcome: "STANDARD_VALUE_PRICING_APPLIED"
          failure-outcome: "STANDARD_VALUE_PRICING_FAILED"
        audit-requirements:
          - "Log standard value pricing decisions"
          - "Track market alignment effectiveness"
          
      economy-value-strategy:
        strategy-id: "pricing-strategy-frameworks-configuration"
        strategy-name: "Economy Value Pricing Strategy"
        strategy-description: "Economy pricing based on cost-effective value proposition"
        value-analysis:
          value-proposition: "ECONOMY"
          customer-benefit: "BASIC"
          differentiation: "MINIMAL"
        pricing-rules:
          - rule-name: "economy-value-pricing"
            rule-condition: "#valueProposition == 'ECONOMY'"
            rule-calculation: "#basePrice * 0.9"
            rule-description: "10% discount for economy value proposition"
            rule-priority: 1
          - rule-name: "cost-effective-positioning"
            rule-condition: "#costEffectiveness == 'HIGH'"
            rule-calculation: "#basePrice * 0.85"
            rule-description: "15% discount for high cost effectiveness"
            rule-priority: 2
          - rule-name: "volume-pricing"
            rule-condition: "#volumeExpectation == 'HIGH'"
            rule-calculation: "#basePrice * 0.80"
            rule-description: "20% discount for high volume expectations"
            rule-priority: 3
        strategy-outcomes:
          success-outcome: "ECONOMY_VALUE_PRICING_APPLIED"
          failure-outcome: "ECONOMY_VALUE_PRICING_FAILED"
        audit-requirements:
          - "Log economy value pricing decisions"
          - "Track volume impact on pricing"
    framework-settings:
      value-assessment: true
      customer-analysis: true
      benefit-quantification: true
    
  cost-plus-pricing-strategies:
    framework-type: "cost-plus-pricing-strategies"
    framework-name: "Cost-Plus Pricing Strategies"
    description: "Frameworks for cost-plus pricing analysis and implementation"
    framework-characteristics:
      strategy-category: "COST_PLUS"
      analysis-focus: "COST_STRUCTURE"
      decision-model: "MARGIN_BASED"
    pricing-strategies:
      standard-margin-strategy:
        strategy-id: "pricing-strategy-frameworks-configuration"
        strategy-name: "Standard Margin Pricing Strategy"
        strategy-description: "Standard cost-plus pricing with fixed margin"
        cost-analysis:
          cost-structure: "STANDARD"
          margin-target: "FIXED"
          markup-approach: "PERCENTAGE"
        pricing-rules:
          - rule-name: "standard-margin-calculation"
            rule-condition: "#costStructure == 'STANDARD'"
            rule-calculation: "#totalCost * 1.25"
            rule-description: "25% markup on total cost"
            rule-priority: 1
          - rule-name: "minimum-margin-protection"
            rule-condition: "(#totalCost * 1.25) < (#totalCost * 1.15)"
            rule-calculation: "#totalCost * 1.15"
            rule-description: "Minimum 15% margin protection"
            rule-priority: 2
          - rule-name: "cost-validation"
            rule-condition: "#totalCost > 0"
            rule-description: "Total cost must be positive"
            rule-priority: 1
        strategy-outcomes:
          success-outcome: "STANDARD_MARGIN_PRICING_APPLIED"
          failure-outcome: "STANDARD_MARGIN_PRICING_FAILED"
        audit-requirements:
          - "Log cost-plus calculations"
          - "Track margin achievement"
          
      tiered-margin-strategy:
        strategy-id: "pricing-strategy-frameworks-configuration"
        strategy-name: "Tiered Margin Pricing Strategy"
        strategy-description: "Cost-plus pricing with tiered margins based on cost levels"
        cost-analysis:
          cost-structure: "TIERED"
          margin-target: "VARIABLE"
          markup-approach: "TIERED"
        pricing-rules:
          - rule-name: "low-cost-tier-margin"
            rule-condition: "#totalCost < 100"
            rule-calculation: "#totalCost * 1.4"
            rule-description: "40% markup for low-cost items"
            rule-priority: 1
          - rule-name: "medium-cost-tier-margin"
            rule-condition: "#totalCost >= 100 && #totalCost < 500"
            rule-calculation: "#totalCost * 1.3"
            rule-description: "30% markup for medium-cost items"
            rule-priority: 1
          - rule-name: "high-cost-tier-margin"
            rule-condition: "#totalCost >= 500"
            rule-calculation: "#totalCost * 1.2"
            rule-description: "20% markup for high-cost items"
            rule-priority: 1
        strategy-outcomes:
          success-outcome: "TIERED_MARGIN_PRICING_APPLIED"
          failure-outcome: "TIERED_MARGIN_PRICING_FAILED"
        audit-requirements:
          - "Log tiered margin applications"
          - "Track cost tier distributions"
    framework-settings:
      cost-tracking: true
      margin-optimization: true
      tier-management: true
    
  dynamic-pricing-strategies:
    framework-type: "dynamic-pricing-strategies"
    framework-name: "Dynamic Pricing Strategies"
    description: "Frameworks for dynamic pricing analysis and implementation"
    framework-characteristics:
      strategy-category: "DYNAMIC"
      analysis-focus: "REAL_TIME_OPTIMIZATION"
      decision-model: "ALGORITHMIC"
    pricing-strategies:
      demand-based-strategy:
        strategy-id: "pricing-strategy-frameworks-configuration"
        strategy-name: "Demand-Based Dynamic Pricing Strategy"
        strategy-description: "Dynamic pricing based on real-time demand patterns"
        dynamic-analysis:
          demand-sensitivity: "HIGH"
          price-elasticity: "MODERATE"
          optimization-frequency: "REAL_TIME"
        pricing-rules:
          - rule-name: "high-demand-adjustment"
            rule-condition: "#currentDemand > #averageDemand * 1.5"
            rule-calculation: "#basePrice * 1.2"
            rule-description: "20% increase for high demand periods"
            rule-priority: 1
          - rule-name: "low-demand-adjustment"
            rule-condition: "#currentDemand < #averageDemand * 0.5"
            rule-calculation: "#basePrice * 0.9"
            rule-description: "10% decrease for low demand periods"
            rule-priority: 1
          - rule-name: "demand-trend-adjustment"
            rule-condition: "#demandTrend == 'INCREASING'"
            rule-calculation: "#basePrice * 1.1"
            rule-description: "10% increase for increasing demand trend"
            rule-priority: 2
        strategy-outcomes:
          success-outcome: "DEMAND_BASED_PRICING_APPLIED"
          failure-outcome: "DEMAND_BASED_PRICING_FAILED"
        audit-requirements:
          - "Log demand-based adjustments"
          - "Track demand pattern analysis"
          
      inventory-based-strategy:
        strategy-id: "pricing-strategy-frameworks-configuration"
        strategy-name: "Inventory-Based Dynamic Pricing Strategy"
        strategy-description: "Dynamic pricing based on inventory levels and turnover"
        dynamic-analysis:
          inventory-sensitivity: "HIGH"
          turnover-optimization: "ACTIVE"
          clearance-automation: "ENABLED"
        pricing-rules:
          - rule-name: "low-inventory-premium"
            rule-condition: "#inventoryLevel < #reorderPoint"
            rule-calculation: "#basePrice * 1.15"
            rule-description: "15% premium for low inventory"
            rule-priority: 1
          - rule-name: "excess-inventory-discount"
            rule-condition: "#inventoryLevel > #maxInventory * 0.8"
            rule-calculation: "#basePrice * 0.85"
            rule-description: "15% discount for excess inventory"
            rule-priority: 1
          - rule-name: "slow-moving-clearance"
            rule-condition: "#inventoryAge > 90 && #turnoverRate < 0.1"
            rule-calculation: "#basePrice * 0.7"
            rule-description: "30% discount for slow-moving inventory"
            rule-priority: 2
        strategy-outcomes:
          success-outcome: "INVENTORY_BASED_PRICING_APPLIED"
          failure-outcome: "INVENTORY_BASED_PRICING_FAILED"
        audit-requirements:
          - "Log inventory-based adjustments"
          - "Track inventory optimization impact"
    framework-settings:
      real-time-processing: true
      algorithmic-optimization: true
      automated-adjustment: true
    
  default:
    framework-type: "default"
    framework-name: "Default Pricing Strategy Frameworks"
    description: "Default pricing strategy framework processing"
    pricing-strategies:
      default-strategy:
        strategy-id: "pricing-strategy-frameworks-configuration"
        strategy-name: "Default Strategy"
        pricing-rules:
          - rule-name: "default-pricing"
            rule-calculation: "#basePrice"
            rule-description: "Default pricing strategy"
    framework-settings:
      default-processing: true

# Framework execution patterns
execution-patterns:
  strategy-category-pattern:
    pattern-name: "Strategy Category Pattern"
    description: "Execute frameworks based on strategy categories"
    strategy-categories: ["COMPETITIVE", "VALUE_BASED", "COST_PLUS", "DYNAMIC"]
    
  analysis-focus-pattern:
    pattern-name: "Analysis Focus Pattern"
    description: "Execute frameworks based on analysis focus"
    analysis-focuses: ["MARKET_POSITIONING", "CUSTOMER_VALUE", "COST_STRUCTURE", "REAL_TIME_OPTIMIZATION"]
    
  decision-model-pattern:
    pattern-name: "Decision Model Pattern"
    description: "Execute frameworks based on decision models"
    decision-models: ["COMPETITOR_BASED", "VALUE_PROPOSITION", "MARGIN_BASED", "ALGORITHMIC"]

# Quality assurance
quality-assurance:
  framework-accuracy:
    - "Pricing strategy frameworks must be accurate"
    - "Strategic analysis must be comprehensive"
    - "Pricing decisions must be sound"
    - "Implementation must be effective"
    
  framework-reliability:
    - "Frameworks must be consistent"
    - "Strategy execution must be reliable"
    - "Performance must be predictable"
    - "Results must be measurable"
    
  strategic-alignment:
    - "Frameworks must align with business strategy"
    - "Pricing strategies must support objectives"
    - "Implementation must be practical"
    - "Results must be actionable"
