# Spring Boot Configuration for APEX REST API
spring:
  application:
    name: apex-rest-api
  
  # Server configuration
  server:
    port: 8080
    servlet:
      context-path: /
    compression:
      enabled: true
      mime-types: application/json,application/xml,text/html,text/xml,text/plain,application/javascript,text/css
  
  # Jackson configuration for JSON processing
  jackson:
    serialization:
      write-dates-as-timestamps: false
      indent-output: true
    deserialization:
      fail-on-unknown-properties: false
    default-property-inclusion: non_null
  
  # Multipart file upload configuration
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      enabled: true

# Management endpoints (Spring Boot Actuator)
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
      base-path: /actuator
  endpoint:
    health:
      show-details: when-authorized
      show-components: always
  health:
    defaults:
      enabled: true
  info:
    env:
      enabled: true
    java:
      enabled: true
    os:
      enabled: true

# Rules Engine specific configuration
rules:
  config:
    default-path: classpath:rules/default-rules.yaml
  performance:
    monitoring:
      enabled: true
  error:
    recovery:
      enabled: true
  cache:
    enabled: true
    ttl-seconds: 3600

# OpenAPI/Swagger configuration for Spring Boot 3.x
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operations-sorter: method
    tags-sorter: alpha
    display-request-duration: true
    display-operation-id: true
  show-actuator: true

# Logging configuration
logging:
  level:
    dev.mars.rulesengine: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springdoc: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/rules-engine-rest-api.log
    max-size: 10MB
    max-history: 30

# Application information
info:
  app:
    name: APEX REST API
    description: Comprehensive REST API for APEX (Advanced Processing Engine for eXpressions) with YAML Dataset Enrichment
    version: 1.0.0
    encoding: UTF-8
    java:
      version: ${java.version}
  build:
    artifact: ${project.artifactId:apex-rest-api}
    name: ${project.name:APEX REST API}
    description: ${project.description:REST API for APEX}
    version: ${project.version:1.0.0}
  api:
    version: v1
    majorVersion: 1
    minorVersion: 0
    patchVersion: 0
    status: stable
    releaseDate: "2025-07-31"
    deprecationPolicy:
      minimumSupportPeriod: "12 months"
      warningHeaders: true
      migrationGuides: true
    versioning:
      strategy: "url-path"
      currentPath: "/api"
      futureVersions:
        v2: "/api/v2"
        v3: "/api/v3"
    compatibility:
      backwardCompatible: []
      forwardCompatible: ["v2-beta"]
      breakingChanges: []

---
# Development profile
spring:
  config:
    activate:
      on-profile: dev
  
  # Development server configuration
  server:
    port: 8080
  
  # Development logging
  logging:
    level:
      dev.mars.rulesengine: DEBUG
      org.springframework.web: DEBUG
      org.springframework.boot.web: DEBUG
    pattern:
      console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

# Development rules configuration
rules:
  config:
    default-path: classpath:rules/dev-rules.yaml
  performance:
    monitoring:
      enabled: true
  error:
    recovery:
      enabled: true

---
# Production profile
spring:
  config:
    activate:
      on-profile: prod
  
  # Production server configuration
  server:
    port: 8080
    compression:
      enabled: true
  
  # Production logging
  logging:
    level:
      dev.mars.rulesengine: INFO
      org.springframework.web: WARN
      org.springframework.boot: WARN
    file:
      name: /var/log/rules-engine/rules-engine-rest-api.log

# Production rules configuration
rules:
  config:
    default-path: file:/etc/rules-engine/production-rules.yaml
  performance:
    monitoring:
      enabled: true
  error:
    recovery:
      enabled: true
  cache:
    enabled: true
    ttl-seconds: 7200

# Production management endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: never

---
# Test profile
spring:
  config:
    activate:
      on-profile: test
  
  # Test server configuration
  server:
    port: 0  # Random port for tests
  
  # Test logging
  logging:
    level:
      dev.mars.rulesengine: DEBUG
      org.springframework.test: DEBUG

# Test rules configuration
rules:
  config:
    default-path: classpath:rules/test-rules.yaml
  performance:
    monitoring:
      enabled: false  # Disable for faster tests
  error:
    recovery:
      enabled: true
