# Financial Services Post-Trade Settlement Rules Configuration
# Demonstrates the new generic architecture with full enterprise metadata support
# This configuration focuses on financial services post-trade settlement enrichment

metadata:
  name: "Financial Services Post-Trade Settlement Rules"
  version: "2.0.0"
  description: "Comprehensive post-trade settlement enrichment rules with full audit support"
  author: "settlement.admin@financialservices.com"
  created: "2024-01-15T10:00:00Z"
  last-modified: "2024-01-20T15:30:00Z"
  tags:
    - "financial-services"
    - "post-trade-settlement"
    - "enrichment"
    - "audit-ready"

# Financial Services Post-Trade Settlement Categories
categories:
  - name: "settlement-enrichment"
    display-name: "Settlement Enrichment"
    description: "Rules for enriching trade data with settlement information"
    priority: 10
    enabled: true
    business-domain: "Financial Services Post-Trade"
    business-owner: "Head of Post-Trade Operations"
    created-by: "settlement.admin@financialservices.com"

  - name: "counterparty-enrichment"
    display-name: "Counterparty Enrichment"
    description: "Rules for enriching counterparty information and validation"
    priority: 20
    enabled: true
    business-domain: "Financial Services Post-Trade"
    business-owner: "Head of Counterparty Management"
    created-by: "counterparty.admin@financialservices.com"

  - name: "regulatory-enrichment"
    display-name: "Regulatory Enrichment"
    description: "Rules for regulatory reporting and compliance enrichment"
    priority: 30
    enabled: true
    business-domain: "Financial Services Post-Trade"
    business-owner: "Chief Compliance Officer"
    created-by: "compliance.officer@financialservices.com"

  - name: "fee-calculation"
    display-name: "Fee and Commission Calculation"
    description: "Rules for calculating fees, commissions, and charges"
    priority: 40
    enabled: true
    business-domain: "Financial Services Post-Trade"
    business-owner: "Head of Operations"
    created-by: "operations.manager@financialservices.com"

# Financial Services Post-Trade Settlement Rules with comprehensive enterprise metadata
rules:
  # Settlement Enrichment Rules
  - id: "settlement-date-validation"
    name: "Settlement Date Validation"
    description: "Validates that settlement date is appropriate relative to trade date"
    category: "settlement-enrichment"
    condition: "#settlementDate != null && #settlementDate.isAfter(#tradeDate)"
    message: "Settlement date must be after trade date"
    priority: 10
    enabled: true
    tags: ["settlement-date", "trade-validation"]

    # Enterprise metadata
    created-by: "settlement.admin@financialservices.com"
    business-domain: "Financial Services Post-Trade"
    business-owner: "Head of Post-Trade Operations"
    source-system: "SETTLEMENT_MANAGEMENT_SYSTEM"
    effective-date: "2024-01-01T00:00:00Z"
    expiration-date: "2025-01-01T00:00:00Z"

    # Custom properties for domain-specific needs
    custom-properties:
      department: "Post-Trade Operations"
      compliance-level: "HIGH"
      review-frequency: "QUARTERLY"
      regulatory-requirement: "T+2_SETTLEMENT"

  - id: "ssi-enrichment"
    name: "Standard Settlement Instructions Enrichment"
    description: "Validates and enriches standard settlement instructions"
    category: "settlement-enrichment"
    condition: "#standardSettlementInstructions != null && #custodianBIC != null"
    message: "Standard Settlement Instructions and custodian BIC required"
    priority: 11
    enabled: true
    tags: ["ssi", "custodian-validation"]

    created-by: "settlement.admin@financialservices.com"
    business-domain: "Financial Services Post-Trade"
    business-owner: "Head of Post-Trade Operations"
    source-system: "SSI_MANAGEMENT_SYSTEM"
    effective-date: "2024-01-01T00:00:00Z"

    custom-properties:
      department: "Settlement Operations"
      compliance-level: "HIGH"
      integration-required: true

  # Counterparty Enrichment Rules
  - id: "lei-validation"
    name: "Legal Entity Identifier Validation"
    description: "Validates that counterparty has a valid Legal Entity Identifier"
    category: "counterparty-enrichment"
    condition: "#counterpartyLEI != null && #counterpartyLEI.length() == 20"
    message: "Valid 20-character LEI required for counterparty"
    priority: 10
    enabled: true
    tags: ["lei", "counterparty", "regulatory-compliance"]

    created-by: "counterparty.admin@financialservices.com"
    business-domain: "Financial Services Post-Trade"
    business-owner: "Head of Counterparty Management"
    source-system: "COUNTERPARTY_MANAGEMENT_SYSTEM"
    effective-date: "2024-01-01T00:00:00Z"

    custom-properties:
      department: "Counterparty Management"
      regulatory-requirement: "EMIR_SFTR"
      validation-level: "CRITICAL"

  - id: "credit-rating-enrichment"
    name: "Credit Rating Enrichment"
    description: "Enriches counterparty data with current credit rating information"
    category: "counterparty-enrichment"
    condition: "#counterpartyCreditRating != null && #counterpartyCreditRating.matches('[A-C][+-]?')"
    message: "Valid credit rating required for counterparty risk assessment"
    priority: 11
    enabled: true
    tags: ["credit-rating", "risk-assessment", "counterparty"]

    created-by: "counterparty.admin@financialservices.com"
    business-domain: "Financial Services Post-Trade"
    business-owner: "Head of Counterparty Management"
    source-system: "CREDIT_RATING_SYSTEM"
    effective-date: "2024-01-01T00:00:00Z"

    custom-properties:
      department: "Risk Management"
      data-source: "EXTERNAL_RATING_AGENCY"
      refresh-frequency: "DAILY"

  # Regulatory Enrichment Rules
  - id: "uti-generation"
    name: "Unique Transaction Identifier Generation"
    description: "Ensures trade has a valid Unique Transaction Identifier for regulatory reporting"
    category: "regulatory-enrichment"
    condition: "#uniqueTransactionId != null && #uniqueTransactionId.length() >= 52"
    message: "Valid UTI with minimum 52 characters required for regulatory reporting"
    priority: 10
    enabled: true
    tags: ["uti", "regulatory-reporting", "compliance"]

    created-by: "compliance.officer@financialservices.com"
    business-domain: "Financial Services Post-Trade"
    business-owner: "Chief Compliance Officer"
    source-system: "REGULATORY_REPORTING_SYSTEM"
    effective-date: "2024-01-01T00:00:00Z"

    custom-properties:
      regulation: "EMIR_SFTR"
      compliance-level: "CRITICAL"
      audit-required: true

  - id: "mifid-reporting-flags"
    name: "MiFID II Reporting Flags Validation"
    description: "Validates that MiFID II reporting flags are properly set"
    category: "regulatory-enrichment"
    condition: "#mifidReportingRequired == true && #reportingFlags != null"
    message: "MiFID II reporting flags must be present when reporting is required"
    priority: 11
    enabled: true
    tags: ["mifid", "reporting-flags", "compliance"]

    created-by: "compliance.officer@financialservices.com"
    business-domain: "Financial Services Post-Trade"
    business-owner: "Chief Compliance Officer"
    source-system: "MIFID_REPORTING_SYSTEM"
    effective-date: "2024-01-01T00:00:00Z"

    custom-properties:
      regulation: "MIFID_II"
      reporting-jurisdiction: "EU"
      validation-level: "HIGH"

  # Fee and Commission Calculation Rules
  - id: "broker-commission-validation"
    name: "Broker Commission Validation"
    description: "Validates that broker commission is within reasonable range"
    category: "fee-calculation"
    condition: "#brokerCommission >= 0 && #brokerCommission <= #tradeValue * 0.01"
    message: "Broker commission must be non-negative and not exceed 1% of trade value"
    priority: 10
    enabled: true
    tags: ["commission", "fee-validation", "broker"]

    created-by: "operations.manager@financialservices.com"
    business-domain: "Financial Services Post-Trade"
    business-owner: "Head of Operations"
    source-system: "FEE_CALCULATION_SYSTEM"
    effective-date: "2024-01-01T00:00:00Z"
    expiration-date: "2025-01-01T00:00:00Z"

    custom-properties:
      fee-type: "BROKER_COMMISSION"
      calculation-method: "PERCENTAGE_BASED"
      regulatory-requirement: true

  - id: "clearing-fee-validation"
    name: "Clearing Fee Validation"
    description: "Validates that clearing fees are properly calculated and applied"
    category: "fee-calculation"
    condition: "#clearingFee > 0 && #clearingFee <= #tradeValue * 0.005"
    message: "Clearing fee must be positive and not exceed 0.5% of trade value"
    priority: 11
    enabled: true
    tags: ["clearing-fee", "fee-validation", "post-trade"]

    created-by: "operations.manager@financialservices.com"
    business-domain: "Financial Services Post-Trade"
    business-owner: "Head of Operations"
    source-system: "CLEARING_FEE_SYSTEM"
    effective-date: "2024-01-01T00:00:00Z"

    custom-properties:
      fee-type: "CLEARING_FEE"
      calculation-method: "FIXED_RATE"
      clearing-house: "LCH_CLEARNET"

# Rule groups for organized execution (optional)
rule-groups:
  - id: "settlement-enrichment-group"
    name: "Settlement Enrichment Validation"
    description: "Complete settlement data enrichment and validation"
    category: "settlement-enrichment"
    priority: 10
    enabled: true
    stop-on-first-failure: false
    parallel-execution: true
    rule-ids:
      - "settlement-date-validation"
      - "ssi-enrichment"

  - id: "counterparty-enrichment-group"
    name: "Counterparty Data Enrichment"
    description: "Critical counterparty data validation and enrichment"
    category: "counterparty-enrichment"
    priority: 10
    enabled: true
    stop-on-first-failure: true  # Stop immediately on counterparty validation failures
    parallel-execution: true
    rule-ids:
      - "lei-validation"
      - "credit-rating-enrichment"

  - id: "regulatory-compliance-group"
    name: "Regulatory Compliance Validation"
    description: "Comprehensive regulatory reporting and compliance checks"
    category: "regulatory-enrichment"
    priority: 10
    enabled: true
    stop-on-first-failure: false
    parallel-execution: true
    rule-ids:
      - "uti-generation"
      - "mifid-reporting-flags"

  - id: "fee-calculation-group"
    name: "Fee and Commission Calculation"
    description: "Complete fee and commission validation and calculation"
    category: "fee-calculation"
    priority: 10
    enabled: true
    stop-on-first-failure: false
    parallel-execution: true
    rule-ids:
      - "broker-commission-validation"
      - "clearing-fee-validation"
