# QuickStart Demo - Configuration
# This file contains configuration settings for the QuickStart demonstration
# Business users can modify these settings to customize demo behavior

metadata:
  version: "1.0"
  description: "Configuration settings for QuickStart demonstration"
  lastUpdated: "2025-07-28"
  author: "APEX Demo Team"

# Demo execution configuration
demo:
  name: "QuickStart Demo"
  description: "Getting started with APEX Rules Engine"
  version: "2.0"
  modes:
    - name: "BASIC"
      description: "Simple rule evaluation and validation"
      enabled: true
    - name: "ADVANCED"
      description: "Complex rules with enrichment and chaining"
      enabled: true
    - name: "PRODUCTION"
      description: "Production-ready patterns and best practices"
      enabled: true

# Validation configuration
validation:
  # Age validation settings
  age:
    enabled: true
    minAge: 18
    maxAge: 120
    errorMessage: "Age must be between 18 and 120 years"
    
  # Email validation settings
  email:
    enabled: true
    requireAtSymbol: true
    requireDomain: true
    errorMessage: "Email must be in valid format (user@domain.com)"
    
  # Balance validation settings
  balance:
    enabled: true
    minBalance: 0.0
    maxBalance: 1000000.0
    errorMessage: "Account balance must be between 0 and 1,000,000"
    
  # Country validation settings
  country:
    enabled: true
    validCountries: ["US", "GB", "CA", "DE", "FR", "JP", "AU", "NZ", "CH"]
    errorMessage: "Country must be from supported list"

# Enrichment configuration
enrichment:
  # Customer tier enrichment
  customerTier:
    enabled: true
    rules:
      - condition: "#accountBalance >= 100000"
        tier: "PLATINUM"
        discountRate: 0.15
      - condition: "#accountBalance >= 50000"
        tier: "GOLD"
        discountRate: 0.10
      - condition: "#accountBalance >= 10000"
        tier: "SILVER"
        discountRate: 0.05
      - condition: "#accountBalance >= 0"
        tier: "BASIC"
        discountRate: 0.00
        
  # Risk rating enrichment
  riskRating:
    enabled: true
    rules:
      - condition: "#accountBalance >= 50000 && #age >= 30"
        rating: "LOW"
      - condition: "#accountBalance >= 10000 && #age >= 25"
        rating: "MEDIUM"
      - condition: "true"
        rating: "HIGH"

# Performance configuration
performance:
  # Caching settings
  caching:
    enabled: true
    maxCacheSize: 1000
    cacheTtlSeconds: 3600
    
  # Concurrent processing
  concurrency:
    enabled: true
    maxThreads: 4
    timeoutSeconds: 30
    
  # Metrics collection
  metrics:
    enabled: true
    collectTimings: true
    collectMemoryUsage: true
    reportingIntervalSeconds: 60

# Logging configuration
logging:
  level: "INFO"
  enableRuleTracing: false
  enablePerformanceLogging: true
  enableValidationLogging: true
  logSuccessfulValidations: false
  logFailedValidations: true

# Error handling configuration
errorHandling:
  # Validation error handling
  validation:
    stopOnFirstError: false
    collectAllErrors: true
    includeFieldNames: true
    includeErrorCodes: true
    
  # Processing error handling
  processing:
    retryOnFailure: true
    maxRetries: 3
    retryDelayMs: 1000
    fallbackToDefaults: true

# Business rules configuration
businessRules:
  # Customer validation rules
  customerValidation:
    enabled: true
    rules:
      - name: "age-validation"
        expression: "#age != null && #age >= 18 && #age <= 120"
        errorCode: "INVALID_AGE"
        severity: "ERROR"
        
      - name: "email-validation"
        expression: "#email != null && #email.contains('@') && #email.contains('.')"
        errorCode: "INVALID_EMAIL"
        severity: "ERROR"
        
      - name: "balance-validation"
        expression: "#accountBalance != null && #accountBalance >= 0"
        errorCode: "INVALID_BALANCE"
        severity: "ERROR"
        
      - name: "country-validation"
        expression: "#country != null && #country in {'US', 'GB', 'CA', 'DE', 'FR', 'JP', 'AU'}"
        errorCode: "INVALID_COUNTRY"
        severity: "WARNING"

# Test scenarios configuration
testScenarios:
  # Basic validation scenario
  basicValidation:
    enabled: true
    description: "Test basic customer validation rules"
    expectedPassCount: 4
    expectedFailCount: 4
    
  # Enrichment scenario
  enrichmentTest:
    enabled: true
    description: "Test customer data enrichment"
    validateEnrichment: true
    expectedEnrichmentFields: ["tier", "discountRate", "riskRating"]
    
  # Performance scenario
  performanceTest:
    enabled: true
    description: "Test performance with multiple customers"
    customerCount: 100
    maxProcessingTimeMs: 1000
    
  # Error handling scenario
  errorHandling:
    enabled: true
    description: "Test error handling and recovery"
    includeInvalidData: true
    validateErrorMessages: true

# Integration configuration
integration:
  # External data sources
  dataSources:
    enabled: false
    customerDataSource: "demo-data/quickstart/customers.yaml"
    configurationSource: "demo-data/quickstart/config.yaml"
    
  # API integration
  api:
    enabled: false
    baseUrl: "http://localhost:8080/api"
    timeout: 5000
    retries: 3

# Demo output configuration
output:
  # Console output settings
  console:
    enabled: true
    showProgress: true
    showDetails: true
    showTimings: true
    colorOutput: true
    
  # File output settings
  file:
    enabled: false
    outputDirectory: "demo-output"
    generateReports: true
    includeMetrics: true
