name: "Simple PostgreSQL Lookup Demo Configuration"
description: "APEX-compliant simple PostgreSQL lookup processing with real business logic"
version: "1.0"

enrichments:
  - id: "database-initialization"
    name: "database-initialization"
    type: "calculation-enrichment"
    description: "Initialize H2 database in PostgreSQL mode for simple lookup operations"
    condition: "#initializationType != null && #initializationScope != null"
    calculation-config:
      expression: "'Database Initialization: ' + #initializationType + ' with scope ' + #initializationScope + ' (Initialized: ' + T(java.time.LocalDateTime).now().toString() + ')'"
      result-field: "databaseInitializationResult"
    field-mappings:
      - source-field: "databaseInitializationResult"
        target-field: "databaseInitializationResult"

  - id: "customer-profile-lookup"
    name: "customer-profile-lookup"
    type: "calculation-enrichment"
    description: "Perform simple customer profile lookup using database operations"
    condition: "#profileLookupType != null && #profileLookupScope != null"
    calculation-config:
      expression: "'Customer Profile Lookup: ' + #profileLookupType + ' with scope ' + #profileLookupScope + ' (Looked up: ' + T(java.time.LocalDateTime).now().toString() + ')'"
      result-field: "customerProfileLookupResult"
    field-mappings:
      - source-field: "customerProfileLookupResult"
        target-field: "customerProfileLookupResult"

  - id: "database-optimization"
    name: "database-optimization"
    type: "calculation-enrichment"
    description: "Optimize database operations with connection pooling and caching"
    condition: "#optimizationType != null && #optimizationScope != null"
    calculation-config:
      expression: "'Database Optimization: ' + #optimizationType + ' with scope ' + #optimizationScope + ' (Optimized: ' + T(java.time.LocalDateTime).now().toString() + ')'"
      result-field: "databaseOptimizationResult"
    field-mappings:
      - source-field: "databaseOptimizationResult"
        target-field: "databaseOptimizationResult"

  - id: "summary"
    name: "summary"
    type: "calculation-enrichment"
    description: "Generate comprehensive simple PostgreSQL lookup summary"
    condition: "#approach != null"
    calculation-config:
      expression: "'Simple PostgreSQL Lookup Summary: Processing completed using ' + #approach + ' (Summary: ' + T(java.time.LocalDateTime).now().toString() + ')'"
      result-field: "simplePostgresqlLookupSummary"
    field-mappings:
      - source-field: "simplePostgresqlLookupSummary"
        target-field: "simplePostgresqlLookupSummary"
