# APEX Compliance Validation Configuration
# External data source configuration for compliance validation
# Replaces hardcoded compliance logic from IntegratedTradeValidatorComplexDemo

metadata:
  id: "Compliance Validation Configuration"
  name: "Compliance Validation Configuration"
  version: "1.0.0"
  description: "Data-driven compliance validation configuration for complex trade validation"
  type: "external-data-config"
  author: "apex.demo.team@company.com"
  created-date: "2024-12-24"
  tags: ["apex-demo", "validation", "trade-validation", "compliance-validation"]

# Compliance validation configuration by compliance type
data:
  standard-compliance:
    validation-id: "COMP001"
    compliance-type: "standard"
    description: "Standard compliance validation parameters"
    high-risk-countries:
      - "CountryX"  # High-risk jurisdiction X
      - "CountryY"  # High-risk jurisdiction Y
      - "CountryZ"  # High-risk jurisdiction Z
    restricted-entities:
      - "EntityA"   # Sanctioned entity A
      - "EntityB"   # Sanctioned entity B
      - "EntityC"   # Sanctioned entity C
    compliance-checks:
      - "Sanctions screening"
      - "AML verification"
      - "KYC compliance"
      - "Regulatory reporting"
    risk-tolerance: "medium"
    validation-rules:
      - "No transactions with high-risk countries"
      - "No dealings with restricted entities"
      - "Complete KYC documentation required"
      - "AML screening must pass"
    
  enhanced-compliance:
    validation-id: "COMP002"
    compliance-type: "enhanced"
    description: "Enhanced compliance validation with extended screening"
    high-risk-countries:
      - "CountryX"  # High-risk jurisdiction X
      - "CountryY"  # High-risk jurisdiction Y
      - "CountryZ"  # High-risk jurisdiction Z
      - "CountryA"  # Additional high-risk jurisdiction A
      - "CountryB"  # Additional high-risk jurisdiction B
    restricted-entities:
      - "EntityA"   # Sanctioned entity A
      - "EntityB"   # Sanctioned entity B
      - "EntityC"   # Sanctioned entity C
      - "EntityD"   # Additional restricted entity D
      - "EntityE"   # Additional restricted entity E
      - "EntityF"   # Additional restricted entity F
    compliance-checks:
      - "Enhanced sanctions screening"
      - "Advanced AML verification"
      - "Enhanced KYC compliance"
      - "Regulatory reporting"
      - "PEP screening"
      - "Adverse media screening"
    risk-tolerance: "low"
    validation-rules:
      - "Strict screening against all high-risk countries"
      - "Zero tolerance for restricted entities"
      - "Enhanced KYC documentation required"
      - "Advanced AML screening must pass"
      - "PEP status verification required"
      - "Adverse media check required"
    
  institutional-compliance:
    validation-id: "COMP003"
    compliance-type: "institutional"
    description: "Institutional compliance validation for large entities"
    high-risk-countries:
      - "CountryX"  # High-risk jurisdiction X
      - "CountryY"  # High-risk jurisdiction Y
      - "CountryZ"  # High-risk jurisdiction Z
    restricted-entities:
      - "EntityA"   # Sanctioned entity A
      - "EntityB"   # Sanctioned entity B
      - "EntityC"   # Sanctioned entity C
    compliance-checks:
      - "Institutional sanctions screening"
      - "Corporate AML verification"
      - "Institutional KYC compliance"
      - "Regulatory reporting"
      - "Board resolution verification"
      - "Authorized signatory validation"
    risk-tolerance: "low"
    validation-rules:
      - "Institutional-grade sanctions screening"
      - "Corporate entity verification"
      - "Board authorization required"
      - "Authorized signatory validation"
      - "Corporate KYC documentation"
      - "Institutional AML compliance"
    
  default:
    validation-id: "COMP000"
    compliance-type: "default"
    description: "Default compliance validation"
    high-risk-countries:
      - "CountryX"
    restricted-entities:
      - "EntityA"
    compliance-checks:
      - "Basic sanctions screening"
      - "Basic AML verification"
    risk-tolerance: "high"
    validation-rules:
      - "Basic compliance validation"

# Compliance validation patterns
validation-patterns:
  sanctions-screening:
    pattern-name: "Sanctions Screening Validation"
    description: "Comprehensive sanctions list screening"
    screening-lists:
      - "OFAC SDN List"
      - "EU Consolidated List"
      - "UN Security Council List"
      - "HMT Consolidated List"
    screening-criteria:
      - "Exact name matching"
      - "Fuzzy name matching"
      - "Address verification"
      - "Date of birth matching"
    validation-thresholds:
      exact-match: 100
      fuzzy-match: 85
      partial-match: 70
      
  aml-verification:
    pattern-name: "Anti-Money Laundering Verification"
    description: "AML compliance verification patterns"
    verification-checks:
      - "Source of funds verification"
      - "Transaction pattern analysis"
      - "Suspicious activity detection"
      - "Regulatory reporting compliance"
    risk-indicators:
      - "Unusual transaction patterns"
      - "High-risk geography involvement"
      - "Cash-intensive business"
      - "Complex ownership structures"
    validation-criteria:
      low-risk: "Standard verification"
      medium-risk: "Enhanced verification"
      high-risk: "Comprehensive investigation"
      
  kyc-compliance:
    pattern-name: "Know Your Customer Compliance"
    description: "KYC documentation and verification patterns"
    required-documents:
      individual:
        - "Government-issued ID"
        - "Proof of address"
        - "Tax identification number"
      corporate:
        - "Certificate of incorporation"
        - "Board resolutions"
        - "Authorized signatory list"
        - "Beneficial ownership disclosure"
    verification-levels:
      basic: "Document verification"
      enhanced: "Document + identity verification"
      comprehensive: "Full background check"

# Regulatory frameworks
regulatory-frameworks:
  mifid-ii:
    framework-name: "Markets in Financial Instruments Directive II"
    jurisdiction: "European Union"
    requirements:
      - "Best execution reporting"
      - "Transaction reporting"
      - "Client categorization"
      - "Suitability assessment"
    compliance-checks:
      - "Pre-trade transparency"
      - "Post-trade transparency"
      - "Investor protection"
      - "Market structure requirements"
      
  dodd-frank:
    framework-name: "Dodd-Frank Wall Street Reform Act"
    jurisdiction: "United States"
    requirements:
      - "Swap dealer registration"
      - "Central clearing requirements"
      - "Margin requirements"
      - "Trade reporting"
    compliance-checks:
      - "Systemically important designation"
      - "Capital requirements"
      - "Risk management standards"
      - "Proprietary trading restrictions"
      
  basel-iii:
    framework-name: "Basel III International Regulatory Framework"
    jurisdiction: "Global"
    requirements:
      - "Capital adequacy ratios"
      - "Liquidity coverage ratio"
      - "Net stable funding ratio"
      - "Leverage ratio"
    compliance-checks:
      - "Risk-weighted assets calculation"
      - "Stress testing"
      - "Systemic risk assessment"
      - "Counterparty credit risk"

# Compliance monitoring
monitoring-capabilities:
  real-time-screening:
    description: "Real-time compliance screening during trade processing"
    capabilities:
      - "Instant sanctions screening"
      - "Real-time risk assessment"
      - "Automated compliance checking"
      - "Exception flagging"
    performance-targets:
      screening-time: "< 500ms"
      accuracy-rate: "99.95%"
      false-positive-rate: "< 2%"
      
  batch-processing:
    description: "Batch compliance processing for periodic reviews"
    capabilities:
      - "Portfolio-level screening"
      - "Historical transaction analysis"
      - "Compliance reporting"
      - "Audit trail generation"
    processing-schedules:
      daily: "End-of-day processing"
      weekly: "Weekly compliance review"
      monthly: "Monthly audit report"
      
  exception-handling:
    description: "Handling of compliance exceptions and violations"
    exception-types:
      - "Sanctions match"
      - "High-risk country exposure"
      - "Suspicious activity detection"
      - "Regulatory breach"
    escalation-procedures:
      level-1: "Automated blocking"
      level-2: "Compliance officer review"
      level-3: "Senior management escalation"
      level-4: "Regulatory notification"

# Performance metrics
performance-metrics:
  compliance-effectiveness:
    violation-detection-rate: 99.9
    false-positive-rate: 1.5
    processing-time: "< 1000ms"
    system-availability: 99.99
    
  regulatory-compliance:
    audit-pass-rate: 100
    regulatory-findings: 0
    compliance-score: 95
    remediation-time: "< 24 hours"
    
  operational-efficiency:
    automation-rate: 95
    manual-review-rate: 5
    exception-resolution-time: "< 4 hours"
    compliance-cost-per-transaction: 0.05
