# APEX Customer Processing Contexts Configuration
# External data source configuration for customer processing contexts
# Replaces hardcoded Map.of context creation from FluentRuleBuilderExample

metadata:
  name: "Customer Processing Contexts Configuration"
  version: "1.0.0"
  description: "Data-driven customer processing contexts configuration for fluent rule builder processing"
  type: "external-data-config"
  author: "apex.demo.team@company.com"
  created-date: "2024-12-24"
  tags: ["apex-demo", "evaluation", "fluent-rule-builder", "customer-processing-contexts"]

# Customer processing contexts configuration by context type
data:
  vip-customer-contexts:
    context-type: "vip-customer-contexts"
    context-name: "VIP Customer Processing Contexts"
    description: "Processing contexts for VIP customer scenarios"
    context-characteristics:
      customer-tier: "VIP"
      processing-priority: "HIGH"
      validation-level: "ENHANCED"
    processing-contexts:
      vip-high-value-us-context:
        context-id: "VIP_HIGH_VALUE_US"
        context-name: "VIP High Value US Context"
        context-description: "VIP customer with high-value transaction in US region"
        customer-data:
          customer-type: "VIP"
          customer-tier: "PREMIUM_VIP"
          account-age: 8
          risk-profile: "LOW"
        transaction-data:
          transaction-amount: 250000.0
          transaction-currency: "USD"
          transaction-type: "HIGH_VALUE"
          value-category: "LARGE"
        regional-data:
          region: "US"
          regulatory-framework: "US_COMPLIANCE"
          compliance-level: "ENHANCED"
          jurisdiction: "FEDERAL"
        processing-expectations:
          approval-path: "VIP_HIGH_VALUE"
          validation-requirements: ["ENHANCED_KYC", "AML_SCREENING", "REGULATORY_CHECK"]
          processing-time: "EXPEDITED"
          manual-review: false
        audit-requirements:
          - "Log VIP high-value processing"
          - "Track premium customer handling"
          
      vip-medium-value-eu-context:
        context-id: "VIP_MEDIUM_VALUE_EU"
        context-name: "VIP Medium Value EU Context"
        context-description: "VIP customer with medium-value transaction in EU region"
        customer-data:
          customer-type: "VIP"
          customer-tier: "STANDARD_VIP"
          account-age: 5
          risk-profile: "LOW"
        transaction-data:
          transaction-amount: 150000.0
          transaction-currency: "EUR"
          transaction-type: "MEDIUM_VALUE"
          value-category: "MEDIUM"
        regional-data:
          region: "EU"
          regulatory-framework: "EU_COMPLIANCE"
          compliance-level: "GDPR_ENHANCED"
          jurisdiction: "EUROPEAN"
        processing-expectations:
          approval-path: "VIP_MEDIUM_VALUE"
          validation-requirements: ["GDPR_COMPLIANCE", "EU_AML", "MIFID_CHECK"]
          processing-time: "STANDARD"
          manual-review: false
        audit-requirements:
          - "Log VIP medium-value processing"
          - "Track EU compliance handling"
          
      vip-cross-border-context:
        context-id: "VIP_CROSS_BORDER"
        context-name: "VIP Cross-Border Context"
        context-description: "VIP customer with cross-border transaction"
        customer-data:
          customer-type: "VIP"
          customer-tier: "GLOBAL_VIP"
          account-age: 12
          risk-profile: "VERY_LOW"
        transaction-data:
          transaction-amount: 500000.0
          transaction-currency: "USD"
          transaction-type: "CROSS_BORDER"
          value-category: "VERY_LARGE"
        regional-data:
          region: "MULTI_REGION"
          regulatory-framework: "GLOBAL_COMPLIANCE"
          compliance-level: "COMPREHENSIVE"
          jurisdiction: "INTERNATIONAL"
        processing-expectations:
          approval-path: "VIP_CROSS_BORDER"
          validation-requirements: ["GLOBAL_KYC", "CROSS_BORDER_AML", "FATCA_CHECK", "CRS_REPORTING"]
          processing-time: "PRIORITY"
          manual-review: true
        audit-requirements:
          - "Log VIP cross-border processing"
          - "Track international compliance"
    context-settings:
      context-caching: true
      dynamic-loading: true
      validation-optimization: true
    
  standard-customer-contexts:
    context-type: "standard-customer-contexts"
    context-name: "Standard Customer Processing Contexts"
    description: "Processing contexts for standard customer scenarios"
    context-characteristics:
      customer-tier: "STANDARD"
      processing-priority: "NORMAL"
      validation-level: "STANDARD"
    processing-contexts:
      standard-medium-value-eu-context:
        context-id: "STANDARD_MEDIUM_VALUE_EU"
        context-name: "Standard Medium Value EU Context"
        context-description: "Standard customer with medium-value transaction in EU region"
        customer-data:
          customer-type: "STANDARD"
          customer-tier: "REGULAR"
          account-age: 3
          risk-profile: "MEDIUM"
        transaction-data:
          transaction-amount: 75000.0
          transaction-currency: "EUR"
          transaction-type: "MEDIUM_VALUE"
          value-category: "MEDIUM"
        regional-data:
          region: "EU"
          regulatory-framework: "EU_STANDARD"
          compliance-level: "GDPR_STANDARD"
          jurisdiction: "EUROPEAN"
        processing-expectations:
          approval-path: "STANDARD_MEDIUM_VALUE"
          validation-requirements: ["STANDARD_KYC", "EU_AML", "GDPR_BASIC"]
          processing-time: "STANDARD"
          manual-review: false
        audit-requirements:
          - "Log standard medium-value processing"
          - "Track standard customer handling"
          
      standard-low-value-us-context:
        context-id: "STANDARD_LOW_VALUE_US"
        context-name: "Standard Low Value US Context"
        context-description: "Standard customer with low-value transaction in US region"
        customer-data:
          customer-type: "STANDARD"
          customer-tier: "BASIC"
          account-age: 2
          risk-profile: "MEDIUM"
        transaction-data:
          transaction-amount: 25000.0
          transaction-currency: "USD"
          transaction-type: "LOW_VALUE"
          value-category: "SMALL"
        regional-data:
          region: "US"
          regulatory-framework: "US_STANDARD"
          compliance-level: "BASIC"
          jurisdiction: "STATE"
        processing-expectations:
          approval-path: "STANDARD_LOW_VALUE"
          validation-requirements: ["BASIC_KYC", "STANDARD_AML"]
          processing-time: "BATCH"
          manual-review: false
        audit-requirements:
          - "Log standard low-value processing"
          - "Track routine processing"
    context-settings:
      context-caching: true
      batch-processing: true
      standard-optimization: true
    
  premium-customer-contexts:
    context-type: "premium-customer-contexts"
    context-name: "Premium Customer Processing Contexts"
    description: "Processing contexts for premium customer scenarios"
    context-characteristics:
      customer-tier: "PREMIUM"
      processing-priority: "HIGH"
      validation-level: "ENHANCED"
    processing-contexts:
      premium-high-value-asia-context:
        context-id: "PREMIUM_HIGH_VALUE_ASIA"
        context-name: "Premium High Value Asia Context"
        context-description: "Premium customer with high-value transaction in Asia region"
        customer-data:
          customer-type: "PREMIUM"
          customer-tier: "PREMIUM_PLUS"
          account-age: 1
          risk-profile: "MEDIUM_HIGH"
        transaction-data:
          transaction-amount: 150000.0
          transaction-currency: "JPY"
          transaction-type: "HIGH_VALUE"
          value-category: "LARGE"
        regional-data:
          region: "ASIA"
          regulatory-framework: "ASIA_PACIFIC"
          compliance-level: "REGIONAL_ENHANCED"
          jurisdiction: "NATIONAL"
        processing-expectations:
          approval-path: "PREMIUM_HIGH_VALUE"
          validation-requirements: ["ENHANCED_KYC", "ASIA_AML", "REGIONAL_COMPLIANCE"]
          processing-time: "EXPEDITED"
          manual-review: true
        risk-assessment:
          risk-score: 85
          risk-category: "ELEVATED"
          risk-factors: ["NEW_ACCOUNT", "HIGH_VALUE", "REGIONAL_COMPLEXITY"]
        audit-requirements:
          - "Log premium high-value processing"
          - "Track elevated risk handling"
          
      premium-complex-multi-region-context:
        context-id: "PREMIUM_COMPLEX_MULTI_REGION"
        context-name: "Premium Complex Multi-Region Context"
        context-description: "Premium customer with complex multi-region transaction"
        customer-data:
          customer-type: "PREMIUM"
          customer-tier: "PREMIUM_ELITE"
          account-age: 6
          risk-profile: "MEDIUM"
        transaction-data:
          transaction-amount: 300000.0
          transaction-currency: "USD"
          transaction-type: "COMPLEX_MULTI_REGION"
          value-category: "VERY_LARGE"
        regional-data:
          region: "MULTI_REGION"
          regulatory-framework: "GLOBAL_PREMIUM"
          compliance-level: "COMPREHENSIVE"
          jurisdiction: "MULTI_JURISDICTIONAL"
        processing-expectations:
          approval-path: "PREMIUM_COMPLEX"
          validation-requirements: ["COMPREHENSIVE_KYC", "GLOBAL_AML", "MULTI_REGION_COMPLIANCE", "PREMIUM_SCREENING"]
          processing-time: "PRIORITY"
          manual-review: true
        risk-assessment:
          risk-score: 75
          risk-category: "MODERATE_HIGH"
          risk-factors: ["MULTI_REGION", "COMPLEX_STRUCTURE", "HIGH_VALUE"]
        audit-requirements:
          - "Log premium complex processing"
          - "Track multi-region compliance"
    context-settings:
      context-caching: false
      real-time-processing: true
      premium-optimization: true
    
  complex-processing-contexts:
    context-type: "complex-processing-contexts"
    context-name: "Complex Processing Contexts"
    description: "Processing contexts for complex multi-branch scenarios"
    context-characteristics:
      customer-tier: "MIXED"
      processing-priority: "VARIABLE"
      validation-level: "ADAPTIVE"
    processing-contexts:
      multi-branch-decision-context:
        context-id: "MULTI_BRANCH_DECISION"
        context-name: "Multi-Branch Decision Context"
        context-description: "Complex context requiring multi-branch decision processing"
        customer-data:
          customer-type: "VARIABLE"
          customer-tier: "ADAPTIVE"
          account-age: "VARIABLE"
          risk-profile: "CALCULATED"
        transaction-data:
          transaction-amount: "VARIABLE"
          transaction-currency: "MULTI_CURRENCY"
          transaction-type: "COMPLEX"
          value-category: "CALCULATED"
        regional-data:
          region: "ADAPTIVE"
          regulatory-framework: "CONTEXT_DEPENDENT"
          compliance-level: "CALCULATED"
          jurisdiction: "DETERMINED_BY_RULES"
        processing-expectations:
          approval-path: "MULTI_BRANCH"
          validation-requirements: ["CONTEXT_DEPENDENT"]
          processing-time: "CALCULATED"
          manual-review: "RULE_BASED"
        decision-factors:
          - "Customer tier assessment"
          - "Transaction value analysis"
          - "Regional compliance requirements"
          - "Risk score evaluation"
        audit-requirements:
          - "Log complex multi-branch processing"
          - "Track adaptive decision making"
    context-settings:
      context-caching: false
      adaptive-processing: true
      complex-optimization: true
    
  default:
    context-type: "default"
    context-name: "Default Customer Processing Contexts"
    description: "Default customer processing context"
    processing-contexts:
      default-context:
        context-id: "DEFAULT"
        context-name: "Default Context"
        customer-data:
          customer-type: "STANDARD"
        transaction-data:
          transaction-amount: 10000.0
        regional-data:
          region: "US"
    context-settings:
      context-caching: true

# Context generation patterns
generation-patterns:
  customer-tier-pattern:
    pattern-name: "Customer Tier Pattern"
    description: "Generate contexts based on customer tiers"
    customer-tiers: ["VIP", "PREMIUM", "STANDARD", "BASIC"]
    
  transaction-value-pattern:
    pattern-name: "Transaction Value Pattern"
    description: "Generate contexts based on transaction values"
    value-ranges: ["HIGH_VALUE", "MEDIUM_VALUE", "LOW_VALUE", "MICRO_VALUE"]
    
  regional-compliance-pattern:
    pattern-name: "Regional Compliance Pattern"
    description: "Generate contexts based on regional requirements"
    regions: ["US", "EU", "ASIA", "AMERICAS", "EMEA", "MULTI_REGION"]

# Quality assurance
quality-assurance:
  context-accuracy:
    - "Processing contexts must be realistic"
    - "Customer data must be consistent"
    - "Transaction data must be valid"
    - "Regional data must be accurate"
    
  data-integrity:
    - "Context data must be complete"
    - "Customer characteristics must be consistent"
    - "Transaction amounts must be reasonable"
    - "Regional compliance must be appropriate"
    
  processing-requirements:
    - "Context generation must be efficient"
    - "Data validation must be comprehensive"
    - "Context caching must be effective"
    - "Processing optimization must be maintained"
