# Financial Demo - Configuration
# This file contains configuration settings for the Financial demonstration
# Business users can modify these settings to customize demo behavior

metadata:
  version: "1.0"
  description: "Configuration settings for Financial demonstration"
  lastUpdated: "2025-07-28"
  author: "APEX Demo Team"

# Demo execution configuration
demo:
  name: "Financial Demo"
  description: "Consolidated financial services with multiple execution modes"
  version: "2.0"
  modes:
    - name: "TRADING"
      description: "Basic financial trading operations and validation"
      enabled: true
    - name: "SERVICES"
      description: "Comprehensive OTC derivatives and financial services"
      enabled: true
    - name: "VALIDATION"
      description: "Financial validation rule sets and compliance"
      enabled: true

# Trading configuration
trading:
  # Trade validation settings
  validation:
    minTradeAmount: 1000.0
    maxTradeAmount: 100000000.0
    largeTradeThreshold: 10000000.0
    reportingThreshold: 1000000.0
    
  # Supported instruments
  instruments:
    - type: "EQUITY"
      minAmount: 1000.0
      maxAmount: 50000000.0
      currencies: ["USD", "EUR", "GBP"]
      
    - type: "BOND"
      minAmount: 10000.0
      maxAmount: 100000000.0
      currencies: ["USD", "EUR", "GBP", "CHF"]
      
    - type: "COMMODITY_SWAP"
      minAmount: 1000000.0
      maxAmount: 100000000.0
      currencies: ["USD", "EUR"]
      
    - type: "FX_SWAP"
      minAmount: 50000.0
      maxAmount: 25000000.0
      currencies: ["USD", "EUR", "GBP", "JPY", "CHF"]
      
    - type: "DERIVATIVE"
      minAmount: 500000.0
      maxAmount: 100000000.0
      currencies: ["USD", "EUR", "GBP"]

# Risk management configuration
riskManagement:
  # Credit limits by counterparty rating
  creditLimits:
    "AAA": 200000000.0
    "AA+": 150000000.0
    "AA": 125000000.0
    "AA-": 100000000.0
    "A+": 75000000.0
    "A": 50000000.0
    "A-": 40000000.0
    "BBB+": 30000000.0
    "BBB": 25000000.0
    "BBB-": 20000000.0
    
  # Risk rating thresholds
  riskRatings:
    low:
      maxAmount: 10000000.0
      minCounterpartyRating: "A-"
      
    medium:
      maxAmount: 25000000.0
      minCounterpartyRating: "BBB+"
      
    high:
      maxAmount: 50000000.0
      minCounterpartyRating: "BBB"
      
  # Market volatility limits
  volatilityLimits:
    low: 0.10
    medium: 0.20
    high: 0.30
    extreme: 0.50

# Compliance configuration
compliance:
  # Regulatory reporting thresholds
  reporting:
    largeExposureThreshold: 25000000.0
    crossBorderThreshold: 5000000.0
    derivativeReportingThreshold: 50000.0
    
  # Jurisdiction-specific rules
  jurisdictions:
    US:
      maxTradeAmount: 100000000.0
      reportingRequired: true
      regulatoryRegime: "DODD_FRANK"
      
    EU:
      maxTradeAmount: 50000000.0
      reportingRequired: true
      regulatoryRegime: "MIFID_II"
      mifidCompliant: true
      
    GB:
      maxTradeAmount: 75000000.0
      reportingRequired: true
      regulatoryRegime: "FCA"
      
    JP:
      maxTradeAmount: 60000000.0
      reportingRequired: true
      regulatoryRegime: "JFSA"
      
  # Trading desk authorizations
  tradingDesks:
    FIXED_INCOME:
      authorizedInstruments: ["BOND", "DERIVATIVE"]
      maxTradeAmount: 100000000.0
      
    EQUITIES:
      authorizedInstruments: ["EQUITY", "DERIVATIVE"]
      maxTradeAmount: 50000000.0
      
    FX:
      authorizedInstruments: ["FX_SWAP", "DERIVATIVE"]
      maxTradeAmount: 25000000.0
      
    COMMODITIES:
      authorizedInstruments: ["COMMODITY_SWAP", "DERIVATIVE"]
      maxTradeAmount: 100000000.0
      
    DERIVATIVES:
      authorizedInstruments: ["DERIVATIVE", "COMMODITY_SWAP", "FX_SWAP"]
      maxTradeAmount: 100000000.0

# OTC derivatives configuration
otcDerivatives:
  # Commodity reference data
  commodities:
    CRUDE_OIL:
      name: "Crude Oil"
      currency: "USD"
      minNotional: 1000000.0
      maxNotional: 100000000.0
      
    NATURAL_GAS:
      name: "Natural Gas"
      currency: "USD"
      minNotional: 500000.0
      maxNotional: 50000000.0
      
    GOLD:
      name: "Gold"
      currency: "USD"
      minNotional: 100000.0
      maxNotional: 25000000.0
      
  # Swap validation rules
  swapValidation:
    minNotional: 1000000.0
    maxNotional: 100000000.0
    maxMaturityYears: 10
    requiredFields: ["commodity", "notional", "maturityDate"]

# Currency configuration
currencies:
  # Exchange rate validation
  exchangeRates:
    validationEnabled: true
    minRate: 0.01
    maxRate: 1000.0
    maxDailyVolatility: 0.10
    
  # Supported currency pairs
  currencyPairs:
    - base: "USD"
      quote: "EUR"
      active: true
      
    - base: "USD"
      quote: "GBP"
      active: true
      
    - base: "USD"
      quote: "JPY"
      active: true
      
    - base: "EUR"
      quote: "GBP"
      active: true
      
    - base: "EUR"
      quote: "CHF"
      active: true

# Performance configuration
performance:
  # Portfolio risk metrics
  portfolioRisk:
    maxVaR95Percent: 0.02  # 2% of portfolio value
    maxStressTestLoss: 0.05  # 5% of portfolio value
    maxConcentrationRisk: 0.15  # 15% in single position
    
  # Processing limits
  processing:
    maxConcurrentTrades: 100
    maxBatchSize: 1000
    timeoutSeconds: 30
    
  # Metrics collection
  metrics:
    enabled: true
    collectTradeMetrics: true
    collectRiskMetrics: true
    collectComplianceMetrics: true
    reportingIntervalSeconds: 60

# Error handling configuration
errorHandling:
  # Trade processing errors
  tradeProcessing:
    retryOnFailure: true
    maxRetries: 3
    retryDelayMs: 1000
    fallbackToManualReview: true
    
  # Validation errors
  validation:
    stopOnFirstError: false
    collectAllErrors: true
    includeFieldNames: true
    includeErrorCodes: true
    
  # Compliance errors
  compliance:
    escalateToCompliance: true
    requireManagerApproval: true
    logAllViolations: true

# Business rules configuration
businessRules:
  # Trade validation rules
  tradeValidation:
    enabled: true
    rules:
      - name: "amount-validation"
        expression: "#amount != null && #amount > 0 && #amount <= 100000000"
        errorCode: "INVALID_AMOUNT"
        severity: "ERROR"
        
      - name: "currency-validation"
        expression: "#currency != null && #currency in {'USD', 'EUR', 'GBP', 'JPY', 'CHF', 'CAD', 'AUD'}"
        errorCode: "INVALID_CURRENCY"
        severity: "ERROR"
        
      - name: "counterparty-validation"
        expression: "#counterparty != null && #counterparty.length() > 0"
        errorCode: "MISSING_COUNTERPARTY"
        severity: "ERROR"
        
      - name: "large-trade-approval"
        expression: "#amount < 10000000 || #status == 'APPROVED'"
        errorCode: "LARGE_TRADE_REQUIRES_APPROVAL"
        severity: "WARNING"
        
  # Risk management rules
  riskManagement:
    enabled: true
    rules:
      - name: "credit-limit-check"
        expression: "#amount <= #counterpartyCreditLimit"
        errorCode: "CREDIT_LIMIT_EXCEEDED"
        severity: "ERROR"
        
      - name: "volatility-check"
        expression: "#marketVolatility <= 0.20 || #amount <= 3000000"
        errorCode: "HIGH_VOLATILITY_LIMIT"
        severity: "WARNING"
        
  # Compliance rules
  compliance:
    enabled: true
    rules:
      - name: "reporting-threshold"
        expression: "#amount >= 1000000"
        errorCode: "REPORTING_REQUIRED"
        severity: "INFO"
        
      - name: "cross-border-compliance"
        expression: "#clientRegion == 'EU' ? #amount <= 5000000 : true"
        errorCode: "CROSS_BORDER_LIMIT"
        severity: "WARNING"

# Test scenarios configuration
testScenarios:
  # Trading mode scenarios
  tradingMode:
    enabled: true
    description: "Basic trading operations"
    expectedTrades: 4
    expectedValidTrades: 4
    
  # Services mode scenarios
  servicesMode:
    enabled: true
    description: "OTC derivatives and services"
    expectedTrades: 6
    expectedComplexTrades: 3
    
  # Validation mode scenarios
  validationMode:
    enabled: true
    description: "Validation rule sets"
    expectedRules: 15
    expectedCategories: 3

# Integration configuration
integration:
  # External data sources
  dataSources:
    enabled: false
    tradeDataSource: "demo-data/financial/trades.yaml"
    configurationSource: "demo-data/financial/config.yaml"
    
  # Market data integration
  marketData:
    enabled: false
    priceSource: "bloomberg"
    rateSource: "reuters"
    updateFrequencySeconds: 60

# Output configuration
output:
  # Console output settings
  console:
    enabled: true
    showProgress: true
    showDetails: true
    showTimings: true
    showRiskMetrics: true
    colorOutput: true
    
  # Report generation
  reports:
    enabled: true
    outputDirectory: "demo-output/financial"
    generateTradeReport: true
    generateRiskReport: true
    generateComplianceReport: true
    reportFormat: "YAML"
