# Comprehensive Financial Settlement Demo Configuration
# Real APEX Services Integration for Financial Settlement Processing

# Configuration Metadata
metadata:
  name: "comprehensive-financial-settlement-demo"
  version: "1.0"
  description: "Comprehensive financial settlement processing using real APEX services"
  category: "enrichment"
  complexity: "advanced"
  author: "APEX Demo Team"

# Comprehensive Financial Settlement Enrichments
enrichments:
  - id: "settlement-validation"
    name: "settlement-validation"
    type: "field-enrichment"
    description: "Comprehensive settlement validation using real APEX processing"
    condition: "#settlementAmount != null"
    field-mappings:
      - source-field: "settlementAmount"
        target-field: "settlementStatus"
        expression: "#settlementAmount > 1000000 ? 'HIGH_VALUE' : 'STANDARD'"
      - source-field: "settlementDate"
        target-field: "settlementUrgency"
        expression: "#settlementDate != null ? 'NORMAL' : 'URGENT'"
      - source-field: "counterparty"
        target-field: "counterpartyRisk"
        expression: "#counterparty == 'BANK_A' ? 'LOW' : 'MEDIUM'"

  - id: "financial-compliance-check"
    name: "financial-compliance-check"
    type: "field-enrichment"
    description: "Financial compliance checking using real APEX services"
    condition: "#transactionType != null"
    field-mappings:
      - source-field: "transactionType"
        target-field: "complianceLevel"
        expression: "#transactionType == 'WIRE' ? 'ENHANCED' : 'STANDARD'"
      - source-field: "jurisdiction"
        target-field: "regulatoryFramework"
        expression: "#jurisdiction == 'US' ? 'US_REGULATIONS' : 'INTERNATIONAL'"
      - source-field: "clientType"
        target-field: "kycRequirement"
        expression: "#clientType == 'INSTITUTIONAL' ? 'ENHANCED_KYC' : 'STANDARD_KYC'"

  - id: "settlement-routing"
    name: "settlement-routing"
    type: "field-enrichment"
    description: "Settlement routing and processing using real APEX services"
    condition: "#currency != null"
    field-mappings:
      - source-field: "currency"
        target-field: "settlementNetwork"
        expression: "#currency == 'USD' ? 'FEDWIRE' : (#currency == 'EUR' ? 'TARGET2' : 'SWIFT')"
      - source-field: "settlementAmount"
        target-field: "processingPriority"
        expression: "#settlementAmount > 10000000 ? 'HIGH' : 'NORMAL'"
      - source-field: "settlementDate"
        target-field: "cutoffTime"
        expression: "#settlementDate != null ? '16:00' : '15:00'"

# Rule Groups for Settlement Processing
rule-groups:
  - id: "comprehensive-settlement-workflow"
    name: "comprehensive-settlement-workflow"
    description: "Comprehensive settlement processing workflow"
    enrichment-sequence:
      - "settlement-validation"
      - "financial-compliance-check"
      - "settlement-routing"
    execution-mode: "sequential"
    error-handling: "continue-on-error"

# External data sources removed for compatibility

# Processing Configuration
processing-config:
  batch-size: 1000
  timeout-seconds: 300
  retry-attempts: 3
  parallel-processing: true
  audit-logging: true
