# Custody Auto-Repair Demo Configuration
# Real APEX Services Integration for Custody Auto-Repair Processing

# Configuration Metadata
metadata:
  name: "custody-auto-repair-demo"
  version: "1.0"
  description: "Custody auto-repair processing using real APEX services"
  category: "enrichment"
  complexity: "advanced"
  author: "APEX Demo Team"

# Custody Auto-Repair Enrichments
enrichments:
  - id: "custody-validation"
    name: "custody-validation"
    type: "field-enrichment"
    description: "Custody validation using real APEX processing"
    condition: "#custodyAccount != null"
    field-mappings:
      - source-field: "custodyAccount"
        target-field: "accountStatus"
        expression: "#custodyAccount != null ? 'ACTIVE' : 'INACTIVE'"
      - source-field: "securityType"
        target-field: "custodyType"
        expression: "#securityType == 'EQUITY' ? 'STOCK_CUSTODY' : 'BOND_CUSTODY'"
      - source-field: "quantity"
        target-field: "positionSize"
        expression: "#quantity > 10000 ? 'LARGE' : 'STANDARD'"

  - id: "auto-repair-processing"
    name: "auto-repair-processing"
    type: "field-enrichment"
    description: "Auto-repair processing using real APEX services"
    condition: "#repairType != null"
    field-mappings:
      - source-field: "repairType"
        target-field: "repairPriority"
        expression: "#repairType == 'CRITICAL' ? 'HIGH' : 'NORMAL'"
      - source-field: "errorCode"
        target-field: "repairAction"
        expression: "#errorCode == 'MISMATCH' ? 'RECONCILE' : 'INVESTIGATE'"
      - source-field: "custodian"
        target-field: "repairMethod"
        expression: "#custodian == 'BANK_A' ? 'AUTOMATED' : 'MANUAL'"

  - id: "settlement-repair"
    name: "settlement-repair"
    type: "field-enrichment"
    description: "Settlement repair processing using real APEX services"
    condition: "#settlementStatus != null"
    field-mappings:
      - source-field: "settlementStatus"
        target-field: "repairRequired"
        expression: "#settlementStatus == 'FAILED' ? 'true' : 'false'"
      - source-field: "failureReason"
        target-field: "repairStrategy"
        expression: "#failureReason == 'INSUFFICIENT_FUNDS' ? 'FUNDING_REPAIR' : 'TECHNICAL_REPAIR'"
      - source-field: "tradeDate"
        target-field: "repairUrgency"
        expression: "#tradeDate != null ? 'NORMAL' : 'URGENT'"

# Rule Groups for Auto-Repair Processing
rule-groups:
  - id: "custody-auto-repair-workflow"
    name: "custody-auto-repair-workflow"
    description: "Custody auto-repair processing workflow"
    enrichment-sequence:
      - "custody-validation"
      - "auto-repair-processing"
      - "settlement-repair"
    execution-mode: "sequential"
    error-handling: "continue-on-error"

# External data sources removed for compatibility

# Processing Configuration
processing-config:
  batch-size: 500
  timeout-seconds: 180
  retry-attempts: 3
  parallel-processing: true
  audit-logging: true
