# APEX Trade Samples Simple Configuration
# External data source configuration for simple trade samples
# Replaces hardcoded trade sample creation from IntegratedTradeValidatorDemo

type: "external-data-config"
name: "trade-samples-simple-config"
description: "Data-driven simple trade samples configuration for integrated trade validation"

# Trade samples configuration by sample type
data:
  equity-trade-sample:
    sample-id: "SAMPLE001"
    sample-type: "equity-trade-sample"
    description: "Valid equity trade sample for basic validation"
    trade-data:
      tradeId: "EQ001"
      instrumentType: "Equity"
      instrumentId: "AAPL.US"
      ticker: "AAPL"
      exchange: "NASDAQ"
      quantity: 100
      price: 150.00
      amount: 15000.00
      currency: "USD"
      tradeDate: "2025-08-30"
      settlementDate: "2025-09-01"
      counterparty: "Goldman Sachs"
      category: "InstrumentType"
    expected-validation-result: "PASS"
    validation-notes: "Standard equity trade with all required fields"
    
  bond-trade-sample:
    sample-id: "SAMPLE002"
    sample-type: "bond-trade-sample"
    description: "Valid bond trade sample for basic validation"
    trade-data:
      tradeId: "BD001"
      instrumentType: "Bond"
      instrumentId: "US10Y.BOND"
      maturityDate: "2035-08-30"
      couponRate: 3.5
      quantity: 10
      price: 98.50
      amount: 9850.00
      currency: "USD"
      tradeDate: "2025-08-30"
      settlementDate: "2025-08-31"
      counterparty: "JPMorgan"
      category: "InstrumentType"
    expected-validation-result: "PASS"
    validation-notes: "Standard bond trade with all required fields"
    
  option-trade-sample:
    sample-id: "SAMPLE003"
    sample-type: "option-trade-sample"
    description: "Valid option trade sample for basic validation"
    trade-data:
      tradeId: "OP001"
      instrumentType: "Option"
      instrumentId: "AAPL.OPT.C.160.20250930"
      underlyingAsset: "AAPL"
      optionType: "Call"
      strikePrice: 160.00
      expirationDate: "2025-09-30"
      quantity: 5
      price: 5.00
      amount: 2500.00
      currency: "USD"
      tradeDate: "2025-08-30"
      settlementDate: "2025-08-31"
      counterparty: "Morgan Stanley"
      category: "InstrumentType"
    expected-validation-result: "PASS"
    validation-notes: "Standard option trade with all required fields"
    
  future-trade-sample:
    sample-id: "SAMPLE004"
    sample-type: "future-trade-sample"
    description: "Valid future trade sample for basic validation"
    trade-data:
      tradeId: "FT001"
      instrumentType: "Future"
      instrumentId: "ES.FUT.202509"
      underlyingAsset: "S&P 500"
      futureType: "Financial"
      expirationDate: "2025-09-15"
      quantity: 2
      price: 4500.00
      amount: 9000.00
      currency: "USD"
      tradeDate: "2025-08-30"
      settlementDate: "2025-08-30"
      counterparty: "CME Group"
      category: "InstrumentType"
    expected-validation-result: "PASS"
    validation-notes: "Standard future trade with all required fields"
    
  invalid-equity-sample:
    sample-id: "SAMPLE005"
    sample-type: "invalid-equity-sample"
    description: "Invalid equity trade sample for negative testing"
    trade-data:
      tradeId: "EQ002"
      instrumentType: "InvalidType"  # Invalid instrument type
      instrumentId: "INVALID.STOCK"
      ticker: "INVALID"
      exchange: "UNKNOWN"
      quantity: 100
      price: 50.00
      amount: 5000.00
      currency: "USD"
      tradeDate: "2025-08-30"
      settlementDate: "2025-09-01"
      counterparty: "Unknown Bank"
      category: "InstrumentType"
    expected-validation-result: "FAIL"
    expected-errors: ["Invalid instrument type"]
    validation-notes: "Trade with invalid instrument type for negative testing"
    
  incomplete-trade-sample:
    sample-id: "SAMPLE006"
    sample-type: "incomplete-trade-sample"
    description: "Incomplete trade sample for negative testing"
    trade-data:
      tradeId: "INC001"
      # Missing instrumentType
      instrumentId: "MISSING.DATA"
      quantity: 100
      price: 100.00
      amount: 10000.00
      currency: "USD"
      tradeDate: "2025-08-30"
      # Missing settlementDate
      counterparty: "Test Bank"
      category: "InstrumentType"
    expected-validation-result: "FAIL"
    expected-errors: ["Missing instrument type", "Missing settlement date"]
    validation-notes: "Trade with missing required fields for negative testing"
    
  generic-trade-sample:
    sample-id: "SAMPLE007"
    sample-type: "generic-trade-sample"
    description: "Generic trade sample for comprehensive validation"
    trade-data:
      tradeId: "GEN001"
      instrumentType: "ETF"
      instrumentId: "SPY.ETF"
      ticker: "SPY"
      exchange: "NYSE"
      quantity: 50
      price: 400.00
      amount: 20000.00
      currency: "USD"
      tradeDate: "2025-08-30"
      settlementDate: "2025-09-01"
      counterparty: "Vanguard"
      category: "InstrumentType"
    expected-validation-result: "PASS"
    validation-notes: "Generic ETF trade for comprehensive validation testing"
    
  default:
    sample-id: "SAMPLE000"
    sample-type: "default"
    description: "Default trade sample"
    trade-data:
      tradeId: "DEFAULT001"
      instrumentType: "Unknown"
      instrumentId: "DEFAULT.INSTRUMENT"
      quantity: 1
      price: 1.00
      amount: 1.00
      currency: "USD"
      tradeDate: "2025-08-30"
      settlementDate: "2025-08-30"
      counterparty: "Default Counterparty"
      category: "Default"
    expected-validation-result: "UNKNOWN"
    validation-notes: "Default trade sample for fallback scenarios"

# Sample generation patterns
generation-patterns:
  equity-pattern:
    pattern-name: "Equity Trade Generation"
    description: "Pattern for generating equity trade samples"
    base-template: "equity-trade-sample"
    variable-fields:
      - "ticker"
      - "quantity"
      - "price"
      - "exchange"
    generation-rules:
      - "Ticker must be valid stock symbol"
      - "Quantity must be positive integer"
      - "Price must be positive decimal"
      - "Exchange must be recognized"
    
  bond-pattern:
    pattern-name: "Bond Trade Generation"
    description: "Pattern for generating bond trade samples"
    base-template: "bond-trade-sample"
    variable-fields:
      - "maturityDate"
      - "couponRate"
      - "quantity"
      - "price"
    generation-rules:
      - "Maturity date must be future date"
      - "Coupon rate must be positive"
      - "Quantity must be positive integer"
      - "Price must be between 0 and 200"
    
  derivative-pattern:
    pattern-name: "Derivative Trade Generation"
    description: "Pattern for generating derivative trade samples"
    base-template: "option-trade-sample"
    variable-fields:
      - "underlyingAsset"
      - "strikePrice"
      - "expirationDate"
      - "optionType"
    generation-rules:
      - "Underlying asset must be valid"
      - "Strike price must be positive"
      - "Expiration date must be future date"
      - "Option type must be Call or Put"

# Sample validation scenarios
validation-scenarios:
  positive-validation:
    scenario-name: "Positive Validation Scenarios"
    description: "Test cases that should pass validation"
    samples:
      - "equity-trade-sample"
      - "bond-trade-sample"
      - "option-trade-sample"
      - "future-trade-sample"
      - "generic-trade-sample"
    expected-results: "ALL_PASS"
    
  negative-validation:
    scenario-name: "Negative Validation Scenarios"
    description: "Test cases that should fail validation"
    samples:
      - "invalid-equity-sample"
      - "incomplete-trade-sample"
    expected-results: "ALL_FAIL"
    
  mixed-validation:
    scenario-name: "Mixed Validation Scenarios"
    description: "Mixed test cases with both pass and fail scenarios"
    samples:
      - "equity-trade-sample"
      - "invalid-equity-sample"
      - "bond-trade-sample"
      - "incomplete-trade-sample"
    expected-results: "MIXED"

# Performance test configurations
performance-configurations:
  bulk-sample-generation:
    configuration-name: "Bulk Sample Generation"
    description: "Generate large number of trade samples for performance testing"
    sample-count: 1000
    base-samples: ["equity-trade-sample", "bond-trade-sample"]
    variation-strategy: "random-field-variation"
    
  validation-performance:
    configuration-name: "Validation Performance Testing"
    description: "Test validation performance with various sample types"
    sample-types: ["equity-trade-sample", "bond-trade-sample", "option-trade-sample"]
    iterations: 100
    performance-targets:
      max-validation-time: "100ms"
      min-throughput: "1000 validations/second"
