# APEX Trade Validation Parameters Configuration
# External data source configuration for trade validation parameters
# Replaces hardcoded parameter logic from IntegratedTradeValidatorDemo

type: "external-data-config"
name: "trade-validation-parameters-config"
description: "Data-driven trade validation parameters configuration for integrated trade validation"

# Trade validation parameters configuration by parameter type
data:
  equity-parameters:
    parameter-id: "PARAM001"
    parameter-type: "equity-parameters"
    description: "Equity trade validation parameters"
    allowed-values:
      - "Equity"
    allowed-categories:
      - "InstrumentType"
    validation-rules:
      - "Instrument type must be Equity"
      - "Category must be InstrumentType"
    parameter-metadata:
      asset-class: "Equity"
      risk-category: "Medium"
      settlement-cycle: "T+2"
      market-hours: "9:30-16:00 EST"
    validation-settings:
      strict-validation: true
      case-sensitive: false
      allow-null-values: false
    
  bond-parameters:
    parameter-id: "PARAM002"
    parameter-type: "bond-parameters"
    description: "Bond trade validation parameters"
    allowed-values:
      - "Bond"
    allowed-categories:
      - "InstrumentType"
    validation-rules:
      - "Instrument type must be Bond"
      - "Category must be InstrumentType"
    parameter-metadata:
      asset-class: "Fixed Income"
      risk-category: "Low"
      settlement-cycle: "T+1"
      market-hours: "8:00-17:00 EST"
    validation-settings:
      strict-validation: true
      case-sensitive: false
      allow-null-values: false
    
  generic-parameters:
    parameter-id: "PARAM003"
    parameter-type: "generic-parameters"
    description: "Generic trade validation parameters"
    allowed-values:
      - "Equity"
      - "Bond"
      - "Option"
      - "Future"
      - "ETF"
    allowed-categories:
      - "InstrumentType"
      - "AssetClass"
      - "SecurityType"
    validation-rules:
      - "Instrument type must be in allowed list"
      - "Category must be recognized"
    parameter-metadata:
      asset-class: "Mixed"
      risk-category: "Variable"
      settlement-cycle: "Variable"
      market-hours: "Variable"
    validation-settings:
      strict-validation: false
      case-sensitive: false
      allow-null-values: true
    
  option-parameters:
    parameter-id: "PARAM004"
    parameter-type: "option-parameters"
    description: "Option trade validation parameters"
    allowed-values:
      - "Option"
      - "Call"
      - "Put"
    allowed-categories:
      - "InstrumentType"
      - "OptionType"
    validation-rules:
      - "Instrument type must be Option"
      - "Option type must be Call or Put"
    parameter-metadata:
      asset-class: "Derivatives"
      risk-category: "High"
      settlement-cycle: "T+1"
      market-hours: "9:30-16:00 EST"
    validation-settings:
      strict-validation: true
      case-sensitive: false
      allow-null-values: false
    
  future-parameters:
    parameter-id: "PARAM005"
    parameter-type: "future-parameters"
    description: "Future trade validation parameters"
    allowed-values:
      - "Future"
      - "Commodity"
      - "Financial"
    allowed-categories:
      - "InstrumentType"
      - "FutureType"
    validation-rules:
      - "Instrument type must be Future"
      - "Future type must be specified"
    parameter-metadata:
      asset-class: "Derivatives"
      risk-category: "High"
      settlement-cycle: "T+0"
      market-hours: "24/7"
    validation-settings:
      strict-validation: true
      case-sensitive: false
      allow-null-values: false
    
  default:
    parameter-id: "PARAM000"
    parameter-type: "default"
    description: "Default trade validation parameters"
    allowed-values:
      - "Unknown"
    allowed-categories:
      - "Default"
    validation-rules:
      - "Basic validation"
    parameter-metadata:
      asset-class: "Unknown"
      risk-category: "Unknown"
      settlement-cycle: "Unknown"
      market-hours: "Unknown"
    validation-settings:
      strict-validation: false
      case-sensitive: false
      allow-null-values: true

# Parameter validation patterns
validation-patterns:
  instrument-type-validation:
    pattern-name: "Instrument Type Validation"
    description: "Validate instrument type against allowed values"
    validation-logic:
      - "Check if instrument type is not null"
      - "Verify instrument type is in allowed values list"
      - "Validate case sensitivity settings"
      - "Apply strict validation if enabled"
    error-handling:
      - "Return validation error for null values"
      - "Return validation error for invalid types"
      - "Log validation warnings for edge cases"
    
  category-validation:
    pattern-name: "Category Validation"
    description: "Validate category against allowed categories"
    validation-logic:
      - "Check if category is not null"
      - "Verify category is in allowed categories list"
      - "Validate category consistency with instrument type"
      - "Apply business rule validation"
    error-handling:
      - "Return validation error for null categories"
      - "Return validation error for invalid categories"
      - "Log validation warnings for inconsistencies"
    
  parameter-consistency-validation:
    pattern-name: "Parameter Consistency Validation"
    description: "Validate consistency between parameters"
    validation-logic:
      - "Check parameter combinations"
      - "Validate business rule compliance"
      - "Verify metadata consistency"
      - "Apply cross-parameter validation"
    error-handling:
      - "Return validation error for inconsistent parameters"
      - "Return validation warning for edge cases"
      - "Log validation information for audit"

# Parameter groups
parameter-groups:
  equity-group:
    group-name: "Equity Parameter Group"
    description: "Parameters for equity trade validation"
    parameters: ["equity-parameters"]
    validation-order: ["instrument-type-validation", "category-validation"]
    
  fixed-income-group:
    group-name: "Fixed Income Parameter Group"
    description: "Parameters for fixed income trade validation"
    parameters: ["bond-parameters"]
    validation-order: ["instrument-type-validation", "category-validation"]
    
  derivatives-group:
    group-name: "Derivatives Parameter Group"
    description: "Parameters for derivatives trade validation"
    parameters: ["option-parameters", "future-parameters"]
    validation-order: ["instrument-type-validation", "category-validation", "parameter-consistency-validation"]
    
  comprehensive-group:
    group-name: "Comprehensive Parameter Group"
    description: "Parameters for comprehensive trade validation"
    parameters: ["generic-parameters"]
    validation-order: ["instrument-type-validation", "category-validation", "parameter-consistency-validation"]

# Performance optimization
performance-optimization:
  parameter-caching:
    cache-strategy: "LRU"
    cache-size: 1000
    cache-ttl: 3600
    cache-key-strategy: "parameter-type-hash"
    
  validation-optimization:
    parallel-validation: true
    validation-timeout: 5000
    batch-validation: true
    early-termination: true
    
  memory-management:
    max-parameter-sets: 100
    parameter-cleanup-interval: 1800
    memory-threshold: "128MB"

# Integration specifications
integration:
  parameter-sources:
    - "Configuration files"
    - "Database tables"
    - "External APIs"
    - "Runtime definitions"
    
  validation-frameworks:
    - "APEX Rules Engine"
    - "Spring Validation"
    - "Custom Validators"
    - "Bean Validation"
    
  output-formats:
    - "Validation results"
    - "Error messages"
    - "Validation reports"
    - "Audit logs"
