# APEX Product Validation Parameters Configuration
# External data source configuration for product validation parameters processing
# Replaces hardcoded product validation parameters from IntegratedProductValidatorDemo

metadata:
  name: "Product Validation Parameters Configuration"
  version: "1.0.0"
  description: "Data-driven product validation parameters configuration for integrated product validation processing"
  type: "external-data-config"
  author: "apex.demo.team@company.com"
  created-date: "2024-12-24"
  tags: ["apex-demo", "validation", "integrated-product", "product-validation-parameters"]

# Product validation parameters configuration by parameter type
data:
  price-range-parameters:
    parameter-type: "price-range-parameters"
    parameter-name: "Price Range Parameters"
    description: "Parameters for price-based product validation"
    parameter-characteristics:
      parameter-category: "PRICE_VALIDATION"
      validation-scope: "PRICE_RANGE"
      dynamic-updates: true
    validation-parameters:
      fixed-income-price-parameters:
        parameter-id: "FIXED_INCOME_PRICE_PARAMS"
        parameter-name: "Fixed Income Price Parameters"
        parameter-description: "Validation parameters for fixed income products"
        price-parameters:
          min-price: 100.0
          max-price: 2000.0
          price-category: "FIXED_INCOME"
          price-validation-type: "RANGE_BASED"
        category-parameters:
          required-category: "FixedIncome"
          category-type: "CONSERVATIVE"
          category-validation-type: "EXACT_MATCH"
        validation-criteria:
          price-weight: 0.7
          category-weight: 0.3
          combined-validation: true
        parameter-settings:
          strict-validation: true
          error-tolerance: "LOW"
          validation-timeout: 3000
        audit-requirements:
          - "Log fixed income parameter usage"
          - "Track parameter validation results"
          
      equity-price-parameters:
        parameter-id: "EQUITY_PRICE_PARAMS"
        parameter-name: "Equity Price Parameters"
        parameter-description: "Validation parameters for equity products"
        price-parameters:
          min-price: 50.0
          max-price: 1000.0
          price-category: "EQUITY"
          price-validation-type: "RANGE_BASED"
        category-parameters:
          required-category: "Equity"
          category-type: "GROWTH"
          category-validation-type: "EXACT_MATCH"
        validation-criteria:
          price-weight: 0.6
          category-weight: 0.4
          combined-validation: true
        parameter-settings:
          strict-validation: true
          error-tolerance: "MEDIUM"
          validation-timeout: 2500
        audit-requirements:
          - "Log equity parameter usage"
          - "Track parameter validation results"
          
      etf-price-parameters:
        parameter-id: "ETF_PRICE_PARAMS"
        parameter-name: "ETF Price Parameters"
        parameter-description: "Validation parameters for ETF products"
        price-parameters:
          min-price: 25.0
          max-price: 2500.0
          price-category: "ETF"
          price-validation-type: "RANGE_BASED"
        category-parameters:
          required-category: "ETF"
          category-type: "DIVERSIFIED"
          category-validation-type: "EXACT_MATCH"
        validation-criteria:
          price-weight: 0.5
          category-weight: 0.5
          combined-validation: true
        parameter-settings:
          strict-validation: false
          error-tolerance: "MEDIUM"
          validation-timeout: 2000
        audit-requirements:
          - "Log ETF parameter usage"
          - "Track parameter validation results"
          
      commodity-price-parameters:
        parameter-id: "COMMODITY_PRICE_PARAMS"
        parameter-name: "Commodity Price Parameters"
        parameter-description: "Validation parameters for commodity products"
        price-parameters:
          min-price: 10.0
          max-price: 5000.0
          price-category: "COMMODITY"
          price-validation-type: "RANGE_BASED"
        category-parameters:
          required-category: "Commodity"
          category-type: "ALTERNATIVE"
          category-validation-type: "EXACT_MATCH"
        validation-criteria:
          price-weight: 0.8
          category-weight: 0.2
          combined-validation: true
        parameter-settings:
          strict-validation: false
          error-tolerance: "HIGH"
          validation-timeout: 1500
        audit-requirements:
          - "Log commodity parameter usage"
          - "Track parameter validation results"
    parameter-settings:
      parameter-caching: true
      dynamic-loading: true
      validation-optimization: true
    
  category-validation-parameters:
    parameter-type: "category-validation-parameters"
    parameter-name: "Category Validation Parameters"
    description: "Parameters for category-based product validation"
    parameter-characteristics:
      parameter-category: "CATEGORY_VALIDATION"
      validation-scope: "PRODUCT_CATEGORY"
      dynamic-updates: true
    validation-parameters:
      fixed-income-category-parameters:
        parameter-id: "FIXED_INCOME_CATEGORY_PARAMS"
        parameter-name: "Fixed Income Category Parameters"
        parameter-description: "Validation parameters for FixedIncome category products"
        category-parameters:
          category: "FixedIncome"
          category-type: "CONSERVATIVE"
          category-characteristics: ["STABLE", "INCOME_GENERATING", "LOW_RISK"]
          category-requirements:
            minimum-credit-rating: "BBB"
            maximum-duration: 30
            minimum-yield: 0.01
        validation-criteria:
          category-validation: "STRICT"
          characteristic-verification: true
          requirement-checking: true
        parameter-settings:
          strict-validation: true
          characteristic-validation: true
          requirement-validation: true
        audit-requirements:
          - "Log FixedIncome category parameter usage"
          - "Track category validation results"
          
      equity-category-parameters:
        parameter-id: "EQUITY_CATEGORY_PARAMS"
        parameter-name: "Equity Category Parameters"
        parameter-description: "Validation parameters for Equity category products"
        category-parameters:
          category: "Equity"
          category-type: "GROWTH"
          category-characteristics: ["VARIABLE", "GROWTH_POTENTIAL", "MODERATE_TO_HIGH_RISK"]
          category-requirements:
            minimum-market-cap: 1000000000
            maximum-volatility: 0.5
            minimum-liquidity: 1000000
        validation-criteria:
          category-validation: "STANDARD"
          characteristic-verification: true
          requirement-checking: true
        parameter-settings:
          strict-validation: false
          characteristic-validation: true
          requirement-validation: true
        audit-requirements:
          - "Log Equity category parameter usage"
          - "Track category validation results"
          
      etf-category-parameters:
        parameter-id: "ETF_CATEGORY_PARAMS"
        parameter-name: "ETF Category Parameters"
        parameter-description: "Validation parameters for ETF category products"
        category-parameters:
          category: "ETF"
          category-type: "DIVERSIFIED"
          category-characteristics: ["DIVERSIFIED", "PASSIVE", "LOW_COST"]
          category-requirements:
            minimum-assets-under-management: 100000000
            maximum-expense-ratio: 0.01
            minimum-holdings: 50
        validation-criteria:
          category-validation: "STANDARD"
          characteristic-verification: true
          requirement-checking: true
        parameter-settings:
          strict-validation: false
          characteristic-validation: true
          requirement-validation: true
        audit-requirements:
          - "Log ETF category parameter usage"
          - "Track category validation results"
          
      commodity-category-parameters:
        parameter-id: "COMMODITY_CATEGORY_PARAMS"
        parameter-name: "Commodity Category Parameters"
        parameter-description: "Validation parameters for Commodity category products"
        category-parameters:
          category: "Commodity"
          category-type: "ALTERNATIVE"
          category-characteristics: ["PHYSICAL_ASSET", "INFLATION_HEDGE", "HIGH_VOLATILITY"]
          category-requirements:
            minimum-contract-size: 1000
            maximum-storage-cost: 0.05
            minimum-trading-volume: 10000
        validation-criteria:
          category-validation: "LENIENT"
          characteristic-verification: false
          requirement-checking: true
        parameter-settings:
          strict-validation: false
          characteristic-validation: false
          requirement-validation: true
        audit-requirements:
          - "Log Commodity category parameter usage"
          - "Track category validation results"
    parameter-settings:
      parameter-caching: true
      category-verification: true
      characteristic-validation: true
    
  quality-validation-parameters:
    parameter-type: "quality-validation-parameters"
    parameter-name: "Quality Validation Parameters"
    description: "Parameters for quality-based product validation"
    parameter-characteristics:
      parameter-category: "QUALITY_VALIDATION"
      validation-scope: "PRODUCT_QUALITY"
      dynamic-updates: true
    validation-parameters:
      premium-quality-parameters:
        parameter-id: "PREMIUM_QUALITY_PARAMS"
        parameter-name: "Premium Quality Parameters"
        parameter-description: "Validation parameters for premium quality products"
        quality-parameters:
          quality-level: "PREMIUM"
          quality-type: "HIGH_END"
          quality-score: 90
          quality-requirements:
            minimum-price: 1000.0
            minimum-rating: "A"
            minimum-track-record: 5
        validation-criteria:
          quality-validation: "STRICT"
          score-assessment: true
          requirement-checking: true
        parameter-settings:
          strict-validation: true
          score-validation: true
          requirement-validation: true
        audit-requirements:
          - "Log premium quality parameter usage"
          - "Track quality validation results"
          
      standard-quality-parameters:
        parameter-id: "STANDARD_QUALITY_PARAMS"
        parameter-name: "Standard Quality Parameters"
        parameter-description: "Validation parameters for standard quality products"
        quality-parameters:
          quality-level: "STANDARD"
          quality-type: "MAINSTREAM"
          quality-score: 70
          quality-requirements:
            minimum-price: 100.0
            minimum-rating: "BBB"
            minimum-track-record: 2
        validation-criteria:
          quality-validation: "STANDARD"
          score-assessment: true
          requirement-checking: true
        parameter-settings:
          strict-validation: false
          score-validation: true
          requirement-validation: true
        audit-requirements:
          - "Log standard quality parameter usage"
          - "Track quality validation results"
          
      basic-quality-parameters:
        parameter-id: "BASIC_QUALITY_PARAMS"
        parameter-name: "Basic Quality Parameters"
        parameter-description: "Validation parameters for basic quality products"
        quality-parameters:
          quality-level: "BASIC"
          quality-type: "ENTRY_LEVEL"
          quality-score: 50
          quality-requirements:
            minimum-price: 10.0
            minimum-rating: "C"
            minimum-track-record: 0
        validation-criteria:
          quality-validation: "LENIENT"
          score-assessment: false
          requirement-checking: false
        parameter-settings:
          strict-validation: false
          score-validation: false
          requirement-validation: false
        audit-requirements:
          - "Log basic quality parameter usage"
          - "Track quality validation results"
    parameter-settings:
      parameter-caching: true
      quality-verification: true
      score-assessment: true
    
  dynamic-validation-parameters:
    parameter-type: "dynamic-validation-parameters"
    parameter-name: "Dynamic Validation Parameters"
    description: "Parameters for dynamic product validation"
    parameter-characteristics:
      parameter-category: "DYNAMIC_VALIDATION"
      validation-scope: "FLEXIBLE"
      dynamic-updates: true
    validation-parameters:
      flexible-validation-parameters:
        parameter-id: "FLEXIBLE_VALIDATION_PARAMS"
        parameter-name: "Flexible Validation Parameters"
        parameter-description: "Flexible validation parameters for dynamic scenarios"
        dynamic-parameters:
          parameter-flexibility: "HIGH"
          validation-adaptability: "DYNAMIC"
          rule-customization: "ENABLED"
        validation-criteria:
          dynamic-validation: true
          parameter-adaptation: true
          rule-flexibility: true
        parameter-settings:
          dynamic-loading: true
          parameter-adaptation: true
          rule-customization: true
        audit-requirements:
          - "Log dynamic parameter usage"
          - "Track flexible validation results"
          
      combined-criteria-parameters:
        parameter-id: "COMBINED_CRITERIA_PARAMS"
        parameter-name: "Combined Criteria Parameters"
        parameter-description: "Parameters for combined validation criteria"
        dynamic-parameters:
          criteria-combination: "PRICE_AND_CATEGORY"
          validation-complexity: "HIGH"
          rule-interaction: "ENABLED"
        validation-criteria:
          combined-validation: true
          criteria-interaction: true
          complex-rules: true
        parameter-settings:
          complex-validation: true
          criteria-combination: true
          rule-interaction: true
        audit-requirements:
          - "Log combined criteria parameter usage"
          - "Track complex validation results"
    parameter-settings:
      parameter-caching: false
      dynamic-loading: true
      flexibility-optimization: true
    
  default:
    parameter-type: "default"
    parameter-name: "Default Product Validation Parameters"
    description: "Default product validation parameter processing"
    validation-parameters:
      default-parameters:
        parameter-id: "DEFAULT_PARAMS"
        parameter-name: "Default Parameters"
        price-parameters:
          min-price: 10.0
          max-price: 10000.0
        category-parameters:
          allowed-categories: ["FixedIncome", "Equity", "ETF", "Commodity"]
    parameter-settings:
      parameter-caching: true

# Parameter optimization patterns
optimization-patterns:
  price-range-optimization:
    pattern-name: "Price Range Optimization"
    description: "Optimize price range parameter processing"
    optimization-techniques: ["RANGE_CACHING", "BOUNDARY_OPTIMIZATION", "VALIDATION_SHORTCUTS"]
    
  category-validation-optimization:
    pattern-name: "Category Validation Optimization"
    description: "Optimize category validation parameter processing"
    optimization-techniques: ["CATEGORY_CACHING", "TYPE_OPTIMIZATION", "CHARACTERISTIC_SHORTCUTS"]
    
  quality-assessment-optimization:
    pattern-name: "Quality Assessment Optimization"
    description: "Optimize quality assessment parameter processing"
    optimization-techniques: ["QUALITY_CACHING", "SCORE_OPTIMIZATION", "REQUIREMENT_SHORTCUTS"]

# Quality assurance
quality-assurance:
  parameter-accuracy:
    - "Validation parameters must be accurate"
    - "Parameter ranges must be appropriate"
    - "Category criteria must be correct"
    - "Quality requirements must be valid"
    
  performance-requirements:
    - "Parameter loading must be efficient"
    - "Validation processing must be fast"
    - "Parameter caching must be effective"
    - "Dynamic updates must be seamless"
    
  business-alignment:
    - "Parameters must reflect business rules"
    - "Validation criteria must be appropriate"
    - "Category requirements must be accurate"
    - "Quality standards must be correct"
