# APEX Reporting Features Configuration
# External data source configuration for advanced reporting features
# Replaces hardcoded reporting logic from YamlDependencyAnalysisDemo

type: "external-data-config"
name: "reporting-features-config"
description: "Data-driven reporting features configuration for dependency analysis"

# Reporting features configuration by feature type
data:
  dependency-tree-visualization:
    feature-type: "dependency-tree-visualization"
    feature-name: "Dependency Tree Visualization"
    description: "Advanced dependency tree visualization and formatting"
    visualization-parameters:
      tree-format: "hierarchical"
      indentation-style: "unicode-box-drawing"
      status-indicators: "enabled"
      color-coding: "enabled"
    formatting-options:
      root-symbol: "└──"
      branch-symbol: "├──"
      continuation-symbol: "│"
      leaf-symbol: "└──"
      status-symbols:
        valid: "✓"
        missing: "✗"
        invalid: "!"
        circular: "~"
        unknown: "?"
    visualization-stages:
      tree-construction:
        stage-name: "Tree Construction"
        stage-description: "Construct hierarchical tree structure"
        processing-steps:
          - step: "build-tree-nodes"
            description: "Build tree nodes from dependency graph"
            timeout: 300
          - step: "establish-parent-child-relationships"
            description: "Establish parent-child relationships"
            timeout: 200
          - step: "calculate-tree-depth"
            description: "Calculate maximum tree depth"
            timeout: 100
        stage-timeout: 600
        
      formatting:
        stage-name: "Tree Formatting"
        stage-description: "Format tree for display"
        processing-steps:
          - step: "apply-indentation"
            description: "Apply hierarchical indentation"
            timeout: 200
          - step: "add-status-indicators"
            description: "Add status indicators to nodes"
            timeout: 150
          - step: "apply-color-coding"
            description: "Apply color coding based on status"
            timeout: 100
        stage-timeout: 450
    feature-settings:
      max-depth: 10
      max-width: 120
      truncate-long-paths: true
      show-file-sizes: false
    
  reverse-dependency-lookup:
    feature-type: "reverse-dependency-lookup"
    feature-name: "Reverse Dependency Lookup"
    description: "Identify which files depend on a given file"
    lookup-parameters:
      lookup-strategy: "comprehensive"
      include-indirect: "enabled"
      performance-optimization: "enabled"
    processing-stages:
      dependency-mapping:
        stage-name: "Dependency Mapping"
        stage-description: "Map all dependency relationships"
        processing-steps:
          - step: "build-forward-map"
            description: "Build forward dependency map"
            timeout: 400
          - step: "build-reverse-map"
            description: "Build reverse dependency map"
            timeout: 400
          - step: "validate-mappings"
            description: "Validate mapping consistency"
            timeout: 200
        stage-timeout: 1000
        
      lookup-processing:
        stage-name: "Lookup Processing"
        stage-description: "Process reverse dependency lookups"
        processing-steps:
          - step: "identify-direct-dependents"
            description: "Identify direct dependent files"
            timeout: 200
          - step: "identify-indirect-dependents"
            description: "Identify indirect dependent files"
            timeout: 300
          - step: "calculate-dependency-impact"
            description: "Calculate impact of changes"
            timeout: 100
        stage-timeout: 600
    feature-settings:
      include-transitive: true
      max-lookup-depth: 5
      cache-results: true
    
  file-type-distribution:
    feature-type: "file-type-distribution"
    feature-name: "File Type Distribution Analysis"
    description: "Analyze distribution of different file types in dependency chain"
    distribution-parameters:
      categorization-method: "extension-based"
      include-statistics: "enabled"
      generate-charts: "text-based"
    processing-stages:
      type-identification:
        stage-name: "Type Identification"
        stage-description: "Identify file types in dependency graph"
        processing-steps:
          - step: "extract-file-extensions"
            description: "Extract file extensions from paths"
            timeout: 100
          - step: "categorize-by-extension"
            description: "Categorize files by extension"
            timeout: 150
          - step: "identify-special-types"
            description: "Identify special file types"
            timeout: 100
        stage-timeout: 350
        
      distribution-calculation:
        stage-name: "Distribution Calculation"
        stage-description: "Calculate file type distribution statistics"
        processing-steps:
          - step: "count-files-by-type"
            description: "Count files by type"
            timeout: 100
          - step: "calculate-percentages"
            description: "Calculate percentage distribution"
            timeout: 50
          - step: "generate-distribution-chart"
            description: "Generate text-based distribution chart"
            timeout: 200
        stage-timeout: 350
    feature-settings:
      chart-width: 60
      show-percentages: true
      sort-by-count: true
    
  comprehensive-reporting:
    feature-type: "comprehensive-reporting"
    feature-name: "Comprehensive Dependency Report"
    description: "Generate comprehensive dependency analysis reports"
    reporting-parameters:
      report-format: "structured-text"
      include-summary: "enabled"
      include-details: "enabled"
      include-recommendations: "enabled"
    report-sections:
      executive-summary:
        section-name: "Executive Summary"
        section-description: "High-level summary of dependency analysis"
        content-elements:
          - "Total files analyzed"
          - "Overall health status"
          - "Critical issues count"
          - "Recommendations summary"
        
      detailed-analysis:
        section-name: "Detailed Analysis"
        section-description: "Detailed dependency analysis results"
        content-elements:
          - "Dependency tree visualization"
          - "Missing files list"
          - "Invalid YAML files list"
          - "Circular dependencies list"
          
      statistics:
        section-name: "Statistics"
        section-description: "Comprehensive dependency statistics"
        content-elements:
          - "File count by type"
          - "Dependency depth analysis"
          - "Health metrics"
          - "Performance metrics"
          
      recommendations:
        section-name: "Recommendations"
        section-description: "Actionable recommendations for improvement"
        content-elements:
          - "Priority issues to address"
          - "Suggested remediation steps"
          - "Best practices recommendations"
          - "Maintenance suggestions"
    processing-stages:
      data-aggregation:
        stage-name: "Data Aggregation"
        stage-description: "Aggregate data from all analysis components"
        processing-steps:
          - step: "collect-analysis-results"
            description: "Collect results from all analysis stages"
            timeout: 200
          - step: "aggregate-statistics"
            description: "Aggregate statistical data"
            timeout: 150
          - step: "consolidate-issues"
            description: "Consolidate identified issues"
            timeout: 100
        stage-timeout: 450
        
      report-generation:
        stage-name: "Report Generation"
        stage-description: "Generate formatted comprehensive report"
        processing-steps:
          - step: "generate-executive-summary"
            description: "Generate executive summary section"
            timeout: 200
          - step: "generate-detailed-analysis"
            description: "Generate detailed analysis section"
            timeout: 400
          - step: "generate-statistics-section"
            description: "Generate statistics section"
            timeout: 200
          - step: "generate-recommendations"
            description: "Generate recommendations section"
            timeout: 300
        stage-timeout: 1100
    feature-settings:
      max-report-length: 10000
      include-timestamps: true
      include-metadata: true
    
  performance-reporting:
    feature-type: "performance-reporting"
    feature-name: "Performance Analysis Reporting"
    description: "Generate performance analysis reports"
    reporting-parameters:
      timing-precision: "milliseconds"
      memory-units: "MB"
      throughput-units: "files/second"
    report-elements:
      timing-analysis:
        element-name: "Timing Analysis"
        element-description: "Analysis of processing times"
        metrics:
          - "Total processing time"
          - "Average time per file"
          - "Slowest processing stage"
          - "Time distribution by stage"
          
      memory-analysis:
        element-name: "Memory Analysis"
        element-description: "Analysis of memory usage"
        metrics:
          - "Peak memory usage"
          - "Average memory per file"
          - "Memory usage by component"
          - "Memory efficiency metrics"
          
      throughput-analysis:
        element-name: "Throughput Analysis"
        element-description: "Analysis of processing throughput"
        metrics:
          - "Files processed per second"
          - "Dependencies processed per second"
          - "Throughput by file type"
          - "Bottleneck identification"
    feature-settings:
      include-charts: true
      chart-type: "text-based"
      precision: 2
    
  default:
    feature-type: "default"
    feature-name: "Default Reporting"
    description: "Default reporting features"
    basic-features:
      - "Basic dependency list"
      - "Simple statistics"
      - "Basic health status"
    feature-settings:
      minimal-output: true

# Reporting templates
reporting-templates:
  standard-report:
    template-name: "Standard Dependency Report"
    template-description: "Standard template for dependency analysis reports"
    sections:
      - "Executive Summary"
      - "Dependency Tree"
      - "Issues Summary"
      - "Statistics"
    formatting:
      header-style: "boxed"
      section-separator: "line"
      indentation: 2
      
  detailed-report:
    template-name: "Detailed Dependency Report"
    template-description: "Comprehensive template with all available information"
    sections:
      - "Executive Summary"
      - "Detailed Analysis"
      - "Dependency Tree"
      - "Reverse Dependencies"
      - "File Type Distribution"
      - "Performance Metrics"
      - "Recommendations"
    formatting:
      header-style: "banner"
      section-separator: "double-line"
      indentation: 4
      
  summary-report:
    template-name: "Summary Dependency Report"
    template-description: "Concise template focusing on key information"
    sections:
      - "Summary"
      - "Critical Issues"
      - "Quick Statistics"
    formatting:
      header-style: "simple"
      section-separator: "space"
      indentation: 1

# Output formatting
output-formatting:
  text-formatting:
    line-width: 80
    header-decoration: "="
    section-decoration: "-"
    bullet-style: "•"
    
  color-coding:
    success-color: "green"
    warning-color: "yellow"
    error-color: "red"
    info-color: "blue"
    
  symbols:
    success: "✓"
    warning: "⚠"
    error: "✗"
    info: "ℹ"

# Quality assurance
quality-assurance:
  reporting-accuracy:
    - "Reports must accurately reflect analysis results"
    - "Statistics must be calculated correctly"
    - "Visualizations must be clear and accurate"
    - "Recommendations must be actionable"
    
  formatting-quality:
    - "Output must be well-formatted and readable"
    - "Charts and visualizations must be clear"
    - "Text alignment must be consistent"
    - "Color coding must be meaningful"
    
  performance-requirements:
    - "Report generation must be efficient"
    - "Memory usage must be controlled"
    - "Large reports must be handled gracefully"
    - "Formatting must not significantly impact performance"
