# APEX Scenario Files Configuration
# External data source configuration for scenario files analysis
# Replaces hardcoded scenario file arrays from YamlDependencyAnalysisDemo

metadata:
  name: "Scenario Files Configuration"
  version: "1.0.0"
  description: "Data-driven scenario files configuration for dependency analysis"
  type: "external-data-config"
  author: "apex.demo.team@company.com"
  created-date: "2024-12-24"
  tags: ["apex-demo", "util", "dependency-analysis", "scenario-files"]

# Scenario files configuration by file type
data:
  validation-scenarios:
    file-type: "validation-scenarios"
    description: "Validation scenario files for dependency analysis"
    scenario-files:
      - file-path: "validation/otc-options-scenario.yaml"
        file-name: "OTC Options Scenario"
        file-description: "OTC Options validation and processing scenario"
        analysis-priority: "high"
        expected-dependencies:
          - "bootstrap/otc-options-bootstrap.yaml"
          - "config/derivatives-validation-rules.yaml"
        file-category: "derivatives"
        complexity-level: "medium"
        
      - file-path: "validation/commodity-swaps-scenario.yaml"
        file-name: "Commodity Swaps Scenario"
        file-description: "Commodity swaps validation and processing scenario"
        analysis-priority: "high"
        expected-dependencies:
          - "bootstrap/commodity-swap/bootstrap-config.yaml"
          - "config/commodity-validation-rules.yaml"
        file-category: "commodities"
        complexity-level: "high"
        
      - file-path: "validation/settlement-auto-repair-scenario.yaml"
        file-name: "Settlement Auto-Repair Scenario"
        file-description: "Settlement auto-repair processing scenario"
        analysis-priority: "high"
        expected-dependencies:
          - "validation/custody-auto-repair-rules.yaml"
          - "config/settlement-processing-rules.yaml"
        file-category: "settlement"
        complexity-level: "medium"
        
      - file-path: "validation/equity-trade-scenario.yaml"
        file-name: "Equity Trade Scenario"
        file-description: "Equity trade validation and processing scenario"
        analysis-priority: "medium"
        expected-dependencies:
          - "bootstrap/equity-bootstrap.yaml"
          - "config/equity-validation-rules.yaml"
        file-category: "equities"
        complexity-level: "low"
        
      - file-path: "validation/bond-trade-scenario.yaml"
        file-name: "Bond Trade Scenario"
        file-description: "Bond trade validation and processing scenario"
        analysis-priority: "medium"
        expected-dependencies:
          - "bootstrap/bond-bootstrap.yaml"
          - "config/bond-validation-rules.yaml"
        file-category: "fixed-income"
        complexity-level: "medium"
    analysis-settings:
      parallel-analysis: true
      timeout-per-file: 5000
      cache-results: true
      detailed-reporting: true
    
  enrichment-scenarios:
    file-type: "enrichment-scenarios"
    description: "Enrichment scenario files for dependency analysis"
    scenario-files:
      - file-path: "enrichment/customer-enrichment-scenario.yaml"
        file-name: "Customer Enrichment Scenario"
        file-description: "Customer data enrichment scenario"
        analysis-priority: "medium"
        expected-dependencies:
          - "datasets/customer-reference-data.yaml"
          - "config/customer-enrichment-rules.yaml"
        file-category: "customer-data"
        complexity-level: "low"
        
      - file-path: "enrichment/product-enrichment-scenario.yaml"
        file-name: "Product Enrichment Scenario"
        file-description: "Product data enrichment scenario"
        analysis-priority: "medium"
        expected-dependencies:
          - "datasets/product-reference-data.yaml"
          - "config/product-enrichment-rules.yaml"
        file-category: "product-data"
        complexity-level: "low"
        
      - file-path: "enrichment/market-data-enrichment-scenario.yaml"
        file-name: "Market Data Enrichment Scenario"
        file-description: "Market data enrichment scenario"
        analysis-priority: "high"
        expected-dependencies:
          - "external-data/market-data-sources.yaml"
          - "config/market-data-rules.yaml"
        file-category: "market-data"
        complexity-level: "high"
    analysis-settings:
      parallel-analysis: true
      timeout-per-file: 3000
      cache-results: true
      detailed-reporting: false
    
  evaluation-scenarios:
    file-type: "evaluation-scenarios"
    description: "Evaluation scenario files for dependency analysis"
    scenario-files:
      - file-path: "evaluation/performance-evaluation-scenario.yaml"
        file-name: "Performance Evaluation Scenario"
        file-description: "Performance evaluation and benchmarking scenario"
        analysis-priority: "low"
        expected-dependencies:
          - "config/performance-benchmarks.yaml"
          - "datasets/performance-test-data.yaml"
        file-category: "performance"
        complexity-level: "medium"
        
      - file-path: "evaluation/compliance-evaluation-scenario.yaml"
        file-name: "Compliance Evaluation Scenario"
        file-description: "Compliance evaluation and reporting scenario"
        analysis-priority: "high"
        expected-dependencies:
          - "config/compliance-rules.yaml"
          - "datasets/compliance-reference-data.yaml"
        file-category: "compliance"
        complexity-level: "high"
    analysis-settings:
      parallel-analysis: false
      timeout-per-file: 4000
      cache-results: false
      detailed-reporting: true
    
  default:
    file-type: "default"
    description: "Default scenario files"
    scenario-files:
      - file-path: "scenarios/default-scenario.yaml"
        file-name: "Default Scenario"
        file-description: "Default processing scenario"
        analysis-priority: "low"
        expected-dependencies: []
        file-category: "default"
        complexity-level: "low"
    analysis-settings:
      parallel-analysis: false
      timeout-per-file: 2000
      cache-results: true
      detailed-reporting: false

# File analysis patterns
file-analysis-patterns:
  validation-pattern:
    pattern-name: "Validation Scenario Analysis"
    description: "Pattern for analyzing validation scenario files"
    analysis-steps:
      - "Load scenario file"
      - "Validate YAML structure"
      - "Extract rule dependencies"
      - "Check bootstrap dependencies"
      - "Validate configuration dependencies"
    validation-rules:
      - "Scenario must have valid YAML syntax"
      - "Rule dependencies must be traceable"
      - "Bootstrap files must exist"
      - "Configuration files must be valid"
    
  enrichment-pattern:
    pattern-name: "Enrichment Scenario Analysis"
    description: "Pattern for analyzing enrichment scenario files"
    analysis-steps:
      - "Load scenario file"
      - "Validate YAML structure"
      - "Extract dataset dependencies"
      - "Check enrichment rule dependencies"
      - "Validate external data sources"
    validation-rules:
      - "Scenario must have valid YAML syntax"
      - "Dataset dependencies must be traceable"
      - "Enrichment rules must exist"
      - "External data sources must be accessible"
    
  evaluation-pattern:
    pattern-name: "Evaluation Scenario Analysis"
    description: "Pattern for analyzing evaluation scenario files"
    analysis-steps:
      - "Load scenario file"
      - "Validate YAML structure"
      - "Extract evaluation dependencies"
      - "Check benchmark dependencies"
      - "Validate test data dependencies"
    validation-rules:
      - "Scenario must have valid YAML syntax"
      - "Evaluation dependencies must be traceable"
      - "Benchmark files must exist"
      - "Test data must be accessible"

# Analysis priorities
analysis-priorities:
  high-priority:
    priority-level: "high"
    description: "High priority files requiring detailed analysis"
    analysis-features:
      - "Comprehensive dependency tracing"
      - "Detailed validation"
      - "Performance monitoring"
      - "Health assessment"
    timeout-multiplier: 2.0
    
  medium-priority:
    priority-level: "medium"
    description: "Medium priority files requiring standard analysis"
    analysis-features:
      - "Standard dependency tracing"
      - "Basic validation"
      - "Performance monitoring"
    timeout-multiplier: 1.0
    
  low-priority:
    priority-level: "low"
    description: "Low priority files requiring basic analysis"
    analysis-features:
      - "Basic dependency tracing"
      - "Basic validation"
    timeout-multiplier: 0.5

# File categories
file-categories:
  derivatives:
    category-name: "Derivatives"
    description: "Derivative instrument scenarios"
    typical-dependencies:
      - "Bootstrap files"
      - "Validation rules"
      - "Market data sources"
    complexity-factors:
      - "Multiple counterparties"
      - "Complex pricing models"
      - "Regulatory requirements"
    
  commodities:
    category-name: "Commodities"
    description: "Commodity trading scenarios"
    typical-dependencies:
      - "Commodity reference data"
      - "Pricing models"
      - "Risk management rules"
    complexity-factors:
      - "Commodity price volatility"
      - "Storage and delivery"
      - "Seasonal patterns"
    
  settlement:
    category-name: "Settlement"
    description: "Settlement processing scenarios"
    typical-dependencies:
      - "Settlement rules"
      - "Market calendars"
      - "Counterparty data"
    complexity-factors:
      - "Multiple markets"
      - "Currency conversions"
      - "Settlement cycles"
    
  equities:
    category-name: "Equities"
    description: "Equity trading scenarios"
    typical-dependencies:
      - "Market data"
      - "Corporate actions"
      - "Trading rules"
    complexity-factors:
      - "Market hours"
      - "Corporate events"
      - "Dividend processing"
    
  fixed-income:
    category-name: "Fixed Income"
    description: "Fixed income scenarios"
    typical-dependencies:
      - "Interest rate curves"
      - "Credit ratings"
      - "Bond reference data"
    complexity-factors:
      - "Interest rate sensitivity"
      - "Credit risk"
      - "Maturity calculations"

# Quality assurance
quality-assurance:
  file-validation:
    - "All scenario files must have valid YAML syntax"
    - "File paths must be accurate"
    - "Expected dependencies must be realistic"
    - "Analysis priorities must be appropriate"
    
  dependency-validation:
    - "Expected dependencies must exist or be marked as optional"
    - "Circular dependencies must be avoided"
    - "Dependency chains must be reasonable"
    - "Missing dependencies must be documented"
    
  analysis-validation:
    - "Analysis settings must be appropriate for file complexity"
    - "Timeouts must be reasonable"
    - "Parallel analysis must be safe"
    - "Caching strategies must be effective"
