# APEX Validation Parameters Configuration
# External data source configuration for validation parameters processing
# Replaces hardcoded validation parameters from IntegratedCustomerValidatorDemo

type: "external-data-config"
name: "validation-parameters-config"
description: "Data-driven validation parameters configuration for integrated customer validation processing"

# Validation parameters configuration by parameter type
data:
  age-range-parameters:
    parameter-type: "age-range-parameters"
    parameter-name: "Age Range Parameters"
    description: "Parameters for age-based customer validation"
    parameter-characteristics:
      parameter-category: "AGE_VALIDATION"
      validation-scope: "AGE_RANGE"
      dynamic-updates: true
    validation-parameters:
      senior-gold-parameters:
        parameter-id: "SENIOR_GOLD_PARAMS"
        parameter-name: "Senior Gold Customer Parameters"
        parameter-description: "Validation parameters for senior Gold customers"
        age-parameters:
          min-age: 60
          max-age: 100
          age-category: "SENIOR"
          age-validation-type: "RANGE_BASED"
        membership-parameters:
          allowed-membership-levels: ["Gold"]
          membership-tier: "PREMIUM"
          membership-validation-type: "EXACT_MATCH"
        validation-criteria:
          age-weight: 0.6
          membership-weight: 0.4
          combined-validation: true
        parameter-settings:
          strict-validation: true
          error-tolerance: "LOW"
          validation-timeout: 3000
        audit-requirements:
          - "Log senior Gold parameter usage"
          - "Track parameter validation results"
          
      young-silver-parameters:
        parameter-id: "YOUNG_SILVER_PARAMS"
        parameter-name: "Young Silver Customer Parameters"
        parameter-description: "Validation parameters for young Silver customers"
        age-parameters:
          min-age: 18
          max-age: 30
          age-category: "YOUNG"
          age-validation-type: "RANGE_BASED"
        membership-parameters:
          allowed-membership-levels: ["Silver"]
          membership-tier: "STANDARD"
          membership-validation-type: "EXACT_MATCH"
        validation-criteria:
          age-weight: 0.5
          membership-weight: 0.5
          combined-validation: true
        parameter-settings:
          strict-validation: true
          error-tolerance: "MEDIUM"
          validation-timeout: 2500
        audit-requirements:
          - "Log young Silver parameter usage"
          - "Track parameter validation results"
          
      middle-aged-gold-parameters:
        parameter-id: "MIDDLE_AGED_GOLD_PARAMS"
        parameter-name: "Middle-Aged Gold Customer Parameters"
        parameter-description: "Validation parameters for middle-aged Gold customers"
        age-parameters:
          min-age: 35
          max-age: 60
          age-category: "MIDDLE_AGED"
          age-validation-type: "RANGE_BASED"
        membership-parameters:
          allowed-membership-levels: ["Gold"]
          membership-tier: "PREMIUM"
          membership-validation-type: "EXACT_MATCH"
        validation-criteria:
          age-weight: 0.6
          membership-weight: 0.4
          combined-validation: true
        parameter-settings:
          strict-validation: true
          error-tolerance: "LOW"
          validation-timeout: 3000
        audit-requirements:
          - "Log middle-aged Gold parameter usage"
          - "Track parameter validation results"
    parameter-settings:
      parameter-caching: true
      dynamic-loading: true
      validation-optimization: true
    
  membership-level-parameters:
    parameter-type: "membership-level-parameters"
    parameter-name: "Membership Level Parameters"
    description: "Parameters for membership-based customer validation"
    parameter-characteristics:
      parameter-category: "MEMBERSHIP_VALIDATION"
      validation-scope: "MEMBERSHIP_LEVEL"
      dynamic-updates: true
    validation-parameters:
      gold-membership-parameters:
        parameter-id: "GOLD_MEMBERSHIP_PARAMS"
        parameter-name: "Gold Membership Parameters"
        parameter-description: "Validation parameters for Gold membership customers"
        membership-parameters:
          membership-level: "Gold"
          membership-tier: "PREMIUM"
          membership-benefits: ["PREMIUM_SUPPORT", "EXCLUSIVE_PRODUCTS", "PRIORITY_SERVICE"]
          membership-requirements:
            minimum-portfolio-value: 500000
            minimum-relationship-duration: 24
            minimum-transaction-volume: 100000
        validation-criteria:
          membership-validation: "STRICT"
          benefit-verification: true
          requirement-checking: true
        parameter-settings:
          strict-validation: true
          benefit-validation: true
          requirement-validation: true
        audit-requirements:
          - "Log Gold membership parameter usage"
          - "Track membership validation results"
          
      silver-membership-parameters:
        parameter-id: "SILVER_MEMBERSHIP_PARAMS"
        parameter-name: "Silver Membership Parameters"
        parameter-description: "Validation parameters for Silver membership customers"
        membership-parameters:
          membership-level: "Silver"
          membership-tier: "STANDARD"
          membership-benefits: ["STANDARD_SUPPORT", "BASIC_PRODUCTS", "REGULAR_SERVICE"]
          membership-requirements:
            minimum-portfolio-value: 100000
            minimum-relationship-duration: 12
            minimum-transaction-volume: 25000
        validation-criteria:
          membership-validation: "STANDARD"
          benefit-verification: true
          requirement-checking: true
        parameter-settings:
          strict-validation: false
          benefit-validation: true
          requirement-validation: true
        audit-requirements:
          - "Log Silver membership parameter usage"
          - "Track membership validation results"
          
      platinum-membership-parameters:
        parameter-id: "PLATINUM_MEMBERSHIP_PARAMS"
        parameter-name: "Platinum Membership Parameters"
        parameter-description: "Validation parameters for Platinum membership customers"
        membership-parameters:
          membership-level: "Platinum"
          membership-tier: "VIP"
          membership-benefits: ["VIP_SUPPORT", "EXCLUSIVE_PRODUCTS", "CONCIERGE_SERVICE"]
          membership-requirements:
            minimum-portfolio-value: 2000000
            minimum-relationship-duration: 36
            minimum-transaction-volume: 500000
        validation-criteria:
          membership-validation: "ULTRA_STRICT"
          benefit-verification: true
          requirement-checking: true
        parameter-settings:
          strict-validation: true
          benefit-validation: true
          requirement-validation: true
        audit-requirements:
          - "Log Platinum membership parameter usage"
          - "Track VIP validation results"
          
      basic-membership-parameters:
        parameter-id: "BASIC_MEMBERSHIP_PARAMS"
        parameter-name: "Basic Membership Parameters"
        parameter-description: "Validation parameters for Basic membership customers"
        membership-parameters:
          membership-level: "Basic"
          membership-tier: "BASIC"
          membership-benefits: ["BASIC_SUPPORT", "STANDARD_PRODUCTS", "SELF_SERVICE"]
          membership-requirements:
            minimum-portfolio-value: 0
            minimum-relationship-duration: 0
            minimum-transaction-volume: 0
        validation-criteria:
          membership-validation: "LENIENT"
          benefit-verification: false
          requirement-checking: false
        parameter-settings:
          strict-validation: false
          benefit-validation: false
          requirement-validation: false
        audit-requirements:
          - "Log Basic membership parameter usage"
          - "Track basic validation results"
    parameter-settings:
      parameter-caching: true
      membership-verification: true
      benefit-validation: true
    
  category-preference-parameters:
    parameter-type: "category-preference-parameters"
    parameter-name: "Category Preference Parameters"
    description: "Parameters for category-based customer validation"
    parameter-characteristics:
      parameter-category: "CATEGORY_VALIDATION"
      validation-scope: "PREFERRED_CATEGORIES"
      dynamic-updates: true
    validation-parameters:
      equity-preference-parameters:
        parameter-id: "EQUITY_PREFERENCE_PARAMS"
        parameter-name: "Equity Preference Parameters"
        parameter-description: "Validation parameters for Equity category preferences"
        category-parameters:
          category: "Equity"
          category-type: "GROWTH"
          risk-level: "MODERATE_TO_HIGH"
          investment-horizon: "LONG_TERM"
        validation-criteria:
          category-validation: "STRICT"
          risk-assessment: true
          suitability-check: true
        parameter-settings:
          risk-validation: true
          suitability-validation: true
          category-matching: "EXACT"
        audit-requirements:
          - "Log Equity preference parameter usage"
          - "Track category validation results"
          
      fixed-income-preference-parameters:
        parameter-id: "FIXED_INCOME_PREFERENCE_PARAMS"
        parameter-name: "Fixed Income Preference Parameters"
        parameter-description: "Validation parameters for FixedIncome category preferences"
        category-parameters:
          category: "FixedIncome"
          category-type: "CONSERVATIVE"
          risk-level: "LOW_TO_MODERATE"
          investment-horizon: "MEDIUM_TERM"
        validation-criteria:
          category-validation: "STANDARD"
          risk-assessment: true
          suitability-check: true
        parameter-settings:
          risk-validation: true
          suitability-validation: true
          category-matching: "EXACT"
        audit-requirements:
          - "Log FixedIncome preference parameter usage"
          - "Track category validation results"
          
      etf-preference-parameters:
        parameter-id: "ETF_PREFERENCE_PARAMS"
        parameter-name: "ETF Preference Parameters"
        parameter-description: "Validation parameters for ETF category preferences"
        category-parameters:
          category: "ETF"
          category-type: "DIVERSIFIED"
          risk-level: "MODERATE"
          investment-horizon: "MEDIUM_TO_LONG_TERM"
        validation-criteria:
          category-validation: "STANDARD"
          risk-assessment: true
          suitability-check: true
        parameter-settings:
          risk-validation: true
          suitability-validation: true
          category-matching: "EXACT"
        audit-requirements:
          - "Log ETF preference parameter usage"
          - "Track category validation results"
    parameter-settings:
      parameter-caching: true
      category-verification: true
      suitability-assessment: true
    
  dynamic-validation-parameters:
    parameter-type: "dynamic-validation-parameters"
    parameter-name: "Dynamic Validation Parameters"
    description: "Parameters for dynamic customer validation"
    parameter-characteristics:
      parameter-category: "DYNAMIC_VALIDATION"
      validation-scope: "FLEXIBLE"
      dynamic-updates: true
    validation-parameters:
      flexible-validation-parameters:
        parameter-id: "FLEXIBLE_VALIDATION_PARAMS"
        parameter-name: "Flexible Validation Parameters"
        parameter-description: "Flexible validation parameters for dynamic scenarios"
        dynamic-parameters:
          parameter-flexibility: "HIGH"
          validation-adaptability: "DYNAMIC"
          rule-customization: "ENABLED"
        validation-criteria:
          dynamic-validation: true
          parameter-adaptation: true
          rule-flexibility: true
        parameter-settings:
          dynamic-loading: true
          parameter-adaptation: true
          rule-customization: true
        audit-requirements:
          - "Log dynamic parameter usage"
          - "Track flexible validation results"
    parameter-settings:
      parameter-caching: false
      dynamic-loading: true
      flexibility-optimization: true
    
  default:
    parameter-type: "default"
    parameter-name: "Default Validation Parameters"
    description: "Default validation parameter processing"
    validation-parameters:
      default-parameters:
        parameter-id: "DEFAULT_PARAMS"
        parameter-name: "Default Parameters"
        age-parameters:
          min-age: 18
          max-age: 100
        membership-parameters:
          allowed-membership-levels: ["Basic", "Silver", "Gold", "Platinum"]
    parameter-settings:
      parameter-caching: true

# Parameter optimization patterns
optimization-patterns:
  age-range-optimization:
    pattern-name: "Age Range Optimization"
    description: "Optimize age range parameter processing"
    optimization-techniques: ["RANGE_CACHING", "BOUNDARY_OPTIMIZATION", "VALIDATION_SHORTCUTS"]
    
  membership-level-optimization:
    pattern-name: "Membership Level Optimization"
    description: "Optimize membership level parameter processing"
    optimization-techniques: ["LEVEL_CACHING", "TIER_OPTIMIZATION", "BENEFIT_SHORTCUTS"]
    
  category-preference-optimization:
    pattern-name: "Category Preference Optimization"
    description: "Optimize category preference parameter processing"
    optimization-techniques: ["CATEGORY_CACHING", "PREFERENCE_OPTIMIZATION", "SUITABILITY_SHORTCUTS"]

# Quality assurance
quality-assurance:
  parameter-accuracy:
    - "Validation parameters must be accurate"
    - "Parameter ranges must be appropriate"
    - "Membership criteria must be correct"
    - "Category preferences must be valid"
    
  performance-requirements:
    - "Parameter loading must be efficient"
    - "Validation processing must be fast"
    - "Parameter caching must be effective"
    - "Dynamic updates must be seamless"
    
  business-alignment:
    - "Parameters must reflect business rules"
    - "Validation criteria must be appropriate"
    - "Membership requirements must be accurate"
    - "Category suitability must be correct"
