# Custody Auto-Repair Demo - Configuration
# This file contains configuration settings for the Custody demonstration
# Business users can modify these settings to customize demo behavior

metadata:
  name: "Custody Auto-Repair Bootstrap Demo - Configuration"
  version: "1.0"
  description: "Configuration settings for Custody auto-repair demonstration (CustodyAutoRepairBootstrap.java)"
  type: "rule-config"
  author: "APEX Demo Team"
  associated-demo: "CustodyAutoRepairBootstrap"
  file-purpose: "Configures settlement instruction validation and auto-repair rules"
  lastUpdated: "2025-07-28"

# Demo execution configuration
demo:
  name: "Custody Auto-Repair Demo"
  description: "Consolidated custody auto-repair with multiple execution modes"
  version: "2.0"
  modes:
    - name: "PRODUCTION"
      description: "Production-oriented auto-repair with FileSystemDataSource patterns"
      enabled: true
    - name: "LEGACY"
      description: "Traditional auto-repair with embedded business logic"
      enabled: true
    - name: "YAML"
      description: "External configuration with business-user maintainable rules"
      enabled: true

# Auto-repair configuration
autoRepair:
  # Core settings
  enabled: true
  respectClientOptOut: true
  highValueManualReview: true
  requireApprovalForHighRisk: true
  auditAllDecisions: true
  
  # Thresholds
  thresholds:
    highValueAmount: 10000000.0      # $10M threshold for high-value transactions
    repairApprovalScore: 0.70        # Score >= 70% for full auto-repair
    partialRepairScore: 0.50         # Score >= 50% for partial repair
    confidenceThreshold: 0.70        # Minimum confidence level
    
  # Processing settings
  processing:
    maxProcessingTimeMs: 100         # Target processing time
    cacheEnabled: true
    auditEnabled: true
    metricsEnabled: true
    
  # Standing instruction weighting
  weights:
    clientSpecific: 0.6              # Client-specific SIs (highest priority)
    marketSpecific: 0.3              # Market-specific SIs (medium priority)
    instrumentSpecific: 0.1          # Instrument-specific SIs (lowest priority)

# Market configuration
markets:
  # Asian markets configuration
  JAPAN:
    currency: "JPY"
    timezone: "Asia/Tokyo"
    settlementCycle: "T+2"
    defaultCustodian: "CUST_JAPAN_DEFAULT"
    defaultCounterparty: "CP_JAPAN_STANDARD"
    regulatoryRequirements: ["JFSA_COMPLIANCE"]
    
  HONG_KONG:
    currency: "HKD"
    timezone: "Asia/Hong_Kong"
    settlementCycle: "T+2"
    defaultCustodian: "CUST_HK_STANDARD"
    defaultCounterparty: "CP_HK_STANDARD"
    regulatoryRequirements: ["SFC_COMPLIANCE"]
    
  SINGAPORE:
    currency: "SGD"
    timezone: "Asia/Singapore"
    settlementCycle: "T+2"
    defaultCustodian: "CUST_SG_STANDARD"
    defaultCounterparty: "CP_SG_STANDARD"
    regulatoryRequirements: ["MAS_COMPLIANCE"]
    
  KOREA:
    currency: "KRW"
    timezone: "Asia/Seoul"
    settlementCycle: "T+2"
    defaultCustodian: "CUST_KR_STANDARD"
    defaultCounterparty: "CP_KR_STANDARD"
    regulatoryRequirements: ["FSC_COMPLIANCE"]
    
  TAIWAN:
    currency: "TWD"
    timezone: "Asia/Taipei"
    settlementCycle: "T+2"
    defaultCustodian: "CUST_TW_STANDARD"
    defaultCounterparty: "CP_TW_STANDARD"
    regulatoryRequirements: ["FSC_TAIWAN_COMPLIANCE"]
    
  AUSTRALIA:
    currency: "AUD"
    timezone: "Australia/Sydney"
    settlementCycle: "T+2"
    defaultCustodian: "CUST_AU_STANDARD"
    defaultCounterparty: "CP_AU_STANDARD"
    regulatoryRequirements: ["ASIC_COMPLIANCE"]

# Client tier configuration
clientTiers:
  PREMIUM:
    description: "Premium institutional clients"
    autoRepairEnabled: true
    confidenceLevel: 0.98
    specialHandling: true
    dedicatedSupport: true
    enhancedMonitoring: true
    
  STANDARD:
    description: "Standard institutional clients"
    autoRepairEnabled: true
    confidenceLevel: 0.90
    specialHandling: false
    dedicatedSupport: false
    enhancedMonitoring: false
    
  BASIC:
    description: "Basic clients"
    autoRepairEnabled: true
    confidenceLevel: 0.80
    specialHandling: false
    dedicatedSupport: false
    enhancedMonitoring: false

# Instrument type configuration
instrumentTypes:
  EQUITY:
    description: "Equity securities"
    defaultSettlementMethod: "DVP"
    defaultDeliveryInstruction: "DELIVER"
    riskCategory: "MEDIUM"
    
  FIXED_INCOME:
    description: "Fixed income securities"
    defaultSettlementMethod: "DVP"
    defaultDeliveryInstruction: "DELIVER"
    riskCategory: "LOW"
    
  DERIVATIVE:
    description: "Derivative instruments"
    defaultSettlementMethod: "DVP"
    defaultDeliveryInstruction: "DELIVER"
    riskCategory: "HIGH"
    
  COMMODITY:
    description: "Commodity instruments"
    defaultSettlementMethod: "DVP"
    defaultDeliveryInstruction: "DELIVER"
    riskCategory: "HIGH"

# Risk management configuration
riskManagement:
  # Risk categories
  riskCategories:
    LOW:
      description: "Low risk transactions"
      maxAmount: 50000000.0
      autoApprovalEnabled: true
      enhancedMonitoring: false
      
    MEDIUM:
      description: "Medium risk transactions"
      maxAmount: 25000000.0
      autoApprovalEnabled: true
      enhancedMonitoring: true
      
    HIGH:
      description: "High risk transactions"
      maxAmount: 10000000.0
      autoApprovalEnabled: false
      enhancedMonitoring: true
      requiresApproval: true
      
  # Monitoring settings
  monitoring:
    realTimeAlerts: true
    thresholdAlerts: true
    anomalyDetection: true
    reportingFrequency: "DAILY"

# Validation configuration
validation:
  # Settlement instruction validation
  settlementInstruction:
    requiredFields: ["instructionId", "clientId", "market", "instrumentType", "settlementAmount", "settlementCurrency"]
    amountValidation:
      minAmount: 1000.0
      maxAmount: 100000000.0
    currencyValidation:
      supportedCurrencies: ["JPY", "HKD", "SGD", "KRW", "TWD", "AUD", "USD", "EUR"]
    marketValidation:
      supportedMarkets: ["JAPAN", "HONG_KONG", "SINGAPORE", "KOREA", "TAIWAN", "AUSTRALIA"]
      
  # Standing instruction validation
  standingInstruction:
    requiredFields: ["siId", "siName", "scopeType", "weight", "confidenceLevel"]
    weightValidation:
      minWeight: 0.0
      maxWeight: 1.0
    confidenceValidation:
      minConfidence: 0.0
      maxConfidence: 1.0

# Performance configuration
performance:
  # Processing limits
  processing:
    maxConcurrentInstructions: 100
    maxBatchSize: 1000
    timeoutSeconds: 30
    
  # Caching settings
  caching:
    enabled: true
    standingInstructionCacheTtl: 3600  # 1 hour
    clientDataCacheTtl: 1800           # 30 minutes
    marketDataCacheTtl: 7200           # 2 hours
    
  # Metrics collection
  metrics:
    enabled: true
    collectRepairMetrics: true
    collectPerformanceMetrics: true
    collectBusinessMetrics: true
    reportingIntervalSeconds: 60

# Error handling configuration
errorHandling:
  # Auto-repair errors
  autoRepair:
    retryOnFailure: true
    maxRetries: 3
    retryDelayMs: 1000
    fallbackToManualReview: true
    
  # Validation errors
  validation:
    stopOnFirstError: false
    collectAllErrors: true
    includeFieldNames: true
    includeErrorCodes: true
    
  # Processing errors
  processing:
    escalateToSupport: true
    createIncident: true
    notifyStakeholders: true

# Business rules configuration
businessRules:
  # Auto-repair eligibility
  autoRepairEligibility:
    enabled: true
    rules:
      - name: "client-opt-out-check"
        expression: "#clientOptOut != true"
        errorCode: "CLIENT_OPTED_OUT"
        severity: "INFO"
        
      - name: "high-value-check"
        expression: "#settlementAmount < 10000000 || #highValueApproved == true"
        errorCode: "HIGH_VALUE_REQUIRES_APPROVAL"
        severity: "WARNING"
        
      - name: "confidence-threshold-check"
        expression: "#totalConfidence >= 0.70"
        errorCode: "CONFIDENCE_BELOW_THRESHOLD"
        severity: "ERROR"
        
  # Field repair rules
  fieldRepair:
    enabled: true
    rules:
      - name: "counterparty-repair"
        expression: "#counterpartyId == null && #applicableSI.defaultCounterpartyId != null"
        action: "SET_FIELD"
        field: "counterpartyId"
        source: "applicableSI.defaultCounterpartyId"
        
      - name: "custodian-repair"
        expression: "#custodianId == null && #applicableSI.defaultCustodianId != null"
        action: "SET_FIELD"
        field: "custodianId"
        source: "applicableSI.defaultCustodianId"
        
      - name: "settlement-method-repair"
        expression: "#settlementMethod == null && #applicableSI.defaultSettlementMethod != null"
        action: "SET_FIELD"
        field: "settlementMethod"
        source: "applicableSI.defaultSettlementMethod"

# Test scenarios configuration
testScenarios:
  # Production mode scenarios
  productionMode:
    enabled: true
    description: "Production-oriented auto-repair"
    expectedInstructions: 3
    expectedRepairs: 2
    
  # Legacy mode scenarios
  legacyMode:
    enabled: true
    description: "Traditional auto-repair"
    expectedInstructions: 4
    expectedRepairs: 3
    
  # YAML mode scenarios
  yamlMode:
    enabled: true
    description: "External configuration auto-repair"
    expectedInstructions: 5
    expectedRepairs: 4

# Integration configuration
integration:
  # External data sources
  dataSources:
    enabled: false
    settlementInstructionSource: "demo-data/custody/settlement-instructions.yaml"
    standingInstructionSource: "demo-data/custody/standing-instructions.yaml"
    configurationSource: "demo-data/custody/config.yaml"
    
  # Database integration
  database:
    enabled: false
    connectionString: "jdbc:h2:mem:custody_demo"
    autoCreateTables: true
    
  # Message queue integration
  messaging:
    enabled: false
    repairNotifications: true
    auditMessages: true

# Output configuration
output:
  # Console output settings
  console:
    enabled: true
    showProgress: true
    showDetails: true
    showTimings: true
    showRepairResults: true
    colorOutput: true
    
  # Report generation
  reports:
    enabled: true
    outputDirectory: "demo-output/custody"
    generateRepairReport: true
    generateAuditReport: true
    generateMetricsReport: true
    reportFormat: "YAML"
    
  # Audit trail
  audit:
    enabled: true
    logAllDecisions: true
    logRepairActions: true
    logPerformanceMetrics: true
    auditDirectory: "audit/custody"
